### ISSUE TITLE
ns formatting with reader conditionals

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1014]
I'm not quite sure what I'd like to see, but the current ns formatting for Reader Conditionals doesn't always look that nice.
- There doesn't seem to be a way to write 
  
  ```
  #?(:clj (:import [rethinkdb.core Connection]))`
  ```
  
  It will always be split onto two lines like this
  
  ```
  #?(:clj
       (:import [rethinkdb.core Connection]))
  ```
- I don't really like how this is formatted either
  
  ```
  (ns rethinkdb.query
    #?(:cljs (:use-macros [rethinkdb.query :only [fn]]))
    (:require [clojure.walk :as walk]
          [rethinkdb.query-builder :as qb :refer [term]]
      #?@(:clj [
              [rethinkdb.net :as net]
              [rethinkdb.core :as core]]))
    #?(:clj
       (:import [rethinkdb.core Connection])))
  ```
  
  or
  
  ```
  (ns rethinkdb.query
  (:refer-clojure :exclude [count filter map get not mod replace merge
                            reduce make-array distinct keys nth min max
                            or and do fn sync time update])
  #?(:cljs (:use-macros [rethinkdb.query :only [fn]]))
  (:require [clojure.walk :as walk]
            [rethinkdb.query-builder :as qb :refer [term]]
    #?(:clj
            [rethinkdb.net :as net])
    #?(:clj
            [rethinkdb.core :as core]))
  #?(:clj
     (:import [rethinkdb.core Connection])))
  ```
- If you put your reader conditionals require's above your combined requires the `:require` block looks a bit confusing. It's not easy to tell where Reader Conditionals stop.
  
  ```
  (:require #?@(:clj [[rethinkdb.net :as net]
                      [rethinkdb.core :as core]])
                      [clojure.walk :as walk]
                      [rethinkdb.query-builder :as qb :refer [term]])
  ```

In one of the previous Cursive releases I seem to remember reader conditionals being aligned to the rest of the forms in the ns block like this:

```
(:require [clojure.walk :as walk]
            [rethinkdb.query-builder :as qb :refer [term]]
            #?(:clj [rethinkdb.net :as net])
            #?(:clj [rethinkdb.core :as core]))
```

To my eyes this is a little cleaner, though I also like the idea behind the current implementation in keeping everything aligned together. I haven't looked to see how other editors are handling this, though there might be some ideas there too.

**Comment by conan** [comment]
I'd also like to see the map formatting used in cljc reader conditionals:
 
    (catch
      #?(:clj  Exception
         :cljs :default) e
    ...)

(2 spaces between `:clj` and `Exception`)

**Comment by mtruyens** [comment]
+ 1

**Comment by mhuebert** [comment]
...just another example,
```
(:require #?@(:clj [clojure.java.io
                      :as
                      io]
                [hiccup.page :as page])
                      [clojure.spec.alpha :as s]
                      [clojure.string :as str])
```

**Comment by cursive-ide** [comment]
My apologies for the long wait on this annoying bug - this has been fixed for the next build, and all the cases in this and the other linked issues now look reasonable.

**Comment by solidfox** [comment]
This gets really bad when parinfer is turned on. Any way to exempt a part of the code from formatting until the EAP is released?
