### ISSUE TITLE
go-loop let bindings don't match loop let binding functionality

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1019]
Cursive is very clever at resolving symbols and can tell which `a` is being referred to at which point in this code:

```
(let [a :aba]
  (loop [a a]
    (println a)
    (recur a)))
```

![screenshot of intellij idea 19-08-15 2 07 58 pm](https://cloud.githubusercontent.com/assets/811954/9347282/ba273f40-467b-11e5-85b7-6a7a550d8212.png)

However it doesn't seem to have the same ability when using a go-loop:

```
(let [a :aba]
  (go-loop [a a]
    (println a)
    (recur a)))
```

![screenshot of intellij idea 19-08-15 2 06 43 pm](https://cloud.githubusercontent.com/assets/811954/9347277/ad751524-467b-11e5-8efd-49528f03c9c0.png)

This seems like a regression or missed feature when implementing support for go-loop.

**Comment by wilkerlucio** [comment]
this duplicates #925
