### ISSUE TITLE
Re-run last command from REPL history

### ISSUE THREAD

**Issue by madvas** [cursive-ide/cursive#1037]
It would be nice, if there was an action (and shortcut) to re-run last command from REPL history.

Often when editing some function I use shortcut to "Load file in REPL" and then I want to call that function - which I have as last calling in REPL anyway.

Thanks

**Comment by cursiveclojure** [comment]
There isn't at the moment, although it's a pretty common request. It's related to #85.

**Comment by cursiveclojure** [comment]
Note that you can also work around this somewhat using *Tools&rarr;REPL&rarr;Search REPL History*. Assign that a shortcut, use that shortcut and then Shift-Enter.

**Comment by cursive-ide** [comment]
This has been fixed in the next build (1.3.0-eap1) as part of the fix for #85.
