### ISSUE TITLE
add right-click option to run individual tests

### ISSUE THREAD

**Issue by KevinCorcoran** [cursive-ide/cursive#106]
I would like to be able to run all of the tests in a single namespace, as well as just a lone `deftest`, via a right-click option in the editor.  Vanilla IntelliJ supports this for JUnit, TestNG, etc.

**Comment by KevinCorcoran** [comment]
Hey Colin,

Are you still planning on implementing an IntelliJ test runner in Cursive?  The REPL-based testing is excellent - at this point, I can't imagine writing code without it! -  but I still end up running a basic `lein test` often, when I need to run the whole test suite, instead of a single namespace or `deftest`, and in those cases it would be great to have a test runner.

BTW, great talk at Clojure/West!

**Comment by cursiveclojure** [comment]
Yes, I am, but it's been fairly low priority since most people have something like `lein test` available to do basically the same thing. I guess I'm a little worried about more or less duplicating functionality. I'll take a quick look and see if I can see how easy it would be to plug something into the test runner UI.

Thanks for the kind words about the talk, I had a great time at the conference. I looked out for you there but didn't see you, it would have been cool to catch up! Next time...

**Comment by cursiveclojure** [comment]
BTW would it be preferable to have this use an open REPL, or to start a new process each time? Or to be able to choose?

**Comment by KevinCorcoran** [comment]
Ha, yeah, I was trying to find you at the party, but couldn't.  It was a little crazy in there.  Next time ...

I think it would be preferable to have this use an existing REPL, in the interest of speed.  But either way would probably be fine with me - mainly, I'd just like a nice UI for debugging test failures from an entire test suite, instead of sifting through the output of `lein test`.

**Comment by cksharma11** [comment]
> The initial version of this will be in the next drop - it's REPL based rather than a runner, although I'll be able to reuse parts of it for a runner. I'm still working on it but the initial version looks like the image below. Right now there are two new commands, one to run all tests in a namespace and one to clear all the test markers. When you run the tests in the REPL markers are added to the editors for test results and if the test failure is a string comparison you can get a diff view from a link in the tooltip. I'll add "run single test" before the next release. I'm not totally happy with the UI yet, this was just the easiest way to get it going without a bunch of Swing hacking, but after some iterations hopefully this will be good - feedback welcome.
> 
> ![test-result-preview](https://camo.githubusercontent.com/58872d1dca74a42b2f27bf17750bfb8fa60a1898/68747470733a2f2f662e636c6f75642e6769746875622e636f6d2f6173736574732f353538393137312f313730313131362f61366435666136362d363034312d313165332d383262302d3938373933663935656235372e706e67)

Hi,

I have gone through the docs and it seems that there is no shortcut for running the test every time I'll have to navigate and run test manually. Is there there anything that I'm missing?

**Comment by cursive-ide** [comment]
This issue has been resolved for a while, as part of #247.
