### ISSUE TITLE
Add def behaviour to `goog-define`

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1067]
`goog-define` was added in ClojureScript [1.7.48](https://github.com/clojure/clojurescript/blob/master/changes.md#1748) and has def style behaviour. It would be nice if this defined symbols in Cursive like a def does. More details on it's usage is in http://www.martinklepsch.org/posts/parameterizing-clojurescript-builds.html.

**Comment by olivergeorge** [comment]
This would be nice.

A workaround to avoid the angry highlighting is to do the declare manually...

```clj
(declare api-uri)
(goog-define api-uri "http://your.api.com")
```
