### ISSUE TITLE
Jump to declaration doesnt work with defonce

### ISSUE THREAD

**Issue by sthomp** [cursive-ide/cursive#1069]
If I create a `(defonce ...)` and reference it somewhere in code I can no longer command-B to jump to declaration. If I change the `(defonce ..)` to be a regular `(def ...)` then it works.

**Comment by vincentjames501** [comment]
+1.

It only appears to happen with strings for me.

![image](https://cloud.githubusercontent.com/assets/396866/17371355/2c4a821a-5965-11e6-89ec-ed60e5c218d4.png)

**Comment by kennyjwilli** [comment]
You can workaround this problem by doing alt+enter over `defonce`, select "Resolve clojure.core/defonce as...", and hit `def`.
