### ISSUE TITLE
Highlight surrounding sexp's

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1088]
It would be really useful to have an equivalent for [HighlightSexps](http://www.emacswiki.org/emacs/HighlightSexps) in Cursive. This could maybe hook into the same code that provides rainbow parens?

**Comment by coltnz** [comment]
Edit -> Extend Selection does this, ⌘D on my machine

**Comment by danielcompton** [comment]
This would be for visual purposes to show all the time, it doesn't influence selections.

**Comment by cursive-ide** [comment]
This is a duplicate of #824.
