### ISSUE TITLE
Find keyword usages dialog buttons should be more descriptive

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1093]
![screenshot of intellij idea-eap 7-10-15 10 22 59 pm](https://cloud.githubusercontent.com/assets/811954/10333695/10f17132-6d42-11e5-9efd-00c2ab00eeff.png)

The Yes/No/Cancel trio of buttons doesn't make a lot of sense here at first glance. It's not clear what the difference between No and Cancel is when reading the message. Another option could be:

````
<keyword> destructures keyword :<keyword>. Do you want to find usages of the keyword or the symbol?

[Cancel] [Symbol] [*Keyword*]
```

**Comment by cursiveclojure** [comment]
Hmm, yeah, that could be a bit clearer.

**Comment by danielcompton** [comment]
The same thing also applies to renaming a keyword.

**Comment by cursive-ide** [comment]
This was fixed a couple of releases ago.
