### ISSUE TITLE
"Move caret to matching brace" doesn't work in the REPL

### ISSUE THREAD

**Issue by cjkent** [cursive-ide/cursive#1103]
A new action was added in a recent build of IDEA 15 EAP which moves the caret between matching braces:

https://youtrack.jetbrains.com/issue/IDEA-12068

It works for (), [] and {} in the Cursive editor but doesn't do anything in the REPL.

**Comment by onetom** [comment]
It's still an issue with IntelliJ 2016.1.1 / Cursive 1.2.4-2016.1
Ctrl-M is the most frequently used shortcut after the cursor keys and slurp/barf, so I miss it badly too.
I feel like I'm doing something wrong... How come other people are not so reliant on this feature?

**Comment by cursive-ide** [comment]
After some investigation, it turns out this doesn't work properly in a lot of "small" editors, including the Python console and the Kotlin REPL. It's a general problem with editors which aren't backed by a real file. I'm investigating to see if I can fix it.

**Comment by cursive-ide** [comment]
So I've hacked a fix for this, and it seems to work. It's a little fragile though, so I'm checking with JetBrains if there's a better way.
