### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by favila** [cursive-ide/cursive#1130]
After upgrading to Cursive 0.1.67, I notice after a few hours of coding that IDEA memory consumption grows and will not free even after closing all projects (but not closing IDEA completely). Eventually the UI becomes glitchy and unresponsive. I didn't have this problem in 0.1.63 (my previous version).

Unfortunately I upgraded Ubuntu from 15.04 to 15.10 around the same time, so I am not sure if this is a cursive issue or an IDEA+Ubuntu Wily issue (there have been some that I hit). I'm seeing if anyone else has observed this issue and so can rule out IDEA+Ubuntu interactions.

I am using openjdk-8_66 with IDEA 14.1.5.

**Comment by danielcompton** [comment]
What are your logs like? I've noticed if I log a lot of events that I can use up heaps of memory.

**Comment by cursiveclojure** [comment]
There's also a new release of ShimDandy out in the last couple of days, which fixes a classloader leak that was discovered in boot. It's not clear to me whether the conditions that led to the problem might apply to Cursive or not, but I'll upgrade and we can see if that helps. 

With this change I've been restarting IntelliJ pretty frequently since it's difficult to use a REPL (the lein environment is set up and torn down for each operation) so I might not have seen a leak.

**Comment by cursiveclojure** [comment]
I also just found another classloader leak. I don't think this should have leaked significant amounts of memory on JDK8, but it's a problem for the permgen in JDK6, at least. I assume openjdk 8 has also removed the permgen?

**Comment by favila** [comment]
Yes, openjdk8 has no permgen, and this is unlikely a metaspace leak because system memory is under control: the jvm heap is what is consumed. I've also always restarted before I got to an OOM. I just know that memory in use is >90% of max, forced GCs after closing all projects (from the welcome screen) do not free anything, and there is significant ui jank that feels like typical GCs.

I'm sorry I haven't been able to reproduce this under controlled conditions or carefully compare it with 0.1.63+idea14+wily. It takes over a half day of work (no restarts, obviously) before I notice it. I did once do a memory dump in visualvm after it started running out of heap. The only thing I noticed was idea's awt event thread was performing a huge number of allocations/sec and holding on to a lot of memory (strings and chars mostly), but I have no idea if that is abnormal.

This week I started using IDEA 15 and I *feel* like the situation is better (I've gone 8 hours without a restart and the heap doesn't seem to be un-GC-able yet), so perhaps it was an idea14+wily issue after all.

**Comment by cursiveclojure** [comment]
Ok, if it happens again, could you take a heap dump and upload it somewhere I can look at it? I can give you details for an S3 bucket if required - drop me a mail on cursive@cursiveclojure.com.

**Comment by deaddowney** [comment]
I'm seeing the same issue and did a heap dump to see what is causing the issue:
 
"ApplicationImpl pooled thread 1267" prio=4 tid=91767 RUNNABLE
	at java.lang.OutOfMemoryError.<init>(OutOfMemoryError.java:48)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	   Local Variable: java.security.ProtectionDomain#1107
	   Local Variable: java.lang.String#395808
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	   Local Variable: java.security.CodeSource#1323
	   Local Variable: byte[]#112053
	   Local Variable: java.net.URL#2986
	   Local Variable: sun.misc.URLClassPath$JarLoader$2#1
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	   Local Variable: java.net.URLClassLoader$1#1
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	   Local Variable: java.lang.String#395805
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	   Local Variable: java.lang.Object#28153
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
	   Local Variable: clojure.lang.Symbol#1752
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	   Local Variable: class clojure.lang.Cons
	   Local Variable: clojure.lang.Cons#25
	   Local Variable: java.lang.String#395748
	   Local Variable: clojure.lang.Compiler$C#2
	at clojure.lang.Compiler.eval(Compiler.java:6779)
	   Local Variable: clojure.lang.Cons#5
	at clojure.lang.Compiler.eval(Compiler.java:6771)
	   Local Variable: clojure.lang.Cons#21
	   Local Variable: clojure.lang.Cons#22
	   Local Variable: java.lang.Integer#583
	at clojure.lang.Compiler.load(Compiler.java:7227)
	   Local Variable: clojure.lang.PersistentList#1976
	   Local Variable: clojure.lang.LineNumberingPushbackReader#2
	   Local Variable: java.lang.Object#28117
	   Local Variable: java.io.InputStreamReader#87
	at clojure.lang.RT.loadResourceScript(RT.java:371)
	   Local Variable: java.lang.String#395724
	   Local Variable: sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream#2
	at clojure.lang.RT.loadResourceScript(RT.java:362)
	   Local Variable: class clojure.lang.RT
	at clojure.lang.RT.load(RT.java:446)
	   Local Variable: java.lang.String#395721
	   Local Variable: java.net.URL#4876
	   Local Variable: java.lang.String#395687
	at clojure.lang.RT.load(RT.java:412)
	   Local Variable: java.lang.String#395686
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	   Local Variable: clojure.core$load$fn__5448#1
	at clojure.core$load.doInvoke(core.clj:5865)
	   Local Variable: clojure.lang.ArraySeq#1
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	   Local Variable: clojure.core$load#1
	at clojure.core$load_one.invoke(core.clj:5671)
	   Local Variable: java.lang.Boolean#2
	   Local Variable: clojure.core$load_one#1
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	   Local Variable: clojure.core$load_lib$fn__5397#1
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	   Local Variable: java.lang.Boolean#1
	   Local Variable: clojure.lang.PersistentArrayMap#2138
	   Local Variable: clojure.lang.Symbol#6289
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	   Local Variable: clojure.core$load_lib#1
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	   Local Variable: clojure.lang.Cons#1
	   Local Variable: clojure.lang.LazySeq#1
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	   Local Variable: clojure.core$load_libs#1
	at clojure.core$apply.invoke(core.clj:632)
	   Local Variable: clojure.core$apply#1
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	   Local Variable: clojure.core$require#1
	at clojure.lang.Var.invoke(Var.java:379)
	   Local Variable: clojure.lang.Var#486
	at org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl.require(ClojureRuntimeShimImpl.java:78)
	   Local Variable: com.intellij.util.lang.UrlClassLoader#1
	   Local Variable: java.lang.String[]#9394
	at cursive.leiningen.ShimBootstrap.invoke(ShimBootstrap.java:25)
	   Local Variable: cursive.leiningen.ShimBootstrap#1
	   Local Variable: java.lang.String#169105
	   Local Variable: java.net.URLClassLoader#4
	   Local Variable: java.net.URL[]#38
	   Local Variable: java.util.ArrayList$Itr#3
	   Local Variable: org.projectodd.shimdandy.impl.ClojureRuntimeShimImpl#1
	at cursive.leiningen.Shim$createShimProvider$1.invoke(Shim.kt:61)
	   Local Variable: cursive.leiningen.Shim$createShimProvider$1#1
	   Local Variable: java.util.LinkedHashMap#3084
	   Local Variable: java.util.ArrayList#27734
	at cursive.leiningen.project.LeinShimProvider$createShim$1.invoke(ProjectDetails.kt:63)
	at cursive.leiningen.project.LeinShimProvider$createShim$1.invoke(ProjectDetails.kt:29)
	   Local Variable: cursive.leiningen.project.LeinShimProvider$createShim$1#2
	at cursive.application.ApplicationKt$sam$Runnable$af99a863.run(Application.kt)
	   Local Variable: cursive.application.ApplicationKt$sam$Runnable$af99a863#2
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	   Local Variable: com.intellij.openapi.application.impl.ApplicationImpl$8#9
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	   Local Variable: java.util.concurrent.Executors$RunnableAdapter#23
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	   Local Variable: java.util.concurrent.FutureTask#15
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	   Local Variable: java.util.concurrent.ThreadPoolExecutor$Worker#34
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

If I do a OQL query in Java VisualVM for classloader types, I see 5 entries for clojure.lang.DynamicClassLoader with 580, 151, 7 and 3 instances respectively.

It appears to be in the Leiningen REPL integration.

**Comment by cursiveclojure** [comment]
Thanks for the investigation. It does look like a classloader leak - which JVM version are you using to run IntelliJ?

Could you load it up in Eclipse MAT and try the following steps? (there's a great tutorial with some screenshots [here](http://java.jiderhamn.se/2011/12/11/classloader-leaks-i-how-to-find-classloader-leaks-with-eclipse-memory-analyser-mat/).

1. Click Cancel in the Getting Started Wizard.
2. Open the Open Query Browser->Java Basics->Class Loader Explorer as shown in that article.
3. On those DynamicClassLoader instances, right click->Path to GC Roots->Exclude all phantom/weak/soft refs.

Does that show any obvious reason that those classloaders should be held? The usual culprit is being the context classloader for the agent thread pool, but I'm pretty sure I shut that down always now.

**Comment by cursiveclojure** [comment]
BTW if you'd rather send me the dump and I can investigate it, drop me a mail.

**Comment by cursiveclojure** [comment]
I actually ran into this myself today, so I have a heap dump from the crash. I'm seeing two java.net.URLClassLoaders, one of which seems to not be collected because it has an object lock on it (MAT reports "Busy Monitor"). @deaddowney do you see that in your dump? I don't have a good theory as to why this might happen though.

**Comment by deaddowney** [comment]
Hi, 
Unfortunately the problem occurs on my work machine and I can't send out the dump, but running MAT on the dump shows that the classloader is being held by the clojure-agent-send-off-pool
Hope that helps
On Nov 23, 2015 18:01, cursiveclojure <notifications@github.com> wrote:Thanks for the investigation. It does look like a classloader leak - which JVM version are you using to run IntelliJ?

Could you load it up in Eclipse MAT and try the following steps? (there's a great tutorial with some screenshots here.

Click Cancel in the Getting Started Wizard.Open the Open Query Browser->Java Basics->Class Loader Explorer as shown in that article.On those DynamicClassLoader instances, right click->Path to GC Roots->Exclude all phantom/weak/soft refs.

Does that show any obvious reason that those classloaders should be held? The usual culprit is being the context classloader for the agent thread pool, but I'm pretty sure I shut that down always now.

**Comment by cursiveclojure** [comment]
@deaddowney Thanks - which Cursive version are you running?

**Comment by deaddowney** [comment]
I'm using cursive-15-0.1.69
On Nov 25, 2015 12:02, cursiveclojure <notifications@github.com> wrote:@deaddowney Thanks - which Cursive version are you running?

**Comment by cursiveclojure** [comment]
@deaddowney Ok, that classloader leak was fixed in 0.1.70. Upgrading should fix it for you.

**Comment by cursive-ide** [comment]
Is this still a problem for anyone?

**Comment by favila** [comment]
The classloader leak fix resolved my original issue, which was memory not freeing even after closing projects and repls. However I still had memory problems, but they were resolveable by killing a repl or closing and reopening a project (rather than restarting IntelliJ)

But I think the latest repl-related memory improvements (#1598 #1605) have completely solved this for me. I've been editing a whole day and haven't had any memory problems, and a forced gc clears heap down to Xms, which was *never* true before. Thanks!

**Comment by cursive-ide** [comment]
Ok, great, thanks for letting me know! I'll close this for now, feel free to re-open if this isn't completely solved.
