### ISSUE TITLE
Can't save binding set of "none" in Clojure Keybindings

### ISSUE THREAD

**Issue by cjkent** [cursive-ide/cursive#1141]
I selected the Cursive binding set but found there were too many clashes so I decided to remove them and sort the keybindings out later when I had more time. But when I selected a binding set of "None" the Apply button greyed out and clicking OK didn't seem to save anything. 

The key bindings are still the Cursive bindings and when I reopen the settings the Cursive binding set is still selected. I had to go into the regular Keybindings settings and individually remove the bindings that were clashing.

I'm a bit puzzled by that settings pane. I was hoping to select the Cursive bindings and then deselect the ones that clashed with the existing bindings that I use. But I can't figure out a way to do that. Is it possible?

I assumed that's what the leftmost column of checkboxes was for but it doesn't seem to do anything. When I select the Cursive binding set none of the checkboxes in that column are selected.

**Comment by cursive-ide** [comment]
This has been obsoleted by #1863.
