### ISSUE TITLE
Emacs-style Lisp comment formatting

### ISSUE THREAD

**Issue by cursive-ghost** [cursive-ide/cursive#115]
See: http://stackoverflow.com/questions/6365334/lisp-commenting-convention

**Comment by qthompson** [comment]
Really minor, but does this automatically support `;;` style comments as shown in the following examples?

From https://www.gnu.org/software/emacs/manual/html_node/elisp/Comment-Tips.html:
```elisp
(prog1 (setq auto-fill-function
             …
             …
  ;; Update mode line.
  (force-mode-line-update)))
```

From http://stackoverflow.com/questions/6365334/lisp-commenting-convention:
```elisp
(defun test (a &optional b)
  ;; Commends indented along with code
  (do-something a)                      ; Comments indented at column 40, or the last
  (do-something-else b))                ; column + 1 space if line exceeds 38 columns
```
