### ISSUE TITLE
Open not importing

### ISSUE THREAD

**Issue by houghcr** [cursive-ide/cursive#1163]
With idea-community-15 and cursive 0.1.70 File->Open on a newly generated Leiningen project (via 'lein new foo', lein version 2.5.3) fails to import the project.

The Project tool window has no folders in it. It lists the top level files but any attempt at editing them brings up a dialog box "Non-Project Files Access" "These files to not belong to the project".

The only way I've found to open a new project is to close any others until the "Welcome to IntelliJ IDEA" floating dialog opens then choose "Import Project" from there. After that initial import the project can be opened as usual.

I'm sorry I can't tell what version of Cursive or of IDEA-15 this started during as I was working on the same project through the last few updates.

**Comment by cursiveclojure** [comment]
Could you reproduce and then send a copy of your log file (*Help->Show log in Finder/Explorer*) to cursive@cursiveclojure.com?

**Comment by danielcompton** [comment]
I was able to resolve this by updating to IntelliJ Ultimate 143.1183.10. @houghcr could you try updating to the latest EAP build?

**Comment by houghcr** [comment]
Seems to have gone away when I updated to 143.1453.5.
