### ISSUE TITLE
Please support compojure-api macros

### ISSUE THREAD

**Issue by dpp** [cursive-ide/cursive#1179]
[compojure-api](https://github.com/metosin/compojure-api) provides enhanced macros for routing.

Cursive doesn't seem to support the macros and will often mark variables as "not found" when they are defined within the compojure-api routes.

It'd be super excellent if cursive supported the compojure-api macros.

This is a low priority for me... a nice to have.

**Comment by timgilbert** [comment]
I'd really like this too.

**Comment by ikitommi** [comment]
Have chatted with Colin about this, would like to provide the bindings, waiting for the Cursive extension api (and repo) to push the c-api definitions.

Related: https://github.com/cursive-ide/cursive/issues/147

**Comment by cursive-ide** [comment]
This has been fixed for the next build (1.3.0-eap1).

**Comment by ikitommi** [comment]
thanks!!
