### ISSUE TITLE
Problems debugging app launched through CIDER

### ISSUE THREAD

**Issue by grammati** [cursive-ide/cursive#1195]
Prior to 1.0, there used to be a way to manually go back to a previous version of cursive. There seems to no longer be a way to do this, or at least I can't find it.

The current version (1.1.0-14.1) is not working well and I would like to go back to 1.0. Is that possible?

thanks

**Comment by cursive-ide** [comment]
Yes, you can download https://updates.cursive-ide.com/downloads/cursive-1.0.0-14.1.zip and install from disk.

What are the problems you're having?

**Comment by grammati** [comment]
Thank you.

The problem was that I could not debug, but it turns out the version of cursive was unrelated.

The actual problem seems to be something in cider. Let me explain.

A common workflow for me is to use both cider and cursive together, like this:

- Add `:jvm-opts ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"]` to my project's dev profile
- Start cider repl from emacs and develop normally
- When I need to debug, attach the Intellij debugger to the running process and set breakpoints
- Eval in emacs via the repl, or C-c C-e, or by hitting a page in my browser, etc.
- Intelij stops at the breakpoints and I can debug

This worked great for me, because it allowed me to use both tools for what they do best (at least for me) - specifically, emacs for most editing, and intellij for debugging.

This no longer works. I'm not sure when it stopped. When I try this now, Intellij does not recognize any line-based breakpoints.

I investigated by setting an exception breakpoint, then adding code to my project to throw, and in this case the debugger does stop at the point of the throw. However, it does not recognize the source as being part of the project. In fact, using the the stack window, I can see the source of pretty much anything *except* code that is actually in my project! Code in my project shows up in the stack view as being in a seemingly generated namespace that contains "mranderson", and clicking it does nothing.

I'm not sure what, if anything, could be done in either cursive or cider to make them work together this way, but it would make me very happy if this workflow became usable again.

Thanks again!

**Comment by cursive-ide** [comment]
This sounds like something that has changed on the CIDER side, perhaps with the recent release. mranderson is the lib they use to rewrite CIDER dependencies so they don't conflict with application ones. However I'm surprised it's being applied to your application code, my understanding is that it shouldn't be. @bbatsov or @benedekfazekas may know more.

**Comment by bbatsov** [comment]
@grammati 

* Why aren't you using CIDER's own debugger? Probably it's not as sophisticated as Cursive's, but it gets the job done.
* I need more details about your setup. mranderson should definitely not be affecting your project's code - as Colin said we use to inline 3rd party deps, so they won't conflict with other versions of them in your own code.

**Comment by benedekfazekas** [comment]
as @bbatsov said mranderson should not affect your project's code.  showing up in a trace does not mean it does necessarily either. wonder if you have refactor-nrepl in your configuration though? if so try to set `cljr-eagerly-build-asts-on-startup` to nil in your emacs configuration and see if that helps.

**Comment by grammati** [comment]
@benedekfazekas , thank you, that seems to have worked.

With `cljr-eagerly-build-asts-on-startup` set to nil, Intellij breakpoints seem to work perfectly, up until I do some refactor operation. I did find-usages, and after that the breakpoints stop working.

**Comment by benedekfazekas** [comment]
that makes sense as when you run a refactor feature that needs the ASTs (like for example find usages does) refactor-nrepl builds the ASTs on demand. building the ASTs also means evaling the top level s-expressions in the project. if you are interested in the reasons I recommend @Bronsa 's talk on this year's clojureX https://skillsmatter.com/skillscasts/7239-immutable-code-analysis-with-tools-analyzer

**Comment by cursive-ide** [comment]
This is also one of the reasons I never eval anything :-)

Looks like this can be closed?

**Comment by benedekfazekas** [comment]
does not that (not evaling) imply limitations?

**Comment by cursive-ide** [comment]
It means I have to reimplement a lot of Clojure's semantics, and I have problems with macros that I have to solve via a (currently internal-only) extension API. But it has a lot of benefits, too.

**Comment by benedekfazekas** [comment]
Interesting stuff. Amazing workflow @grammati that you use both tools ;)

**Comment by grammati** [comment]
@cursive-ide , yes you can close this issue - it's not a cursive problem, although I did find another one while investigating (see below).

For the record, I believe the ultimate cause of being unable to stop at breakpoints is missing line numbers. If I have Intellij stop at a thrown exception in the same function where a line-based breakpoint fails to break, the stack viewer shows a line number of -1. This happens after refactor-nrepl builds the ast, or after evaluating a defn in emacs with C-M-x. Evaling the buffer with C-c C-k brings the line numbers back, and breakpoints work again.

The mranderson connection that I reported earlier was a red herring. The debugger was actually stopping on unrelated code in a similarly named namespace. That's #168, which I can now reproduce reliably.

**Comment by cursive-ide** [comment]
Interesting, I don't know why that would happen, that sounds like material for a refactor-nrepl bug to me.

Anyway, I'll close this. I'm very interested in repro steps for #168, but I'll move over there for that.
