### ISSUE TITLE
can not auto indent and auto complete when type parentheses

### ISSUE THREAD

**Issue by zjhmale** [cursive-ide/cursive#1205]
in old way if i type a left parentheses besides a pair of parentheses it will auto indent and auto complete

```
()
```
=>
```
() ()
```

but just an hour ago i suddenly find out that i can not use this magic any more if i do the same thing it will just add a left parentheses there like normal editors

```
()
```
=>
```
(()
```

for more i can not delete a pair of parentheses

in old way

```
()
```
=>
```

```

for now

```
()
```
=>
```
(
```

really wired, and i did not change any config for sure, how can i fix this issue?  i reinstalled the cursive plugin and still got the same issue.

**Comment by zjhmale** [comment]
@cursive-ide

**Comment by zjhmale** [comment]
@cursive-ide

**Comment by zjhmale** [comment]
enable structural editing can fix this

![2016-01-01 12 12 37](https://cloud.githubusercontent.com/assets/6234553/12066071/74341e44-b01c-11e5-8ffc-1b5396b32991.png)

by the way what is `Maintain selection when surrouding with braces`? i turned it on but nothing magic happened there when i programming with clojure

**Comment by cursive-ide** [comment]
Yes, you need structural editing on for these to work.
"Maintain selection..." is for when you have something selected and you open a paren to surround the selection (this requires *Editor&rarr;General&rarr;Smart Keys&rarr;Surround selection on typing quote or brace*). That flag controls whether the selection is maintained or removed.

**Comment by zjhmale** [comment]
got it, thx :)
