### ISSUE TITLE
Unable to download sources [1.1.0, IntelliJ 14.1.5]

### ISSUE THREAD

**Issue by hlship** [cursive-ide/cursive#1206]
When I attempt to download sources I get a failure referring to a plugin in the containing project.

![ifn_class_-_ereceipts-services_-____workspaces_walmart_ereceipts-services_](https://cloud.githubusercontent.com/assets/52660/12128120/343dd04a-b3b0-11e5-9f7b-2d39185fec5a.png)

No output in idea.log.

**Comment by hlship** [comment]
Under IntelliJ 15 EAP, I still see the error in the Error Log, but sources do seem to download.

**Comment by hlship** [comment]
Actually, it's inconsistent. I was able to download clojure's sources, but not certain others.

**Comment by hlship** [comment]
Still having the problem, and increasing annoyance.

I'm not on Intellij 16.1 and Cursive 1.2.1.

**Comment by cursive-ide** [comment]
Ok, I'll try to take a look at this for the next build.

**Comment by hlship** [comment]
Happiness!
