### ISSUE TITLE
IntelliJ hangs when opening large project

### ISSUE THREAD

**Issue by levand** [cursive-ide/cursive#1213]
IntelliJ opens and displays the splash screen fine, but when I open a certain large project, IntelliJ hangs hard. The UI becomes completely unresponsive (beachball on OSX El Capitan), and I am forced to do a hard kill of the IntelliJ process.

This happens consistently with this one project, other projects are fine. The only way to get it to stop happening is to delete the `.idea` and `*.iml` files and recreate the project, in which case it works fine for 1-2 days until the problem starts happening again.

This is using 1.1.0-15, and I have observed this issue on IntelliJ 14.1 and 15.0.2. I do suspect Cursive is at fault, since the project opens if I disable the Cursive plugin. 

I have attached log fragments from the IntelliJ log and a thread dump of the IntelliJ process in its "hung" state. It looks like a deadlock in the Swing event thread, perhaps?

Unfortunately this is a high severity issue for me, as this is my "day job" project.

[intellij-log.txt](https://github.com/cursive-ide/cursive/files/87508/intellij-log.txt)
[intellij-dump.txt](https://github.com/cursive-ide/cursive/files/87509/intellij-dump.txt)

**Comment by pmoriarty** [comment]
Looks like this is related to #1210. Same stack trace:

```
AWT-EventQueue-0 15.0.2#IC-143.1184.17, eap:false" #26 prio=6 os_prio=31 tid=0x0000000102b02800 nid=0xfa03 runnable [0x0000700002cb4000]
   java.lang.Thread.State: RUNNABLE
	at cursive.resolve$light_keys.invoke(resolve.clj:168)
	at cursive.resolve$resolve_keys.invoke(resolve.clj:179)
```

**Comment by cursive-ide** [comment]
Yes, this looks like #1210.
