### ISSUE TITLE
Cursive not working in Andoid Studio - compiles ok, but won't build

### ISSUE THREAD

**Issue by SteveInNZ** [cursive-ide/cursive#1218]
I can install `Cursive` into `Android Studio`, and it seems to compile ok and run in a `leiningen` `REPL`, but when I try and build and deploy to an Android device, the build fails with errors, as follows:

    Error:(6, 18) error: package com.domain does not exist
    Error:(15, 49) error: cannot find symbol variable tiny

I have a stackoverflow post which explains the steps I took in detail:
http://stackoverflow.com/questions/34778119/how-to-build-android-apps-using-cursive-in-android-studio

When I try the same example in `IntelliJ` it works fine, and I can get `lein-droid` samples working fine too, it looks like there's something different in the way `Android Studio` does it's build that `Cursive` isn't accounting for maybe?

If I try calling my Clojure code from Java using another method, ie:

    IFn clojureFunction = Clojure.var("com.comain.tiny", "binomial");
    clojureFunction.invoke(1, 2);

This will build and deploy to a device, but comes up with an error at runtime:

    Caused by: java.lang.IllegalStateException: Attempting to call unbound fn: #'com.domain.tiny/binomial
    at clojure.lang.Var$Unbound.throwArity(Var.java:43)
    at clojure.lang.AFn.invoke(AFn.java:36)
    at clojure.lang.Var.invoke(Var.java:383)

So it looks like the the same problem, ie the classes haven't been included in the build.

**Comment by cursive-ide** [comment]
Thanks for the detailed description - I posted [an answer](http://stackoverflow.com/a/34802728/155368) over there, does that help?

**Comment by SteveInNZ** [comment]
Hi, thanks for the suggestion, but it didn't help. (I've added a comment on stackoverflow - would you prefer me to comment here, stackoverflow, or both?)

**Comment by cursive-ide** [comment]
Let's discuss it over here, then we can update over there if/when we find the answer.

So after changing that config, if you do a *Build->Rebuild Project* do you see Clojure classes appearing in your output path?

**Comment by SteveInNZ** [comment]
No, I don't see any Clojure class files being generated. (gradle seems to generate the Java classes inside `app/build/intermediates/classes/debug` BTW) Note that at this stage I don't have leiningen configured - does Cursive require leiningen to be able to compile it's classes? I could set that up, but I'm not sure where I should set it to generate it's classes to)

**Comment by cursive-ide** [comment]
No, it shouldn't require Leiningen. If you look in *File->Project Structure->[your module]->Paths*, does the output path look right?

**Comment by SteveInNZ** [comment]
There is no `Paths` tab there, this is one of place where Android Studio differs from IntelliJ. The only way I can see to add something to the classpath is when you first create a file and it says `File tiny.clj is not under a source root` so you click on `Add source root`. I also tried adding a new Clojure file under the existing Java src root to see if it built it from there, but no luck.

**Comment by cursive-ide** [comment]
Ok, I'm going to try to set this up with your instructions and see if I can see what's going on since I'm not at all familiar with Android Studio.

**Comment by cursive-ide** [comment]
Ok, here's what I've discovered. It seems that in Android Studio, all projects are managed by Gradle. Gradle doesn't support Clojure by default, but there's a plugin to enable that: [Clojuresque](https://bitbucket.org/clojuresque/clojuresque). I don't know what the state of it is, given that the documentation example says to use 1.0.0, but the current version is 1.7.0. There's a [pull request](https://bitbucket.org/clojuresque/clojuresque/pull-requests/1/readme-usage-example-update/diff) (in fact, the only open pull request on the project) to fix that. Unfortunately, the [only open issue](https://bitbucket.org/clojuresque/clojuresque/issues/1/the-plugin-is-not-compatible-with-googles) on the project says that Clojuresque is not compatible with Android, and indeed after some faffing around I managed to add the following to my `build.gradle`:

```
buildscript {
    repositories {
        mavenCentral()
        maven { url 'http://clojars.org/repo' }
        maven { url 'https://oss.sonatype.org/content/repositories/releases' }
    }
    dependencies {
        classpath 'clojuresque:clojuresque:1.7.0'
    }
}

apply plugin: 'clojure'
```

Adding this leads to the following error: 

> Error:The 'java' plugin has been applied, but it is not compatible with the Android plugins.

I believe Clojuresque is based on the Java plugin, which might explain that.

Unfortunately, my knowledge of Android Studio and Gradle is practically nil. I don't know how easy this would be to fix, if it's possible at all. @kotarak may know more. I believe the first step would be to try to get Android apps to build with Gradle, but I suspect that Cursive would still need some work to function correctly with Android Studio (e.g. fix the namespace creation bug you found, and I suspect that Cursive should not mark directories as source - that should be done from Gradle).

Alternatively, it should be possible to build Android apps using only leiningen, but then you miss out on the Android specific tooling in AS - I don't know how big a loss that is.

Sorry I don't have a better answer.

**Comment by SteveInNZ** [comment]
Ok, thanks for your time looking into this. I have used `lein-droid` (https://github.com/clojure-android/lein-droid) successfully to build and run Android apps, but having to use Emacs as an IDE doesn't really fill me with joy - especially after having being introduced to `Cursive` - I'd much prefer a modern IDE rather than one from 40 years ago :-)

I'm sure there are others who use Android Studio and Clojure who'd like to see this working, so I'll keep an eye on this issue and hopefully someone else will come along with more knowledge of Android and the Gradle build process.

**Comment by cursive-ide** [comment]
Hehe, I totally understand. Note that there should be nothing stopping you from using lein-droid with Cursive - just create a lein project and then import it into Cursive. That should work, except that as I mentioned above you won't get the Android Studio goodness, whatever that is.

**Comment by SteveInNZ** [comment]
For reference, I've just found an issue logged with `Clojuresque` on this subject. Unfortunately there hasn't been any activity on this issue for 18 months:
https://bitbucket.org/clojuresque/base/issues/20/clojuresque-is-incompatible-with-android

**Comment by cursive-ide** [comment]
I see, that issue seems to be on the `base` project, I hadn't checked there. Hopefully you get some response there, it would be nice if this worked.

**Comment by SteveInNZ** [comment]
> there should be nothing stopping you from using lein-droid with Cursive

Just out of interest sake, I've tried that, but when I try to build the project I get this:

    Error:Android Dex: [leindroidtest] Unable to execute DX
    Error:Android Dex: [leindroidtest] com.android.dex.DexException: Multiple dex files define Lclojure/asm/AnnotationVisitor;
There may be some settings somewhere to fix this but I know way too little about the build process to be able to go any further without some help.

**Comment by cursive-ide** [comment]
Hmm, I'm not sure about this sorry - I've never used it. Perhaps the lein-droid community could help you out with this.

In the meantime, I'm going to close this issue. It's unfortunate that this doesn't work, but the reasons for it not working don't seem to be Cursive-specific.

**Comment by cursive-ide** [comment]
@SteveInNZ There's a new Gradle Clojure plugin which might work better for Android development. You can find it [here](https://github.com/graclj/graclj). If you do try it, I'd be very interested to know how it works. @ajoberstar would probably be interested to know too.

**Comment by SteveInNZ** [comment]
@cursive-ide @ajoberstar I've given Graclj a try, and after a little tweaking, have managed to get it running in Android Studio. However, I don't know enough about Gradle or the plugins to know how to integrate the compilation of the Clojure compile  into the Android build process, so I've raised an issue with Graclj and a new stackoverflow question:
https://github.com/graclj/graclj/issues/40
http://stackoverflow.com/questions/35965305/how-do-i-use-clojure-in-android-studio-using-graclj
Fingers crossed...

**Comment by cursive-ide** [comment]
@SteveInNZ I've actually spent some time migrating the Cursive build to Gradle, and I have a simple compile + test plugin working. I based it on the Kotlin plugin, and that also has an Android version. I'll try to get that tidied up this week with the Android code added so you can try it out. It's using a custom plugin, not graclj, since I couldn't get graclj to work with the plugins I needed since it's using some features that are upcoming but not stable yet.

**Comment by SteveInNZ** [comment]
@cursive-ide I'm certainly interested in your experimental plugin, if there's anything you'd like me to do to help you with testing etc just let me know. I've done quite a bit of work in Android Studio so am happy to help out where I can !

**Comment by aadrian** [comment]
> I've actually spent some time migrating the Cursive build to Gradle and I have a simple compile + test plugin working.

Any news on publishing the plug-in ?

Most of our projects consist of modules in several languages (hence Gradle) and so far Clojure is the only one that needs a separate Projects :(.

All Clojure users I know (that do production stuff) are in the same position, and often we do small modules in other languages just because it's less effort instead of starting and "integrating" a new Clojure "project" just for that. 

Not sure though what Lein could do to make this Gradle integration easier, since Lein will never support so many different platforms like Gradle does.

**Comment by cursive-ide** [comment]
I just haven't got around to it. I'm planning to cut an EAP release either tomorrow or Monday, and I'll release it next thing after that.

**Comment by cursive-ide** [comment]
I've just published the [Gradle plugin](https://github.com/cursive-ide/gradle-clojure), see [here](https://cursive-ide.com/archive/2132.html) for details. It does not yet have support for compiling Android code, I'll add that soon.

**Comment by aadrian** [comment]
> I've just published the Gradle plugin, see here for details. 

Fantastic! Thank you!

Now we only need in IntelliJ when creating a Gradle based project:
![cursive_gradle_multi](https://cloud.githubusercontent.com/assets/140953/18118011/83c639fa-6f52-11e6-837c-66cd09c038ea.png)

to have Cursive as an option, the same way it's available when creating a Java one:
![cursive_java_multi](https://cloud.githubusercontent.com/assets/140953/18118019/9b004d7c-6f52-11e6-8657-4d8d2e70d4c4.png)

and use use your Gradle plug-in in the generated project files :).

**Comment by cursive-ide** [comment]
Yes, that would be nice - I'll wait a bit until I'm sure it's stable, and then add that.
