### ISSUE TITLE
  "Send X to REPL" not working

### ISSUE THREAD

**Issue by nathvi** [cursive-ide/cursive#1220]
What I did:
1. Highlighted the text (+ 2 2) in my editor
2. Right clicked.
3. Selected REPL 
4. Clicked Send '(+ 2 2) to REPL 

What error I got in the REPL:
CompilerException java.lang.RuntimeException: Unable to resolve symbol: +

**Comment by cursive-ide** [comment]
This is not a bug. When you send forms from the editor to the REPL, by default they are executed in the namespace of the file from which you sent them, not the current namespace in the REPL. If you have not loaded that file into the REPL, then the namespace will not have been created and the symbols from `clojure.core` will not have been referred into it. You can fix this problem by doing *Tools&rarr;REPL&rarr;Load File in REPL* before sending the form to the REPL.

**Comment by nathvi** [comment]
Gotcha. Thanks.
