### ISSUE TITLE
High CPU usage (600%)

### ISSUE THREAD

**Issue by pmoriarty** [cursive-ide/cursive#1224]
Suddenly started seeing 400-600% CPU usage. I was editing a build.gradle file at the time and it seems that the high usage eventually stops if I leave the IDE idle. Touching the file starts it off again.

Note, I'm using `gradle idea` to build the iml and ipr files rather than pointing IDEA to the gradle build files. I'm also only making whitespace changes to the file.

IDEA keeps throwing thread dumps at me which look like Cursive is heavily involved:

[threadDump-20160120-124916.txt](https://github.com/cursive-ide/cursive/files/97441/threadDump-20160120-124916.txt)
[threadDump-20160120-124615.txt](https://github.com/cursive-ide/cursive/files/97442/threadDump-20160120-124615.txt)
[threadDump-20160120-123828.txt](https://github.com/cursive-ide/cursive/files/97443/threadDump-20160120-123828.txt)
[threadDump-20160120-123403.txt](https://github.com/cursive-ide/cursive/files/97444/threadDump-20160120-123403.txt)

IDEA 15.0.2
Cursive 1.1.0
OS X 10.11.2

**Comment by pmoriarty** [comment]
More thread dumps...

[threadDump-20160120-130448.txt](https://github.com/cursive-ide/cursive/files/97461/threadDump-20160120-130448.txt)
[threadDump-20160120-133850.txt](https://github.com/cursive-ide/cursive/files/97506/threadDump-20160120-133850.txt)

**Comment by pmoriarty** [comment]
Just an update here. Disabling either the Gradle plugin OR Cursive fixes this issue.

Here are some more thread dumps after enabling both plugins and opening just build.gradle in the editor (no clojure files open):

[threadDump-20160122-090136.txt](https://github.com/cursive-ide/cursive/files/100508/threadDump-20160122-090136.txt)
[threadDump-20160122-090335.txt](https://github.com/cursive-ide/cursive/files/100509/threadDump-20160122-090335.txt)

**Comment by pmoriarty** [comment]
Seeing this in most of the thread dumps:

```
	at cursive.psi.impl.javaView.ClojureClassFinder.findPackage(ClojureClassFinder.java:116)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findPackage(JavaPsiFacadeImpl.java:224)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyImportHelper.processImplicitImports(GroovyImportHelper.java:98)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileImpl.processDeclarations(GroovyFileImpl.java:167)
```

Looks like some interplay between the Groovy plugin and Cursive.

**Comment by pmoriarty** [comment]
Possibly related to https://youtrack.jetbrains.com/issue/IDEA-143913

**Comment by pmoriarty** [comment]
Still seeing this with IDEA 2016.1 and Cursive 1.2.4. Disabling the Gradle plugin fixes the issue. The Groovy plugin can still be used.

**Comment by pmoriarty** [comment]
As I tend to use the IDEA plugin for Gradle disabling the Gradle plugin for IDEA is ok for me for now. Since you seem to use Gradle too I curious to know if you've encountered this?

**Comment by cursive-ide** [comment]
I haven't seen this one in particular but I have seen some performance weirdness recently. I'll investigate this as part of that.

**Comment by cursive-ide** [comment]
Closing this issue since I believe it's been fixed in the dev build you've been using. Let me know if that's not the case.
