### ISSUE TITLE
Possible incorrect indentation for forms used in anonymous functions

### ISSUE THREAD

**Issue by jhalterman** [cursive-ide/cursive#1227]
When using a form like `let` inside an anonymous function, the body of the let statement does not indent as it typically does elsewhere. See attached screenshot:

![screen shot 2016-01-20 at 7 19 22 pm](https://cloud.githubusercontent.com/assets/228804/12470654/e2d552d0-bfaa-11e5-89bf-64f5f106b02f.png)

**Comment by cursive-ide** [comment]
Interesting, would you like it indented one space more there? That happens because the "paren" in that case is two chars wide.

**Comment by jhalterman** [comment]
Ah, that makes sense about the two char side "paren". One more character would make it appear indented in the same way as other `let` statements, so yea, that is what I was expecting (FWIW :) )
