### ISSUE TITLE
Make Cursive compatible with IntelliJ 16 EAP

### ISSUE THREAD

**Issue by extesy** [cursive-ide/cursive#1228]
IntelliJ 16 EAP has been released for a few weeks now and is quite stable, but Cursive IDE plugin is not available for it. It makes me sad :cry:

**Comment by SerCeMan** [comment]
:+1:

**Comment by extesy** [comment]
@cursive-ide IntelliJ 16 is now in public preview: https://www.jetbrains.com/idea/nextversion/

**Comment by mehrad-rafigh** [comment]
+1

**Comment by jorge-marques** [comment]
:+1:

**Comment by extesy** [comment]
@cursive-ide Has 1.1.1 been released?

**Comment by cursive-ide** [comment]
It hasn't, no - I've actually found a pretty bad problem with v16 which I'm trying to fix now.

**Comment by stoyle** [comment]
v16 is officially out, and this issue has been closed, but that was before your last comment. Fixed, or still working on it?

**Comment by cursive-ide** [comment]
It's fixed, but Parinfer (the other main feature of this release) has been much more difficult than expected. I hope to make this release tomorrow.

**Comment by cursive-ide** [comment]
Cursive 1.2.1 is out now!

**Comment by ulvigu** [comment]
Thank you!

**Comment by fatlazycat** [comment]
How do you install this ? I'm in 2016.1, gives me an option to install a 15-1.2.1 of the plugin.

Seems to download it then nothing. i.e. no option to restart etc.

If i restart intellij it appears not to be installed.

Diff plugin needed ?

Thanks

**Comment by cursive-ide** [comment]
That's really strange, that version of the plugin is wrong for your version of IntelliJ. Can you attach a screenshot of what you're seeing in the plugin settings window?

**Comment by fatlazycat** [comment]
<img width="997" alt="choose plugins to install or enable" src="https://cloud.githubusercontent.com/assets/338975/13903379/1dd2c2a2-ee70-11e5-91b9-545ec6e5a340.png">

**Comment by cursive-ide** [comment]
How are you getting to that page? It doesn't look like any of the windows I get in *Settings&rarr;Plugins*

**Comment by fatlazycat** [comment]
When it's trying to configure plugins for unknown types.

<img width="936" alt="browse repositories" src="https://cloud.githubusercontent.com/assets/338975/13903397/cf7fc306-ee70-11e5-8b9d-8b0981e81eb6.png">

**Comment by cursive-ide** [comment]
That's just because I can't figure out their date format :-)

That is very strange - I can't see why it should offer you the older version. If you download [this file](http://updates.cursive-ide.com/downloads/cursive-1.2.1-2016.1.zip) and *Settings&rarr;Plugins&rarr;Install from Disk* that should work.

**Comment by fatlazycat** [comment]
Thanks that works.

**Comment by dhruvbhatia** [comment]
Experienced the same message as @fatlazycat , but downloading and manually installing the `.zip` worked. :+1:

**Comment by eatobin** [comment]
I have the same comment as the two above and my screen shot would have been identical. The manual install did the job but this plugin was unavailable through IDEA 2016.1...

**Comment by dl1ely** [comment]
Yes, same here. Did update from 2015 to 2016, then Cursive plugin was displayed as incompatible with my IJ version. Did uninstall it, and when reinstalling, i only get the v15 plugin offered in the list of available plugins.

**Comment by dl1ely** [comment]
Oh, after doing the „from disk“ install and restarting IJ, i got a popup like „repository URLs updated for 2016.1“, and now the 2016 version of Cursive is listed when browsing the repositories. This is strange, as i did restart IJ after deinstalling the old version of Cursive.

**Comment by mehrad-rafigh** [comment]
I had no issues btw. I was able to install the right version of cursive on my Intellij 2016.1 from the plugins menu.

**Comment by dustingetz** [comment]
Same issue - upgraded to idea 2016.1 today and am offered incompatible version of cursive. I believe caused by importing settings, it sees the old custom repo url. Removing the customized repo url fixed issue and can install now.

**Comment by cursive-ide** [comment]
@dustingetz Yes, that's the problem, sorry, I discussed it in Slack but didn't update this issue. Basically it's an IntelliJ bug, which will show you incorrect versions from the custom repos that Cursive uses for EAP releases. Removing the custom repo and refreshing should show the correct version.
