### ISSUE TITLE
Intellij crashes when adding a leiningen project

### ISSUE THREAD

**Issue by ricecooker** [cursive-ide/cursive#1230]
When adding project.clj as a Leiningen Project, IntelliJ just crashes.
IDEA version: 15.0.3
Cursive: 1.1.0-15
Platform: OSX 10.11.2

Only message in idea.log is:
```
2016-01-22 15:09:57,892 [2814688]   INFO -        #com.intellij.idea.Main - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------
2016-01-22 15:09:57,938 [2814734]   INFO - il.indexing.FileBasedIndexImpl - START INDEX SHUTDOWN
2016-01-22 15:09:58,018 [2814814]   INFO - il.indexing.FileBasedIndexImpl - END INDEX SHUTDOWN
2016-01-22 15:09:58,018 [2814814]   INFO - stubs.SerializationManagerImpl - START StubSerializationManager SHUTDOWN
2016-01-22 15:09:58,018 [2814814]   INFO - stubs.SerializationManagerImpl - END StubSerializationManager SHUTDOWN
2016-01-22 15:09:58,050 [2814846]   INFO - newvfs.persistent.PersistentFS - VFS dispose started
2016-01-22 15:09:58,267 [2815063]   INFO - newvfs.persistent.PersistentFS - VFS dispose completed
2016-01-22 15:09:58,268 [2815064]   INFO - org.jetbrains.io.BuiltInServer - web server stopped
```

Project.clj file below:
[project.clj.txt](https://github.com/cursive-ide/cursive/files/101381/project.clj.txt)

**Comment by cursive-ide** [comment]
That's very strange - how are you adding this? Using the context menu in the project window?

**Comment by ricecooker** [comment]
Either.  Started happening when my trial ended and I added my license.  IntelliJ would crash at startup and I had no idea why.  Generally after indexing when it started synchronizing Leiningen is when it dies.

Only had a better idea after I deleted my .iml, .idea folders, recreated the project as a regular cli project everything was okay.  Then when I right-context click project.clj and click on "Add as Leiningen Project" that's when it crashes.

Alternately if I open the project.clj, I get the notification up top that the file isn't registered as a Leiningen Project.  If I click on the "Add" link, it then crashes the same way.

**Comment by cursive-ide** [comment]
That's truly bizarre. I'll look at this first thing next week.

**Comment by ricecooker** [comment]
Much appreciated.  Thanks for the quick response.  Let me know if there's anything I can do in terms of log files, etc.

**Comment by cursive-ide** [comment]
If you could send a log file (*Help->Show log in Finder/Explorer*) after reproducing the problem that would be useful.

**Comment by ricecooker** [comment]
Here you go!
[idea.log.txt](https://github.com/cursive-ide/cursive/files/103667/idea.log.txt)

**Comment by ricecooker** [comment]
In case anyone else is having the issue, to open the project after messing it up, remove the following from $PROJECT_DIR$/.idea/misc.xml

```
  <component name="LeiningenProjectsManager">
    <option name="projectFiles">
      <list>
        <option value="file://$PROJECT_DIR$/project.clj" />
      </list>
    </option>
  </component>
```

**Comment by bsiver** [comment]
@ricecooker : I'm actually having a very similar problem right now, removing the project from the LeiningenProjectsManager allows IntelliJ to boot once again.  What exactly about your project.clj was causing the crash?  I can't seem to glean this info from the IntelliJ logs.

**Comment by ricecooker** [comment]
There's nothing in the intellij logs.  Was hoping someone on the cursive side could help me figure out the problem.  Happy to install a different build, etc to figure out what's wrong.

**Comment by cursive-ide** [comment]
@bsiver @ricecooker I'll look at this today. When you say it crashes, do you mean the whole IDE exits unexpectedly? Looking at the logs you've both sent, it looks like the IDE just suddenly shuts down. I wonder if a lein plugin is calling `System.exit()` or something.

I'll try to reproduce with the `project.clj` above.

**Comment by cursive-ide** [comment]
Sadly I can't reproduce - I can import the `project.clj` above fine. Can you give me any more detail about what "just crashes" means?

**Comment by bsiver** [comment]
@cursive-ide - In my case, IntelliJ closes entirely without presenting any error message.  I would expect to see an exception somewhere, but the logs are not very telling.  My project.clj does require dependencies that are also a part of the same workspace, I'm not sure if that's potentially causing a problem.

**Comment by cursive-ide** [comment]
@bsiver If you comment out any lein plugins in your `project.clj` and `profiles.clj` does that help?

**Comment by bsiver** [comment]
@cursive-ide Good catch!  I tried commenting out plugins line by line, and found out the presence of the `lein-ring` plugin seemed to be causing the crash.  I was able to add my project successfully after that.  Strangely, the crash doesn't persist when I uncomment that plugin after adding the project.  Thanks for the help.

**Comment by cursive-ide** [comment]
@bsiver Very strange! I'll look through the source of that plugin and see if I can see a `System/exit` in there anywhere.

@ricecooker Does commenting out plugins help your case as well?

**Comment by ricecooker** [comment]
@cursive-ide My offending plugin is: ```[lein-version-script "0.1.0"]```.  Unlike bsiver when if I uncomment the line the crash persists at the next start or when the "Refresh Leiningen Projects" button is pushed in the Leiningen view.

**Comment by cursive-ide** [comment]
@ricecooker Thanks, I'll try to reproduce with that. That plugin is calling `leiningen.core.main/abort`, which I have hooked so this doesn't happen. I'll investigate why that might not work.
