### ISSUE TITLE
Disable automatic formatting

### ISSUE THREAD

**Issue by casperc** [cursive-ide/cursive#1231]
When using the 'raise' command, automatic formatting is fired as well, changing code that has nothing to do with the form or lines I am changing.

It might be the case that other editor actions also fire an autoformat.

In my eyes this is a big 'no no', since it tends to obfuscate revision history. Can this please be disabled, or have an option to disable?

**Comment by cursive-ide** [comment]
This seems similar to #836. I'll close this, please comment over there whether the proposed solution would work for you.
