### ISSUE TITLE
IntelliJ crashes when adding a submodule from existing sources

### ISSUE THREAD

**Issue by bsiver** [cursive-ide/cursive#1234]
I have an existing project that I am attempting to add a submodule to.  The project has 3 submodules, but when attempting to add one submodule in particular, IntelliJ crashes every time and then subsequently crashes every time I restart IntelliJ.  If I remove the submodule from `  <component name="LeiningenProjectsManager">` in `.idea/misc.xml`, IntelliJ starts just fine.

Here is my [idea.log ](https://gist.github.com/bsiver/b49add73af7a55e37b51) file from when the crash happens.

**Comment by cursive-ide** [comment]
Can you confirm that this is the same problem as #1230, i.e. that disabling the plugin fixes it? If so we can close this as a dupe.

**Comment by bsiver** [comment]
@cursive-ide: yup, I will close this one.
