### ISSUE TITLE
add link to intellij-keymap-exporter plugin to Cursive documentation

### ISSUE THREAD

**Issue by behrica** [cursive-ide/cursive#124]
I think that in order to efficiently work with Cursive, the user need to learn the keystrokes for the paredit-like mode.

I configured them for me, but there is no easy way to print them nicely.

On my research to do so, I found the intellij-keymap-exporter plugin, which allows to export the current keymap to a nicely formatted pdf file.

In its current state the plugin hard-codes the list of all actions, for which it prints the key binding. But it was rather easy to extend this list with the Cursive action id's.

The result is a nice one-page pdf, showing all my key-bindings including the Cursive ones. You can find an example here for reference: https://github.com/behrica/intellij-plugin-export-keymap/blob/master/example-keymap.pdf?raw=true

The source code of my modification is here: https://github.com/behrica/intellij-plugin-export-keymap

It is still in a rather crude state, but the gradle build file is able to create a correct jar of the plugin. This jar is not yet a correctly packaged intellij plugin, but by doing the following steps you can get it working already:
1. Download the original plugin from here: http://plugins.jetbrains.com/plugin/7066?pr=phpStorm
2. Build the jar from this source: https://github.com/behrica/intellij-plugin-export-keymap with gradle. (it still contains hradcode links to my intellij installation, which need to be changed)
3. Replace the jar inside the zip file you downloaded in step 1 (intellij-keymap.jar)
4. Install the plugin zip with Intellij plugin mamanger "install plugin from disk"

My next step is to make the gradle build file be able to build the plugin. then I add some documentation 

Maybe it would be useful that you add a link to it as part of the Cursive documentation

**Comment by fatlazycat** [comment]
+1

**Comment by jefffriesen** [comment]
I tried this plugin (https://plugins.jetbrains.com/plugin/7066?pr=phpStorm) but got errors:
```
IncompatibleClassChangeError: the number of constructors during runtime and compile time for com.intellij.openapi.ui.DialogWrapper do not match. Expected 6 but got 7
```
I know this isn't your plugin, but there's definitely a need to export a reference to Cursive and custom key bindings. When viewing the keybindings it's a modal and you can't edit your code at the same time. Are there any simple solutions to this that people have found?

**Comment by cursive-ide** [comment]
I'm sorry for the very long delay with this. #1863 has added an action (*Help->Show Cursive Cheat Sheet*) which will open an HTML cheat sheet in the browser. It contains CSS which means it should print ok, please let me know if there are issues with this. It should usually fit on one page, but that depends on the keymap since in some maps there are many more bindings defined - the Emacs ones in particular tend to spill over into a second page.
