### ISSUE TITLE
Project structure is ignored

### ISSUE THREAD

**Issue by andrusieczko** [cursive-ide/cursive#1245]
Hey,

My `.iml` file looks fine but some of the settings are completely ignored.

For example:
```
<orderEntry type="jdk" jdkName="1.8" jdkType="JavaSDK" />
```

When I restart IntelliJ, open Project Structure, I see the project uses Java 1.7 and when I go then to the `.iml` file, the entry with Java 1.8 disappears.

I can observe the same behavior with modules.

I'm using IntelliJ 14.1.5 and Cursive 1.1.0-14.1.

Thanks,
Karol

**Comment by cursive-ide** [comment]
I'm not sure this is Cursive related, since it shouldn't ever touch the project JDK, in particular. Are you using Leiningen? If so then the module JDK will be set to inherit from the project when it's synced, but I don't think Cursive ever updates the project JDK.

**Comment by andrusieczko** [comment]
Alright, thank you.

All my teammates have been having the same issue and we haven't experienced it with Java, so I assumed it must be Cursive.

I'll look at it more closely then. Closing the issue.

Thanks again!

**Comment by cursive-ide** [comment]
Ok, great - if you do come up with any more information let me know and I can investigate further.
