### ISSUE TITLE
Invalid license certificate

### ISSUE THREAD

**Issue by tomcz** [cursive-ide/cursive#1248]
I have purchased a commercial license but cursive does not accept it. It displays an 'Invalid License Certificate' message.

Yes, I have posted both the Begin and End lines.

**Comment by cursive-ide** [comment]
Did you get this resolved? There are a couple of things that typically go wrong here, let me know if this still isn't working.

**Comment by tomcz** [comment]
Still not working. Tried it in fresh installs of intellij ultimate and community editions.

**Comment by cursive-ide** [comment]
There are two main issues that occur here:

- If you're using Thunderbird as a mail client, uses the first of the dashes in the BEGIN LICENCE line as a quote mark, and removes it. That line should be the same length as the lines containing the hex digits, and as the END LICENCE line. If it’s one char shorter, manually add a dash at the beginning of that line and that should fix it.
- There is another issue which happens sometimes when copying the licence via Slack or Skype - there should be a blank line before the hex digits. If there isn’t one, adding that should fix it too.

**Comment by tomcz** [comment]
Right, it looks like gmail messes with the dashes as well, so you have to view the original email to get the right amount of dashes. My license is now working so thank you, but I would suggest that relying on the number of dashes to validate it is a little error prone.

**Comment by cursive-ide** [comment]
That's odd, no-one has ever reported that with gmail before. Did it also just take off the first dash? I've fixed the validation for that case, the validation is basically that the text is exactly right since it uses a digital signature.

**Comment by tomcz** [comment]
From the visible email:
-———- BEGIN LICENCE -———-
-———- END LICENCE -————-

From the raw email:
---------- BEGIN LICENCE ----------
---------- END LICENCE ------------

As you can see, all sorts of bad things happened to the dashes.

**Comment by cursive-ide** [comment]
That's bizarre. Thinking about it, I look at these licences all the time in Gmail, and I never see anything like that. Do you have any sort of plugin, or anything that might cause that?

**Comment by tomcz** [comment]
No idea, corporate gmail setup. Though to be honest the email itself was forwarded to me from our IT services. Who knows what they are running.

**Comment by cursive-ide** [comment]
Ok, that might have been the problem then. Anyway, it's not a problem a lot of people are having, so if it's working for you that's good enough for this issue I think. Thanks for the info!

**Comment by tomcz** [comment]
Yeah, something for me to remember if I see it happening to someone else. Thanks for you help mate.

**Comment by grandbora** [comment]
Came across the same problem my former colleague @tomcz has encountered. The same trick solved the issue for me. Would be nice if validation doesn't rely on the number of dashes.

**Comment by cursive-ide** [comment]
@grandbora In recent versions of Cursive, it no longer does - it just requires some number of dashes on either side of the BEGIN LICENCE and END LICENCE lines. I suspect that what is happening is that something somewhere in your email chain (I assume it's the same problem if you're colleagues) is replacing the dash character with something else - an em dash representing various dashes together, or something like that.
