### ISSUE TITLE
Sources of JDK and dependencies should not be included on classpath

### ISSUE THREAD

**Issue by pmoriarty** [cursive-ide/cursive#125]
Since 0.1.06 sources of dependent modules have been added to the classpath. 

Sources of the JDK and general dependencies are also included. This is dangerous since source jars are not meant for this.

In particular this is an issue for me since the neko-html source jar includes META-INF/services configuration that registers HTMLConfiguration and causes logback XML config files to be parsed as HTML breaking logging completely.

I think if you're going to continue to put dependent module sources on the classpath you should offer an option to disable that behaviour. I'm not convinced it's the right approach myself so I'd like to disable it.

For example, unless I exclude logback-test.xml from being copied to the output dir I get a warning about it appearing twice on the class path.

**Comment by cursiveclojure** [comment]
This is going way back in time, but just a heads up - in the next build this config flag will be moved from a project setting to an IDE one, which means it will apply to all projects. Re-reading the comments here it seems like this is what you'd want anyway. Unfortunately there's no good way to migrate project settings to IDE ones, so just so you're aware, you'll probably have to set this flag again after the next release.
