### ISSUE TITLE
Easy navigation to namespace declaration (with fuzzy matching) similar to "Navigate > Class..."

### ISSUE THREAD

**Issue by dragoncube** [cursive-ide/cursive#1251]
There are two possible solutions:
*  "Navigate > Symbol..." should include namespaces too
* OR add "Navigate > Namespace..." menu item

**Comment by cursive-ide** [comment]
In fact there is already a "Go to Namespace" action, but now that you mention it I didn't add it to the Navigate menu. I'll do that.

**Comment by dragoncube** [comment]
Oh, great! Adding it to the menu would help to discover it easier for new users, thanks!
