### ISSUE TITLE
Test actions don't obey the transitive loading flag

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1254]
Reported in Slack: the test actions (Run tests in NS and Run test under caret) both always sync transitively out of date files, they don't respect the flag to control whether this should happen.

**Comment by jcromartie** [comment]
:+1: this also seems to cause loading of files outside of source directories

**Comment by jcromartie** [comment]
Specifically: .clj files that are outside of my Leiningen project's source directories, but which have been recently modified in IntelliJ.

**Comment by cursive-ide** [comment]
Yes, that is an additional bug which would explain what you're seeing. I'm amazed no-one has come across this before.

**Comment by cursive-ide** [comment]
That's being tracked in #1255.
