### ISSUE TITLE
No Test Failure Highlighting

### ISSUE THREAD

**Issue by davidmace** [cursive-ide/cursive#1258]
I'm using Cursive in IntelliJ. When I run tests, I get the following output in the REPL and no highlighting of which test fails.

Error handling response - class java.lang.IllegalArgumentException: Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null

Ran 1 tests containing 1 assertions.
1 failures, 0 errors.

---

My code is as follows:

```
(ns yoyo
  (:use [clojure.test])
  )

(deftest foo
  (is (= 5 (+ 2 2))))
```

---

Thanks :).

**Comment by cursive-ide** [comment]
Could you attach your log (*Help-Show log in Finder/Explorer*) after reproducing this problem? Also, if you could create a small project showing the problem and put it on Github that would be great.

**Comment by lsenta** [comment]
I have the same issue, (IntelliJ 15.0.3).

No highlights in the editor and no feedback for errors in the REPL:

```
Testing my.core
Error handling response - class java.lang.IllegalArgumentException: Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null
Error handling response - class java.lang.IllegalArgumentException: Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null
Error handling response - class java.lang.IllegalArgumentException: Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null
Error handling response - class java.lang.IllegalArgumentException: Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null
Error handling response - class java.lang.IllegalArgumentException: Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null
Error handling response - class java.lang.IllegalArgumentException: Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null

Ran 1 tests containing 6 assertions.
2 failures, 0 errors.
```


here's the corresponding IJ log line:

```
2016-03-06 02:42:06,680 [ 486843]  ERROR -             cursive.repl.nrepl - Error handling response
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null
 at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByPath (LocalFileSystemBase.java:-1)
    cursive.testing.actions$find_file_and_line.invoke (actions.clj:197)
    cursive.testing.actions/fn (actions.clj:222)
    clojure.lang.MultiFn.invoke (MultiFn.java:229)
    cursive.testing.actions$test_handler$reify__11439.out (actions.clj:285)
    cursive.repl.nrepl$handler.invoke (nrepl.clj:283)
    cursive.repl.nrepl$nrepl_start$fn__3878$fn__3882$fn__3889.invoke (nrepl.clj:331)
    cursive.repl.nrepl$nrepl_start$fn__3878$fn__3882.invoke (nrepl.clj:330)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)
 ```

I haven't managed to reproduce the error. A minimal luminus project with a copy of my code and tests does not trigger the error.

Few notable things in my case:
- I have code in cljc
- I upgraded my project by:
    1. Move `current/` to `current-old/`
    2. Create `current/` project with last luminus template
    3. Copy code, test by test, from `current-old/*` to `current/`

The issue appeared after I delete `current-old`.
Clicking on "errors hypertexts" in the test REPL would redirect to the files of `current-old` half of the time.

- I tried to "Invalidate IntelliJ Cache and Restart", didn't solve the issue. 
- I tried to rename the `.iml` and `.idea` then re-create the project, didn't solve the issue.

**Comment by lsenta** [comment]
My issue happens on a single test file, `schart.test.core` that I created recently (not moved from `old`).
Copying the code in another test works, or running it in `schart.test.omg` works.

**Comment by katox** [comment]
I see these "@NotNull" errors if I add test.check defspec or test.chuck deftests into tested ns.

**Comment by dmarjenburgh** [comment]
Possible the same as #1525

**Comment by ronaldsuwandi** [comment]
Had the same issue as @lsenta before, turns out it's a dumb namespace error, in I used `-` in the package directory `blah-blah` instead of `blah_blah`. Fixed it by renaming the directory to use underscore

**Comment by Jarzka** [comment]
Same issue here. Caused by the fact that namespace and directory path did not match.

The error message given by Cursive should be improved.

**Comment by alexanderkiel** [comment]
I have still the same problem in `1.6.2-eap2-2017.2`:

```
2017-11-06 16:05:28,386 [ 870557]  ERROR -            #cursive.repl.nrepl - Error handling response
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null
 at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByPath (LocalFileSystemBase.java:-1)
    cursive.testing.actions$find_file_and_line.invoke (actions.clj:207)
    cursive.testing.actions/fn (actions.clj:215)
    clojure.lang.MultiFn.invoke (MultiFn.java:229)
    cursive.testing.actions$test_handler$reify__13194.out (actions.clj:289)
    cursive.repl.nrepl$handler.invoke (nrepl.clj:342)
    cursive.repl.nrepl$nrepl_start$fn__3802$fn__3806$fn__3813.invoke (nrepl.clj:403)
    cursive.repl.nrepl$nrepl_start$fn__3802$fn__3806.invoke (nrepl.clj:402)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)
```

I don't see anything special in my test. Would it be possible to throw a own exception with more details instead of invoking `findFileByPath` with a `null` `path`?

**Comment by Procrat** [comment]
I just upgraded to the latest version of IntelliJ and this error started occurring for me as well. I upgraded Cursive from the latest stable 1.6.1 to `1.6.2-eap2-2017.2`, but the problem persists.

```
2017-11-15 16:31:43,714 [ 295142]  ERROR -            #cursive.repl.nrepl - Error handling nREPL response
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null
 at com.intellij.openapi.vfs.impl.local.LocalFileSystemBase.findFileByPath (LocalFileSystemBase.java:-1)
    cursive.testing.actions$find_file_and_line.invoke (actions.clj:207)
    cursive.testing.actions/fn (actions.clj:215)
    clojure.lang.MultiFn.invoke (MultiFn.java:229)
    cursive.testing.actions$test_handler$reify__13194.out (actions.clj:289)
    cursive.repl.nrepl$handler.invoke (nrepl.clj:342)
    cursive.repl.nrepl$nrepl_start$fn__3802$fn__3806$fn__3813.invoke (nrepl.clj:403)
    cursive.repl.nrepl$nrepl_start$fn__3802$fn__3806.invoke (nrepl.clj:402)
    clojure.lang.AFn.call (AFn.java:18)
    java.util.concurrent.FutureTask.run (FutureTask.java:266)
    java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1142)
    java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:617)
    java.lang.Thread.run (Thread.java:745)
```

**Comment by Procrat** [comment]
I just upgrade again to the latest versions of IntelliJ and Cursive EAP and this problem no longer occurs! I'm not sure whether this was by accident or intentional, but thank you anyway!

**Comment by hannahhenderson** [comment]
I had the same error message, and eventually realized my Cursive license was expired, so I wasn't getting updates.

**Comment by conan** [comment]
Is there any way we can re-open this issue or should I start a new one?

**Comment by cursive-ide** [comment]
@conan Sorry, I've been travelling this week and haven't had a chance to look at this. I think opening a new issue linking to this one is probably the best thing to do since I suspect this is a new issue - the previous one was definitely fixed.

**Comment by christinning** [comment]
I can't see any new issue regarding this. 

I'm seeing the same thing only when I add a clojure.test.check.clojure-test defspec to my test. Test results are reported correctly.

Intellij 2017.3, 
Cursive 1.6.3-2017.3

```
{:result true, :num-tests 1000, :seed 1527346948322, :test-var "test-name"}
Error handling response - class java.lang.IllegalArgumentException: Argument for @NotNull parameter 'path' of com/intellij/openapi/vfs/impl/local/LocalFileSystemBase.findFileByPath must not be null

Ran 3 tests containing 4 assertions.
0 failures, 0 errors.

```

**Comment by Vinai** [comment]
Still happening with 1.9.1-eap1-2019.1
