### ISSUE TITLE
Feature request: Integrate with IntelliJ test panel

### ISSUE THREAD

**Issue by lsenta** [cursive-ide/cursive#1260]
`Tools→REPL→Re-run last test action in REPL` is pretty handy but without the ability to see the tests results from where I am it's almost useless.

Is there a way to integrate Cursive tests with [IntelliJ's panel](https://www.jetbrains.com/idea/help/viewing-and-exploring-test-results.html)?

**Comment by cursive-ide** [comment]
See [here](https://github.com/cursive-ide/cursive/issues/299#issuecomment-183995920) re: test results.

There's no test runner, but there will be soon. See #247. I'm going to close this as a dupe.
