### ISSUE TITLE
Leiningen 2.6.1?

### ISSUE THREAD

**Issue by eatobin** [cursive-ide/cursive#1262]
I may have missed this in documentation but does Cursive support Leiningen 2.6.1? I don't see how to select past version 2.5.3 in the Build Tools, Leiningen, Project Settings Preferences dropdown. Thank you.

**Comment by cursive-ide** [comment]
It doesn't yet, I'll add it for the next build.

**Comment by eatobin** [comment]
Great. Thank you.

**Comment by eatobin** [comment]
One other thing please: how do I switch from Stable to EAP builds so I can see this addition sooner? I uninstalled and re-installed Cursive but was not presented with the Stable/EAP choice like I was on "first" install. (Assume this option is stored somewhere with license info.) Don't see a choice elsewhere??
