### ISSUE TITLE
Switch between Stable/EAP builds?

### ISSUE THREAD

**Issue by eatobin** [cursive-ide/cursive#1263]
How does one switch from Stable to EAP builds once you have made an initial choice? I uninstalled and re-installed Cursive but was not presented with the Stable/EAP choice like I was on "first" install. Don't see a choice elsewhere in IntelliJ Preferences? Thank you.

**Comment by sfnelson** [comment]
Have a look in your IntelliJ Preferences directory (e.g. `~/Library/Preferences/IntelliJIdea15/`). In `options/options.xml` I see:

```
    <property name="cursive.eap.updates.asked" value="true" />
```

**Comment by eatobin** [comment]
Thank you. I changed this to:

<property name="cursive.eap.updates.asked" value="false" />

and hope I'm now on the EAP channel!

**Comment by marco-m** [comment]
Cursive documentation at https://cursive-ide.com/userguide/troubleshooting.html explains how to switch.

I think this ticked can be closed :-)
