### ISSUE TITLE
Refactoring when rename higher namespace level

### ISSUE THREAD

**Issue by kwladyka** [cursive-ide/cursive#1264]
It will be so great if refactoring will work also with changing higher namespace level.

For example moving from `foo.bar.abc` to `foo.abc`. Or when move form `foo.abc` to `foo.bar.abc`.

At that moment it doesn't work with change like this.

**Comment by danielcompton** [comment]
I think this is a dupe of https://github.com/cursive-ide/cursive/issues/817.
