### ISSUE TITLE
No closing parenthesis when starting anonymous function shorthand

### ISSUE THREAD

**Issue by mtruyens** [cursive-ide/cursive#1265]
Assume you have written
(  )
and your cursor is between the two parentheses. 
Now, when you try to insert an anonymous function shortcut — i.e. #( ... ) — no closing parenthesis is inserted when you have typed in the #(
As a result, at that point, you end up with an unbalanced expression:
(#()

Curiously, this bug does not show up when the outer parentheses are square brackets.

**Comment by dhruvbhatia** [comment]
I just tried to replicate this and can't. What v of IntelliJ and Cursive are you using?

![cursive](https://cloud.githubusercontent.com/assets/1193022/13201126/36703fb0-d8b8-11e5-838b-9fcd6b2a0838.gif)

**Comment by mtruyens** [comment]
Thanks for the quick check! I just noticed it only happens when structural editing is OFF. (Nevertheless, it seems like a bug to me even when structural editing is off.)

**Comment by dhruvbhatia** [comment]
Thanks for clarifying, you are correct - I can reproduce this with structural editing turned off.
Makes me wonder if the default behaviour when `SE = off` should be to not even create a closing `)` when one enters `(`?

Also, I found a related issue: #1101

**Comment by mtruyens** [comment]
I think the closing parentheses should effectively be added. In other programming languages, where no structural editing exists, the same closing-behaviour for parentheses exists...
