### ISSUE TITLE
Add alt symbol support

### ISSUE THREAD

**Issue by neverfox** [cursive-ide/cursive#1266]
Feature request:

Allow a configuration setting that will convert certain symbols to symbolic characters, similar to what can be done with clojure mode in Emacs:

`#()` -> `λ()`
`(fn [])` -> `(ƒ [])`
`#{}` -> `∈{}`

**Comment by cursive-ide** [comment]
This is provided by the [Clojure Pretty Symbol](https://github.com/zjhmale/intellij-clojure-pretty-symbol) plugin.
