### ISSUE TITLE
Feature Request: Folding code and data

### ISSUE THREAD

**Issue by lsenta** [cursive-ide/cursive#1269]
Folding let and data would be handy, especially when working with html:

``` clojure
(defn x [a]
  (let [b (+ 1 a)
        c (+ 1 a)
        d (+ 1 a)
        f (fn [x] (println b))]
    (println b)))
```

=>

``` clojure
(defn x [a]
  (let [b c d f]
    (println b)))
```

And for large hiccup-like defs

``` clojure
[:html
  [:body
   [:div#page-container.sidebar-l.sidebar-o.side-scroll.header-navbar-fixed
    "<!-- Side Overlay-->"
    [:aside#side-overlay
     "<!-- Side Overlay Scroll Container -->"
     [:div#side-overlay-scroll
      {:style ""}
      "<!-- Side Header -->"
      [:div.side-header.side-content
       "<!-- Layout API, functionality initialized in App() -> uiLayoutApi() -->"
       [:button.btn.btn-default.pull-right
        {:data-action "side_overlay_close",
         :data-toggle "layout",
         :type "button"}
        [:i.fa.fa-times]]
       [:span
        [:img.img-avatar.img-avatar32
         {:alt "", :src "assets/img/avatars/avatar10.jpg"}]
        [:span.font-w600.push-10-l "Ryan Hall"]]]
      "<!-- END Side Header -->"
      "<!-- Side Content -->"
      [:div.side-content.remove-padding-t
       "<!-- Side Overlay Tabs -->"
       [:div.block.pull-r-l.border-t
        [:ul.nav.nav-tabs.nav-tabs-alt.nav-justified
         {:data-toggle "tabs"}
         [:li.active
          [:a
           {:href "#tabs-side-overlay-overview"}
           [:i.fa.fa-fw.fa-coffee]
           "\n                                Overview"]]
         [:li
          [:a
           {:href "#tabs-side-overlay-sales"}
           [:i.fa.fa-fw.fa-line-chart]
           " Sales"]]]
```

=>

``` clojure
[:html
  [:body
   [:div#page-container.sidebar-l.sidebar-o.side-scroll.header-navbar-fixed
    [:aside#side-overlay
     [:div#side-overlay-scroll ...]
     [:div.side-content.remove-padding-t ...]]]
```

(the example is not correct but you get the idea).

**Comment by cursive-ide** [comment]
Interesting idea, I especially like the let folding. The hiccup one is more difficult since it's hard to detect that a particular form is meant to be data, but this could possibly be triggered via metadata or something similar.

**Comment by lsenta** [comment]
:+1: You could do the same for maps,
`{:a 1 :b 2 :c 3} => {:a :b :c}`
(not sure how the UI should behave to show the folding explicitly)

For the hiccup one, tbh that's the main "issue" that brought me here, I have huge, "uninteresting", pile of nested vectors. wouldn't showing the first item be a nice "get started" feature to have?

**Comment by lorddoig** [comment]
Related - support for this IntelliJ feature would be nice: https://www.jetbrains.com/idea/help/folding-custom-regions-with-line-comments.html

**Comment by torbjornvatn** [comment]
I'd also like folding on fold comments, here's a new link to the documentation: https://www.jetbrains.com/help/idea/2016.2/code-folding.html#supported_comments

**Comment by occamin** [comment]
This would also be a major feature add for me.

**Comment by akovantsev** [comment]
original comment:
https://clojurians-log.clojureverse.org/cursive/2017-06-01.html#inst-2017-06-01T19:52:35.147550Z

> Is there a way to style how folded blocks of code are displayed?
> Here some current collapsed top level forms examples:
```
(let ...)
(defn foo ...)
(def bar ...)
(spec/def ...)
```
> What I'd really like, is to show spec/defs keyword, and single-arity function's args (if those are on the same line, ofc.):
```
(defn foo [bar baz] ...)
(spec/def :foo/bar ...)
```
> I know, there is a settings page for unresolved symbols to "alias" those to known macros structure, like "treat rum/defc just like defn".
> Is there something like this, but for code folding representation?

**Comment by neuromantik33** [comment]
Folding on data structures is a big plus for me, especially useful for editing large edn files with many nested maps, collapsing some would greatly be appreciated! :)

**Comment by cursive-ide** [comment]
I've fixed some of these cases for the next build, and broken the remaining cases (mostly around per-form customisation) out into #2042. 

What is fixed here:
1. You can now use fold comments using `; region Title` and `; endregion` comments, and there's a Surround With... option to wrap a block like this. 
2. Data structures in EDN files can now be folded, and Cursive will try to be smart about showing a preview.

Arbitrary data structures are _not_ folded in Clojure code right now, since it's hard to distinguish them from syntax elements (e.g. `let` binding vectors). That's being tracked in #2042 and will be fixed there.
