### ISSUE TITLE
Error loading CLJX files into the REPL

### ISSUE THREAD

**Issue by kernelp4nic** [cursive-ide/cursive#1270]
I think this was working before... It happens with every cljx file.

```
Loading src/cljx/file.cljx... 
CompilerException java.lang.RuntimeException: No reader function for tag +clj, compiling:
```

**Comment by kernelp4nic** [comment]
IntelliJ Version: IC-142.5047.6
Cursive version: 1.1.0-15

**Comment by kernelp4nic** [comment]
Dupe of: #1116

**Comment by kernelp4nic** [comment]
This is still happening...

```
CompilerException java.lang.RuntimeException: No reader function for tag +clj, compiling:(/Users/kernelp4nic/file.cljx:3:54) 

(ns some-namespace
  #+clj (:require [clj-time.core :as t]
                           [clj-time.coerce :as time-coercer])
  #+clj (:import org.apache.commons.validator.routines.EmailValidator))
```

**Comment by cursive-ide** [comment]
That's possible. Realistically, I'm unlikely to fix this given that CLJX support is tricky and fragile, and it's basically legacy technology now that CLJC is available.

**Comment by kernelp4nic** [comment]
Fair enough, we are in process of migrating everything to cljc but have some legacy files yet.
Thanks! closing this up
