### ISSUE TITLE
RuntimeException: Invalid header deserialising from... when attempting to open a file

### ISSUE THREAD

**Issue by iguana** [cursive-ide/cursive#1271]
Trying to open a file in the editor, Getting a runtime error:

RuntimeException: Invalid header deserialising from BXJlbGoD+M0PAwAHYXJpb....

I have submitted the error report using IntelliJ.

**Comment by iguana** [comment]
Was able to find a workaround:
If I right-click on the file, select "Mark as plaintext", I am able to open it. I then right-click again, and select "Mark as Clojure" and it works.

Still getting dozens of these errors.

**Comment by cursive-ide** [comment]
This looks like your indices have become corrupted. Does *File->Invalidate Caches and restart* help?

**Comment by iguana** [comment]
Yes, thank you!
