### ISSUE TITLE
Incorrect indentation after indexing completes

### ISSUE THREAD

**Issue by balduncle** [cursive-ide/cursive#1288]
I have a problem where Cursive tries to line up everything after a function name with the function name.  For example, ...

<img width="125" alt="screen shot 2016-03-15 at 8 42 00 pm" src="https://cloud.githubusercontent.com/assets/8840656/13799557/69ace73c-eaee-11e5-94ca-89c17152caa3.png">

If I select File > Invalidate Caches / Restart > Invalidate and Restart, Cursive formats this properly with a 2 space indent, until the initial indexing completes.  Once indexing completes I have the same problem again.

I'm running Cursive 1.1.0-14.1 and IDEA 14.1.6 on a Mac with Java 1.8.0_65.  I had the same issue with IDEA 15.0.4.

**Comment by cursive-ide** [comment]
The problem you're having is that Cursive can't resolve `defn` correctly, hence the fact that everything is highlighted. Is this Clojure or CLJS code? Is your code under a source root (blue folder) or test root (green folder)? Does your project have the Clojure or ClojureScript jars correctly added as dependencies? How did you create this project?

**Comment by balduncle** [comment]
- Clojure
- Source root (blue)
- [org.clojure/clojure "1.7.0"] is in my project.clj
- New from existing source, importing from Leiningen project.clj

**Comment by cursive-ide** [comment]
Do you see the Clojure jar in your External Libraries section at the bottom of your project view, and do you see the library in your module's dependencies in _File&rarr;Project Structure&rarr;Modules&rarr;<your module>&rarr;Dependencies_?

**Comment by balduncle** [comment]
No it doesn't.  Did I miss something in the docs?

**Comment by cursive-ide** [comment]
What you probably have to do is to open _View&rarr;Tool Windows&rarr;Leiningen_ and press the Refresh button there. Leiningen dependencies are not synced automatically when you've changed the project.clj. That said, it's a strange project.clj that doesn't have Clojure as a dep. Let me know if that works.

**Comment by balduncle** [comment]
Weird... my project.clj wasn't even listed there.  I added it and the problem went away.  Thanks for the quick turn around and the great editor!

**Comment by cursive-ide** [comment]
Interesting, you should have received a "Leiningen project not registered" banner warning when opening the project.clj, with a link to add it - did you see that?

**Comment by balduncle** [comment]
No I didn't.  To validate, I just reproduced the old problem again by removing my project.clj from the Leiningen view, closed the project and opened it and I don't get any warning banner.

**Comment by cursive-ide** [comment]
You're right, that seems to be broken - I just filed #1289 for that.
