### ISSUE TITLE
Upgrading to 2016 parens don't close

### ISSUE THREAD

**Issue by timothypratley** [cursive-ide/cursive#1297]
Put the cursor on an opening paren and enter a new paren.
(some-form)

actual:
((some-form)

expected:
()(some-form)

opening a paren on a new line makes a closed pair ()

**Comment by cursive-ide** [comment]
This is a change I think because of the new parinfer functionality - structural editing is now off by default. If you turn that on in the status bar widget, does that fix the problem?

**Comment by timothypratley** [comment]
Ah ok got it - yes

**Comment by timothypratley** [comment]
Thanks for the new release :) Trying parinfer mode and it seems like I get the best of both worlds using it?? I can still use slurp barf etc.... and it wraps by default which is cool. o_O I like it very much so far.

**Comment by cursive-ide** [comment]
Great! Yes, all the standard paredit commands can be used, they're not tied to paredit mode. I'm very interested in feedback on how parinfer works in practice. Thanks for letting me know!

**Comment by timothypratley** [comment]
Hi Colin,

In parinfer mode is there a way to make <tab> indent by 'level' instead of indent size?

Example:

```
(let [a {:a 1}]
  b (+ 1 2))
```

Here It takes 2 tab presses to get to the indentation that will slurp the b up.

A more realistic example:

```
(swap! model/app-state assoc :players (conj (second ?data))) 
(js/Date.)
```

Should be formatted as

```
(swap! model/app-state assoc :players (conj (second ?data))
       (js/Date.)))
```

I'd like the best of both worlds, the ability to use tab to indent, and for it to snap to the correct formatting width. Maybe this is possible with some configuration?

**Comment by cursive-ide** [comment]
Yes, I'm planning to add this as an enhancement. It seems like there are several possible places you might like to tab to:
```clojure
(swap! model/app-state assoc :players (conj (second ?data))
 (js/Date.))) ; Probably don't want this for lists, only vectors or maps
```
or
```clojure
(swap! model/app-state assoc :players (conj (second ?data))
  (js/Date.))) ; This one for macros
```
or
```clojure
(swap! model/app-state assoc :players (conj (second ?data))
       (js/Date.))) ; Here for functions
```

**Comment by timothypratley** [comment]
awesome!
