### ISSUE TITLE
Undo after parinfer jumps cursor back to wrong position

### ISSUE THREAD

**Issue by rauhs** [cursive-ide/cursive#1299]
1. Do an edit somewhere (Pos: A)
2. Click further away from the edit (Pos: B)
3. Do a parinfer action, like indent/tab
4. Undo

Expected: The indent gets undone and cursor is at the position B.

Current behavior: The indent gets undone and cursor jumps to position A.

Edit: possibly needs an edit at A first.

**Comment by sfnelson** [comment]
Note that #583 has regressed, possibly related.

**Comment by cursive-ide** [comment]
I never managed to reproduce this exactly as written, but it definitely seems to be working now with all the parinfer fixes in 1.2.2. Please re-open if this continues to be a problem in the next build.

**Comment by cursive-ide** [comment]
There's another issue in 1.2.2 - undo undoes moving the caret. I think this is because parinfer is run on caret movement, although it should not make an undoable change if no changes are required.

**Comment by cursive-ide** [comment]
Comments from @rauhs in Slack:

> I move the cursor from column 0 to column 1, Then press undo continuously. It just goes back and forth from 0 to 1
> even up and down
> If some actual edit happens it undoes that, then again jumps back and forth
> But if (1) edit (2) move the cursor (3) undo -> just jumps back and forth

> If i use `CTRL-Z` to undo it does the behavior that I described. If I choose `Edit-undo` it does undo the things (kinda, needing 3 steps per undo)

**Comment by cursive-ide** [comment]
Another symptom received by email:
	1) Start with some random little form like "(hash-map :key, "val”)”
	2) Select “val” and delete it.
	3) Press backspace once to delete a space.
	4) Press Cmd + Z for Undo. The space comes back.
	5) Cmd + Z again, and .. “val” doesn’t re-appear!

**Comment by FranciscoE-Hudl** [comment]
All undo-redo has stopped for me, sadly. The caret moves, but the values are not reapplied. When it's changed back to Paredit, both the previous history and the caret changes from undo-redo diring parinfer are part of the history now.

**Comment by jvtrigueros** [comment]
I'm also seeing this symptom, I'm on Windows if that matters at all.
