### ISSUE TITLE
keyword syntax broken in 1.2.1-2016.1

### ISSUE THREAD

**Issue by desbo** [cursive-ide/cursive#1300]
Since upgrading keyword syntax highlighting has stopped working. In the language colour settings, it appears to be inheriting from something that doesn't exist:

![screen shot 2016-03-20 at 10 32 58](https://cloud.githubusercontent.com/assets/1064734/13903941/492bca54-ee87-11e5-9c83-13693d5c0203.png)

**Comment by viniciushana** [comment]
Same here

**Comment by wilkerlucio** [comment]
Until it gets released, if you used the regular color on the light theme it is `#660E7A`.

**Comment by neverfox** [comment]
If it helps with debugging, I use the Obsidian theme found [here](http://color-themes.com/?view=theme&id=563a1a6180b4acf11273ae3d). It's more than just the keywords that stopped following the theme.

**Comment by neverfox** [comment]
Okay, I can confirm that it's just the keywords (which in Obsidian, should be a shade of blue).
