### ISSUE TITLE
parinfer behaves oddly in split window

### ISSUE THREAD

**Issue by jonoflayham** [cursive-ide/cursive#1301]
parinfer isn't usable in split windows, as far as I can currently tell.  Steps to reproduce:

- open a new project and a source file
- ensure you're in parinfer mode
- use Window/Editor tabs/Split horizontally
- in the new split window, it isn't possible even to def anything: the space you enter after 'def' is immediately deleted

This happens with IDEA 2016.1 (build IU-145.258) and Cursive 1.2.1-2016.1

PS notwithstanding this, congratulations on matching IDEA 2016 and the parinfer implementation in general!

**Comment by cursive-ide** [comment]
Yes, this is an issue with parinfer. Currently it assumes that there is only one caret for a given document, which is not true in your case. Since you have two editors open on the same document, you have two carets as well and stock parinfer does not handle this well. I'm thinking about a solution.

**Comment by stijnopheide** [comment]
In general, parinfer stops working when you split windows. Even after opening another file in the newly created split window, it doesn't automatically balance parens anymore.

**Comment by cursive-ide** [comment]
@stijnopheide Note that this will still be a problem if you split and leave the file open in another editor tab, even if you later have another tab selected.

**Comment by jonoflayham** [comment]
Yes, that's what I find.  To put it more positively, a workaround to the problem is never to have the same file open in more than one editor tab.  As far as I can, parinfer starts working again even in split views once you ensure this.
