### ISSUE TITLE
After installing 1.2.1, no autocomplete

### ISSUE THREAD

**Issue by Engelberg** [cursive-ide/cursive#1302]
I can force autocomplete with Ctrl-Space, but it doesn't happen automatically while typing.

**Comment by cursive-ide** [comment]
Is this only when in Parinfer mode?

**Comment by adam-r-kowalski** [comment]
I am having the same issue, when parinfer mode is enabled auto completion stops.

**Comment by wilkerlucio** [comment]
I can still manually call the autocomplete using "cmd + space". But it's not showing up automatically as it used to be.

**Comment by Engelberg** [comment]
Yes.  It appears to be tied to parinfer mode.
