### ISSUE TITLE
Tab key doesn't add spaces anymore if Structure Edit is OFF

### ISSUE THREAD

**Issue by tuhlmann** [cursive-ide/cursive#1304]
After installing the latest Cursive version (1.2.1-15) I can no longer press the tab key to insert spaces to for instance verticly align :require :as statements.
It does also no longer work to press tab in order to change the indentation of a form. Shift-Tab does outdent, then pressing Tab again indents to the correct position, but further Indentation is not possible.

Structural Edit is Off.

**Comment by ertugrulcetin** [comment]
Also tab does not work when inserting live templates.
