### ISSUE TITLE
After upgrade to 1.2.1, Tab key no longer works for executing (expanding) Live Templates

### ISSUE THREAD

**Issue by mtruyens** [cursive-ide/cursive#1305]
My temporary solution is to change all Live Templates to expand with the Enter key, instead of the Tab key.

**Comment by ertugrulcetin** [comment]
I was going to open this issue. Having same issue !

**Comment by ertugrulcetin** [comment]
It does not work when enabling Parinfer mode.
Everything is okay with Paredit mode.
