### ISSUE TITLE
Running Lein run configurations produces "KotlinReflectionNotSupportedError"

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1308]
Reported by email and IRC:

> When I try to run any Leiningen tasks from the Leiningen tools, I am getting this exception
> 
> KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the class
> 
> I can run lein commands fine from the terminal though

**Comment by franciscocpg** [comment]
When version 1.2.2 will be released?
