### ISSUE TITLE
Gutter icons are too small on retina screens (1.2.1)

### ISSUE THREAD

**Issue by sfnelson** [cursive-ide/cursive#1310]
<img width="102" alt="screen shot 2016-03-21 at 2 22 31 pm" src="https://cloud.githubusercontent.com/assets/325974/13908833/732ec8c6-ef70-11e5-9568-61cad10418df.png">

After updating to IntelliJ 2016.1 and Cursive 1.2.1 the gutter icons that appear when running tests in the REPL are too small and clipped on my retina iMac.

**Comment by hlship** [comment]
Solution: buy Colin a retina Mac.

**Comment by sfnelson** [comment]
I'm pretty sure he has one...

**Comment by cursive-ide** [comment]
Yes, I have a retina MBP but I don't see this issue. I'll add double size icons for this and see if that helps.

**Comment by cursive-ide** [comment]
Ok, I have added @2x icons for these, I'm going to optimistically assume this will fix the problem. If it doesn't, feel free to reopen this.
