### ISSUE TITLE
Color Schemes after 2016.1/1.2.1

### ISSUE THREAD

**Issue by neverfox** [cursive-ide/cursive#1314]
I upgraded Intellij and Cursive to the new versions at the same time, so I'm unsure about where the problem lies, but a lot of the color schemes that worked well for Clojure in v15/pre-1.2.1 no longer work. Everything gets a sort of bland color treatment or a treatment that's not what one would expect. In the old versions, none of the themes were Clojure-specific, but they often turned out pretty decent anyway. I assume that Intellij changed the way schemes are done, so that's possibly one issue. However, even the built-ins, like Darcula, that I can assume got updated with the platform, aren't doing what they used to do with Clojure, e.g. keywords used to get a lavender color, but now they're just white. Is it possible that Cursive also has some changes (or lack thereof) that might not be allowing themes to apply as before? Is anyone else seeing this behavior?

**Comment by conan** [comment]
I also see this, it's the keywords that I really noticed.  I think it's because some of the colours in the parent theme are now deprecated, and by default Cursive uses the inherited colour.  It would be useful to know what the colours all were before so we can restore them manually.

**Comment by kennyjwilli** [comment]
If it helps, here is a screenshot of the problem..
![screenshot from 2016-03-21 12-48-50](https://cloud.githubusercontent.com/assets/2453976/13932050/9fbf444a-ef63-11e5-8612-6c62a319cb62.png)

**Comment by cursive-ide** [comment]
This is tracked in #1300 and is fixed for the next build.

**Comment by neverfox** [comment]
If it helps with debugging, I use the Obsidian theme found [here](http://color-themes.com/?view=theme&id=563a1a6180b4acf11273ae3d). It's more than just the keywords that stopped following the theme.

**Comment by cursive-ide** [comment]
@neverfox What else have you seen broken, apart from keywords? I didn't see the Obsidian theme previously so it'll be hard for me to see what's changed.

**Comment by neverfox** [comment]
It might just be keywords, but I'll have to get a screenshot from another machine that I haven't upgraded.
