### ISSUE TITLE
"Kotlin reflection implementation..." error in Lein tasks under 1.2.1-2016.1

### ISSUE THREAD

**Issue by eatobin** [cursive-ide/cursive#1315]
When running Lein tasks (test, version...) the task fails with an error about "Kotlin reflection" not being on the classpath. See attached screenshot. I have clicked the button to report this to Cursive but wanted to report it here too.

![2016-03-21-085650_1920x1080_scrot](https://cloud.githubusercontent.com/assets/870698/13921094/4855d364-ef44-11e5-820e-404dca35bed4.png)
 Thanks.

**Comment by favila** [comment]
I am also hitting this issue.

**Comment by cursive-ide** [comment]
Yes, this is being tracked in #1308 and is resolved for the next build.
