### ISSUE TITLE
Parinfer does not respect "Maintain selection when surrounding with braces"

### ISSUE THREAD

**Issue by conan** [cursive-ide/cursive#1319]
Parinfer will ignore the fact that you have unchecked the Editor > General > Smart Keys > "Maintain selection when surrounding with braces" setting.  This means that when you select something and press the open bracket to surround it, if you immediately start typing then you overwrite it rather than typing before it.

So if I have the 4 selected in this form:

    (+ 4 3)

Then I press "(":

    (+ (4) 3)

The 4 is still selected, so if I type "-" it overwrites the 4 and I get this:

    (+ (-) 3)

What I wanted was to type before the 4 like this:

    (+ (-4) 3)

**Comment by cursive-ide** [comment]
I'd forgotten about this issue sorry, this is fixed in 1.2.3.
