### ISSUE TITLE
hangs IDEA 2016.1

### ISSUE THREAD

**Issue by Bill** [cursive-ide/cursive#1321]
In a large mixed Java+Clojure project, with some Clojure files open in tabs, if I restart the IDE, it hangs in the "Loading Project/Loading files…" dialog. I tried rebooting my Mac and IDEA "Invalidate Caches/Restart…". That didn't help.

If I disable the plugin and restart IDEA, the project loads fine.

If I close all the Clojure files/tabs and re-enable the plugin and restart the IDEA, the project loads fine.

Another Clojure-only project does not exhibit this failure.

Cursive version 1.2.1-2016.1 on OS X 10.11.3

**Comment by cursive-ide** [comment]
Could this be the same as #1210?

**Comment by Bill** [comment]
Might be the same, but in my case, I never see the hang after IDEA has successfully loaded my project.

I only see the hang when loading the project for the first time.

**Comment by cursive-ide** [comment]
Do you have any auto-generated thread dumps, as described [here](https://intellij-support.jetbrains.com/hc/en-us/articles/207241235)?

**Comment by Bill** [comment]
I went to capture the thread dump per the instructions but today I can't repro the issue.

I can load the big Java+Clojure project today with Cursive and Parinfer enabled, with a Clojure file showing in an editor tab.

If I see this again, I'll reopen the issue.
