### ISSUE TITLE
Editing map literal with parinfer

### ISSUE THREAD

**Issue by stijnopheide** [cursive-ide/cursive#1323]
In an editor window (in the REPL window this works correctly), trying to create a map literal behaves oddly:

```{:a|}```

pressing space here always removes the space. So in order to add a value after the key, you have to go through this sequence:

```{:a:b|} => {:a|:b} => {:a |:b}```

**Comment by stijnopheide** [comment]
This behaviour disappears when restarting IntelliJ.

**Comment by cursive-ide** [comment]
Is it possible that you had the same file open in two editor tabs, for example after splitting it? That exhibits behaviour like this due to the multiple carets.

**Comment by stijnopheide** [comment]
Yes, probably.
