### ISSUE TITLE
Parinfer REPL editor spams command history

### ISSUE THREAD

**Issue by neverfox** [cursive-ide/cursive#1324]
1. Enter parinfer mode
2. Type and run something in the REPL editor
3. Type something else and run it
4. Press up arrow to move through history of commands
5. You only get one command, so you keep banging at the arrow key
6. You finally pull put the command history window (option-S) and you see the command listed the number of times you pressed the up arrow
7. Type and run a new command, and then check option-S again, and all is right, but it will just happen again

**Comment by coltnz** [comment]
Actually thought I had a keyboard malfunction there for a minute..
