### ISSUE TITLE
REPL history hangs Intellij

### ISSUE THREAD

**Issue by martinraison** [cursive-ide/cursive#1325]
Intellij hangs every time I open the REPL history window. It started happening after I once copy-pasted a giant block of code in the REPL and evaluated it. I guess this giant block of code still sits in the history and is causing the issue. Is there a simple way to at least cleanup the history?

**Comment by cursive-ide** [comment]
Not a very nice one - in your `.idea` directory, you'll find a file called `Replstate.xml`. Shut down IntelliJ, delete that file and you should be good. Could you check if you have any auto-generated stack traces? See [here](https://intellij-support.jetbrains.com/hc/en-us/articles/207241235) for details.

**Comment by martinraison** [comment]
Thanks for the workaround! I was only able to get some stacktraces while Intellij was struggling:
[stack.txt](https://github.com/cursive-ide/cursive/files/187138/stack.txt)
[stack2.txt](https://github.com/cursive-ide/cursive/files/187137/stack2.txt)
[stack3.txt](https://github.com/cursive-ide/cursive/files/187139/stack3.txt)

I'm not sure how useful this is (but Intellij is indeed spending a lot of time in `ReplHistoryChooser$HistoryRenderer`, which doesn't seem too surprising)

**Comment by martinraison** [comment]
By the way, as a small feature request, I think it would be nice to have the option to erase the REPL history from IntelliJ itself.

**Comment by gnl** [comment]
Similar problem here, but the workaround doesn't work - I exit IntelliJ, delete replstate.xml, next time I launch the repl (nREPL with leiningen) the file is restored from somewhere, contains the same history (incl. the extra long line) and still hangs the IDE. I'm able to escape out of it after a while, but the history search is basically unusable like this.

Tried deleting the repl conf and creating a new one with a different name, same result. I'm running Cursive on OS X.

**Comment by gnl** [comment]
I had to delete the ReplState entry from workspace.xml as well, it seems REPL history is saved there as well.

**Comment by gnl** [comment]
Another workaround (at least for my common use case of sending long forms from the editor) - disable 'Add forms sent from editor to REPL history' under Languages & Frameworks > Clojure
