### ISSUE TITLE
Cursive not generating java classes from ns with gen-class

### ISSUE THREAD

**Issue by pkozikow** [cursive-ide/cursive#1326]
Module A has a clojure file with a gen-class. Module B depends on module A and uses the generated class from Java, but this class cannot be found. Compiling everything externally with maven works fine. Also, the weird thing is that it works with Intellij/cursive for some people here but not others. We're all using the same version (1.2.1-2016.1) and settings, as far as I can tell.

Is there any reason why cursive would decide not to compile this ns despite `Compile all Clojure namespaces` being selected? we compared the config for people for whom it doesn't work with those for whom it does like a thousand times and can't find anything different.

**Comment by cursive-ide** [comment]
No, I can't think of any reason. Does everyone get the class file generated in their target dir?

**Comment by pkozikow** [comment]
No, that's the problem. For some people the class is not generated, even after executing the ns as a Clojure application. Basically it acts as if `Compile all Clojure namespaces` was not checked, except it is.

**Comment by pkozikow** [comment]
I did some more experiments and I'm pretty sure this problem happens consistently now. The reason why it appeared that it worked for some people is that they already had the compiled classes in the ouptut dir, and as long as they didn't delete them, everything was working. 

This is a regression that appeared in one of the most recent versions. It is a pretty big deal for us at Liveramp as it breaks the dev workflow for all our Java devs.

**Comment by cursive-ide** [comment]
Ok, I'll check this. So the problem is that the gen-class namespace is never getting compiled in Cursive?

**Comment by pkozikow** [comment]
Correct. I'm guessing AOT compilation as a whole might not be working, but our specific issue is with gen-class namespaces. Thanks for looking into it.

**Comment by cursive-ide** [comment]
As you determined, the build functionality was not being called at all due to some changes in naming after moving my build to Gradle recently. Unfortunately in this case, IntelliJ just fails totally silently, not even an error in the log. I have no idea how I've been able to compile Cursive, since I also use this functionality.

Anyway, this is fixed for the next build.

**Comment by pkozikow** [comment]
It looks like it's working. Thanks!
