### ISSUE TITLE
Invalid numeric-prefixed symbol literals are not highlighted as compile errors

### ISSUE THREAD

**Issue by jnape** [cursive-ide/cursive#1328]
The following block of code isn't highlighted by cursive as a compile error, though it should be, since numerals are illegal as a symbol literal prefix:

```clojure
(let [2-records [{:a 1} {:a 2}]]
  2-records)
```

Cursive should probably report `2-records` as a problem in the editor.

**Comment by cursive-ide** [comment]
Hmm, that is definitely wrong, thanks. I'll check what LispReader does there.
