### ISSUE TITLE
Sometimes parinfer doesn't allow adding a space to the end of a list during editing

### ISSUE THREAD

**Issue by gnl** [cursive-ide/cursive#1329]
...effectively forcing the user to type in the new form, then go back and add a space to separate it from the previous one.

Usually parinfer only seems to do its thing when the cursor leaves the currently edited line, which makes sense, but sometimes this breaks and it cleans up the space right after it's entered.

I haven't been able to narrow down when this happens, so far the behaviour seems sporadic, but it does happen quite often.

**Comment by cursive-ide** [comment]
This usually happens when you've split a document into two tabs, see #1301. Is that your case? If so that is fixed for the next build, along with many other cases.

**Comment by gnl** [comment]
This is it! After a split has been done, it seems to stop working for that particular file even after closing and reopening it for the duration of the session.

P.S. Great job on Cursive, absolutely love it. I'm still in the evaluation period, but will be placing my order soon.

**Comment by cursive-ide** [comment]
Ok, great! I'll close this issue then since it duplicates the other.

Thanks for the kind words too, I'm glad you're liking Cursive!
