### ISSUE TITLE
Parinfer and REPL history navigation stuck

### ISSUE THREAD

**Issue by jussiarpalahti** [cursive-ide/cursive#1332]
When trying to move in REPL history with up or down arrow keys or Cmd/Ctrl + up/down arrow for multi line commands, REPL gets stuck when Cursive is in Parinfer mode.

When I open the "Search REPL History" dialog the last command I have been trying to skip over is now repeated as many times as I have used arrow keys:

<img width="945" src="https://cloud.githubusercontent.com/assets/11941245/14156238/0c1f28b4-f6ce-11e5-88aa-f0a3219256f0.png">

If structural editing is off or in paredit mode everything works as it should, both for single line and multi-line commands. For some reason those "extra commands" disappear from the "search history" when I change editing modes, and only the commands I have actually submitted remain.

**Comment by cursive-ide** [comment]
Yes, this is #1324, fixed for the next build.
