### ISSUE TITLE
Parinfer triggers on-the-fly code analysis every time the cursor is moved leading to lagginess

### ISSUE THREAD

**Issue by gnl** [cursive-ide/cursive#1333]
...without there being any changes to the file. This has a very noticeable effect on input lag when moving around bigger files. With structural off or paredit mode all is good.

Maybe there's some way to set a "run-inference-on-cursor movement" flag when the current line is edited and unset it when moving away until the next edit, to make it less eager?

**Comment by cursive-ide** [comment]
Unfortunately this is an intrinsic part of parinfer as it's currently implemented - see [here](http://shaunlebron.github.io/parinfer/#knowing-when-parens-move-in-indent-mode). I'm actually planning to implement a parinfer-lite which will hopefully improve this and other problems people have had with parinfer proper.

**Comment by cursive-ide** [comment]
Sorry, I just read your last paragraph carefully - that might be an option, although I think that the definitive solution will be a mode that works in a slightly different way. I'm hoping to trial that for the next build once the current one is stable.

**Comment by gnl** [comment]
Cool, thanks!

**Comment by gnl** [comment]
This seems to be fixed in 1.2.3, been working great so far.

**Comment by cursive-ide** [comment]
Whoops, you're right, I'd forgotten about this one, thanks for letting me know! Glad it's working well.
