### ISSUE TITLE
Autocomplete does not trigger while typing in Parinfer mode

### ISSUE THREAD

**Issue by voxlet** [cursive-ide/cursive#1334]
On v1.2.1-2016.1 + OSX 10.11.4, The autocomplete window pops up while typing as expected in Paredit and Structural Off, but not in Parinfer mode. Manual triggering via a shortcut works though. 
I have tried clearing settings, reinstalling IDEA/Cursive, and testing on a fresh project with no change in behaviour. 

As a recent convert to Cursive (thanks to Parinfer!) and seeing no one else has reported this, I just hope I'm not making some trivial mistake on my end... Any help would be greatly appreciated!

**Comment by cursive-ide** [comment]
Actually, this has been reported in #1302, and is fixed for the next build.

**Comment by voxlet** [comment]
Facepalm. Will search closed issues next time. Thanks, and sorry for the hassle!
