### ISSUE TITLE
Quick definition doesn't work for clojure.core functions

### ISSUE THREAD

**Issue by conan** [cursive-ide/cursive#1339]
My _Quick Definition_, _Quick Documentation_ and _Parameter Info_ work for:
- cljs.core macros (e.g. `let`)
- 3rd party functions (e.g. core.async's `<!`)
- 3rd party macros (e.g. core.async's `go`)
- my functions
- my macros

But they don't work for:
- cljs.core functions (e.g. `swap!`)

This applies both to the keyboard shortcuts and the menu items.  Weird, huh?

**Comment by cursive-ide** [comment]
I can't reproduce this. Does "File->Invalidate caches..." fix it?

**Comment by conan** [comment]
Seems to work now, so closing.
