### ISSUE TITLE
Undo broken with parinfer in 1.2.2?

### ISSUE THREAD

**Issue by gnl** [cursive-ide/cursive#1340]
When in parinfer mode undo works fine as long as one stays in the same line, but as soon as one starts moving around the file, it seems that the line up/down operations are pushed onto the undo stack and that's what gets undone instead of the actual last edit.

I wasn't able to find a way to undo the actual editing without switching to paredit or structural off, then the move operations are still on the stack but so is the actual edit. That makes using parinfer mode all the time pretty much impossible, so as it is, I'm still staying mostly in paredit mode and only moving to parinfer mode for specific tasks like balancing parens after refactorings.

It works, but I would love to be able to stay in parinfer mode and not bother with any of that. If this is reproduceable and indeed a Cursive bug rather than something in my environment, do you think it would be possible to do some kind of a mini-quick-fix release just for this?

**Comment by cursive-ide** [comment]
This is being tracked in #1299. I'll definitely try to get a fix for this out on Monday.
