### ISSUE TITLE
Emacs tab indent doesn't work on last line in Parinfer on 1.2.2

### ISSUE THREAD

**Issue by jussiarpalahti** [cursive-ide/cursive#1341]
If you're writing in REPL or on the last line of the file, emacs tab doesn't work, and console gets an error message about every tab pressed:
IndexOutOfBoundsException: Wrong line: 2. Available lines count: 2 <- or what the file's length is

If I add a comment or something as the last line in REPL or code editor, all the preceding lines indent normally. I believe this was working before on 1.2.1.

**Comment by cursive-ide** [comment]
I can't reproduce this. Can you send the whole stacktrace? You can probably find it in your log (*Help&rarr;Show Log in Finder/Explorer*)

**Comment by jussiarpalahti** [comment]
Since it made an exception, IntelliJ asked me if I wanted to "report to Cursive". So I complied. I don't know where that went... It looks like the error report should contain the stacktrace.

I try to see if I can get a small test case.

**Comment by cursive-ide** [comment]
Ah, my apologies, I hadn't checked the tracker. I have the trace from there, thanks. If you can come up with a test case that would be very helpful too.

**Comment by cursive-ide** [comment]
Ok, I think I see the issue. I'll fix this tomorrow morning.
