### ISSUE TITLE
Parinfer breaks when using \[ and \]

### ISSUE THREAD

**Issue by sveri** [cursive-ide/cursive#1342]
Using selmer I tried to set different tag open / close delimiters which break parinfer (Cursive version: 1.2.1-2016.1).

To reproduce open a new clj namespace and type:

    {:tag-open \[ :tag-close \]}
    {:tag-open \[ :tag-close \]}

While trying to enter the second line it will start to do weird things and it is impossible to enter the above two lines correctly. This also happens if these two lines are separated in different functions.

**Comment by shaunlebron** [comment]
Sorry about this, I somehow missed the case of escaped close-parens.  I've published a one-line fix for the JS version.  Should make its way into the JVM version soon.
