### ISSUE TITLE
Paredit – closing brackets not inserted before tokens, spaces not inserted anywhere

### ISSUE THREAD

**Issue by michalmarczyk** [cursive-ide/cursive#1347]
I *think* this used to work pre-Parinfer, but now it definitely doesn't – note that I only use the regular Paredit mode:

1. Typing an opening bracket of any kind with the caret placed immediately before a token fails to insert the closing bracket: `|foo` + <kbd>(</kbd> → `(foo`, whereas `() foo` (or at least `()foo`) would be expected. *I think this is new in 1.2.3.*

2. Typing an opening bracket of any kind with the caret placed immediately after a non-tag token fails to produce a space in addition to the bracket: for example `(let|)` + <kbd>[</kbd> → `(let[])`, whereas I would expect `(let [])` (note the added space after the symbol `let`). *Much less serious, but still somewhat annoying… Present in the previous release and still present in 1.2.3.*

**Comment by cursive-ide** [comment]
Ugh, sorry about this one. This was caused by shadowing a field with an accessor which provided some default behaviour due to the change in the structural style selection, and then not always calling the accessor.

**Comment by michalmarczyk** [comment]
Worked like a charm, thanks so much!
