### ISSUE TITLE
Follow alias defs

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1354]
Reported via email:

One pattern that happens from time to time here is that I have a namespace that alias functions on other namespaces, for example, I do that with Datomic namespace because I usually need some basic functions frmo there (db, q, conn...) but also want many other helper ones, so I create my own datomic namespace, alias some functions and define others (so I can include a single namespace on the other places).

Anyhow, the issue is that by aliasing the functions as:
```
(def q d/q)
```
When auto-completing the editor just consider it to be a regular var (no arguments list).

Do you think would be feasable to Cursive to "detect" these kind of alias and automatically pull the arguments list?

**Comment by danielcompton** [comment]
Dupe of #944 I think.

**Comment by cursive-ide** [comment]
It is indeed.
