### ISSUE TITLE
Run tests improvements request [1.2.4-2016.1]

### ISSUE THREAD

**Issue by hlship** [cursive-ide/cursive#1362]
As elsewhere, easy way to run a single test would be nice.  FYI: http://dev.clojure.org/jira/browse/CLJ-1908

Often, the hover for a failure is very, very large.  I use stuart.seirra/component, so sometimes it's a component (a large, deeply nested map) that is referenced in the failure message.  Dealing with that in a nicer way would help, as would making the gutter icon clickable to get the test failure panel.

A better way, if possible, for comparing Clojure data structures would be nice.

Cursive does not seem to be using the testing context in the failure hover (the testing context is maintained by the `clojure.test/testing` macro).  It is helpful for identifying what failed, or what the test intent was.

**Comment by peterwestmacott** [comment]
+1 for testing context.

**Comment by hlship** [comment]
So Cursive does allow you to run a single test (I don't remember why I didn't think so).  Very long failures are a problem, as are garbled exceptions when using io.aviso/pretty (the ANSI escape sequences screw things up).  Finally, the gutter icon is NOT clickable if the test code execution multiple times and has multiple failures.

**Comment by onetom** [comment]
This issue could be closed IMHO.

The gutter icon is clickable now.
Single tests are possible to run with the `Run '<test-name>' in REPL` action.
Clearing ANSI codes is still an issue, but its desired behaviour should be better specified in a separate issue.

**Comment by cursive-ide** [comment]
I agree, I'm going to close this one, the large test hover problem is detailed in several issues: #1680, #2032, #2396, and the others seem covered in recent versions.
