### ISSUE TITLE
"Run nREPL with Leiningen" option disabled

### ISSUE THREAD

**Issue by Bill** [cursive-ide/cursive#1365]
When I create a new run configuration via Run > Edit Configurations… + Clojure REPL > Local, in the panel, the "Run nREPL with Leiningen" section is disabled—I cannot choose to run an nREPL with Leiningen.

![screen shot 2016-04-13 at 8 37 33 am](https://cloud.githubusercontent.com/assets/4002/14499413/0860133e-0153-11e6-8de2-08aa3533b49c.png)

I've uninstalled/reinstalled Cursive and restarted IntelliJ.

I _am_ able to run a REPL (e.g. by context-clicking a project and choosing "Run 'REPL for <projectname>'" from the menu)—it's just that I just don't get the option to create a Leiningen nREPL run config on the Clojure REPL run config panel.

**Comment by Bill** [comment]
Well that was quick. The problem was that my Leiningen module is part of a larger project. The module has both a `project.clj` and a `pom.xml`. I had the module configured under Maven and not Leiningen. 

When I went to the Leiningen tools window I noticed my module was not listed. When I tried to add it IntelliJ told me it was already managed with Maven and could not be managed with both Maven and Leiningen.

So I _removed_ my module form the project (context-clicked the module in the project tools window and selected "remove module". After that I was able to add it to the Maven tools window (using "+") and after that the "Run nREPL with Leiningen" option magically appeared on the Clojure REPL run config panel.

**Comment by Bill** [comment]
A final note: after this fix, while the "Run nREPL with Leiningen" was no longer disabled, unfortunately I was not able to select my (Leiningen) module from the "Project" list in the "Run nREPL with Leiningen" section of the run config panel accessed via the Run > Edit Configurations… menu.

A restart of IntelliJ did not help.

But I _was_ able to reach a run config panel with my Leiningen module pre-selected via the context menu on my project in the project tool window: "Create REPL for '<module-name>'".

**Comment by cursive-ide** [comment]
So just so I'm clear - it sounds like when you re-imported the project, you re-imported it with Maven, is that right? So the project is still not registered as a Leiningen project?

**Comment by Bill** [comment]
No @cursive-ide I mis-spoke in my previous comment. When I re-imported it, I re-imported it as a Leiningen module.

I have corrected my comment above.
