### ISSUE TITLE
with-redefs should inherit "align let binding values" code style setting

### ISSUE THREAD

**Issue by jnape** [cursive-ide/cursive#1367]
It seems that let clauses and friends (with-open, for example) are supposed to collectively behave according to the "align let binding values" checkbox under Settings -> Editor -> Code Style -> Clojure -> General. However, this alignment rule isn't applied to with-redefs, and it feels like it should be.

**Comment by dpassen1** [comment]
Any movement on this? There are a number of forms that should align like let.

**Comment by peter-ryan** [comment]
+1

**Comment by jnape** [comment]
Bump. Any further thoughts on this @cursive-ide?

**Comment by cursive-ide** [comment]
I'll fix this now. Any other forms that are missing this? @dpassen1 Mentioned that there might be more I've missed.

**Comment by jnape** [comment]
Definitely `with-open`, `for`, `doseq`, and `loop` off the top of my head. Any others anyone else can think of?

**Comment by cursive-ide** [comment]
They should all be handled now. Here's the current list:
```
clojure.core/let
clojure.core/let*
clojure.core/with-open
clojure.core/with-local-vars
clojure.core/when-let
clojure.core/when-first
clojure.core/if-let
clojure.core/loop
clojure.core/loop*
clojure.core/dotimes
clojure.core/if-some
clojure.core/when-some
clojure.core/for
clojure.core/doseq
cljs.core/let
cljs.core/when-let
cljs.core/when-first
cljs.core/if-let
cljs.core/loop
cljs.core/dotimes
cljs.core/if-some
cljs.core/when-some
cljs.core/for
cljs.core/doseq
compojure.core/let-routes
```

**Comment by dpassen1** [comment]
List looks good.

**Comment by jnape** [comment]
And `with-redefs`, right?

**Comment by cursive-ide** [comment]
Not yet :-)
