### ISSUE TITLE
"Evaluate Expression" and "Watches" do not work with Clojure 1.8

### ISSUE THREAD

**Issue by plummet** [cursive-ide/cursive#1370]
Description
-----
I created a new project with `lein new app steve` and then used File > New > Project from Existing Sources to import it (with Leiningen external model).  When I attempt to debug the project, the variables show fine in the Debug pane, but any expression in Watches or the Evaluate Expression window show `NullPointerException` rather than the value of the expression.

Screenshots
-----
Run configuration:
![run configuration](https://cloud.githubusercontent.com/assets/2670776/14696797/fdae4420-074b-11e6-8c37-7cb3f77525b8.png)

With Clojure 1.7.0:
![clojure 1 7 0](https://cloud.githubusercontent.com/assets/2670776/14696672/1b608c5e-074b-11e6-9776-79c9bb0fc07c.png)

With Clojure 1.8.0:
![clojure 1 8 0](https://cloud.githubusercontent.com/assets/2670776/14696674/1e0d487a-074b-11e6-97a9-173e3ed83f7b.png)

Version Info
-----

IntelliJ IDEA 2016.1.1
Build #IU-145.597, built on March 29, 2016
JRE: 1.8.0_60-b27 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation

Java x64 version 1.8.0_66-b18
Cursive version 1.2.4-2016.1
Leiningen version 2.6.1
Windows 10 Pro x64 (Version 1511 - OS Build 10586.218)

**Comment by cursive-ide** [comment]
Hmm, I wonder if the new direct linking has broken something - I'll investigate, thanks.
