### ISSUE TITLE
Stuck "scanning project directories"

### ISSUE THREAD

**Issue by blandinw** [cursive-ide/cursive#1376]
Hi,

I'm running Cursive 1.2.4 and IntelliJ 2016.1.1.
I'm trying to recursively import a bunch of projects from a root directory and Cursive is stuck "Scanning project directories" (cf. screenshot).

Is there any way I can get more logs on what is happening? Any DEBUG category I can spy on?

![image](https://cloud.githubusercontent.com/assets/413070/14770383/0e1ec786-0a25-11e6-9fa8-80a0dc9954e6.png)

**Comment by cursive-ide** [comment]
If the whole UI locks up, could you check to see if you've had any [thread dumps](https://intellij-support.jetbrains.com/hc/en-us/articles/206544899) created?

**Comment by blandinw** [comment]
The UI doesn't lock up, the spinner keeps spinning and everything is responsive.
The "Scanning project directories" step has been running for 5-6 hours before I stopped it.
That's why I was hoping to check some logs before having to dump threads. I'll get a thread dump anyway.

**Comment by blandinw** [comment]
Here it is: http://pastebin.com/SrA4EcM1

**Comment by cursive-ide** [comment]
Thanks - someone just reported by email a similar problem, but that one locked the whole UI, I assumed it was the same.

So that thread dump is interesting, there's no mention of Cursive anywhere at all. Looking at that, it looks like it's actually the indexing that's the problem. Just so I'm clear, it looks like the import has succeeded (i.e. it's created the project and imported the structure correctly - source directories etc) and this happens once it's opened the new project. Is that correct? Does "File->Invalidate Caches and restart" help this problem?

**Comment by cursive-ide** [comment]
Actually, this looks like #1160, which I investigated but couldn't reproduce and then got no further feedback on. Could you try the suggestion [here](https://github.com/cursive-ide/cursive/issues/1160#issuecomment-162171579) and mail me the result?

**Comment by blandinw** [comment]
Sure. Here is a gif in the meantime, if it gives you more insights.
https://www.dropbox.com/s/0jpi0lyhjb4pvtq/cursive-gif.gif?dl=0

**Comment by cursive-ide** [comment]
Thanks, can you make that public? I can't see it without signing in to dropbox, and I don't have an account there.

**Comment by blandinw** [comment]
I sent an email with the gif at cursive@cursiveclojure.com.
There's nothing in the logs for #com.intellij.openapi.project.DumbServiceImpl.
I see one (probably unrelated error) http://pastebin.com/ukrXi30P

**Comment by cursive-ide** [comment]
It looks like there might be a race condition in the indexing code, although I have no idea how Cursive would influence that. Could you try setting the debug log for "com.intellij.openapi.vfs.impl.local.NativeFileWatcherImpl" and see if that shows anything?

**Comment by blandinw** [comment]
Not seeing anything particular.
I'll close the issue as it does not seem look related to Cursive.
Thanks for your time!

**Comment by cursive-ide** [comment]
Ok, thanks. I'd create a YouTrack issue for the JetBrains developers to see what they think - #1160 definitely found that disabling Cursive fixed their problem. It's hard to test when you need lein to import, though.
