### ISSUE TITLE
Copy from REPL window not working

### ISSUE THREAD

**Issue by cataboom** [cursive-ide/cursive#1380]
Edit->Copy and Command-C copy not working from REPL window in v1.2.5.

**Comment by ikitommi** [comment]
Also, can't use find in the repl.

**Comment by raspasov** [comment]
Have the same problem as well - can't find in REPL. It now tries to to find in the REPL eval box (where you normally type to eval something in the REPL manually).

**Comment by Producr** [comment]
I, too, have both issues on Windows 10 (can't find in REPL and can't copy from it).
