### ISSUE TITLE
ns declaration rename of refer's support

### ISSUE THREAD

**Issue by rauhs** [cursive-ide/cursive#1382]
The IDE crashed on me (submitted the stacktrace) when I entered

```
(ns fo
  ""
  (:refer [clojure.zip :rename {,
```

where I did NOT previously import `clojure.zip`. The `,` indicates the cursor position.

Also, the following seems to be unsupported in the sense that it complains about **cannot resolve symbol**:

```
(ns foo
  (:require [clojure.data.zip :refer [ancestors descendants]
                :rename {ancestors xml-ancestors descendants xml-descendants}]))
```

**Comment by houghcr** [comment]
This also happens here as soon as the '{' is typed:
```
(ns foo
    (:refer-clojure :rename {
```

Here's the IDE Fatal Errors stacktrace:
[http://pastebin.com/4RZt6dDh](http://pastebin.com/4RZt6dDh)

Additionally, sometimes when deleting or editing that line the error "Unable to save settings: Failed to save settings. Please restart IntelliJ IDEA" happens.

**Comment by houghcr** [comment]
@cursive-ide Any further information I can add to this to help? Having all of IDEA crash is extremely inconvenient and frustrating.

**Comment by cursive-ide** [comment]
I just tried to reproduce this, I can reproduce the stacktrace but nothing like the whole IDE crashing. Can you add more detail about what this means?

Concretely, I turned off structural editing, and turned off matched brace insertion so I could get unbalanced forms. I typed in the above, got the stacktrace but could then terminate the form and continue editing with no problem.

**Comment by rauhs** [comment]
No hard crash anymore for me, though I can't use the backspace after it happened so I need to restart IntelliJ.

**Comment by cursive-ide** [comment]
Ok, playing around with that some more, I could reproduce the "Unable to save settings" error. It's very strange, I'll ask JetBrains what they think.

**Comment by cursive-ide** [comment]
This is looking like an IntelliJ bug. Hopefully we can actually use this to debug it, since they've never been able to reproduce it reliably.

**Comment by houghcr** [comment]
This happens for me with structural editing (paredit) and matched brace insertion both active.

**Comment by cursive-ide** [comment]
@houghcr So in your previous example, the braces would actually be closed?

**Comment by houghcr** [comment]
Yep.
As everything crashes this is what is left in the editor:

```
(ns foo
    (:refer-clojure :rename {}))
```

Immediately after typing the first curly bracket its completion appears then NPEs start showing up. Then unable to save settings...

**Comment by cursive-ide** [comment]
Yes, I've been working with JetBrains and we've identified the problem. I'll fix it for the next drop.
