### ISSUE TITLE
Add ability to delete items from REPL history

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1383]
There have been numerous issues (#336, #971, #1325) which could have been fixed or at least worked around if it were possible to delete items from the REPL history.

**Comment by katox** [comment]
This would be very handy. Sometimes I make a typo in a longer REPL line that I need to reuse multiple times later on. It's very annoying to select the version with a typo instead of the correct one because they look almost the same (and the search filter applies to both usually).
