### ISSUE TITLE
Auto-detect new namespace type

### ISSUE THREAD

**Issue by mmower** [cursive-ide/cursive#1397]
Given the propensity for organising files as:

```
src/
 clj/
 cljc/
 cljs/
```

when you use the "New Clojure Namespace" feature it would seem harmless to walk the folder hierarchy and see if you can find one of `clj`, `cljc`, or `cljs` as a parent and auto-select the appropriate type of namespace accordingly.

**Comment by danielcompton** [comment]
Dupe of #904.
