### ISSUE TITLE
Can't use space when on Parinfer mode

### ISSUE THREAD

**Issue by ronaldsuwandi** [cursive-ide/cursive#1398]
Today I suddenly can't use space when trying to create new function.. I had to switch to Paredit in order to do so - the video shows what happens: http://imgur.com/UfxUeKI

I'm using Cursive 1.2.6-2016.1 on IntelliJ 2016.1

**Comment by ronaldsuwandi** [comment]
I managed to reproduce this bug. This only happens if I have checkout project and was trying to edit the checked out project. Steps to reproduce:

1. Create leiningen project A
2. Create leiningen project B - project B should have project A in their `checkouts` directory (symlink)
3. Open *both* project A and project B using Cursive (2 windows)
4. When editing clojure file in project A, I can't use space after typing `(defn`
5. If either window is closed (either project A or B is closed), then editing clojure file in project A is working fine

**Comment by cursive-ide** [comment]
Thanks for the repro case, I'll look at this today.
