### ISSUE TITLE
Incorrect arity detection

### ISSUE THREAD

**Issue by mbossenbroek** [cursive-ide/cursive#1399]
Cursive doesn't seem to detect the correct arity of this function when it's used within a macro:

![screen shot 2016-05-10 at 12 31 37 pm](https://cloud.githubusercontent.com/assets/6173807/15159901/d606c2d4-16ab-11e6-9f7e-660d3591f0c2.png)

**Comment by cursive-ide** [comment]
This is fixed in the next build (1.3.0-eap1). There's some doc about how it works [here](https://cursive-ide.com/userguide/macros.html).
