### ISSUE TITLE
Intellij Idea won't start after installing Cursive

### ISSUE THREAD

**Issue by marcesher** [cursive-ide/cursive#14]
Greetings,

I'm on Intellij IDEA 12.1.3 Ultimate, Mac OSX 10.8.4, Apple JDK 1.6.045.

I installed Cursive via http://cursiveclojure.com/plugins.xml, and now when IDEA restarts, it hangs on the loading screen.

And here's the relevant snippet from idea.log:

2013-10-09 08:44:49,048 [  11063]  ERROR - s.clojure.config.InitComponent - Reflection warnings:
Reflection warning, clojure/tools/nrepl/ack.clj:47:3 - reference to field close can't be resolved.
Reflection warning, clojure/tools/nrepl/middleware.clj:135:3 - call to replaceAll can't be resolved.
Reflection warning, clojure/tools/nrepl/middleware/interruptible_eval.clj:53:52 - reference to field iterator can't be resolved.
Reflection warning, clojure/tools/nrepl/middleware/interruptible_eval.clj:109:3 - call to java.util.concurrent.ThreadPoolExecutor ctor can't be resolved.
Reflection warning, clojure/tools/nrepl/middleware/session.clj:41:54 - call to append can't be resolved.
Reflection warning, clojure/tools/nrepl/middleware/session.clj:230:30 - call to put can't be resolved.
Reflection warning, clojure/tools/nrepl/middleware/session.clj:230:30 - call to put can't be resolved.
Reflection warning, clojure/tools/nrepl/server.clj:42:21 - reference to field close can't be resolved.
Reflection warning, clojure/tools/nrepl/server.clj:133:28 - call to java.net.InetSocketAddress ctor can't be resolved.

Thoughts? What other information can I provide that will help diagnose?

Thanks!

**Comment by wolfwell5** [comment]
Meet this issue when I install Cursive after install Clojure kit, I don't know if these two conflict lead to this issue ?

**Comment by wolfwell5** [comment]
And I delete `clojure-plugin` this directory (/Library/Application Support/JetBrains/IntelliJIdea2020.3/plugins), the idea restart successfully !
