### ISSUE TITLE
parinfer mode bug, rearranges parens when it should not 

### ISSUE THREAD

**Issue by jasonjckn** [cursive-ide/cursive#1404]
I tried the very last example on https://shaunlebron.github.io/parinfer/

`(def m {:foo 1
              :bar 2
              :baz 3})`

when modifying the var name `m` to `my-map` the curly brace jumps from the 3rd line to the 1st line unexpectedly  

otherwise I'm really liking this mode, thanks!

**Comment by jasonjckn** [comment]
+1

**Comment by cursive-ide** [comment]
This is fixed by the new parinfer smart mode (#1937).
