### ISSUE TITLE
Cannot "rename" (via Shift+F6) to a symbol that ends with '

### ISSUE THREAD

**Issue by martinraison** [cursive-ide/cursive#1408]
Small bug: when renaming a symbol, if the new name ends with an apostrophe (as is often the case in Clojure), I get the message "Inserted identifier is not valid".

**Comment by cursive-ide** [comment]
This was reported in #709 and it was fixed in 1.2.7, just out yesterday!

**Comment by martinraison** [comment]
Ah, great! Sorry I missed the other report.
