### ISSUE TITLE
the  Non-Commercial Licence is empty  

### ISSUE THREAD

**Issue by xingzhefeng** [cursive-ide/cursive#1412]
Transaction: 2879261-CHRE171E5F310CA-39A4910CD0
Paddle.com Market Ltd
J314, The Biscuit Factory
100 Clements Road
London, SE16 4DG
United Kingdom

Company No. 08172165
VAT No. GB 150 8481 14
 
 
 	
Product
Cursive Non-Commercial Licence
 
there no connent . it's very Sadness

**Comment by cursive-ide** [comment]
I've just emailed you another copy of your licence.

**Comment by xingzhefeng** [comment]
tks ;)
