### ISSUE TITLE
Macro wrapping def screws things up for Cursive

### ISSUE THREAD

**Issue by vikeri** [cursive-ide/cursive#1417]
I am using a debug macro that wraps my entire code as per https://github.com/Day8/re-frame/wiki/Debugging#your-project. This confuses Cursive (naturally) and it writes that a lot of stuff can not be resolved (see image). Can I solve this somehow? Help Cursive by telling it to ignore the lines that define the macro or something?

<img width="260" alt="skarmavbild 2016-05-25 kl 12 04 19" src="https://cloud.githubusercontent.com/assets/846688/15536575/2f967f7a-2272-11e6-87c7-0b4b96cdff4a.png">

**Comment by cursive-ide** [comment]
Assuming you're talking about clairvoyant, this was fixed in the latest EAP.
