### ISSUE TITLE
Unable to Disable Check for EAP Builds

### ISSUE THREAD

**Issue by alexanderkiel** [cursive-ide/cursive#1418]
I'm unable to uncheck `Check for EAP builds` under `Languages & Frameworks / Clojure / Update options`. I'm on 2016.1.2.

**Comment by cursive-ide** [comment]
You're right, that doesn't seem to update correctly.

**Comment by cursive-ide** [comment]
This is fixed for the next build. In the meantime, a workaround is to go to *Settings&rarr;Plugins->Browse Repositories...->Manage Repositories...* and remove the repo `https://plugins.jetbrains.com/plugins/eap/8090`.

**Comment by alexanderkiel** [comment]
Thanks the workaround works.
