### ISSUE TITLE
REPL is disabled

### ISSUE THREAD

**Issue by malnormalulo** [cursive-ide/cursive#1425]
A few weeks ago, I updated my installation of Cursive, and I have been unable to run the REPL since. I've tried a few times to do a complete uninstall/reinstall of IntelliJ and Cursive -- complete with hunting down and deleting all the configs and such -- to no avail.

When I go to the tools menu, the REPL submenu is not visible (tools.png, attached), even though it is visible in the "Menus and Toolbars" settings (config.png, attached).

Attempting to force the issue by putting some of the REPL commands elsewhere (try_to_force_it.png, attached) works, in a sense, but results in a grayed-out menu item (exists_but_gray.png, attached). Pulling up the REPL through View > Tool Windows > REPL does bring up the window, but it is empty (empty_repl.png, attached).

I've bundled up the IntelliJ log files (purged right before reproducing this) and attached them as well.

OS: Win10

Cursive version: 1.2.6-2016.1

IntelliJ IDEA 2016.1.2
Build #IC-145.972, built on May 14, 2016
JRE: 1.8.0_77-b03 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

All IntelliJ settings are default.

[log.zip](https://github.com/cursive-ide/cursive/files/288650/log.zip)
![tools](https://cloud.githubusercontent.com/assets/7827826/15637201/4e99ecb4-25e1-11e6-9d6a-f2b91df57e51.png)
![config](https://cloud.githubusercontent.com/assets/7827826/15637198/4e8f371a-25e1-11e6-8256-7b68b2dffa6c.png)
![try_to_force_it](https://cloud.githubusercontent.com/assets/7827826/15637202/4e99e61a-25e1-11e6-9170-09311c486c76.png)
![exists_but_gray](https://cloud.githubusercontent.com/assets/7827826/15637200/4e99c3ec-25e1-11e6-9dec-3572d88d0bc6.png)
![empty_repl](https://cloud.githubusercontent.com/assets/7827826/15637199/4e96f07c-25e1-11e6-9046-8b483bcd5b56.png)

**Comment by cursive-ide** [comment]
The fact that the REPL menu is unavailable simply reflects the fact that you have no REPL running - those items are only available with a working REPL. How are you trying to start the REPL? Looking at your screenshot, it seems that you are not using Leiningen, is that correct?

**Comment by malnormalulo** [comment]
That was a dummy project -- I observed this originally in leiningen-enabled ones.

Based on your response, I dug a little more into the project and found the "create REPL" option. After a little fiddling with config (setting the project SDK and language level, since those settings were lost in the clean wipe), it's launched successfully. Strange, I've never done that manually before -- it always, if I remember correctly, spun up the nREPL server automatically for me.

Anyway, I have it working correctly now, thanks for the guidance!
