### ISSUE TITLE
Macroexpand doesn't work in REPL

### ISSUE THREAD

**Issue by katox** [cursive-ide/cursive#1426]
Macroexpand shortcut does nothing in REPL. It fires up in editor but it shows an unexpanded form?

[Macroexpand output](http://imgur.com/lmSmeiK)

If executed directly, the output can be expanded:

> (clojure.spec/def-impl
>  :utility-info.core-test/date
>  (quote (clojure.core/fn [%](clojure.core/instance? java.util.Date %)))
>  (fn\* [p1__2321#](instance? java.util.Date p1__2321#)))

**Comment by cemerick** [comment]
Can confirm, same here. I'd expect the initial view to be expanded at least one level, but any combination of Ctrl-Right or clicking the right arrow with the cursor positioned in various areas of the popup as suggested [here](https://cursive-ide.com/archive/810.html) doesn't yield any changes, either.

**Comment by TheRaspPie** [comment]
Yes, same here.

**Comment by cemerick** [comment]
I actually never have any success with macroexpand in the editor, either (I must have not read the issue title / description very well).

Others are getting a useful/functional macroexpand popup outside of the REPL?

**Comment by cemerick** [comment]
This is not fixed. Using 1.5.0-eap7 under intellij 2016.3.6, the macroexpansion popup still just does nothing……except for *one* time, when it did something, but the output seemed to unrelated to my code (I saw lots of `cursive.riddley` metadata, `fn`s when the code I was macroexpanding wasn't going to produce any, etc.

**Comment by cursive-ide** [comment]
I've decided to leave this one closed. @cemerick's last comment was one misunderstanding (Cursive expects the caret to be within the macro form, not after it) and one bug. I've filed that as #1733 since this issue is already logged against an earlier EAP build, and is no longer related to the original issue.
