### ISSUE TITLE
Invalid arity detection for protocol implementation

### ISSUE THREAD

**Issue by hadronzoo** [cursive-ide/cursive#1431]
I'm using Cursive `1.3.0-eap2-3-g0e4c6c9`.

I cloned the [onyx](https://github.com/onyx-platform/onyx) repo and opened the [`onyx.state.bookkeeper` namespace](https://github.com/onyx-platform/onyx/blob/0.9.x/src/onyx/state/bookkeeper.clj). Cursive is incorrectly reporting arity errors for the `component/Lifecycle` protocol implementation:

<img width="570" alt="o s bookkeeper - onyx - code onyx - intellij idea community edition 2016 2 eap 2016-06-06 17-11-22" src="https://cloud.githubusercontent.com/assets/1408/15839600/c0135500-2c09-11e6-984c-eedd742a5ae3.png">

<img width="335" alt="o s bookkeeper - onyx - code onyx - intellij idea community edition 2016 2 eap 2016-06-06 17-12-10" src="https://cloud.githubusercontent.com/assets/1408/15839610/d5468884-2c09-11e6-8dd9-ba72e9e78b0c.png">

The namespace compiles without issue and Cursive does not seem to be incorrectly reporting errors for other namespaces.

**Comment by rsachdeva** [comment]
This is happening in Cursive 1.4.0-2016.3 also.
![screen shot 2016-11-30 at 4 34 11 pm](https://cloud.githubusercontent.com/assets/232903/20774274/46344d46-b71b-11e6-9bda-9f91286ddaf2.png)
![screen shot 2016-11-30 at 4 36 37 pm](https://cloud.githubusercontent.com/assets/232903/20774275/4634a61a-b71b-11e6-8785-dd4017839d3c.png)

**Comment by armed** [comment]
Same here with v1.12.2
