### ISSUE TITLE
Customising symbol resolution with `defn` style

### ISSUE THREAD

**Issue by pbzdyl** [cursive-ide/cursive#1440]
Currently custom symbol resolution supports following styles: `def`, `let`, `for`, `->` and `->>`.

It would be useful to also support `defn` style. It would work in cases like [`defcommand` for Hystrix](https://github.com/Netflix/Hystrix/tree/master/hystrix-contrib/hystrix-clj). Currently function (Hystrix command) arguments are not resolved and are shown as unresolved symbols in the args vector and function body.

Example Hystrix function/command:

```
(defcommand shorten-url
  {:hystrix/command-key "ShortenUrl"
   :hystrix/group-key GoogleApi}
  [long-url api-key]
  (println long-url api-key))
```

**Comment by mtruyens** [comment]
+ 1

 I was just about to ask for the same feature...

**Comment by favila** [comment]
+1 "Works like defn" is a very common macro pattern. I currently set these to "works like def" but the locals they define in the vector are still unresolved.

Interestingly, I was able to edit the config file where these are stored (`IDEA_CONFIG_DIR/config/options/ClojureResolveSettings.xml`) and change `resolve-as` to `clojure.core/if-let`, `clojure.core/when-let`, (I have two macros with the same shape as `if-let` and `when-let`) and `clojure.core/defn` and Cursive appears to understand correctly the binding and scope of the local vars my macros create.

**Comment by cursive-ide** [comment]
I'll add `defn` to the list of options. 

@favila, yes, you can hack your config file as you've discovered, and it will work as you expect in the meantime.

**Comment by cursive-ide** [comment]
@favila One thing to note with that hack - if you fiddle with that file and add a modification which requires indexing more vars (i.e. not just local bindings), you’ll need to do a *File->Invalidate Caches*.
