### ISSUE TITLE
Suggestions list - missing live template description/abbreviation

### ISSUE THREAD

**Issue by kernelp4nic** [cursive-ide/cursive#1442]
This was working before...For example I have a live template for `println`, but now in the suggestions list doesn't show the description and I'm unable to differentiate the template from the clojure fns.

![2016-06-20_10-35-12](https://cloud.githubusercontent.com/assets/519481/16196075/c97ab2f4-36d2-11e6-804e-98b239063b1d.png)

```
IntelliJ IDEA 2016.1.1
Build #IC-145.597, built on March 29, 2016
JRE: 1.8.0_40-release-b132 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Cursive: Version: 1.3.0-eap3-2016.1
```

**Comment by kernelp4nic** [comment]
It's worse than I was thinking...if you have just a live template as a suggestion it doesn't show at all but the template stills works.

This is critical for me :(

**Comment by kernelp4nic** [comment]
If I create a live template to be used in every context, it's not shown on Clojure files, but shown in another files.

It's like the Clojure context is broken or something.

Just updated to the latest version of intellij and still have the same behaviour.

```
IntelliJ IDEA 2016.1.3
Build #IC-145.1617, built on June 3, 2016
JRE: 1.8.0_76-release-b198 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by cursive-ide** [comment]
I tried this, and I can see what you mean. However, for me the built in ones seem to work, this is only an issue for user defined ones. Is that what you're seeing too? For example, does `defn` show in the autocomplete list?

**Comment by cursive-ide** [comment]
Actually, I take it back - this does work for me, however they don't appear in the completion list until the whole name of the template is typed out. So I have to enter `println` entirely before it appears in the completion.

**Comment by kernelp4nic** [comment]
Built in seems to works yes, but I can confirm this was working before because it broke my entire workflow.

![2016-06-21_11-06-42](https://cloud.githubusercontent.com/assets/519481/16232307/6221b55c-37a0-11e6-90b9-a95d8b17e8a8.png)


![getstate](https://cloud.githubusercontent.com/assets/519481/16232313/66fbcda6-37a0-11e6-95ac-3874515689fb.gif)

**Comment by kernelp4nic** [comment]
This is driving me nuts! :)
I don't even know if this is a Cursive problem or an Intellij problem.

I would appreciate any clues.

**Comment by cursive-ide** [comment]
Sorry, I have no idea what's going on here :(

![screen shot 2016-07-01 at 2 35 53 pm](https://cloud.githubusercontent.com/assets/5589171/16510343/39377d88-3f99-11e6-8feb-f0a860d25ac7.png)

Does this fail for you in clj and cljs, or only cljs?

Looking at your first example, every completion appears 3 times - is this normal? I'm wondering if you have CLJS on your classpath 3 times, and that might be what is messing things up.

**Comment by kernelp4nic** [comment]
I can confirm this fails under clj/cljs/cljc/cljx. Tested in bash for example and it works fine:

![2016-07-01_08-24-33](https://cloud.githubusercontent.com/assets/519481/16520228/26936aea-3f65-11e6-9c54-74b3bd83e5ab.png)
![2016-07-01_08-24-42](https://cloud.githubusercontent.com/assets/519481/16520231/28183148-3f65-11e6-9aad-5c7082683364.png)

**Comment by kernelp4nic** [comment]
Sorry about the noise. I reinstalled intellj because this was driving me nuts and imported my old config and templates are back as they supposed to.

![2016-07-15_11-52-08](https://cloud.githubusercontent.com/assets/519481/16880649/a2442d28-4a8c-11e6-80a3-9f97191eff23.png)

Do I close this issue?

**Comment by cursive-ide** [comment]
That's really weird. I'm going to blame some IntelliJ weirdness on that one. I'll close this since I don't think there's anything I could do to fix it.

**Comment by kernelp4nic** [comment]
oh my...it's happening again :-(

**Comment by kernelp4nic** [comment]
So, I finally got it working again. I removed IdeaIC2016.2 folder and reinstalled Cursive.

OSX:

```
mv ~/Library/Application Support/IdeaIC2016.2 ~/Library/Application Support/IdeaIC2016.2.broken
```

I needed to change every Live Template context to Clojure again.
