### ISSUE TITLE
Maven pom file editing is broken in Java projects when Cursive is installed

### ISSUE THREAD

**Issue by cjkent** [cursive-ide/cursive#1445]
https://youtrack.jetbrains.com/issue/IDEA-157818

**Comment by cursive-ide** [comment]
I can't reproduce this. The only place where Cursive appears in that stacktrace is when you press backspace, Cursive checks to see if it should handle that, decides that it shouldn't and then delegates to the default handler (com.intellij.openapi.editor.actionSystem.EditorActionHandler). 

Do all the stacktraces look the same? Can you tell me anything more about the project, or provide a small project which reproduces the error?

**Comment by cjkent** [comment]
I can't reproduce this any more. I'm using IDEA 162.1447.7 and Cursive 1.3.0-rc1-2016.2
