### ISSUE TITLE
Add support for new namespacing in Clojure 1.9-alpha8

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1450]
See [CLJ-1910](http://dev.clojure.org/jira/browse/CLJ-1910) and [CLJ-1919](http://dev.clojure.org/jira/browse/CLJ-1919).

**Comment by rauhs** [comment]
Tiny note: Please support "grow selection" for something like `#:foo{:bar :y}`

**Comment by cursive-ide** [comment]
This is fixed in the next build.
