### ISSUE TITLE
Editor/Code Style/Clojure/General -> Comment Alignment

### ISSUE THREAD

**Issue by kernelp4nic** [cursive-ide/cursive#1451]
There is a way to disable this feature? I just want the comments to be treated as normal chars.
I'm using Paredit integration, I think he is the responsible for the new line?

I normally type `;` by mistake and comment with another keystroke.

![comment](https://cloud.githubusercontent.com/assets/519481/16468690/87d2b74a-3e23-11e6-969d-167a9e30ce86.gif)

**Comment by cursive-ide** [comment]
Yes, Paredit is the one moving the parens to the next line. Generally when I fat-finger the ; key, undo is the best option since it restores things back to the way they were. There's no way to turn this off individually right now, sorry.

**Comment by kernelp4nic** [comment]
Thanks for your quick response! Closing this up since there is no way to avoid it. :)
