### ISSUE TITLE
Installing Cursive throws java.security.cert.CertificateException

### ISSUE THREAD

**Issue by ArnSch** [cursive-ide/cursive#1452]
The SSL certificate for updates.cursive-ide.com seems to be invalid.

**Comment by cursive-ide** [comment]
This shouldn't be required for installing Cursive any more. Can you check *Settings&rarr;Plugins&rarr;Browse Repositories&rarr;Manage Repositories* and see if you have any URLs configured there with that domain? If so, you can remove them, go back to *Browse Repositories*, refresh and you should be able to install.

**Comment by ArnSch** [comment]
Sorry for lack of detail. This is a fresh install of Intellij 15, and have no URLs in the 'Manage Repositories' view. 

I tried with Intellij 2016 and I'm getting the same issue.

See screen recording https://www.dropbox.com/s/fk9guippfrt2m1l/cursive-issue-low.mov?dl=0

**Comment by cursive-ide** [comment]
I see, that's very strange - it looks like the JetBrains repository is actually fetching Cursive from my website for older versions, which I think was to do with the way I uploaded them. If you go [here](https://plugins.jetbrains.com/plugin/8090?pr=&showAllUpdates=true), find the 1.3.0-eap3 version corresponding to the IntelliJ version you want to use (e.g. 1.3.0-eap3-15 or 1.3.0-eap3-2016.1) then download it using the link at the right, you can then install that using *Settings&rarr;Plugins&rarr;Install from disk*.

This should all be fixed soon when my provider reissues my cert - sorry for the hassle.

**Comment by cursive-ide** [comment]
I've just managed to get my cert reissued and installed, so everything should be back to normal now. Sorry for the hassle!

**Comment by ArnSch** [comment]
Thank you!
