### ISSUE TITLE
Stack trace abbreviaton broken with Clojure 1.9

### ISSUE THREAD

**Issue by stevebuik** [cursive-ide/cursive#1454]
stack traces are no longer hiding all the cruft i.e. fn calls not in my codebase. 

I tried it with a v1.7 project and it works as expected.

**Comment by stevebuik** [comment]
I did a bit more digging with a simple test case and this is not a bug (at least not new to 1.9). It must be specific to my tests. When running the test below, the stack trace abbreviation does not work in either clj version. 

 (ns cursive-tests
   (:require [clojure.test :refer :all]))

 (deftest foo
          (throw (ex-info "bar" {})))

It would be nice if it did work for this case but it's not affected by clj version. I'll leave this for you to close in case there is some validity to the lack of abbreviation in v1.7 as well?

**Comment by cursive-ide** [comment]
This was actually broken in a recent Cursive release. It's fixed now, and I also fixed some `clojure.stacktrace` cases that weren't being caught, and stacktrace elements from the new direct linking.
