### ISSUE TITLE
Cursive Started Crashing - cursive.resolve$light_keys.invoke

### ISSUE THREAD

**Issue by asaegyn** [cursive-ide/cursive#1455]
Went to edit a file, and all of a sudden Cursive hung. My project was already loaded. I tried restarting intellij and my computer, same issue.

Not sure if it's a dupe of this: https://github.com/cursive-ide/cursive/issues/1210

Log: 
[threadDump-20160707-211827.txt](https://github.com/cursive-ide/cursive/files/353333/threadDump-20160707-211827.txt)

IntelliJ 15.0.6
Cursive 1.3.0-rc1-15
OS 10.11.3

**Comment by asaegyn** [comment]
The work around in that issue worked (disable auto indent...). Not sure if there's a proper fix for this though.

**Comment by cursive-ide** [comment]
This is a dupe, I've just fixed the root cause.
