### ISSUE TITLE
Overtone freesound.org can't paste code to Stdin

### ISSUE THREAD

**Issue by madvas** [cursive-ide/cursive#1460]
I wanted to try out [Overtone](https://github.com/overtone/overtone). 
I followed instructions as:
`lein new insane-noises`
Added ` [overtone "0.10.1"]` to deps
Then created REPL from project.clj via cursive.

I sent following into REPL
`(use 'overtone.live)` - Works well
`(use 'overtone.inst.sampled-piano)` - This opens freesound.org in browser where I authorise Overtone.  In REPL it says: 
```
--> Asset not cached - starting download...
Authorize in browser and paste code in Stdin.
https://www.freesound.org/apiv2/oauth2/authorize/?client_id=ea6297be42e9de76d47c&response_type=code
```
So I paste authorisation code into REPL input, but nothing happens. REPL stays hanging. 

When I try this in regular terminal REPL, it works well.

![snap 2016-07-13 at 21 00 56 782x939](https://cloud.githubusercontent.com/assets/3857155/16816120/fd1d91fe-493c-11e6-9e63-370b9d608e2b.png)

**Comment by dviramontes** [comment]
@madvas have you tried running it from `lein run`.
`lein repl` did not work for me but the former did.

**Comment by madvas** [comment]
This issue was resolved together with https://github.com/cursive-ide/cursive/issues/228
