### ISSUE TITLE
Auto-closing not working with Parinfer on

### ISSUE THREAD

**Issue by nwjsmith** [cursive-ide/cursive#1463]
In Cursive 1.3.0/IntelliJ 2016.2 with Parinfer turned on, auto-closing is not working reliably. When I change lines, things seem to work correctly. Here is a screen capture of the behaviour:

![eb9386da-a0a6-4f9e-958a-77e0343d2d2b-74678-000085ada9eba448](https://cloud.githubusercontent.com/assets/1348/16876986/2df6ef72-4a74-11e6-8fcc-815fb0e36a29.gif)

**Comment by cursive-ide** [comment]
This is fixed for the next build - it was caused by a change in the way IntelliJ notifies of some document changes in 2016.2.
