### ISSUE TITLE
Intellij consuming 100% CPU at startup

### ISSUE THREAD

**Issue by kernelp4nic** [cursive-ide/cursive#1469]
I know this could be an intellij problem, but It only happens with my clojure projects.
Sometimes when starting Intellij, it keeps "synchronizing project" and never stop, I have to kill it.

I have to remove the entire `.idea` folder and reimport the project again.

![2016-07-22_11-52-53](https://cloud.githubusercontent.com/assets/519481/17062067/be7db1fa-5007-11e6-8e93-46d467d48e2b.png)

Any ideas?

**Comment by elmingo** [comment]
maybe this is #1210?

**Comment by kernelp4nic** [comment]
Thanks! I will try those tips! Closing this...
