### ISSUE TITLE
Navigate to declaration with namespaced keyword

### ISSUE THREAD

**Issue by mtruyens** [cursive-ide/cursive#1470]
Especially since the arrival of Spec, it would be cool if you could press Cmd/Ctrl-B (for Navigate | Declaration) on a namespaced keyword, to go to the correct location in the namespace where the keyword was declared.

**Comment by cursive-ide** [comment]
Yes, this has only really made sense since spec, since previously keywords weren't actually declared anywhere. See #1439 for a related idea.

**Comment by danielcompton** [comment]
Also relates to #1549.

**Comment by cursive-ide** [comment]
In the next build, this is fixed for the following cases:
```
clojure.spec/def
clojure.spec.alpha/def
cljs.spec/def
cljs.spec.alpha/def
re-frame.core/reg-sub
re-frame.core/reg-sub-raw
re-frame.core/reg-fx
re-frame.core/reg-cofx
re-frame.core/reg-event-db 
re-frame.core/reg-event-fx 
re-frame.core/reg-event-ctx
```
