### ISSUE TITLE
Error when run 'Load file in REPL' on an clj file which requires cljc file

### ISSUE THREAD

**Issue by visibletrap** [cursive-ide/cursive#1472]
There is this error showing up on REPL window when executing 'Load file in REPL' on an clj file which internally requires a cljc file. It causes clj file won't be able to load to repl.

```
Error evaluating - class java.lang.ClassCastException: com.intellij.openapi.vfs.newvfs.impl.VirtualFileImpl cannot be cast to java.lang.Comparable
```

Step to replicate problem
 1. Clone project https://github.com/visibletrap/replicate-cursive-bug
 1. Start Run nREPL with Leiningen REPL
 1. Open file `src/clj/replicate_bug/core.clj`
 1. Run Tools > REPL > Load file in REPL

Tested on Version: 1.3.1-eap1-2016.2
It doesn't happen to me on 1.3.0-2016.2

**Comment by danielcompton** [comment]
I also noticed this by having two files, `test.clj` and `test.cljc`. Neither required the other, but I still got this error.
