### ISSUE TITLE
Support CLJS namespace aliasing

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1481]
A new feature of CLJS (unreleased at time of writing) lets you write `clojure.test` and have the CLJS compiler fall back to `cljs.test` if it can't find a ClojureScript/CLJC file called `clojure.test`: http://blog.fikesfarm.com/posts/2016-07-03-clojurescript-clojure-namespace-aliasing.html

This means that a CLJC namespace requiring `[clojure.test :as t]` should resolve valid in CLJS mode and CLJ mode.

**Comment by mtruyens** [comment]
This is now official in Clojurescript 1.9.198: https://groups.google.com/forum/#!topic/clojure/-uG5kDcSEIs

**Comment by cursive-ide** [comment]
Yes, I'm going to get this into a 1.4.0 EAP release soon.

**Comment by cursive-ide** [comment]
Sadly, I've had to bump this to the next EAP build due to the subtleties involved.
