### ISSUE TITLE
Namespaced map literal (Clojure 1.9.0) breaks structural editing

### ISSUE THREAD

**Issue by vmarcinko** [cursive-ide/cursive#1482]
New namespace map literals currently (Cursive 1.3.1) don't play well with structural editing where they are not treated as a whole, but as 2 expressions, so some paredit actions such as slurp/barf don't work as expected.

**Comment by wilkerlucio** [comment]
I'm also finding this problem, but in my case, it's causing the editor to mistakenly think I'm sending extra arguments to the function, as:

![screenshot 2016-08-26 09 40 05](https://cloud.githubusercontent.com/assets/25736/18005573/1b9a44a0-6b71-11e6-8208-9bcc66717a59.png)

**Comment by cursive-ide** [comment]
I believe this should have been fixed in the last EAP.
