### ISSUE TITLE
Support symbol resolution with clojure namespace aliasing

### ISSUE THREAD

**Issue by mfikes** [cursive-ide/cursive#1491]
If you have ClojureScript code that looks like

```
(ns foo.core
  (:require [cojure.spec :as s]))

(s/def ::even? (s/and number? even?))
```

an improvement to Cursive would be smarts to understand `clojure` -> `cljs` namespace aliasing logic so that the `s/def` and `s/and`, _etc_. are resolved in the IDE.

**Comment by cursive-ide** [comment]
Yes, this is #1481 I believe.
