### ISSUE TITLE
“Error generatings stubs” because of warnings

### ISSUE THREAD

**Issue by atroche** [cursive-ide/cursive#1492]
Hi Colin,

Great idea re. generating stubs, it's going to make working with Amazonica much nicer (I was already using `cursive/datomic-stubs`).

I'm getting this error when trying it out though:

![image](https://cloud.githubusercontent.com/assets/29839/17720659/f22ef450-6466-11e6-9097-aa35c4d9116d.png)

These are warnings I normally get when launching a REPL etc.

Cheers,

Alistair

**Comment by cursive-ide** [comment]
Interesting - does this prevent the stubs from being created? I don't think it should. I'll see what I can do about that, I'm not sure that just filtering out all warnings is a good idea, but I'm not sure what the best way to display them would be.

**Comment by atroche** [comment]
Oh, good, it actually is generating stubs:

![image](https://cloud.githubusercontent.com/assets/29839/17721240/274c2fa4-646c-11e6-8569-2e07fc9a45cd.png)

I got confused because there's a case where Amazonica doesn't provide a namespace for one of the AWS classes, and I do it manually:

```clj
(ns cal.utils.admin.route53-domains
  (:require [amazonica.core :as amz])
  (:import com.amazonaws.services.route53domains.AmazonRoute53DomainsClient))

(amz/set-client AmazonRoute53DomainsClient *ns*)
```

![image](https://cloud.githubusercontent.com/assets/29839/17721206/d18d2ce4-646b-11e6-8ccf-3885e81a3272.png)

Obviously that's well outside the scope of what you're trying to do :)

I also just realised that I can manually declare the functions I need like this:

```clj
(amz/set-client AmazonRoute53DomainsClient *ns*)

(declare list-domains)
(declare check-domain-availability)
(declare register-domain)
```

Thanks for your help!

**Comment by cursive-ide** [comment]
Nice, glad it's working. In a later EAP when you can add namespaces yourself, you should be able to add your additional namespace at that point. The only caveat is that it may need to be manually refreshed - I still haven't thought through the edge cases yet.
