### ISSUE TITLE
Ability to ignore certain "Require namespace" hints

### ISSUE THREAD

**Issue by madvas** [cursive-ide/cursive#1499]
In a file I require `time` as alias from my own namespace, not `clj-time.core`. It's like `[myproject.time :as time]`. This namespace works as wrapper around `clj-time.core`, so there's no `now` function directly defined. I don't expect IDE to understand this, I just want to tell IDE not to give me "Require namespace" bubble for `time/now`. Bubble keeps showing up constantly, visually blocking other code.

![image](https://cloud.githubusercontent.com/assets/3857155/17865830/59878716-68a4-11e6-9c93-477eb2a23da6.png)

**Comment by cursive-ide** [comment]
I see - yes, this is annoying. In this case, it shouldn't offer to require at all if you already have the same alias used for a different namespace.
