### ISSUE TITLE
Symbol resolution in if-let branch resolves incorrectly

### ISSUE THREAD

**Issue by dmarjenburgh** [cursive-ide/cursive#1518]
In the following code

```clojure
(if-let [x nil]
  x
  x)
```
The symbol `x` in the second branch (when `x` is `nil`) should not be resolvable (it will not compile), but Cursive resolves it to the `x` in the binding.

The same if true for: `if-some`, `when-let`, `when-some`

**Comment by cursive-ide** [comment]
Yes, this is #500.
