### ISSUE TITLE
Find usages is not considering the new keyword destructuring

### ISSUE THREAD

**Issue by wilkerlucio** [cursive-ide/cursive#1523]
When trying to find usages for a given keyword, Cursive currently doesn't detect correct keywords expanded by the new `:NAMESPACE/keys [...]` syntax. Example, given the following code:

``` clojure
(s/def :person/name string?)
; given we ask to find the usages of :person/name

; the parameter on this function is found at the usages
(defn name [{:keys [person/name]}]
  name)

; this is not being considering an usage, even though is equivalent of the previous one
(defn name' [{:person/keys [name]}]
  name)
```

**Comment by wilkerlucio** [comment]
Ah, and one quick extra, please consider that this is also valid syntax: `(let [{::keys [from-cur-ns]}])`.

**Comment by yonatane** [comment]
I've seen this fixed at 1.4.0-eap4-2016.2 (didn't try ::keys though)

**Comment by wilkerlucio** [comment]
Still not working here.

**Comment by wilkerlucio** [comment]
I'm pretty sure this was fixed a long time ago, closing it.
