### ISSUE TITLE
REPL logs error when running defspec

### ISSUE THREAD

**Issue by dmarjenburgh** [cursive-ide/cursive#1525]
When using the defspec macro from clojure.test.check.clojure-test, the REPL logs the following error every time the test is run with the `Run tests in current NS in REPL` command.

![image](https://cloud.githubusercontent.com/assets/4067618/18375986/22e5dfa4-765b-11e6-9b97-6c9a904667b6.png)

When the test-var is run as a function in the repl, no error is shown. Only on the REPL command.
(I'm using OS X 10.11.6, Cursive 1.4.0-eap2-2016.2, Clojure 1.8.0, test.check 0.9.0)

**Comment by ikitommi** [comment]
Same here with the latest version per today, with this ns:

https://github.com/metosin/spec-tools/blob/master/test/cljc/spec_tools/json_schema_test.cljc

using `[com.gfredericks.test.chuck.clojure-test :refer [checking]]`

**Comment by miikka** [comment]
Still experiencing this when using defspec with Cursive v1.8.0-2018.3.

**Comment by conan** [comment]
I'm also experiencing this problem, and I can't run the test under the caret - it isn't interpreted as a test because there's no `deftest` presumably.  

Cursive 1.8.2-eap4-2019.1

**Comment by Vinai** [comment]
Still happening with 1.9.1-eap1-2019.1
