### ISSUE TITLE
Clojure scratch files cannot be loaded into REPL due to file extension

### ISSUE THREAD

**Issue by kernelp4nic** [cursive-ide/cursive#1528]
When I create a scratch file, the file is named `scratch`, `scratch_1` and so on. But this files cannot be loaded into the REPL.

If I browse to the folder of scratches and change the file extension the file correctly loaded to the REPL.

![2016-09-13_12-19-54](https://cloud.githubusercontent.com/assets/519481/18479741/7d628546-79ac-11e6-9fd6-50ff00a64bc5.png)

**Comment by cursive-ide** [comment]
The description of this issue is obsolete - scratch files are now created with the correct extension. However loading files still didn't work due to another message: "Cannot load <file> file into the active REPL. It is not in scope for the module used to start the REPL". This is now fixed.
