### ISSUE TITLE
Printing namespaced maps doesn't match Clojure

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1541]
Reported via Slack:

```
(binding [*print-namespace-maps* false] {:foo/bar 1})
=> #:foo{:bar 1}
```

**Comment by cursive-ide** [comment]
This is trickier than I expected, and I have moved it out of the 1.4.0 EAP for the moment.

nREPL prints its values using the `pr-values` middleware ([here](https://github.com/clojure/tools.nrepl/blob/master/src/main/clojure/clojure/tools/nrepl/middleware/pr_values.clj)). This is unfortunately not very customisable, in particular there's no way to set the `*print-namespace-maps*` variable. See [NREPL-55](http://dev.clojure.org/jira/browse/NREPL-55) for a request to allow this to be customised. 

As described in that link, Whidbey does hack that variable by fiddling with the nREPL internals. Something similar might be possible, but is likely to compose badly with anyone who has Whidbey installed in their project. 

CIDER also has its own pprinting [middleware](https://github.com/clojure-emacs/cider-nrepl/blob/master/src/cider/nrepl/middleware/pprint.clj), but I don't know if they completely replace nREPL's evaluation infrastructure or not.

Cursive will happily pretty-print whatever values are sent back, so if a sane way to customise the value printing can be found, Cursive will handle it out of the box.

**Comment by cursive-ide** [comment]
On a closer reading, what CIDER does is to create a transport which removes `:value` fields and pprints them to output. This seems unlikely to compose well either.

**Comment by danielcompton** [comment]
Namespaced maps also don't print on separate lines in the test results window, which makes them hard to read for large maps.

<img width="635" alt="screenshot of intellij idea 26-05-17 5-13-49 pm" src="https://cloud.githubusercontent.com/assets/811954/26481669/dbf25f84-4236-11e7-865a-a00336ca99f3.png">
<img width="635" alt="screenshot of intellij idea 26-05-17 5-14-19 pm" src="https://cloud.githubusercontent.com/assets/811954/26481671/ddbdc966-4236-11e7-8125-0f56256eb1cc.png">

**Comment by sashton** [comment]
Further example of hard to read test results. It's pretty un-usable at the moment.

![screenshot from 2017-08-16 21-05-04](https://user-images.githubusercontent.com/1523536/29394310-c3ca35dc-82c6-11e7-8f1e-51fb7d9a2eba.png)

![screenshot from 2017-08-16 21-04-45](https://user-images.githubusercontent.com/1523536/29394314-ca1fd2c0-82c6-11e7-8ddc-1f49d1136294.png)

**Comment by cursive-ide** [comment]
Ok, this whole issue is not resolved due to the problems described above, but the namespaced map printing in test results is fixed for the next build.

**Comment by wilkerlucio** [comment]
Any news on this? As more as I used namespaced keywords, more I would like to get rid of them -.-

**Comment by puredanger** [comment]
Just a side note - on the original example, the code is not actually being printed inside the binding so the example is just returning a map, which is then printed by the repl. It is possible to modify the printing behavior if you print inside the binding where the dynvar is set:

`(binding [*print-namespace-maps* false] (prn {:foo/bar 1}))  ;;=> {:foo/bar 1}`

**Comment by cursive-ide** [comment]
@puredanger But then the result is actually a string, right? i.e. Cursive won't pretty print and highlight it.

**Comment by puredanger** [comment]
Right, this is why I said it’s a side note. I think the primary issue here is how to get the Print part of the REPL to do the right thing.

The point I’m making is that the first example in this issue is confusing because the binding is not wrapping any call to print, so that binding will never have any effect.

A sufficient example is to just do:

`{:foo/bar 1}`

Which will rely on the repl printer to decide how to print the response.

**Comment by cursive-ide** [comment]
I'm marking this as closed, since this has been fixed in recent nREPL versions as `nrepl/nrepl#33`.
