### ISSUE TITLE
unable to launch a repl for projects that don't explicitly declare clojure version

### ISSUE THREAD

**Issue by cprice404** [cursive-ide/cursive#1542]
This is related to lein 2.7.1, `:managed-dependencies`, and the `lein-parent` plugin.

The latest cursive EAP ( `1.4.0-eap2-15` ) doesn't work with `lein-parent` because Cursive has a hook around `leiningen.core.project/read` (or perhaps `read-raw`) that assumes the input is going to be a File; however, with `lein-parent` it may instead be a `Reader`, so cursive throws an error.

As an attempt to workaround this we tried creating a different plugin that does the same sort of thing to get managed dependencies from a parent project, but doesn't call the functions in `leiningen.core.project`, to avoid Cursive's hook.  This works insofar as it allows us to get past the errors in just loading the leiningen project in Cursive.  However, if you then try to create a REPL configuration, you get an error in the Run/Debug configuration dialog that says:

`Run Configuration Error: No Leiningen modules containing clojure.main found`

Presumably this is because we are trying to inherit the clojure version from our parent project (to ensure that all of our projects are using a consistent version).  So if I change the dependency from:

```clj
[[org.clojure/clojure]] ; no version specified, inherit from parent
```

to

```clj
[[org.clojure/clojure "1.8.0"]]
```

and then do "Refresh leiningen projects" in cursive, then the REPL will work.

**Comment by cursive-ide** [comment]
This is fixed (or at least, made redundant) by fixing #1543.
