### ISSUE TITLE
Assoc incorrectly indented 1.4.0-eap3-2016.2

### ISSUE THREAD

**Issue by scottlowe** [cursive-ide/cursive#1550]
I got an automatic update today and noticed that formatting of `assoc` has changed.

```
(assoc {}
  :foo
  :bar)
```

Pretty sure that this relates to Cursive 1.4.0-eap3-2016.2, because Cursive was doing the right thing previously.

I have tried altering the indentation preferences but I'm unable to get the correct effect.

**Comment by cursive-ide** [comment]
As far as I can remember, the `assoc` formatting has always been like that in Cursive. It's somewhat controversial, but it hasn't changed for a long time.

I've added a new indentation type (which I've been meaning to for a while now) of "Function", which will indent a form as functions do by default - this sounds like what you want.

**Comment by scottlowe** [comment]
I've got your update. Works a treat!

Thank you! :-)
