### ISSUE TITLE
Constant high CPU usage on clojurescript project

### ISSUE THREAD

**Issue by thheller** [cursive-ide/cursive#1554]
Whenever I try to work on the clojurescript source Cursive will constantly use a large amount of CPU time spread over multiple cores. IDEA/Cursive work as normal but due to the constant usage the fans of my macbook are running constantly and power is drained quite rapidly.

Note that I am not doing anything, just one file open and we are at about 125% cpu used. after the file has been open only quitting IDEA will end the CPU usage. Looks like a loop somewhere isn't stopping ever.

Steps to reproduce:
- `git clone https://github.com/clojure/clojurescript.git`.
- Open IDEA and "Import Project" via the `project.clj` of clojurescript. Wait for everything to settle down and note that the CPU is still fine.
- Open `src/main/clojure/cljs/analyzer.cljc`. There is a short burst of CPU activity but after that the CPU does not return to normal levels even after closing the file.

Can be reproduced after restarting IDEA. Not sure if other files are affected as well but this is the simplest way to reproduce it.

Might be something on my machine as I have not tested anywhere else. It is a MacBook Pro (Retina, 15-inch, Mid 2015) running macOS Sierra 10.12 (but I saw this issue on 10.11 as well).

**Comment by danielcompton** [comment]
Can you try 'Invalidate Caches / Restart' to check if this goes away after blowing away the cache?

<img width="407" alt="screenshot of intellij idea 7-10-16 8-32-26 am" src="https://cloud.githubusercontent.com/assets/811954/19167539/9aedc084-8c68-11e6-85b4-a85b234214fe.png">

**Comment by thheller** [comment]
Tried that before ... no luck. I can reproduce this on a fresh checkout with a new project so cache should not be a factor anyways.

**Comment by CmdrDats** [comment]
I'm having similar pains, my machine is not having fun with all the CPU churn

**Comment by danielcompton** [comment]
I don't see the high CPU usage, but Cursive is very prone to hanging for me when working on the ClojureScript project.

**Comment by k7d** [comment]
Still appears to be happening in 1.5.1-10-g290cf84. This is CPU when I'm not doing anything:

![image](https://user-images.githubusercontent.com/181645/26985238-d48cbc16-4cff-11e7-9852-76efaa8f577e.png)

It makes the editor itself nearly unusable as there frequent visible delays when editing code.
