### ISSUE TITLE
Option to deactivate editor frame on REPL command

### ISSUE THREAD

**Issue by spieden** [cursive-ide/cursive#1562]
I'm using tools.namespace to reload code (instead of the inbuilt Cursive file reloading) via a REPL command bound to a key combination. Files aren't saved in Intellij until an editor frame is deactivated, so running "refresh" via the REPL command doesn't pick up changes just made. (You instead have to switch editor frames or activate the REPL to deactivate and flush the frame you modified.)

This ticket is to add an option to deactivate and reactivate the current editor frame when running a REPL command.

**Comment by cursive-ide** [comment]
Just to clarify - the requirement is actually that all files should be saved before running a REPL command, correct? This makes perfect sense, I'll do that.
