### ISSUE TITLE
idea 16 cant create leiningen project

### ISSUE THREAD

**Issue by 602884291** [cursive-ide/cursive#1563]
idea 16 cant create leiningen project

**Comment by cursive-ide** [comment]
I'll need some more detail on what is going wrong to help with your problem.

**Comment by 602884291** [comment]
Today, I finally solved the problem.The reason is that the hosts file  is not configured for localhost 127.0.0.1,so leiningen throw Connected refused Exception,but idea not will show this message，So it caused idea to crash.And cause me to think it's cursive's problem.
