### ISSUE TITLE
Stop stealing focus when starting REPL

### ISSUE THREAD

**Issue by oshyshko** [cursive-ide/cursive#1579]
The existing behavior of REPL is very irritating and distracting due to consistent keyboard focus theft.

Consider the following scenario:
1. I use  Shift+F10 combination to fire a Clojure REPL (it usually takes few seconds usually to fully load the JVM, so it's typical to launch it ahead of time and continue working on code).

2. A REPL docked window appears at bottom.

3. Keyboard focus is moved to the REPL (but I don't want it, I want to continue editing my source code). I press Escape to move keyboard focus back to editor, and keep editing, while REPL is initializing.

![image](https://cloud.githubusercontent.com/assets/73026/20122482/e6343ce4-a5cc-11e6-8093-2d073cb19d1e.png)

4. Keyboard focus is in editor, I am working on source code. Something changes in REPL window, presumably it finished loading the JVM and is ready for input. The focus is stollen again and moved back to REPL (as it goes through initialization steps) -- while I continue typing on keyboard, thinking I am editing the code and then discover that the focus got stollen. Again. I press Escape again to move back to editor and try to restore what I was working about...

This is very irritating and distracting and happening again and again.

Please, don't steal keyboard focus and let the user decide where to put it.

P.S. The philosophy of IntelliJ IDEA is to never steal keyboard focus.
It *always* remains in the editor. No background jobs can steal it. It's sacred.

The way I personally use REPL never requires focus in REPL window. I send pieces of code directly from editor.

I *never* use input field at the bottom of the REPL -- basically it's just a huge line of UI that occupies a portion of a screen that I never use. I remember that La Clojure didn't have that separation between the log and input field -- it was just one field. In other words, La Clojure was not wasting screen space, but still let typing expressions into REPL for those who wanted that.

P.P.S. There is `[x] Activate tool window` setting in REPL run configuration, but it's state is ignored -- it keeps stealing the focus two times.

![image](https://cloud.githubusercontent.com/assets/73026/21440846/d95a7fc0-c849-11e6-86e0-7e738773cde2.png)

**Comment by cursive-ide** [comment]
This is a tricky issue. Looking at the code, you're correct that the focus is taken multiple times and that should probably be fixed. But you're wrong that the focus is never taken by toolwindows - if you open a new terminal, or any of the many console types (I tried the Kotlin REPL and the Python Console), they will receive the focus when the toolwindow is opened. In general, if you start some process and the expectation is that you will type into it, IntelliJ will focus it. It's more difficult in this case because the Clojure REPL takes so long to start.

Most users *do* type into the REPL pane, and if I change this so that it never receives the focus then those users will have to use another keystroke every time they start a REPL. Users already complain that too many keystrokes are required to get a REPL running in a new project, and I don't want to add to that.

The "Activate tool window" setting is not for this, that is used with normal run configs to control whether the toolwindow is opened at all by default.

I think the best option here is probably to provide a checkbox in the run configuration controlling whether to focus the input box or not. Then it can be controlled per run config, or set in the run config defaults to whatever you want.

BTW re: the screen space use compared to La Clojure - La Clojure did actually separate out the REPL input and output fields, it just had no visible divider between them. Output was never shown in the last line of the REPL window. So the only space you're actually losing compared to La Clojure (or the other IntelliJ terminal types) is the thickness of the divider.

**Comment by oshyshko** [comment]
> But you're wrong that the focus is never taken by toolwindows...

Nope. It seems that there's a misunderstanding happening between "focus never taken by toolwindows" (which I didn't say) and "stealing focus" (which I actually said):

> P.S. The philosophy of IntelliJ IDEA is to never steal keyboard focus.
> It always remains in the editor. No background jobs can steal it. It's sacred.

Key points: *stealing focus* and *background jobs*. All attention to user pain points.

If a user opens a terminal by clicking its toolwindow or by a keystroke -- it's user action.
The user wants the focus to be there. He intended it. The window opens and the focus is *immediately there* -- giving immediate feedback that the input is happening there now.
No keyboard focus theft happening -- everything is as user expecting.

Now let's compare it to what happens with Cursive REPL:

1. A user launches Cursive REPL, let's say using `Shift+F10` key.
2. Cursive REPL opens at the bottom. BUT! The focus remains in the editor -- so the message the user receives from UI is "I got your action, I drew something on screen, but I haven't taken your cursor, see? So you are free to continue working on wherever you were." -- this makes Cursive REPL some sort of *background job* -- it didn't take an action on grabbing the focus, so it has no right to do it in future whenever it decides to. It has the behavior of *background job*.
3. So the user continues working, believing that he is in control of the situation.
4. But Cursive REPL decides at some *random* point in time to actually grab the focus, regardless of what the user was doing, in the middle of his work -- the UI basically unusable anyways for the duration of several seconds between the moment Cursive REPL was launched.

This is focus theft. This should not happen.

You either grab focus immediately after user action (if this was *intended by user* action), or never take it afterwards. But you never keep user in a state when he or should be waiting some undetermined time to be interrupted -- let the user be in control of his computer.

Important point: if an interactive UI element grabs focus when it was touched and receives input cancellation (`Escape` key in IntelliJ) -- the signal from user is that "I got you, but I don't want to work with now, dismissed.", the UI element should never grab the focus event (what Cursive REPL is doing), once dismissed it should never annoy user.

> I think the best option here is probably to provide a checkbox in the run configuration controlling whether to focus the input box or not. Then it can be controlled per run config, or set in the run config defaults to whatever you want.

This would be great.

With this setting you both groups of users will be happy:
- those who use REPL as a "output" window and send pieces of code directly from editor
- those who program directly from REPL (still, there should be no delay in taking focus after launch or ignoring of `Escape` key)

> La Clojure did actually separate out the REPL input and output fields, it just had no visible divider between them.
Oh, I see. Then La Clojure wastes screen space as well, it just does it in less obvious way (no distracting extra lines across the screen).

P.S. Not all tool windows that have input steal focus.

So, for `terminal` -- grabbing focus is the only behavior. There's no way of controlling terminal through keys, except when it's focused. Also, running a terminal and having it on screen without controlling it is useless. So, the only possible and meaningful reaction to user input is to open terminal UI and give it focus immediately.

> (I tried the Kotlin REPL and the Python Console ...

As for Python and Kotlin: yes, they are REPL, but REPLs can be controlled without direct control (compare to Terminal example above). Also, those are 3rd party plugins (even that Kotlin is being developed at JetBrains), they are relatively new, inexperienced (in terms of UI/UX, especially when compared to what IntelliJ original designers and UI/UX specialists did) and you probably going to do a disservice to yourself if you follow their examples, rather than investigating users' pain points of your UI/UX.

Here is an example of a tool window that doesn't take focus:

1. Create `Example.java` in a Java project and paste this:
```java
import java.io.IOException;

public class Example {
    public static void main(String[] args) throws IOException {
        System.out.println("Press enter to continue");
        System.in.read();
    }
}
```
2. While in the editor, press `Ctrl + Shift + F10` (on windows) -- this will compile and launch the program.

You will see a window that is not focused, but which is expecting input.

**Comment by cursive-ide** [comment]
> Also, those are 3rd party plugins (even that Kotlin is being developed at JetBrains), they are relatively new...

No, they're not - PyCharm is a full JetBrains IDE, and the source is in the IntelliJ community edition source repo. It went 1.0 in 2010. Kotlin is newer, but it has senior JetBrains people working on it - it's no side project.

Anyway, we'll have to agree to disagree on some of the details. Unfortunately there are two alternatives when someone does want the focus in the REPL - immediately focus the REPL when it starts and make them wait a long time before they can do anything, or focus the REPL when it's ready, which will be some arbitrary time after the user executing the command to start the REPL. Neither are very good. But you're right that the multiple focusing is a bug, I'll fix that and I'll add the option to not focus the REPL at all.

**Comment by oshyshko** [comment]
>  I'll fix that and I'll add the option to not focus the REPL at all.

Thank you!

**Comment by oshyshko** [comment]
The issue is still relevant.
Cursive version `1.5.0-2017.1`
