### ISSUE TITLE
Changing to dark color scheme confuses REPL 

### ISSUE THREAD

**Issue by mtruyens** [cursive-ide/cursive#1594]
When I change IntelliJ's theme from the white default to dark ("Darcula"), everything goes fine — except for error messages printed in the REPL (which are almost invisible, due to the black font color). I have to restart IntelliJ to restore the color of the error messages in the REPL.

This may seem like a trivial annoyance, but it means that I have to restart IntelliJ at least twice each day (I like the dark colors early in the morning and late in the evening, but not throughout the day).

Example of how everything should look:
<img width="870" alt="screen shot 2016-11-24 at 20 54 59" src="https://cloud.githubusercontent.com/assets/1895793/20609072/7901e220-b288-11e6-97ce-65ca2d21efd1.png">

Example of the wrong color of the error messages:
<img width="716" alt="screen shot 2016-11-24 at 20 54 14" src="https://cloud.githubusercontent.com/assets/1895793/20609088/a35a0318-b288-11e6-9487-6409a8b37853.png">

**Comment by Menthalion** [comment]
Also ran into this problem today. When switching the color theme with CTRL-` from default to Darcula, all windows except for the REPL output immediately change their color correctly. To have the REPL output change, ALL IntelliJ instances need to be closed and IntelliJ restarted.

This is pretty bothersome for people that need to switch themes much based on daytime or light conditions (glare)

**Comment by cursive-ide** [comment]
This is fixed for the next build. Let me know if there are still problems with this, there were a few places where colours were calculated and then cached.

**Comment by mtruyens** [comment]
Reopening, because the problem seems to have returned in 2018.2.1 — but not all of the time. (It seems to me that when a file was opened for quite a long time, it will no longer change its theme, while freshly opened files do...).

**Comment by cursive-ide** [comment]
When you say files, are you talking about files in editors? Because the original problem was in the REPL, correct?
