### ISSUE TITLE
High CPU usage (from REPL?)

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1598]
Since updating to 2016.3 I've noticed really high CPU usage in the REPL on a project, and culminating in either a hang or OOM. I've sent through my logs and a heap dump privately. It looks like there is something in the REPL system which is running something in the background and it grows over time. Bit of a vague bug report sorry, happy to provide more info if needed.

**Comment by cursive-ide** [comment]
I've seen something like this as well. I'll investigate what you sent, thanks.

**Comment by madvas** [comment]
After update, I get high CPU usage + very slow responsiveness when editing clojurescript function which contains js interop. For example: 
```clojure
(.toString "abc")
``` 
Couple of these inside function and I can barely edit that function. Interestingly editing other functions works perfectly fine at full speed. Only when I try to touch function that contains JS interop

**Comment by danielcompton** [comment]
That kinda matches what I was seeing, I was doing file IO with Java interop.

**Comment by hmnjeon** [comment]
I've experienced the same bug when I was experimenting with clojure.spec library. And also symbol resolution in REPL went on and off frequently.

**Comment by madvas** [comment]
I believe this is still not completely resolved in `Version: 1.4.2-eap1-2016.3`. It it definitely somewhat better than before, but editor is still noticebly slower when editing functions with JS calls like `(.toString )` in CLJS

**Comment by madvas** [comment]
Please fix this bug, it makes cursive unusable for JS interop. Still not fixed in ` 1.5.0-eap1-2016.3`
