### ISSUE TITLE
REPL gets slower over time 

### ISSUE THREAD

**Issue by PetrGlad** [cursive-ide/cursive#1605]
I suspect that the problem is caused by syntax highlight in REPL output window. To trigger the problem  try evaluating `(range 1000000)` in REPL. The result is eventually printed, but Idea almost hangs, and AWT event queue thread is busy allocating lots of RangeHighlighterImpl and RangeHighlighterTree$RHNode. So heap is full, GC is busy. 
If I patient enough or click "Clear output for current REPL" then in a while Idea gets back to normal. 
But without clearing output window after evaluating `(range 1000000)` 3 classes RangeHighlighterImpl, RangeHighlighterTree$RHNode and SmartList-s (that hold range highlighters) take 70% of 1gb heap.  

Output highlighting is nice as long as it does not get in the way. Maybe add option to disable it in output? Or highlight only reasonable number of most recent lines?

**Comment by cursive-ide** [comment]
Yes, I came to the same conclusion investigating this last week. I think the solution will be to only retain the last 50k (configurable) lines, or perhaps to only highlight that number, as you suggest.

**Comment by hmnjeon** [comment]
+1. REPL is painfully slow to use after the last (or before that) update. Symbol resolution comes and goes. It hangs for about a second every two or three seconds even after 100 or 200 lines (doesn't take long session to become a resource hogging monster). REPL is a critical part of my development workflow or any other's workflow I presume, so please make it work again.

**Comment by PetrGlad** [comment]
Maybe I did not notice this before. Today I experienced same problem, then closed all opened editors and cleared REPL output and input panes. So now REPL is completely empty and no opened editors. But AWT event loop is still keeping CPU busy and allocating memory. After closing REPL ~500mb freed, and CPU usage back down to almost zero.

**Comment by PetrGlad** [comment]
Also I just tried 1.4.2-eap1-2016.3
Linne limit seem to help with the problem but only if pretty printing is enabled. Pretty printing splits lines so number of lines grows with output size.
`(range 1000000)` still causes problems if "Pretty print REPL return values" is not enabled. Apparently because we have one extremely long line.
