### ISSUE TITLE
IDEA quits when nREPL is running

### ISSUE THREAD

**Issue by pganelin** [cursive-ide/cursive#1609]
I started using nREPL in IDEA 2016.3 and after a few minutes IDEA crashes (JVM crash) generating "replay_pid*.log" file  in C:\Java\IDEA-2016.3\jre\jre\bin\ directory. Never happened before with just Java development. Should I report the issue to cursive, IDEA team or Oracle?  I attached crash file (renames log ->txt).

Clojure version: 1.8.0
Cursive version: 1.4.1-2016.3

[replay_pid9184.txt](https://github.com/cursive-ide/cursive/files/649563/replay_pid9184.txt)

**Comment by cursive-ide** [comment]
I think this should be reported to JetBrains - certainly Cursive shouldn't be able to provoke an IDE process crash.
