### ISSUE TITLE
MacOSX keybindings issue

### ISSUE THREAD

**Issue by achikin** [cursive-ide/cursive#1610]
Steps to reproduce:
1. Go to Preferences -> Keymap

2. Copy standard schema

<img width="711" alt="cursive1" src="https://cloud.githubusercontent.com/assets/611419/21173712/1f2a1c92-c1ea-11e6-9679-254d2b4f8beb.png">

3. Go to Preferences -> Keymap -> Clojure keybindings

4. Choose Cursive

5. Uncheck checkboxes for bindings you don't want to activate

<img width="1110" alt="cursive2" src="https://cloud.githubusercontent.com/assets/611419/21173753/5850313c-c1ea-11e6-9686-a29b51531cc4.png">

6. Press <kbd>Apply</kbd>

7. As you'd expect - they don't appear in the 'Current key' column. As you don't expect - all checkboxes that you've unchecked are checked and vice versa.

<img width="1114" alt="cursive3" src="https://cloud.githubusercontent.com/assets/611419/21173804/aee54a32-c1ea-11e6-9592-8e2659092a7c.png">

8. Close Preferences and open them again

9. All checkboxes are unchecked. **All** keybindings are listed in 'Current key' column.

<img width="1126" alt="cursive4" src="https://cloud.githubusercontent.com/assets/611419/21173847/e959e86c-c1ea-11e6-9434-d8d7b3e46bb7.png">

10. Close Preferences and try <kbd>⌘</kbd>+<kbd>[</kbd>. Instead of taking you to the previous editing place it wraps whatever under cursor with square brackets. Which means the binding is active and there is no way to switch it off.

IntelliJ IDEA 2016.3
---------------------------------------------------|
Community edition
Build #IC-163.7743.44, built on November 18, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Cursive 
--|
Version 1.4.1-2016.3
Built on: 2016-12-06 20:53
Built from: 1.4.1

**Comment by cursive-ide** [comment]
This has been obsoleted by #1863.
