### ISSUE TITLE
Please add "Sync files in REPL automatically" option

### ISSUE THREAD

**Issue by devurandom** [cursive-ide/cursive#1623]
It would be great if whenever I save a file in the editor, it would be automatically synced to the REPL.

**Comment by cursive-ide** [comment]
This pretty much works like this already, only in reverse. In IntelliJ, you almost never save files by hand - it's done automatically. So the best way to do this is to use *Tools->REPL->Load file in REPL* or *Tools->REPL->Sync files in REPL* - these will both save all files before loading.

**Comment by ketankshukla** [comment]
Can you add the option of syncing the files automatically on auto save? That way I don't have to keep typing the shortcut to do it manually.
