### ISSUE TITLE
Unused Imports and Global Variables Not Detected

### ISSUE THREAD

**Issue by NarekA** [cursive-ide/cursive#1637]
I have noticed that my unused imports and unused global bindings are not being detected I am running `Version: 1.4.3-2016.3`.

![screen shot 2017-01-13 at 2 55 53 pm](https://cloud.githubusercontent.com/assets/737367/21948477/6997b0b4-d9a0-11e6-8ca2-3b26a9116b20.png)

**Comment by vincentjames501** [comment]
+1. I've been noticing this for a while. I'm on 1.5.0-eap6. It also seems to be present with unused function arguments.

**Comment by NarekA** [comment]
Yup, I'm getting it with function arguments too.

**Comment by vincentjames501** [comment]
@cursive-ide , this one is a huge bummer and is affecting a few people at my work as well. I feel so dirty committing code with a bunch of unused requires, fn args, etc :( .

**Comment by vincentjames501** [comment]
Not sure how it happened, but my inspections got disabled in Settings>Editor>Inspections>Clojure

**Comment by cursive-ide** [comment]
@vincentjames501 In your mail to the mailing list, you showed a screenshot that showed them enabled. Was the problem the severity?

<img width="552" alt="screen shot 2017-04-30 at 14 40 27" src="https://cloud.githubusercontent.com/assets/5589171/25560859/276fb7d8-2db3-11e7-9ed8-898201538ec1.png">

**Comment by vincentjames501** [comment]
Yes it was.

**Comment by cursive-ide** [comment]
@NarekA Can you confirm whether this is the problem in your case too?

**Comment by NarekA** [comment]
@cursive-ide Looks like that was the problem for me too! I think we can close this issue.

**Comment by cursive-ide** [comment]
Thanks! I have no idea how that might have happened, but I'm glad the fix is so simple.

**Comment by NarekA** [comment]
I remember looking at that, but I didn't realize warning was the correct setting.
