### ISSUE TITLE
"Extend Selection" doesn't work properly when invoked from a keyboard shortcut

### ISSUE THREAD

**Issue by cjkent** [cursive-ide/cursive#1639]
The "Extend Selection" action seems to extend the selection twice when invoked from a keyboard shortcut. If I have 

    (foo)

and I extend the selection with the caret on `foo` I would expect `foo` to be selected. But `(foo)` is selected. Every subsequent time the action is invoked it extends the selection twice. "Shrink Selection" behaves in the same way.

If I open the action popup and invoke "Extend Selection" from there it behaves as expected and only expands the selection one item at a time.

IntelliJ 2017.1 EAP build 171.2014.21
Cursive 1.4.3-2017.1

**Comment by cjkent** [comment]
I've just updated to the latest IntelliJ EAP and the problem has gone away.

**Comment by cursive-ide** [comment]
This is actually a more general but very intermittent bug where Cursive actions are sometimes repeated twice. I suspect it might be an IntelliJ problem but I'm not sure yet.
