### ISSUE TITLE
REPL does not pretty print values that contain namespaced keys

### ISSUE THREAD

**Issue by Odinodin** [cursive-ide/cursive#1648]
The REPL does no syntax highlighting or pretty printing when the REPL result contains namespaced keys.

**Comment by Odinodin** [comment]
Example value that is not pretty printed:

    #:something{:a "a"}

**Comment by onetom** [comment]
According to http://dev.clojure.org/jira/browse/CLJ-1910 :
> TODO: pprint support for namespaced maps
> TODO: printer flag to suppress printing namespaced maps
but in fact `clojure.pprint/pprint` does work in in 1.9.0-alpha14, eg:
```
(pprint '#:leg{:type :deal.type/equity, :name "i2H8SlwI8C17GH4", :notional 3.28814697265625M})

#:leg{:type :deal.type/equity,
      :name "i2H8SlwI8C17GH4",
      :notional 3.28814697265625M}
```
and as the last comments state, there is a flag to turn off this map namespacing:
```
(do (set! *print-namespace-maps* false)
    (pprint '#:leg{:type :deal.type/equity, :name "i2H8SlwI8C17GH4", :notional 3.28814697265625M}))

{:leg/type :deal.type/equity,
 :leg/name "i2H8SlwI8C17GH4",
 :leg/notional 3.28814697265625M}
```

An example in the Cursive REPL however looks like this:
```
(do (set! *print-namespace-maps* false)
    '#:leg{:type :deal.type/equity, :name "i2H8SlwI8C17GH4", :notional 3.28814697265625M})

=> {:leg/type :deal.type/equity, :leg/name "i2H8SlwI8C17GH4", :leg/notional 3.28814697265625M}
```
Not sure why is it on one row, but it's at least syntax highlighted.
