### ISSUE TITLE
Cmd+Shift+L/R resizes REPL instead of selecting line

### ISSUE THREAD

**Issue by a613** [cursive-ide/cursive#1651]
Cmd+Shift+Left and Cmd+Shift+Right are standard keyboard shortcuts for selecting from the cursor to the start/end of the current line.

Recently they have been resizing the width of the REPL tool window, making it impossible to select a line using the keyboard.

Even if this is configurable, I don't think Cursive's defaults should collide with standard shortcuts like these.

Fix criteria:
- By default, bind REPL resizing to shortcuts that aren't standard existing ones

**Comment by a613** [comment]
Decline as not an issue. It looks like the shortcuts were bound by IntelliJ (maybe a recent update), not Cursive.

<img width="753" alt="screen shot 2017-01-26 at 11 09 05 am" src="https://cloud.githubusercontent.com/assets/5733420/22339417/eacb188a-e3b7-11e6-8740-b6122ea5b8c0.png">

**Comment by cursive-ide** [comment]
Ok, thanks for the investigation - you're right that that is a surprising conflict. Fortunately you can just rebind the stretch ones.
