### ISSUE TITLE
REPL keeps freezing

### ISSUE THREAD

**Issue by ertugrulcetin** [cursive-ide/cursive#1668]
It happens most of the time, I can't even move the cursor.

I can't type fast enough because I have to wait the frozen REPL and type it again.

I think this is a huge problem.

**Comment by cursive-ide** [comment]
I need more information than this to be able to help.

1. Does it happen on all projects, or just on one?
2. Does it happen as soon as the REPL is started, or after working for a while?
3. Are you running out of memory in your REPL process or your IDE process? You can check memory usage using the widget enabled by *Settings&rarr;Appearance & Behavior&rarr;Appearance&rarr;Show memory indicator*.

**Comment by ertugrulcetin** [comment]
1) All projects
2) After working for a while.
3) Memory keeps increasing.

**Comment by cursive-ide** [comment]
Which Cursive version are you running? There were fixes for this problem in the latest build.

**Comment by ertugrulcetin** [comment]
Version: 1.4.3-2016.3
Built on: 2017-01-01 17:36
Built from: 1.4.3-4-gcb28fc4

**Comment by cursive-ide** [comment]
Are you able to share a heap dump when the IDE is very slow or locked up? See [here](https://intellij-support.jetbrains.com/hc/en-us/articles/207241235-Reporting-performance-problems) for details on how to do this. Do you have somewhere you could share it and send me a link to cursive@cursive-ide.com?

**Comment by ertugrulcetin** [comment]
Yeah, I will do that.

**Comment by ivarref** [comment]
I'm having this issue too (though it does not completely freeze), particularly if I'm editing multiple lines.

**Comment by cursive-ide** [comment]
@ivarref If you enable the memory indicator, does it appear to be a memory issue as well? Are you able to share a heap dump if so?

**Comment by cursive-ide** [comment]
BTW I can provide space to upload the dumps to if required.

**Comment by ertugrulcetin** [comment]
@cursive-ide any updates?

**Comment by cursive-ide** [comment]
@ertugrulcetin No, I'm going to look at this today hopefully. There seem to be a couple of unrelated problems. In your case, I was also waiting for some memory dumps to be able to investigate.

**Comment by ertugrulcetin** [comment]
It turned out there was no memory leak from my side, I said memory keeps increasing but it was a normal thing and GC starts during the increase so all good.I think it has nothing to do with the memory.

**Comment by cursive-ide** [comment]
I've investigated this and I have a working theory, although I can't reproduce the problem. I'm going to try to produce a dev build to test in the next day or so.

**Comment by rajdevireddy** [comment]
I have the same problem. I increased the -Xmx to 3gb when I first got the out of memory error. And I still keep running into this. This happens after using REPL for few minutes. I am running IDE on a Mac OS X 10.11.6 and here are IntelliJ version details.

IntelliJ IDEA 2016.3
Build #IC-163.7743.44, built on November 17, 2016
JRE: 1.8.0_112-release-408-b2 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Cursive version = 1.4.1-2016.3
Built on: 2016-12-06 20:53
Built from: 1.4.1

Attached a screen print of the memory error popup and heap dump. Appreciate any help in fixing this problem. Thanks.

<img width="728" alt="screen shot 2017-03-01 at 9 28 18 pm" src="https://cloud.githubusercontent.com/assets/6588756/23490465/c6af7ee4-fec6-11e6-8c5d-1dd74010925f.png">

**Comment by ertugrulcetin** [comment]
It looks like it's a common problem.

**Comment by cursive-ide** [comment]
There's a dev build up now on the [plugin repo site](https://plugins.jetbrains.com/plugin/8090-cursive). Try it out by going to the site, selecting the dev channel, and downloading the 1.5.0-eap2 build corresponding to your IntelliJ version. Then you can install it using *Settings->Plugins->Install from disk...*. I'm hopeful that this will fix these slowdown issues.

Note that this is a dev build, I've given it some fairly perfunctory testing but the REPL completion might be buggy or incomplete. I'd love to know about it if that turns out to be the case.

**Comment by cursive-ide** [comment]
Sorry, this was closed automatically in the process of building the dev build, reopening until it's confirmed fixed.

**Comment by ertugrulcetin** [comment]
I couldn't load from disk, I've unzipped the file and got a file called cursive-plugin and followed the path you've provided and selected the cursive file and nothing happened.Maybe I'm doing something wrong I don't know.

**Comment by cursive-ide** [comment]
You don't need to unzip it, just point IntelliJ at the zip file.

**Comment by ertugrulcetin** [comment]
Getting plugin `Cursive` is incompatible with this installation error.

**Comment by cursive-ide** [comment]
That's because you've downloaded the wrong version. Make sure you download the version which is compatible with your version of IntelliJ.

**Comment by cursive-ide** [comment]
I've had no more feedback on this, so I'm going to mark it as closed and release the dev build as an EAP. Any further issues can be filed against that.

**Comment by ertugrulcetin** [comment]
@cursive-ide Thank you so much, now it works great! What was the problem?

**Comment by rajdevireddy** [comment]
Thank you I just installed the 1.5.0.eap3. Will keep you posted if this happens again.

**Comment by cursive-ide** [comment]
@ertugrulcetin Some details are [here](https://groups.google.com/d/msg/cursive/UL6ICi4leV8/hsM6TEiwAwAJ).

**Comment by rajdevireddy** [comment]
Been using the 1.5.0.eap since yesterday. No issues so far. Thank much for the fix.
