### ISSUE TITLE
Add `import-vars` hook for Clojure.Java-Time

### ISSUE THREAD

**Issue by dm3** [cursive-ide/cursive#1670]
Moved from #711.

Currently Cursive doesn't expose any extension API for custom symbol resolution. There's built-in support for Potemkin (`import-vars`). [Clojure.Java-Time](https://github.com/dm3/clojure.java-time) decided to copy the `import-vars` macro into its source tree to avoid the dependency on Potemkin. 

As per our conversation on Slack#cursive, could you please add support for `java-time.potemkin.namespaces/import-vars` to Cursive until the extension API is released?

**Comment by cursive-ide** [comment]
Looking back at this, I remembered why this was difficult. It's not just the `import-vars` issue, but also the fact that `clojure.java-time` dynamically creates a lot of vars using macros. I've solved both issues with Cursive's relatively new stubs functionality, which will introspect the `java-time` namespace and create indexable stubs. I've played around with the API a bit and it seems to work - please let me know if there are further issues.

**Comment by sooheon** [comment]
I'm not seeing support for java-time

**Comment by ivos** [comment]
On Version: 1.8.1-eap2-2017.2.

Still not supported in Cursive.

![cursive-java-time](https://user-images.githubusercontent.com/389192/52482597-f9b36480-2bb1-11e9-8093-710dc27e81a6.png)

**Comment by cursive-ide** [comment]
@sooheon @ivos To get this support, you should see a notification pop up, which looks like this:

![Screen Shot 2019-03-11 at 14 18 27](https://user-images.githubusercontent.com/5589171/54094864-b3f9df80-439b-11e9-85ed-1a6817118007.png)

Clicking the "Generate now" link will cause the support to be built for Cursive.

**Comment by Sangdol** [comment]
Thanks for the answer, @cursive-ide. 

I don't see the pop up for some reason even after restarting my Intellij. Is there any way to trigger the pop-up notification or generate the stub?

**Comment by mdhaney** [comment]
@Sangdol I had the same issue today and I right-clicked on the project and choose "Refresh Clojure Deps Projects".  After it loaded the deps again, I got the popup asking to generate stubs and then it was able to resolve the clojure-time vars.

**Comment by Sangdol** [comment]
@mdhaney thanks for the answer. When opened the file to check it out today, the problem was already gone. That said, I believe your answer will help others who end up on this page for this issue.

**Comment by cnwobi** [comment]
I do not get the pop-up for some reason
