### ISSUE TITLE
Make ns form formatting obey 1-space-list setting

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1676]
It should be possible to format `ns` forms like this: https://stuartsierra.com/2016/clojure-how-to-ns.html. Currently this is not possible because the `ns` formatting customisations don't take the 1-space-list formatting setting into account.

**Comment by gfredericks** [comment]
Probably not directly relevant, but just in case I should mention that I have a linter lein-plugin thing that targets this format: https://github.com/gfredericks/how-to-ns

**Comment by cursive-ide** [comment]
One thing to note is that the ns guide doesn't really specify anything about the indent, just how the forms themselves are used. The [Clojure style guide](https://github.com/bbatsov/clojure-style-guide#one-space-indent) does, but that's [contentious](https://github.com/bbatsov/clojure-style-guide/issues/126). Recent versions of clojure-mode provide a setting to allow two-space indent by default.
