### ISSUE TITLE
Lein Artifact Search could search for partial matches in artifact name

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1677]
Typing "async" or "core.async" in the artifact search doesn't bring up core.async, only "org.clojure:core.async" or "org core.async" does. It looks like only the group ID is being searched for partial matches, not the artifact ID?

**Comment by cursive-ide** [comment]
Yes, this was [mentioned](https://groups.google.com/d/msg/cursive/DYOqfuEHhAs/_hKU31LqAgAJ) on the mailing list too.

**Comment by danielcompton** [comment]
I still find searching for "core.async" doesn't bring up "org.clojure/core.async", but if I type in "org.clojure" then core.async is a selection offered. Not sure if this is a quirk of my repo state?
<img width="454" alt="screenshot of intellij idea 5-05-17 8-37-44 pm" src="https://cloud.githubusercontent.com/assets/811954/25738710/bc9d052c-31d2-11e7-83ff-c37d7853ff9a.png">
<img width="578" alt="screenshot of intellij idea 5-05-17 8-37-55 pm" src="https://cloud.githubusercontent.com/assets/811954/25738711/be375810-31d2-11e7-9064-cd2a099cd442.png">

**Comment by cursive-ide** [comment]
Reopening this to investigate.

**Comment by danielcompton** [comment]
I suspect this might be some difference between local and remote repos? I don't have Maven central indexed cause it introduced way too much irrelevant stuff, and just rely on the right things being in my local `m2`.

I can see suggestions `org.clojars.cemerick/core.match` when I type "core.match" even though I don't have that in my m2 (so that must be coming from the Clojars index). I do have a `org.clojure/core.match` in my local repo, but it isn't shown as a suggestion.

<img width="393" alt="screenshot of intellij idea 8-05-17 10-00-42 am" src="https://cloud.githubusercontent.com/assets/811954/25785468/4026cc94-33d5-11e7-8b56-c816a03c95da.png">

**Comment by cursive-ide** [comment]
Ok, that's the problem then. I have Maven Central indexed, and I see this working correctly. I'm not sure why your local repo isn't working, if you look at the Repositories settings does it indicate that your local repo has been indexed?

**Comment by cursive-ide** [comment]
I'm definitely seeing results come back from my local repository - I'm not sure why this would not be working for you. Perhaps try updating your local repo index in the Repositories config, and see if that helps?

**Comment by cursive-ide** [comment]
I'm going to close this. I’m not sure why it’s not searching your local repo, but I’m confident it’s not a Cursive problem. Feel free to re-open if you suspect it is at any point.

**Comment by cursive-ide** [comment]
This was my fault, I totally failed to register what your screenshots were showing - I was testing the artifact add dialog, not the completion in `project.clj` - doh.
