### ISSUE TITLE
Cursive shouldn't complain about private s3 repos not being indexed.

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1686]
When a private repo on s3 is used with Leiningen, IntelliJ can't index it since it doesn't understand the s3 URLs. Cursive shouldn't complain about these repos not being indexed.

**Comment by rafaeldff** [comment]
Intellij bug that may be related: https://youtrack.jetbrains.com/issue/IDEA-135229

**Comment by cursive-ide** [comment]
@rafaeldff I've [commented](https://youtrack.jetbrains.com/issue/IDEA-135229#comment=27-2036302) over there. The problem is that the lein wagon is different to the Maven one, in particular the Maven one doesn't understand `s3p://` as far as I can tell. So even if they manage to fix this for Maven, their solution will probably not work for lein or Gradle without interaction from the relevant plugins.

**Comment by cursive-ide** [comment]
This is fixed in the next build. Note that the only part that is fixed is Cursive complaining about the repo not being indexed - there doesn't seem to be a good way to get the indexing to happen, so artifacts from those repos will not be present in the new autocomplete etc.
