### ISSUE TITLE
Keywords with multiple slashes

### ISSUE THREAD

**Issue by 1067** [cursive-ide/cursive#1692]
The  `:db/core/type ` keyword is legal, however IDE treat it as invalid.
Is there any option to tune such behavior it in current version?

**Comment by cursive-ide** [comment]
Actually, that's not a legal keyword. From the Clojure [reader page](https://clojure.org/reference/reader):

> Symbols
> `/` has special meaning, it can be used once in the middle of a symbol to separate the namespace from the name, e.g. `my-namespace/foo`.

> Keywords
> Keywords are like symbols...

Basically, a keyword is lexically like a symbol that must start with a `:`. Symbols only allow a single `/`.

Generally this is a pretty weakly-specified part of Clojure, but it's pretty clear that only a single slash is allowed in both keywords and symbols.
