### ISSUE TITLE
REPL Commands - Execute Last Command in same context

### ISSUE THREAD

**Issue by wilkerlucio** [cursive-ide/cursive#1693]
I just started getting to real uses of REPL Commands, they are great! :)

One suggestion I have is regarding the `Last REPL Command` usage. Right now we have 2 context (namespace) options to run the REPL command:

1. Execute in current REPL namespace
2. Execute in a specific namespace

A common pattern that I end up having here is that I'm running commands with Run Top Level form (or run form under cursor), which uses the current file namespace, and after that I try to run Last REPL Command, doing that usually get's me an error, because it tries to run into the current namespace (which usually is `user`). Can we have an option where instead it remembers the last command namespace context and re-use it on the next run with Last REPL Command?

Thanks.

**Comment by cursive-ide** [comment]
Oh, good catch - yes, I'll fix that.
