### ISSUE TITLE
Discover nrepl remote port automatically like Cider

### ISSUE THREAD

**Issue by achikin** [cursive-ide/cursive#1698]
Could you please add port discovery option to remote nrepl connection?
We have set up our project so nrepl starts on random port and it is very inconvenient to check the port in console each time and fix it in run configuration.

**Comment by cursive-ide** [comment]
You should be able to do this by using the "Use Leiningen REPL port" options - does that do what you want?

**Comment by achikin** [comment]
Works great, thank you!
