### ISSUE TITLE
100% CPU usage in REPL server

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1701]
Reported by @rauhs in Slack:

> Since the last update I'm getting a 100% CPU usage my clojure process when I connect a CLJ repl to it. I can see the NREPL thread running at 100% of my process. Killing the REPL windows in cursive brings it back down to 0.
> Also seems to be constantly loading new classes (or define classes probably) (edited)
> (not a clojurescript repl)

**Comment by rauhs** [comment]
I see thousands of these:

```clojure
 {:code
  "(cursive.repl.runtime/completions 'clojure.pprint 'clojure.java.javadoc 'clojure.java.classpath 'mount.core 'clojure.core 'srs-s.services.app 'clojure.tools.namespace.repl 'clojure.tools.logging 'clojure.repl)",
  :id "5cc4cb61-63a3-4bab-a19a-0b1e336e0be0",
  :op "eval",
  :session "bc7b2bd9-fc8a-475a-902d-efd9d28c0c89",
  :transport
  #object[clojure.tools.nrepl.transport.FnTransport 0x74192b3d "clojure.tools.nrepl.transport.FnTransport@74192b3d"],
  :date #inst "2017-04-04T09:41:56.299-00:00"}
 {:code
  "(cursive.repl.runtime/completions 'clojure.pprint 'clojure.java.javadoc 'clojure.java.classpath 'mount.core 'clojure.core 'srs-s.services.app 'clojure.tools.namespace.repl 'clojure.tools.logging 'clojure.repl)",
  :id "81fe22b7-bcb6-4808-8b92-0cb421b4382d",
  :op "eval",
  :session "bc7b2bd9-fc8a-475a-902d-efd9d28c0c89",
  :transport
  #object[clojure.tools.nrepl.transport.FnTransport 0x74192b3d "clojure.tools.nrepl.transport.FnTransport@74192b3d"],
  :date #inst "2017-04-04T09:41:56.325-00:00"}
```

(I added a date to the msgs)

**Comment by cursive-ide** [comment]
@rauhs How are you tracing those? Can you see the response to one of those messages?

**Comment by rauhs** [comment]
I started my own nrepl server with my own middleware (that does that logging). I think the answer is empty every time.

**Comment by cursive-ide** [comment]
Can you see if the answer is nil, or an empty map? I can't see how that's possible, looking at the code - it's pretty simple.

**Comment by cursive-ide** [comment]
BTW you can also test by running that code directly in your REPL:
```
(cursive.repl.runtime/completions 'clojure.pprint 'clojure.java.javadoc 'clojure.java.classpath 'mount.core 'clojure.core 'srs-s.services.app 'clojure.tools.namespace.repl 'clojure.tools.logging 'clojure.repl)
```

The code for the `completions` function is very simple, and I can't see how it would return either nil or an empty map:

```
(defn completions [& ns-symbols]
  (reduce (fn [ret ns-symbol]
            (if-let [ns (find-ns ns-symbol)]
              (assoc ret (name ns-symbol) (ns-info ns))
              ret))
          {:namespaces (set (map (comp name ns-name) (all-ns)))}
          ns-symbols))
```

**Comment by cursive-ide** [comment]
Actually, I'm wondering if that code is throwing an exception, and that is producing no valid return value. I'm very interested to know what that returns for you. I've seen this one, but couldn't reproduce it.

**Comment by rauhs** [comment]
I sent you a gist on slack. I'm not 100% certain if the answer is empty. I start an NREPL server with this middleware (and not the swap! to log):

```clojure
(defn log-msg
  [h]
  (fn [msg]
    (swap! received-msgs conj (assoc msg :date (Date.)))
    (let [ans (h msg)]
      (swap! sent-msgs conj (assoc ans :date (Date.)))
      ans)))
```

Other than the above middleware I only use `nrepl/default-handler`. Right now the mass message don't happen when I connect cursive to my own NREPL server, but they do when I connect to the `lein repl :host localhost :port ...` server.

**Comment by rauhs** [comment]
With eap4 one of the first message:
```clojure
 {:file
  "(ns cursive.repl.runtime\ ....... )\n",
  :file-name "runtime.clj",
  :file-path
  "/home/rauh/.IntelliJIdea2016.3/config/plugins/clojure-plugin/lib/runtime-1.5.0-eap4-2016.3.jar!/cursive/repl/runtime.clj",
  :id "4a417b10-cafb-48a4-823f-8a4798ca3e44",
  :op "load-file",
  :session "f33c16b9-bbe9-46d5-91b9-4a5d8d3597b7",
  :transport
  #object[clojure.tools.nrepl.transport.FnTransport 0x7aa49504 "clojure.tools.nrepl.transport.FnTransport@7aa49504"],
  :date #inst "2017-04-06T14:33:38.768-00:00"}
```

**Comment by rauhs** [comment]
Both the REPL-y and the cursive repl runtime run fine if I REPL the code myself. Hmm...

**Comment by rauhs** [comment]
Ok so I'm not an NREPL expert. But it seems that `:ans` is not the way that the NREPL sends its answer. I hooked into `c.t.n.transport`:
```clojure
(deftype FnTransport [recv-fn send-fn close]
  Transport
  ;; TODO this keywordization/stringification has no business being in FnTransport
  (send [this msg] (do
                     (spit "/tmp/cursive-msgs" (with-out-str (pprint/pprint msg))
                           :append true)
                     (-> msg clojure.walk/stringify-keys send-fn)) this)
  (recv [this] (.recv this Long/MAX_VALUE))
  (recv [this timeout] (clojure.walk/keywordize-keys (recv-fn timeout)))
  java.io.Closeable
  (close [this] (close)))
```

and I can see all the completions being successfully responded.

**Comment by cursive-ide** [comment]
No, `:ans` isn't the response, in fact that looks like the request? Anyway, `:value` is where the eval result comes back.

**Comment by cursive-ide** [comment]
One other question, since AFAIK you're the only user with this problem - do you have any other middleware that might be causing this problem?

**Comment by rauhs** [comment]
No, only the `nrepl/default-handler`.
