### ISSUE TITLE
How to turn off structural editing?

### ISSUE THREAD

**Issue by Alter57** [cursive-ide/cursive#1704]
Hi, 

I want to turn off structural editing in intellij, but I couldn't find this option anywhere. According to [docs](https://cursive-ide.com/userguide/paredit.html),  it can be done through Settings→Editor→General→Smart Keys→Use structural editing. Unfortunately, there is no such option, at least in Intellij 2016.2.5 (on Linux Ubuntu).

**Comment by cursive-ide** [comment]
You're right, the doc is slightly out of date. You want the Structural editing style option switched to None. You can also use the widget in the status bar:

<img width="1126" alt="screen shot 2017-04-06 at 22 32 06" src="https://cloud.githubusercontent.com/assets/5589171/24749958/3051efa8-1b19-11e7-86ae-53e7ea6a445d.png">
