### ISSUE TITLE
Add "Sync all modified files to disk" option to REPL commands

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1706]
I'm using the [reloaded.repl](https://github.com/weavejester/reloaded.repl) workflow for a project, and I have bound `(reset)` inside the `user` namespace as a REPL command. I have it set to Sync all modified files before executing. If I do a quick edit, then run my reset command, the files aren't synced to disk, so Cursive knows to reload it, but it won't get reloaded by tools.namespace. I've put an example REPL session below

```
;; Modify my.cool.app
;; Run repl command
Loading src/my/cool/app.clj... done
(reset)
:reloading () ;; This should have included my changed file, and anything that depended on it.
;;; Wait a few seconds, then rerun it
=> :resumed
(reset)
:reloading (my.cool.app my.cool.web-server my.cool.system my.cool.main user) ;; Now it looks correct
=> :resumed
```

It would be great if there was another option before executing to sync files to disk, or some other way to signal tools.namespace on which files need to be reloaded.

**Comment by danielcompton** [comment]
I've done a bit of digging with Instruments, I'm not certain I've got the answers, but I think I have a plausible explanation for what is going on. Talking with @cursive-ide, he confirmed that he does sync files to disk before reloading them.

I'm using Boot on this project, and connecting to it from Cursive via a remote REPL.

To reproduce:

1. Write an invalid form, e.g. `(if (= 1 2))`
2. Save the form, wait a few seconds
3. Kill the line with the form on it, and quickly call `reloaded.repl/reset` from a REPL command
4. Observe a reloading error saying the form isn't valid

What I think is happening is:

1. Bad form is deleted
2. REPL command is called
3. File is saved to disk by IDEA (via move based semantics, but not relevant here)
4. Cursive loads the file into the REPL
5. Cursive runs `(reset)` in the `user` namespace
6. `reset` looks at the files on disk in the boot temporary cache folder and loads them (these are the old files)
7. An error occurs
8. Boot synchronises the files across to its cache folder (I couldn't observe this process happening in instruments, but I can see the reads in the cache folder location).

I suspect the problem is that Cursive is running the command before Boot has copied the files over, so it reloads the bad/old files. This is understandable as Cursive doesn't know about what Boot is doing.

To figure out if this is really the case, step 8 needs to be observed to confirm when/how the files are copied into the boot cache folder.

**Comment by danielcompton** [comment]
A workaround I've come up with is to call `(#'boot.core/sync-user-dirs!)` first. So my full REPL command is:

```
(#'boot.core/sync-user-dirs!) (reset)
```

This could be improved by using a non-private function, and maybe using a blocking semaphore variant when reloading instead of boot's nonblocking one.

**Comment by cursive-ide** [comment]
I'm going to close this, since there's a workaround and boot is basically obsolete these days.
