### ISSUE TITLE
Suggestion: Right click on a symbol and get option to copy its fully qualified name to clipboard

### ISSUE THREAD

**Issue by hlship** [cursive-ide/cursive#1708]
I'm often doing this when writing documentation ... I want the fully qualified name of a symbol.  It would be nice if I could do that with a right click option.  The existing *Copy Reference* menu item provide a reference to a line number for a file in a JAR in the local Maven repository, not quite what I need.

**Comment by cursive-ide** [comment]
This actually used to work, but it looks like it got broken somewhere along the way. It's fixed for the next build.

**Comment by hlship** [comment]
Just tried this in 1.5.0 and it's better, but not right. Copies a file reference, e.g., "com/walmartlabs/lacinia/schema.clj:411", not a qualified symbol name ("com.walmartlabs.lacinia.schema/create-root-selector"), which is what I would like.

**Comment by cursive-ide** [comment]
That's probably #1745 - it didn't work from declarations, only from usages. It's fixed in the latest EAP.
