### ISSUE TITLE
Leiningen project change detection should check file contents

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1715]
[boot-lein-generate](https://github.com/onetom/boot-lein-generate) recreates the project.clj file every time it is run. This causes Cursive's change detection to say that a project needs to be imported every time you run a boot command, even though nothing has changed. It could be good for Cursive to hash the project.clj file or otherwise check for content changes.

**Comment by cursive-ide** [comment]
It actually does this already - it calculates a CRC excluding whitespace. It's possible there's a bug there, is the file content definitely identical (i.e. no generation timestamps in comments or anything like that)?

**Comment by danielcompton** [comment]
Hmm, I think it's because the generation includes a git hash in the version, e.g.: `"0.0.2-g9470ab5-dirty"`. Consecutive reruns of boot without changing git don't trigger an import message.
