### ISSUE TITLE
Can't see what I'm typing in the figwheel repl

### ISSUE THREAD

**Issue by yanglinz** [cursive-ide/cursive#1727]
OSX 10.12.4
IntelliJ 2017.2.1 Community Edition
Cursive 1.4.3-2017.1

I setup the cursive REPL following this guide https://github.com/bhauman/lein-figwheel/wiki/Running-figwheel-in-a-Cursive-Clojure-REPL. The REPL seems to evaluate as expected, but I can't see what I'm typing into the REPL. 

http://i.imgur.com/xN89ZZq.gif

**Comment by yanglinz** [comment]
User error. Disregard :)

**Comment by jpbogle** [comment]
I have the same problem...how did you fix this?

**Comment by cursive-ide** [comment]
What it looks like in that gif is that the REPL entry pane is collapsed below, and he was expecting the output pane to be where input was entered. Cursive uses separate panes for input and output, you can see this [here](https://cursive-ide.com/userguide/repl.html) under "Using the REPL". Someone has reported that dragging it can be difficult to do, and that double clicking resizes it more effectively - I can't reproduce that, for me, dragging where indicated here always works:

![screen shot 2018-06-18 at 12 50 50](https://user-images.githubusercontent.com/5589171/41513892-de9882d6-7291-11e8-8bea-8e8d1d8bdadc.png)

**Comment by tbsvttr** [comment]
I had the same issue and it took me like an hour to figure this out. Thanks to the comment of @cursive-ide  I finally did.

Maybe you could include that in the Troubleshooting section of the User Guide?
