### ISSUE TITLE
Higher-level macroexpansion output appears when expanding subexpressions

### ISSUE THREAD

**Issue by cemerick** [cursive-ide/cursive#1738]
Say I start with this in the macroexpansion popup:

```clojure
(case (+ 1 5)
  3 (->> (repeat 12) (apply +)))
```

…and I want to expand _only_ `->>`. AFAICT, I can't; I presume this is because cursive is always expanding from the toplevel for `&env` reasons as you alluded to before?

```clojure
(let* [^java.lang.Object G__46286 (+ 1 5)]
  (case* ^java.lang.Object G__46286
         0
         0
         (throw (java.lang.IllegalArgumentException. (str "No matching clause: "
                                                          ^java.lang.Object G__46286)))
         {3 [3 (apply + (repeat 12))]}
         :compact
         :int))
```

This is _super_ unhelpful, hopefully for obvious reasons. Now I see the purpose of the flashing yellow after each macroexpansion step, to indicate the output corresponding to the expression you had selected for expansion in the first place. That coping mechanism just isn't 

Assuming you're starting with the original `case` expr, and attempt to expand the `->>` form, I think everyone is actually expecting to see this:

```clojure
(case (+ 1 5)
  3 (apply + (repeat 12)))
```

Since you know which expr is being expanded, and you know the range of the resulting expansion in the output (thus the yellow flashing), hopefully getting to the cleaner output above will be reasonably straightforward.

(Related to #1733 #1426)

**Comment by cursive-ide** [comment]
Yes, this should be simple to fix, I think.
