### ISSUE TITLE
Symbol resolution for deftest-like macros

### ISSUE THREAD

**Issue by vincent-dm** [cursive-ide/cursive#1743]
We use in-house macros, like `deftest+` and  `deftest-db`, to improve the default `clojure.test/deftest`.

Because of this, the `run test under caret in REPL` command does not work on these macros. I assume that Cursive is hardcoded to look for `deftest`. (Though the `run tests in current NS in REPL` command does work with our macros)

Is it possible to fix this? Maybe by adding a `deftest` option to the **symbol resolution** list, so that we can define which symbols should be treated like `deftest`?

__FYI (why we have these macros)__
* `deftest+` allows us to write the test name as a string, and will also fail the test if there was an exception in non-main thread
* `deftest-db` makes sure that database are truncated between test runs

**Comment by cursive-ide** [comment]
This has been mostly fixed in #1881. You can now customise a macro to resolve as any other macro, so you should be able to do this using that functionality. The one thing that will not work is if you have `deftest+` tests with string names, since the `deftest` grammar isn't expecting that.
