### ISSUE TITLE
Execute REPL command in current file namespace

### ISSUE THREAD

**Issue by wilkerlucio** [cursive-ide/cursive#1756]
Currently, we have the option to run a REPL command on a particular namespace or into current REPL namespace. I would suggest we also have the possibility to run in the current file namespace. I'm writing some REPL commands where knowing which is the current file (active on the main window) is so that I could resolve a selected symbol correctly. That would enable more fine-grained customizations.

**Comment by wilkerlucio** [comment]
Another suggestion, instead of having the option to run in the current namespace, a replace snippet like `~ns` (similar to how `~selection` works) would solve this issue, since then would be able to localize the snippet with that.

**Comment by cursive-ide** [comment]
Right, see #1694.

**Comment by wilkerlucio** [comment]
Ok, I realized both of then has their own value, even with `~ns` like, Run In Current File namespace still useful, for example, if you have part of your selection pointing to local stuff (for eg: `::local-keyword`).

**Comment by cursive-ide** [comment]
This was also requested on the [mailing list](https://groups.google.com/d/msg/cursive/-1KJuW3lfNQ/Pa4jwM8HAQAJ):

> Cursive's built-in "Send top-level form to repl" knows to eval in the *editor* namespace, not the REPL one, but (as I just discovered), this ability is not available to REPL commands. We currently have three options for the execution namespace: current REPL ns, original ns (only for "re-execute last command"), and a specific namespace. I'm hoping it would be straight forward to add a fourth option - "Execute in focused editor namespace"?

**Comment by imrekoszo** [comment]
@cursive-ide is there any documentation available about substitutions, like `~selection`? I just stumbled upon this feature by checking the google group.

**Comment by cursive-ide** [comment]
@imrekoszo There isn't, no, although they should be documented [here](https://cursive-ide.com/userguide/repl.html#repl-commands) - I'll fix that.

**Comment by imrekoszo** [comment]
Thanks a mill, Colin! Also, is there a reason why the Edit REPL commands dialog doesn't have a plus button to create a new command?

**Comment by cursive-ide** [comment]
No, it definitely should do.

**Comment by cursive-ide** [comment]
@imrekoszo The substitutions are now documented [here](https://cursive-ide.com/userguide/eap/repl.html#repl-commands).

**Comment by imrekoszo** [comment]
That's great, thank you!

**Comment by holyjak** [comment]
If you read up to here: you can add `(in-ns '~file-namespace)` to your REPL command to run the rest in the file's namespace
