### ISSUE TITLE
Feature Request: Folding edn data

### ISSUE THREAD

**Issue by olivergeorge** [cursive-ide/cursive#1777]
IntelliJ does a good job of folding on large JSON files.  It's quite fine grained.

![image](https://cloud.githubusercontent.com/assets/99447/26811574/19cbc2c8-4ab6-11e7-92b9-571f113102fd.png)

I think the same would be super useful for EDN files.  Currently there's no options to fold.

![image](https://cloud.githubusercontent.com/assets/99447/26811594/36e6acb0-4ab6-11e7-8c95-7ef9fad16bd6.png)

Ideally, I'd like to fold on maps and vectors in code too.  Currently there's no option to fold.

![image](https://cloud.githubusercontent.com/assets/99447/26811621/5a49b332-4ab6-11e7-87cf-e86c0b008b6f.png)

**Comment by wilkerlucio** [comment]
Also folding lists would be great, in Fulcro we use long nesting of lists for the UI, folding those inside would be very helpful.

**Comment by cursive-ide** [comment]
This is now obsolete, Cursive has done this for a while now.
