### ISSUE TITLE
New test files have four spaces instead of two in before the (:require) form

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#1790]
Creating a file in a test directory with `1.6.0-eap2-2017.1` creates this file:

```
(ns myco.app.queries.file-test
    (:require [clojure.test :refer :all]))
```

There should probably only be two leading spaces on the second line, not four.

Similar to #1082

**Comment by cursive-ide** [comment]
Yes, this is difficult, I tried to fix it and couldn't. I believe this is because the code is reformatted after being created, and the formatter doesn't have sufficient context (the file has not been indexed yet).

**Comment by cursive-ide** [comment]
This is fixed by simply not reformatting after the file is created.
