### ISSUE TITLE
Test creation doesn't work with Gradle

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1792]
This is because the test and source directories are in different modules, because the Gradle integration creates one per source set.

**Comment by pmoriarty** [comment]
Interested to hear you thoughts on this one. Related to this, I uncheck the module per source set option so I can run tests in the REPL (only one module can be selected to build the classpath per REPL).

**Comment by cursive-ide** [comment]
This is fixed in the next build. 

@pmoriarty Re: tests, you should be able to use your test module as the REPL module. Since it depends on the main module, it will include its classpath as well as adding the test part as well.
