### ISSUE TITLE
Add breadcrumbs

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1793]
Here's what the Python one looks like:

![python-breadcrumbs](https://user-images.githubusercontent.com/5589171/27663953-139d3944-5cb9-11e7-846b-fe63180ebbfc.jpg)

**Comment by staypufd** [comment]
Thanks for adding it!

**Comment by cursive-ide** [comment]
Fix released in 1.13.1-eap6 on 2023-10-20.

**Comment by staypufd** [comment]
Thanks for the fix.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1 on 2023-12-07.
