### ISSUE TITLE
Support for letfn - 0.6.07

### ISSUE THREAD

**Issue by hlship** [cursive-ide/cursive#18]
It would be nice if locally defined functions, via letfn, were supported. Currently they show up as unresolved references.

![connection_watch clj_-__switch__-_nexus_-____workspaces_annadale_nexus_](https://f.cloud.github.com/assets/52660/1302190/73636768-312f-11e3-9988-535dc2d73252.png)

**Comment by brjann** [comment]
In clojurescript `letfn` gets the wrong indentation and it looks like the function is being called. The function name is however resolved. I have tried to resolve as clojure.core/letfn but does not help.
![image](https://user-images.githubusercontent.com/11245519/115243262-07b28780-a123-11eb-94a3-2deca664379e.png)
