### ISSUE TITLE
Run Clojure Application doesn't trigger a recompile of java code in Cursive 1.6

### ISSUE THREAD

**Issue by pkozikow** [cursive-ide/cursive#1800]
I'm running a Clojure test for Java code in a maven module. I'm not sure if this happens consistently every time, but I've run into several instances where I update the Java code but when I run the Clojure test the change is not reflected. After recompiling the module manually the change appears as expected.

This is a regression in version 1.6. The previous version didn't have this problem.

**Comment by cursive-ide** [comment]
What's probably happening is that in 1.6.0, the default is no longer to have Make as a before-run task for Clojure configs (see [#1184](https://github.com/cursive-ide/cursive/issues/1184), it talks about REPL configs but this is more generally for Clojure configs). Can you check if this is missing, and if adding it back fixes the problem?

**Comment by pkozikow** [comment]
Yes, that was it. Adding `build` as a before-run task fixes it.
