### ISSUE TITLE
Reformat code corrupts certain *.cljc files when using Parinfer

### ISSUE THREAD

**Issue by vincent-dm** [cursive-ide/cursive#1805]
When I use the `Reformat Code` command in a `*.cljc` file with Parinfer on, it corrupts a specific (but valid) require block:

1. This code:
```clj
(ns replication
  (:require [other.ns :as other]
            #?@(:cljs [[foo.bar :as bar]]
                :clj  [[bazz.fizz :as fizz]])))
```

...is reformatted into this (invalid) code:
```clj
(ns replication
  (:require [other.ns :as other]
    #?@(:cljs [[foo.bar :as bar]]
        :clj  []
            [bazz.fizz :as fizz])))
```
-----

2. It also happens when I switch the ordering of the fixed require and the reader conditional.

In that case, this code:
```clj
(ns replication
  (:require #?@(:cljs [[foo.bar :as bar]]
                :clj  [[bazz.fizz :as fizz]])
            [other.ns :as other]))
```

...is reformatted into this (valid but wrong) code:
```clj
(ns replication
  (:require #?@(:cljs [[foo.bar :as bar]]
                :clj  [[bazz.fizz :as fizz]
                       [other.ns :as other]])))
```
-----

3. Finally, I noticed that the reformatting works when I remove the `[other.ns :as other]` require:

So this code:
```clj
(ns replication
  (:require #?@(:cljs [[foo.bar :as bar]]
                :clj  [[bazz.fizz :as fizz]])))
```
...is left intact.

-----

I'm not sure whether this is a Cursive or Parinfer bug.  Unfortunately, I didn't find a similar reformatting command in Atom to test against a different Parinfer implementation.

But since this corruption doesn't happen when I reformat the same code in a `*.clj`-file, Cursive is my best guess.

**Comment by schnipseljagd** [comment]
I have the same problem. Using separate requires solves it for me.

```clojure
(ns foo
  (:require #?(:cljs [cljs-time.core :as t]
                     :clj [clj-time.core :as t]))
  (:require #?(:clj [clj-time.spec]))
```

**Comment by cursive-ide** [comment]
More cases from @awkay in Slack:

> Colin, I notice that in CLJC files, the “reformat” action in Cursive makes a mess of conditional splicing….e.g., this is what I get:

```
(ns fulcro.client.dom
  (:refer-clojure :exclude [map meta time mask select])
  #?(:cljs (:require-macros [fulcro.client.dom :as dom]))
  (:require
    [clojure.string :as str]
    [fulcro.client.impl.protocols :as p]
    [fulcro.util :as util]
    [clojure.spec.alpha :as s]
    #?@(:clj  (
    [clojure.core.reducers :as r]
    [clojure.future :refer :all]
    [fulcro.checksums :as chk])
        :cljs ([cljsjs.react]
                [cljsjs.react.dom]
                [goog.object :as gobj])))
```

>even if I try to manually wrap the stuff up, it still forces it down. This makes using parinfer, for example, corrupt the code. I would expect something like:

```
(ns fulcro.client.dom
  (:refer-clojure :exclude [map meta time mask select])
  #?(:cljs (:require-macros [fulcro.client.dom :as dom]))
  (:require
    [clojure.string :as str]
    [fulcro.client.impl.protocols :as p]
    [fulcro.util :as util]
    [clojure.spec.alpha :as s]
    #?@(:clj  ([clojure.core.reducers :as r]
               [clojure.future :refer :all]
               [fulcro.checksums :as chk])
        :cljs ([cljsjs.react]
                [cljsjs.react.dom]
                [goog.object :as gobj])))
```

**Comment by cursive-ide** [comment]
I believe this is fixed, I've just re-tested all these cases and they now work correctly. If I'm wrong about this, please let me know and I'll re-open.
