### ISSUE TITLE
Default Project SDK is never remembered

### ISSUE THREAD

**Issue by cap10morgan** [cursive-ide/cursive#1813]
This seems like it might be an IntelliJ issue rather than a Cursive one, but it's hard to say for sure.

The problem I run into is that anytime I open a new project (i.e. it has no `.idea/`, `project.iml`, etc.) with `idea .`, it says I have to setup the SDK. I have set a default project SDK in the default project structure settings, but it never seems to get picked up in this scenario.

**Comment by awkay** [comment]
I've had a similar issue. Mine is creating two .iml files, sometimes not seeing the SDK (I upgraded Java and that might have fixed it???), and the second IML module showed up correctly, but the IDE seemed to use the first. Deleting the errant module from the project settings seems to fix it sometimes, as does sometimes refreshing lein...basically fiddling with it eventually gets it to work, but it is a pretty crappy experience. No source paths set, etc.

**Comment by cursive-ide** [comment]
@awkay When you say it's creating two .iml files, is it creating module.iml and module-1.iml? If so, that's probably [\#1789](https://github.com/cursive-ide/cursive/issues/1789), which is fixed in 1.6.1-eap1, out today.

Let me know if not, and I'll try to reproduce with 1.6.0 and that project.

**Comment by cap10morgan** [comment]
My issue isn't about project-specific settings. It's about the default project structure and (not) applying it to newly-imported lein projects with no pre-existing IntelliJ metadata.

**Comment by awkay** [comment]
@cap10morgan That was part of what I was seeing. The SDK issue seemed to be fixed by the reset of IntelliJ. @cursive-ide : the new EAP build did fix my problem.

**Comment by wilkerlucio** [comment]
I was having this too, but seems to be fixed since the release 1.6.1-eap1. Have you tried loading new projects after this release?

**Comment by wilkerlucio** [comment]
Nevermind, my screen was outdated here, didn't saw you guys conversation before sending 😅

**Comment by cap10morgan** [comment]
This does seem to be fixed in the latest EAP release. Thanks all!
