### ISSUE TITLE
Wrong number of args (0) passed... Error?

### ISSUE THREAD

**Issue by eatobin** [cursive-ide/cursive#1823]
I believe this is perfectly valid code - and runs fine in a console REPL - but errors inside the Cursive REPL:

    Connecting to local nREPL server...
    Clojure 1.8.0
    nREPL server started on port 41303 on host 127.0.0.1 - nrepl://127.0.0.1:41303
    *ns*
    => #object[clojure.lang.Namespace 0x4394b860 "user"]
    (defn concat-some
      [f vec1 vec2]
      ((fn [x] (filter f x)
        (concat vec1 vec2))))
    => #'user/concat-some
    (concat-some even? [1 2 3] [4 5 6])
    clojure.lang.ArityException: Wrong number of args (0) passed to: user/concat-some/fn--4953

Am I missing something here?

Thank you for your help!

**Comment by eatobin** [comment]
Actually, I copied the code directly from [here](https://clojurebridge.github.io/community-docs/docs/clojure/higher-order-function/) (where it is correct) and pasted it straight into both Cursive and a console REPL successively. It pastes differently (don't know why - maybe that's the question) in each and I didn't notice the paren difference.

**Comment by eatobin** [comment]
**Edit and Follow-up:**

This is definitely a Parinfer issue. This code:

    (defn concat-some
      [f vec1 vec2]
      ((fn [x] (filter f x))
        (concat vec1 vec2)))
    (concat-some even? [1 2 3] [4 5 6])

when pasted into the Cursive REPL with Parinfer turned on produces an incorrect paste and the resulting ArityException above. The same code pasted into the same REPL with Paredit turned on or Structural Editing turned off produces the expected output:

    ;; => #'user/concat-some
    ;; => (2 4 6)

I did not know that Structural Editing when active in Cursive is used in the editor - AND the REPL. I would still hope that valid code is valid code regardless of mode and wonder if this is the intended result of pasting into a Cursive/Parinfer REPL.(?)

Thank you again for your help with this.

**Comment by cursive-ide** [comment]
This is fixed with the new integration of parinfer v3. Cursive no longer automatically indents code using paren mode (which would sometimes break), instead it marks where the code has inconsistent indentation so it's clear what needs to be fixed:


![screen shot 2018-03-09 at 15 21 52](https://user-images.githubusercontent.com/5589171/37187161-ea691742-2340-11e8-8602-64b05d3e4713.png)
