### ISSUE TITLE
"Show difference" is not showing up when I mouse over a failed assertion

### ISSUE THREAD

**Issue by tanya-coding** [cursive-ide/cursive#1843]
Using: 
IntelliJ IDEA 2017.2.3
Build #IC-172.3968.16, built on August 21, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

Cursive: 1.6.1-2017.2

**Comment by kipz** [comment]
I have the same issue after upgrading and reregistering the Cursive plugin. I don't recall the version I was on, but I have the same versions as @tanya-coding above now.

**Comment by kipz** [comment]
Related maybe? https://github.com/cursive-ide/cursive/issues/1013
