### ISSUE TITLE
Resolve user-macro as comment

### ISSUE THREAD

**Issue by olivergeorge** [cursive-ide/cursive#1850]
As a work around for problems with syntax highlighting, how about allowing user defined macros to be resolved as the comment macro since that doesn't highlight errors.

![image](https://user-images.githubusercontent.com/99447/30404137-6c150efc-9928-11e7-8f7e-3e29b15ef5eb.png)

**Comment by pbaille** [comment]
The workaround i've found is to disable warnings display at the IDE level :)

**Comment by cursive-ide** [comment]
@pbaille That's a very heavy hammer, you could use *Settings->Languages & Frameworks->Clojure->Highlight unresolved symbols* instead :-)

**Comment by pbaille** [comment]
nice! I will :)

**Comment by pbaille** [comment]
@cursive-ide  any thought on the original "resolve user-macro as comment" question?

**Comment by cursive-ide** [comment]
This is duplicated by #2417, released in 1.9.4-eap3 which was just released.
