### ISSUE TITLE
Make Cursive available for Intellij 2017.3

### ISSUE THREAD

**Issue by alvarogarcia7** [cursive-ide/cursive#1854]
Hello @cursive-ide ,

First of all, great work with Cursive. I love it ❤️ !

Would it be possible to have a Cursive EAP version working for IntelliJ 2017.3 EAP version? 

I could try it myself and report difficulties (what works and what does not) if I can get access to a version that is not limited by version number 172.* (Tried installing from disk the latest 1.6.1-2017.2 but it is limited to that version, as far as I know) 

I'm currently on IntelliJ IDEA Ultimate 173.2463.16.

Many thanks in advance,

PS: I've searched on the mailing list at https://groups.google.com/forum/#!forum/cursive and did not find anything related to 2017.3 or EAP

**Comment by cursive-ide** [comment]
Yes, this will be in the next EAP, I'm working on it now. It's a little tricky, but I hope to finish it soon.
