### ISSUE TITLE
Close project without being asked "Do you want to close the REPL ... ?"

### ISSUE THREAD

**Issue by marco-m** [cursive-ide/cursive#1867]
Hello,
currently if I close the current project or if I quit IDEA and I have a REPL open by Cursive I get a popup asking "Do you want to close the REPL ... ?".
Would it be possible to have a setting to just close the project without any kind of "Are you sure ?" popups ?
thanks!
marco

**Comment by cursive-ide** [comment]
This prompt now has a "Don't ask me again" checkbox, and can be re-enabled at *Settings&rarr;Languages & Frameworks&rarr;Clojure&rarr;Confirm REPL exit*.

**Comment by marco-m** [comment]
thanks! :-) 🌷
