### ISSUE TITLE
The REPL window loses docking capability once undocked

### ISSUE THREAD

**Issue by michalmarczyk** [cursive-ide/cursive#1874]
IntelliJ IDEA 2017.2.5
Cursive 1.6.1-2017.2, 1.6.2-eap1-2017.2

In new projects, the REPL appears to default to pinned + docked, that is, the gear menu in the REPL section of the IntelliJ window has check marks next to "Pinned Mode" and "Docked Mode"; at least this has been the case with a couple of Leiningen projects I've recently imported. Once detached by selecting "Floating Mode" or "Windowed Mode", however, it cannot be returned to the original state via the UI – at least not in the obvious way of selecting "Docked Mode" again – because those options disappear from the gear menu. NB. in the past the options used to be there and they worked.

It is possible to fix this temporarily through a manual edit to `workspace.xml` (specifically by changing the REPL's `window_info`'s `type` attribute to `DOCKED`), but it doesn't fix the problem permanently – the next time it's undocked it forgets how to re-dock itself. Also the edit seems to have no effect if the project in question is currently open in IntelliJ. (At least a full restart is not required.)

**Comment by cursive-ide** [comment]
So it's somewhat counterintuitive (this may be a recent IntelliJ change, I'm not sure), but once set to Floating mode, the menu only contains the "Floating mode" entry with a tick beside it. If you select this item again (to de-select floating mode, I assume is the implication) the toolwindow will go back to being docked. Does this work for you?

**Comment by michalmarczyk** [comment]
It does! Thanks so much!

Actually I get both "Windowed Mode" and "Floating Mode" options in all detached windows, but picking the current one does have the effect of going back to docked. (In contrast, picking "Docked Mode" when it's already docked appears to leave it docked, but with no check mark. Oh well.)

Also I do seem to have a vague recollection of this no longer working after an IntelliJ rather than a Cursive update. I thought it was some change on their end you'd need to adjust to… Didn't occur to me to "deselect" "Windowed Mode" like this. Thanks again!
