### ISSUE TITLE
Configuration schemes for symbol resolution settings

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1885]
Currently it can be hard to share the "Resolve <sym> as..." settings between users in a team since they're always stored in the IDE. It would be useful to allow this information to be assigned to projects too.

There are a couple of use cases:

1. Settings for forms defined in a particular project nearly always belong to the project itself, since all devs working on the project will need them and they're never needed outside that project.
2. Settings for common forms for third-party libraries are better stored with the IDE since they will probably be used across multiple projects and it would be a pain to set them all up each time.

The best solution seems to be a simplified form of the configuration Schemes that IntelliJ supports for code styles. For code styles, IntelliJ allows the config to either be stored with the project, or in one of several named profiles stored with the IDE. Project settings can be copied to a new IDE profile, and settings from an IDE profile can be copied to the project. I think this can be simplified for the symbol resolution settings since I don't see a need for multiple IDE profiles.

So in the *Settings&rarr;Languages & Frameworks&rarr;Clojure&rarr;Symbol Resolution* panel, the user will be able to select "IDE" or "Project" for the config storage. There will be options provided to clear the current scheme, and merge the settings from it to the other scheme (i.e. if you currently have "Project" selected you'll be able to select "Merge to IDE" which will merge the Project settings over the IDE ones and select "IDE" as the current option, and vice versa). New config items will always be added to the currently selected scheme.

**Comment by bobfejes** [comment]
I don't see what's described above in 1.6.2-2017.3: there is not IDE/Project selection option on the Symbol Resolution panel. Am I missing something?
