### ISSUE TITLE
Can't turn off Move Form Up/Down in Keymap settings

### ISSUE THREAD

**Issue by oshyshko** [cursive-ide/cursive#1891]
Cursive overrides IntellIJ's default behavior of `Ctrl+Shift+Up` and `Ctrl+Shift+Down` and doesn't allow user to restore IntelliJ's default behavior (move line up/down).

`Edit > Structural Editing > ...`
![image](https://user-images.githubusercontent.com/73026/32762807-839111c2-c8b0-11e7-89be-b872f56120a5.png)

On the screenshot above you can see the key bindings.

However, if you go to Keymap settings, you will not find it there:
![image](https://user-images.githubusercontent.com/73026/32762922-4ec75c02-c8b1-11e7-9bf9-c37b74301a73.png)

You can not disable it.

Very annoying. Especially if you've been using IntelliJ for long time.

Version: `1.6.2-eap2-2017.2`

**Comment by cursive-ide** [comment]
Hmm, that is strange, I'll investigate that.

**Comment by cursive-ide** [comment]
I'm not sure what's going on there. I see these both when navigating through _Main Menu&rarr;Edit&rarr;Structural Editing_:
<img width="699" alt="screen shot 2017-11-15 at 15 26 15" src="https://user-images.githubusercontent.com/5589171/32815561-90bc617a-ca19-11e7-9311-5bcb91b696f8.png">

And when searching for them:
<img width="488" alt="screen shot 2017-11-15 at 15 26 43" src="https://user-images.githubusercontent.com/5589171/32815572-9bb198de-ca19-11e7-9f9e-83e3c32be9fe.png">

Do you see them when searching?

Which keymap are you using? There's another odd thing which is that your keybinding is different to mine, even though they should both be using the default. 

EDIT: after investigating this further, it looks like you're using the original Mac OS keymap - I see the behaviour you describe there.

**Comment by oshyshko** [comment]
Yes, I am using a modified default OS X keymap.

![image](https://user-images.githubusercontent.com/73026/32815921-2c4fb452-c96b-11e7-9dea-ab16b91a9ad1.png)

**Comment by cursive-ide** [comment]
If you search for "Move statement up/down", which bindings do they use?

**Comment by oshyshko** [comment]
![image](https://user-images.githubusercontent.com/73026/32817236-8587f600-c971-11e7-823c-f2dd3112ec80.png)

**Comment by cursive-ide** [comment]
This is actually the same root cause as #1880.
