### ISSUE TITLE
StackOverflowError for code snippet

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#1899]
Reported by @ikitommi in Slack:

Adding this (broken let) will cause Cursive (and IDEA) to halt (throws StackOverFlowError):

```
(defn wild-param? [segment]
  (let [string-segment (if keyword? segment) (name segment) segment]
    (str/starts-with? string-segment ":")))
```

**Comment by cursive-ide** [comment]
@ikitommi I can't reproduce this with just this snippet, either in CLJ or CLJC. There must be something else provoking it.

**Comment by ikitommi** [comment]
I need to isolate to problem, in one of our multi-module setups. Will post when know more. Thanks for investigating! This can be closed.

**Comment by cursive-ide** [comment]
Ok, I'll close this in the meantime.
