### ISSUE TITLE
LATEST results in unresolved symbols

### ISSUE THREAD

**Issue by weltan** [cursive-ide/cursive#1904]
I noticed that our project had a lot of unresolved symbols: some clojure.core functions like `defn`, `ns`, but also pretty much all our dependencies weren't resolving. 

Turns out it's because we use "LATEST" to choose dependency versions for our project.clj:
```
:dependencies [[org.clojure/clojure "LATEST"]
               [org.immutant/web "LATEST"]
               [ring/ring-core "LATEST"]
               [ring/ring-devel "LATEST"]
               [ring/ring-json "LATEST"]
               [compojure "LATEST"]
               [caesium "LATEST"]
               [buddy/buddy-auth "LATEST"]
               [buddy/buddy-sign "LATEST"]])
```
I switched LATEST for the associated version numbers, and everything was fixed.

I can add this workaround as a comment on #626, but is it possible for Cursive to support "LATEST"? Or am I doing something wrong?

**Comment by cursive-ide** [comment]
Does Leiningen itself support that? I can't find anything in the doc to suggest that it does. [This SO answer](https://stackoverflow.com/a/5698227/155368) says it does, but there's a comment on that from 2014 saying it no longer does so. That answer links to [this question](https://stackoverflow.com/questions/30571/how-do-i-tell-maven-to-use-the-latest-version-of-a-dependency) talking about how Maven supports it, but the accepted answer on that question states that Maven hasn't supported it either for over 6 years now.

**Comment by weltan** [comment]
We did some digging on this:

- You are correct, "LATEST" is a Maven 2 thing, and support was dropped in version 3.
- However, it turns out that [Leinigen and Clojars both use the Maven 2 repository layout](https://github.com/clojars/clojars-web/wiki/About#do-i-have-to-use-leiningen-with-clojars-and-clojars-with-leiningen), so it is supported by Leiningen, albeit indirectly...

We came to Clojure from Java, so that's where we picked it up, but it does look supported, at least for now...weird.

Would love a fix, but also totally understand if you don't think it's worth it! :)

**Comment by cursive-ide** [comment]
I was curious about this, because I couldn't see any reason why this wouldn't work in Cursive - Cursive just calls out to Leiningen to get the information it needs. But this seems to be a lein bug, or at least "LATEST" isn't supported correctly there.

Here's a `project.clj`:
```
(defproject latest-test "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [hiccup "1.0.5"]])
```

Using this, `lein deps :tree` shows:
```
~/d/c/latest-test> lein deps :tree
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [hiccup "1.0.5"]
 [org.clojure/clojure "1.8.0"]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
```
which is correct (nREPL and clojure-complete come from a lein profile). 

However if I switch to this:
```
(defproject latest-test "0.1.0-SNAPSHOT"
  :dependencies [[org.clojure/clojure "LATEST"]
                 [hiccup "LATEST"  :exclusions [[org.clojure/clojure]]]])
```

(the exclusion in hiccup is to avoid an irrelevant warning about confusing deps)

Then `lein deps :tree` shows:
```
~/d/c/latest-test> lein deps :tree
 [clojure-complete "0.2.4" :exclusions [[org.clojure/clojure]]]
 [org.clojure/tools.nrepl "0.2.12" :exclusions [[org.clojure/clojure]]]
```

However, oddly, the classpath is correct:
```
~/d/c/latest-test> lein classpath
/Users/colin/dev/cursive-bugs/latest-test/test:/Users/colin/dev/cursive-bugs/latest-test/src:/Users/colin/dev/cursive-bugs/latest-test/dev-resources:/Users/colin/dev/cursive-bugs/latest-test/resources:/Users/colin/dev/cursive-bugs/latest-test/target/classes:/Users/colin/.m2/repository/org/clojure/clojure/1.9.0-RC2/clojure-1.9.0-RC2.jar:/Users/colin/.m2/repository/org/clojure/spec.alpha/0.1.143/spec.alpha-0.1.143.jar:/Users/colin/.m2/repository/org/clojure/core.specs.alpha/0.1.24/core.specs.alpha-0.1.24.jar:/Users/colin/.m2/repository/hiccup/hiccup/2.0.0-alpha1/hiccup-2.0.0-alpha1.jar:/Users/colin/.m2/repository/org/clojure/tools.nrepl/0.2.12/tools.nrepl-0.2.12.jar:/Users/colin/.m2/repository/clojure-complete/clojure-complete/0.2.4/clojure-complete-0.2.4.jar
```

I suspect that the bug in the dependencies being returned is what's affecting Cursive, since it uses that to figure out which libraries to attach to the project.

I'm going to close this - if you have reason to believe that there's something else going on, feel free to re-open.
