### ISSUE TITLE
Not all usages of namespaced keywords are found

### ISSUE THREAD

**Issue by mtruyens** [cursive-ide/cursive#1908]
(As per the request to log this as a bug: https://groups.google.com/forum/#!topic/cursive/vG5Uxm8ip2M)

Under Cursive 1.6.2 (tested with IntelliJ 2017.3), not all usages of namespaced keywords are found. This used to work perfectly under previous versions. Problematic examples seem to particular include identifiers under re-frame's reg-event-db function.

Steps: 
1. start & import a new re-frame project (using "lein new re-frame dummy")
2. In namespace dummy.events, add a function 

```
(re-frame/reg-event-db
  :abc/xyz
  (fn  [_ _]
    db/default-db))
```

3. Use that same keyword (:abc/xyz) somewhere else in the code base. 
4. Position the cursor on that keyword, and request its usages (Edit | Find | Find usages...)
5. Notice that the function added under dummy.events is not included in the resulting list.

**Comment by cursive-ide** [comment]
So I think this is working as expected. Keywords in spec and re-frame are now considered definitions, not usages. So if I have:

![screen shot 2017-12-06 at 16 48 54](https://user-images.githubusercontent.com/5589171/33643706-bdb32244-daa5-11e7-98db-33900793d77a.png)

and I find usages on the keyword, I get the following:

![screen shot 2017-12-06 at 16 49 39](https://user-images.githubusercontent.com/5589171/33643714-cb68e0e0-daa5-11e7-9ff4-6f84c7e7d464.png)

That is, one instance of the keyword is considered the definition, and the other is considered a usage. This is consistent with how vars are treated:

![screen shot 2017-12-06 at 16 50 27](https://user-images.githubusercontent.com/5589171/33643732-eec4e62e-daa5-11e7-9796-043d362426ff.png)

![screen shot 2017-12-06 at 16 50 35](https://user-images.githubusercontent.com/5589171/33643748-f4b146c2-daa5-11e7-9c18-82d6f304c3ae.png)

Is there a reason you'd expect the keyword definitions to work differently from normal var definitions?

**Comment by wilkerlucio** [comment]
I just had this space expectation as well. I guess on keywords my expectation is that usages should find all of then, usages and definitions.

**Comment by conan** [comment]
I'd really like to be able to switch back to the old behaviour.  I have specs, Datomic schema and re-frame subscriptions which share names, and I currently have to use Find in Path to find or replace them.  It makes refactoring them more difficult - one of the wonderful things about using an IDE like Cursive is that it's trivial to change a name, and losing that capability has a big impact on my everyday development.  Coupled with #1913 it feels like a lot of great functionality has been lost; I'd rather have Find Usages work on all keywords than any bespoke support for re-frame subs/events and similar.

**Comment by cursive-ide** [comment]
Here's a repro case from @awkay:
```clojure
(ns com.fulcrologic.fulcro.b
  (:require
    [clojure.spec.alpha :as s]))

(s/def ::y number?)

-----

(ns com.fulcrologic.fulcro.a
  (:require
    [com.fulcrologic.fulcro.b :as b]
    [clojure.spec.alpha :as s]))

(s/def ::x int)

(defn f [{::keys   [x]
          ::b/keys [y]}])
```

Renaming `::y` doesn't update the destructuring, which it should.

**Comment by wilkerlucio** [comment]
I like to reinforce the point of Conan, I agree with him that having a good
rename is really important. So much that in some new projects we have
people considering using `:keys [::a/foo]` instead of `::a/keys [foo]` just
to make the editor happy when renaming, which is quite a bad thing to
happen IMO. I would totally vote for prioritizing these basic features over
any new thing.
---
Wilker Lúcio
http://about.me/wilkerlucio/bio
Woboinc Consultant
+55 81 82556600

**Comment by cursive-ide** [comment]
Yes I agree, and until discussing it with @awkay the other day I hadn't thought about all the ramifications. I'm fixing this now, and it should be in the next build. My plan is to have all keywords act as they did previously, but in the case of keywords which define things (specs, re-frame elements) you'll be able to navigate to the definitions.

**Comment by cursive-ide** [comment]
This is (finally!) fixed and released today in 1.8.2-eap4. This goes back to treating keywords as they worked previously, but still allows you to navigate to definitions if they exist. It will also continue to show the definition in the structure view.

This is a change with a lot of potentially subtle ramifications, so if anything looks amiss please let me know and I'll look at it ASAP.

**Comment by cursive-ide** [comment]
Oh, and one other thing which I explained in Slack, but should go here for posterity:

Currently if there’s a destructuring like:

```clojure
(defn f [{::b/keys [x y]}]
```

and I rename `::b/y` to `:other/baz`, the destructuring will be changed to:

```clojure
(defn f [{:keys [::b/x :other/foo]}]
```

Basically right now a `:keys` destructuring will never be split, just the prefixes will be adjusted to ensure the code is correct. It seems like there's probably scope for a preference of some kind (a formatting flag, or some such) specifying that you prefer the namespace to go on the `:keys` keyword, i.e. you'd prefer the above example to be split into:

```clojure
(defn f [{::b/keys [x] :other/keys [y]}]
```

I actually had no idea this was even a thing, and it doesn't work in Clojure 1.7 but does in recent versions. If this is something that anyone would prefer, please let me know and I'll look at it.

**Comment by wilkerlucio** [comment]
@cursive-ide I use `::x/keys` syntax everywhere, would be nice to select this as the way to keep destructuring.

**Comment by cursive-ide** [comment]
@wilkerlucio I filed #2191 for that.
