### ISSUE TITLE
Support for deps.edn

### ISSUE THREAD

**Issue by olivergeorge** [cursive-ide/cursive#1910]
Based on: https://clojure.org/guides/deps_and_cli

Developers should be able to setup a project where the classpath / dependency management is configured with a deps.edn file.

* Source files should have correct syntax highlighting because symbols resolve
* Should be able to setup a REPL based on the deps.edn classpath

**Comment by marco-m** [comment]
Related: lein plugin to support deps.edn (work in progress): https://github.com/RickMoynihan/lein-tools-deps

**Comment by theronic** [comment]
For those of us using boot-clj, it's a real pain maintaining up-to-date dependencies in a project.clj file. Please consider adding deps.edn support :)

**Comment by thheller** [comment]
FYI: For `deps.edn` you can run `clojure -Spom` to generate a `pom.xml`. You can use that to create the project in IDEA/Cursive. Not perfect either but beats manually maintaing a `project.clj`.

**Comment by theronic** [comment]
thanks, @thheller! how do I tell Cursive to use the pom.xml file?

**Comment by alex-dixon** [comment]
@theronic Right click `pom.xml` -> "Add as Maven Project"

**Comment by petterik** [comment]
If you - like me - can't find the "Add as Maven Project" option when you right click on your `pom.xml`, you might be missing the `Maven Integration` plugin for Intellij. Install it and the option should appear.

**Comment by thheller** [comment]
`File -> New -> Project from Existing Sources` and then select the `pom.xml`. Or `Import Project` if you are on the IntelliJ Welcome screen.

**Comment by awebneck** [comment]
While the `clojure -Spom` method works great for the core project, the `pom.xml` generated thereby doesn't take into account, for instance, environment-like aliases. E.g. while `deps.edn` generally designates test dependencies and additional paths as an additional alias (i.e. `:test`), this does not result in a `pom.xml` containing the `<testSourceDirectory>` element, used by IntelliJ when importing a maven project to designate the source directory for test namespaces, and so necessitates additional manual setup. Moreover, however, the Maven `pom.xml` schema has no mechanism of specifying dependencies not hosted from a Maven repo (e.g. github-only-hosted projects), while this *is* a part of `deps.edn`, and so when generating `pom.xml` those dependencies get skipped entirely. All that to say, 👍 to seeing in-built support for `deps.edn` without having to resort to generation of a Maven `pom.xml`.

**Comment by atroche** [comment]
This is pretty useful https://gist.github.com/mfikes/f803fef3013927c376063a3d72b69d60 :

> The following provides some workarounds for some issues when using lein-tools-deps from Cursive on macOS.

**Comment by coltnz** [comment]
If you want to Cursive, Boot and deps this is the magic

https://gist.github.com/coltnz/3f38d7b08a3dff7d1bbda580d498188f

**Comment by theronic** [comment]
I can't find the deps.edn tool window in Cursive. Can anyone tell me where it is? Feels like something that belongs in documentation/readme.

**Comment by thheller** [comment]
It is not released yet and only available in EAP builds.

See EAP in https://cursive-ide.com/userguide/

**Comment by khardenstine** [comment]
FWIW I've found the tool window only shows up once you import a module using deps:
![image](https://user-images.githubusercontent.com/7741805/46877033-cc29fa80-ce0d-11e8-8acc-7a22681e50db.png)

**Comment by juskrey** [comment]
![image](https://user-images.githubusercontent.com/3420759/46901417-110c6a80-cebc-11e8-9017-3cd78277c34d.png)

**Comment by theronic** [comment]
@juskrey where do I go from here?

![no way to use deps.edn from Cursive](https://user-images.githubusercontent.com/1011676/55212002-dfcbf080-51f6-11e9-8f0a-5bcb443b0086.png)

deps.edn is in project root, but it won't start using it.

**Comment by timeyyy** [comment]
I created a new project by deleting the .idea folder and opening the deps.edn file. I could then see my project under `Linked Clojure Deps projects`

**Comment by theronic** [comment]
Just to bump this - I can't figure out how to get Cursive to use deps.edn for a project that started out with a project.clj.

**Comment by theronic** [comment]
Just had to google again how to switch from project.clj to deps.edn. Ideally, when I open deps.edn in IntelliJ, it should prompt me with a bar at the top, "do you want to install deps.edn monitoring for dependency management?"

**Comment by theronic** [comment]
For future self: File -> New -> Module From Existing Sources... -> Choose the deps.edn file in the current project folder, and it'll work.

**Comment by aarishramesh** [comment]
> For future self: File -> New -> Module From Existing Sources... -> Choose the deps.edn file in the current project folder, and it'll work.

Aliases for starting the nREPL can be defined from Edit configurations. Under 'Run with Deps' Aliases can be defined
