### ISSUE TITLE
Cursive is disabled by IntelliJ IDEA due to incompatibility with Java 9

### ISSUE THREAD

**Issue by finalfantasia** [cursive-ide/cursive#1914]
Cursive is disabled by IntelliJ IDEA when run with JDK9, here is the screenshot of the error message that pops up:

![cursive_java9_incompatibility](https://user-images.githubusercontent.com/2316604/33798934-94e30c98-dcd6-11e7-8faa-68e6cd226007.png)

Environment:
Cursive 1.6.2 (built on 2017-11-28 14:49)
IntelliJ IDEA 2017.3 (Community Edition)
Build #IC-173.3727.127, built on November 27, 2017
JRE: 9.0.1+11 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.13.16-302.fc27.x86_64

**Comment by cursive-ide** [comment]
Right, Cursive is only supported when using the JetBrains bundled JDK, which is JDK 8. They're planning to move that to JDK 9 (see: JetBrains/jdk8u_jdk#4), but I have no idea when that might happen. I'm going to close this in the meantime.
