### ISSUE TITLE
Midje support

### ISSUE THREAD

**Issue by rssole** [cursive-ide/cursive#1918]
This is not really an issue but rather a question,
are you planning to add support for Midje similar to
what is currently available for core testing facility?

Kind regards

**Comment by viebel** [comment]
Is there a support for Midje in Cursive?

**Comment by cursive-ide** [comment]
Since this ticket was referenced in Slack, I thought I should update it. I’m very unlikely to support Midje. It has been effectively dead for ages and is a tangled mass of macros. Sorry I don't have a better answer.

I'm going to close this issue, for the moment at least.
