### ISSUE TITLE
parinfer smartmode

### ISSUE THREAD

**Issue by vehas** [cursive-ide/cursive#1937]
nowaday parinfer support  smartmode which is smart combination between indent mode and parent mode [https://github.com/shaunlebron/parinfer/tree/master/lib#smartmodetext-options](https://github.com/shaunlebron/parinfer/tree/master/lib#smartmodetext-options)
Will cursive support this?

**Comment by cursive-ide** [comment]
Yes, in fact there's a dev build with this available now for testing: see [here](https://groups.google.com/d/topic/cursive/ZJ4fcp3A988/discussion) for details on how to install it.
