### ISSUE TITLE
Parinfer does not preserve indentation or mode unclear

### ISSUE THREAD

**Issue by theronic** [cursive-ide/cursive#1950]
The Parinfer reference implementation [preserves indentation](https://shaunlebron.github.io/parinfer/), but Cursive's Parinfer does not preserve my indentation. 

## Example

Where <kbd>|</kbd> is cursor:

```
|(let [x 4]
  (+ x 6))
```

Now I'll type some characters, e.g. the ignore macro. Let's see what happens.

## Expected:

The tree should indent.  Note <kbd>_</kbd> denotes important whitespace:

```
#_|(let [x 4]
____(+ x 6))
```

## Actual:

But instead, the children fall out of the branch:

```
#_|(let [x 4])
__(+ x 6)
```

Maybe I'm stuck in a mode I can't get out of, but [Modes Are Bad™](http://wiki.c2.com/?DontModeMeIn).

How do I know what's going on?

**Comment by cursive-ide** [comment]
The indentation preserving behaviour is new in Parinfer V3. There's a dev build of Cursive out with it (see [here](https://groups.google.com/d/topic/cursive/ZJ4fcp3A988/discussion) for details, right now it has to be manually installed), it'll be in an EAP build within a couple of days.

**Comment by cursive-ide** [comment]
BTW I'll close this issue since the solution is imminent.
