### ISSUE TITLE
C-j from .cljc for clojure.core fns doesn't show anything useful

### ISSUE THREAD

**Issue by dustingetz** [cursive-ide/cursive#1951]
C-j is: "Show a popup window with documentation for the symbol at caret"

![image](https://user-images.githubusercontent.com/124158/37157788-b17a860c-22b7-11e8-8624-18a52a549260.png)
from the repl works:
![image](https://user-images.githubusercontent.com/124158/37157797-b63f8ebc-22b7-11e8-8a9a-469e6186dac9.png)

The difference is, the CLJC context needs a disambiguator:
![image](https://user-images.githubusercontent.com/124158/37157816-c3c75c90-22b7-11e8-9ac7-ba800a028809.png)

They have the same airity and args (which is rather the point of cljc) so would it be possible to just choose one?

**Comment by cursive-ide** [comment]
This is tracked in #1645.
