### ISSUE TITLE
Add option to set environment variables in leiningen run config

### ISSUE THREAD

**Issue by eoliphan** [cursive-ide/cursive#1953]
This only seems to be an option for repl configs.  Most config would go in a profile but there are certain things (e.g. AWS env settings, etc) that one might prefer to set in the run config

**Comment by cursive-ide** [comment]
This is fixed for the next build. Also in that build is #2160, which allows support for `.env` files via the [EnvFile](https://github.com/ashald/EnvFile) plugin, which may be preferable.
