### ISSUE TITLE
[BUG] Reformatting breaks reader conditionals in require form when using parinfer

### ISSUE THREAD

**Issue by gnl** [cursive-ide/cursive#1972]
Reformatting this part of a `:require` clause:
```
   #?(:clj  [orchestra.spec.test :as ost]
      :cljs [orchestra-cljs.spec.test :as ost])
```
results in this:
```
   #?(:clj)
   [orchestra.spec.test :as ost
      :cljs [orchestra-cljs.spec.test :as ost]]
```

Tried to trick it...

```
   #?(:clj [orchestra.spec.test :as ost])
   #?(:cljs [orchestra-cljs.spec.test :as ost])
```

...but no luck:

```
   #?(:clj)
   [orchestra.spec.test :as ost]
   #?(:cljs [orchestra-cljs.spec.test :as ost])
```

Only seems to affect the `:clj` clause. Outside of the `:require` form reader conditionals work exactly as expected.

This is probably related to #1014 and seems like a 'cosmetic formatting issue + parinfer = big breaking issue' type of situation.

It's sort of critical for me, because right now every time I reformat I have to go to the top of my namespace and fix the conditionals, so a quick fix or a temporary workaround would be much appreciated. Thank you!

Edited:
Cursive version: 1.7.0-eap1-2018.1

**Comment by cursive-ide** [comment]
My apologies for the long wait on this one - it has been fixed in #1014.
