### ISSUE TITLE
Cursive & Specter not playing nicely

### ISSUE THREAD

**Issue by LispEngineer** [cursive-ide/cursive#1973]
Using `[com.rpl/specter "1.0.2"]` in an IntelliJ 2018.1 with Cursive 1.7.0-eap1-2018.1 on macOS 10.12 with Clojure 1.8.0 and Lein 2.7.1:

Cursive and Specter seem to have some issues. It can't resolve some of the referred things. Here is a minimal `.clj` source file with a few examples:

```clojure
(ns cursive-specter
  (:require  [com.rpl.specter :as specter
              :refer-macros [transform]
              :refer [transform MAP-VALS ALL FIRST LAST collect-one must]]))

(transform [:monsters ALL] str {:monsters [1 2 3]})

(transform [:quests ALL (collect-one FIRST) LAST]
           (fn [k val] (assoc val :quest-tag k))
           {:quests {:quest1 {:a :b :c :d} :quest2 {:e :f :g :h}}})
```

In my IDE, `ALL` and `collect-one` are highlighted as "cannot resolve."

I'm going to imagine that it's related to how Specter makes its own macros for defining things, such as: (from `com.rpl.specter` namespace)

```clojure
(defnav
  ^{:doc "Navigate to every element of the collection. For maps navigates to
          a vector of `[key value]`."}
  ALL
  []
  (select* [this structure next-fn]
    (n/all-select structure next-fn))
  (transform* [this structure next-fn]
    (n/all-transform structure next-fn)))
```

Mind you, Cursive also cannot resolve `defnav` when looking at Specter source code.

Looks like it's a situation where Cursive needs more semantic insight into things that aren't simple `(def ...)` forms?

**Comment by tanya-coding** [comment]
I have the same issue and in addition to unresolved symbols, anywhere I use specter's `END` I get suggestions to import `com.sun.nio.zipfs ZipFileSystem$END`

**Comment by JustinSpedding** [comment]
I am still having the same issue with `[com.rpl/specter "1.1.2"]` and Cursive 1.8.2-2019-2. There are some other libraries that I use for which Cursive can create shims. Can we do the same thing with specter?

**Comment by jdhollis** [comment]
I'm running into this as well. Perhaps #2767 would resolve many of the issues?

**Comment by mortenschioler** [comment]
Mitigated this problem by "resolving as..." on the following:

```clojure
com.rpl.specter/defcollector clojure.core/defn
com.rpl.specter/defdynamicnav clojure.core/defn
com.rpl.specter/defmacroalias clojure.core/def
com.rpl.specter/defnav clojure.core/defn
com.rpl.specter/defrichnav clojure.core/defn
```

**Comment by jdhollis** [comment]
> Mitigated this problem by "resolving as..." on the following:
> 
> ```clojure
> com.rpl.specter/defcollector clojure.core/defn
> com.rpl.specter/defdynamicnav clojure.core/defn
> com.rpl.specter/defmacroalias clojure.core/def
> com.rpl.specter/defnav clojure.core/defn
> com.rpl.specter/defrichnav clojure.core/defn
> ```

This solved the problem for me. I guess I should have spent more time digging into the library…

Thanks!

**Comment by cursive-ide** [comment]
Fix released in 1.13.1-eap9 on 2023-11-27.

**Comment by cursive-ide** [comment]
@AndyCorlin You should have received a popup suggesting that you generate stubs - did you do that?

**Comment by cursive-ide** [comment]
Fix released in 1.13.1 on 2023-12-07.

**Comment by AndyCorlin** [comment]
> @AndyCorlin You should have received a popup suggesting that you generate stubs - did you do that?

Aha - I have seen that message over the years, but no idea what for and where it came from.

Now that I tried it I get:
```
Cursive Stub generation
com.intellij.execution.process.ProcessNotCreatedException Cannot run program "C:\Users\AndersCorlin\.jdks\corretto-1.8.0_392\bin\java.exe" (in directory "C:\BB\Gimli1\deeds-api"): CreateProcess error=206, The filename or extension is too long
```

Windows has a limitation of path names of 256 characters .There is registry setting where you can enable "long path names", which I have set, but the application must also be compiled with a manifest that it supports it.

For the normal REPL I have a similar problem, but that can be fixed by using "Shorten command line" = "JAR manifest".

@cursive-ide, does this give you any clues of how to fix it?

**Comment by mortenschioler** [comment]
@AndyCorlin try perusing https://github.com/cursive-ide/cursive/issues/2021

**Comment by AndyCorlin** [comment]
Thanks @mortenschioler! I had to go through all modules and set it one by one, but then it worked.
