### ISSUE TITLE
Feature Request: Easily search REPL output

### ISSUE THREAD

**Issue by conan** [cursive-ide/cursive#1984]
I've never been able to search the REPL output.  I think I had it working a very long time ago for a very short space of time, but I've tried several times since then to make it work and haven't been able to do it.

I would like to press Ctrl+F in the REPL to search the output.  Note that I'm not just referring to the REPL History (i.e. the commands I have typed in), I'm referring to stdout and stderr output that has been printed to the top REPL box.

**Comment by bjonica** [comment]
Odd, this seems to work for me. Under OS X, if I click on the REPL output window, press cmd+f, I'm able to search through the REPL output. Maybe the keybinding is misconfigured. 

Does focusing the repl window, and going to edit -> find -> find bring up a find bar that is able to search through everything in the repl?

**Comment by sooheon** [comment]
Confirmed working in Mac OS X

**Comment by conan** [comment]
Ah!  I see.  I have my REPL in a separate window, where there is no menu.  OK I guess this works, thanks.
