### ISSUE TITLE
REPL commands get added to REPL history

### ISSUE THREAD

**Issue by thheller** [cursive-ide/cursive#1990]
I'm messing with a few of the newly added REPL substitutions (eg. `~current-test-var`) and I noticed that every command sent to the REPL is added to the REPL history. The behavior seems to be new as previous versions did not do this.

It would be nice if there was a way to turn this off.

**Comment by cursive-ide** [comment]
Yes, this changed recently, see [this thread](https://groups.google.com/d/topic/cursive/hOzq8XiTmKA/discussion) for context. As mentioned in that thread, there's a "Add forms sent from editor to REPL history" setting which REPL commands currently do not obey. Would you want a separate setting, or would making the REPL commands obey this be sufficient? The implication there would be that if you turn that off, then "Send top form to REPL" and family would no longer add to the history either.

**Comment by thheller** [comment]
I have that turned off as well. Not sure what is best here. Might be best to have a separate setting.

**Comment by thheller** [comment]
An option to not show what was sent to the REPL might also be nice.

I'm trying to get my usual CLJ REPL workflow to also work with CLJS. I work by writing a `clojure.test/deftest` and then using the `Run test in REPL` or `Re-Run`. This works well for CLJ but is not supported for CLJS. So I added a command that sends this to emulate `Run test in REPL`

```
(require 'shadow.test.repl)
(shadow.test.repl/run-test
  {:file-name "resolve_test.clj"
   :file-path "C:/Users/thheller/code/shadow-cljs/src/repl/shadow/cljs/resolve_test.clj"
   :file-ns 'shadow.cljs.resolve-test
   :test-var #'shadow.cljs.resolve-test/test-resolve-config})
```

It works ok but is quite verbose if the above is displayed in the REPL window every time. An option to either display nothing or something like just showing "Running <name of command>"  instead would be very neat.

**Comment by thheller** [comment]
It might make sense to make this a per command toggle as well.

**Comment by tekacs** [comment]
Not sure how to propose support for this issue.

My workflow is similar to the above, where I have a 'reload' key which does a namespace reload and stops/starts my mount system.

The verbosity in the terminal isn't a concern, but it makes it difficult to use REPL history effectively when going up is almost always my reload command (which is multiline!)
