### ISSUE TITLE
"Cannot switch to ClojureScript namespace in Clojure REPL" for cljs > 1.10.63

### ISSUE THREAD

**Issue by juskrey** [cursive-ide/cursive#1993]
When running figwheel, can't switch to cljs namespace for newer Clojurescript versions

![image](https://user-images.githubusercontent.com/3420759/40421068-335ed79c-5e93-11e8-8d34-58415fea6298.png)

**Comment by cursive-ide** [comment]
Ok, you can work around this by manually toggling the REPL type:

<img width="409" alt="screen shot 2018-05-24 at 06 31 00" src="https://user-images.githubusercontent.com/5589171/40449624-884cfc04-5ec8-11e8-82c8-e8e968745f55.png">

I'll check why that is no longer switching automatically and fix it.
