### ISSUE TITLE
Cursive not finding symbols for user defined functions in other related namespaced

### ISSUE THREAD

**Issue by Alex-Keyes** [cursive-ide/cursive#1994]
I can't get Cursive to index / recognize the symbols from other namespaces in the file I am currently editing.  I've looked at https://github.com/cursive-ide/cursive/issues/626, but it doesn't _quite_ relate since I'm not having any issues with standard `clojure.core` functions, but rather functions that I've defined in other namespaces.  
<img width="265" alt="screen shot 2018-05-29 at 3 55 25 pm" src="https://user-images.githubusercontent.com/11702294/40682244-46596bda-6359-11e8-8848-cc9a09b8492c.png">
<img width="612" alt="screen shot 2018-05-29 at 3 55 18 pm" src="https://user-images.githubusercontent.com/11702294/40682246-466725a4-6359-11e8-9ae6-4372dee0dd6b.png">
Here is an example screenshot showing the problem and the directory structure that the project uses.  This is all under a `src` folder that is defined in the project.clj.

**Comment by cursive-ide** [comment]
Can you show me how the `stats-top-terms` symbol is defined in the `stats` namespace?

**Comment by Alex-Keyes** [comment]
I think I might have realized the problem.  These are not defined as functions, but rather are defined using the `resource` macro from [liberator](https://clojure-liberator.github.io/liberator/).  Is there anyway to have cursive understand where these things are implemented?  
<img width="358" alt="screen shot 2018-05-30 at 10 15 24 am" src="https://user-images.githubusercontent.com/11702294/40726068-f55c8cb8-63f2-11e8-9943-0a9782ceb161.png">
(here's an example)

**Comment by cursive-ide** [comment]
@Alex-Keyes Is `stats-top-terms` defined that way as well?

**Comment by Alex-Keyes** [comment]
yep!

**Comment by Alex-Keyes** [comment]
Any idea on whether this is resolvable?

**Comment by cursive-ide** [comment]
Yes, I'll add support for the liberator macros.
