### ISSUE TITLE
Can't see require vectors within reader conditionals

### ISSUE THREAD

**Issue by jdf-id-au** [cursive-ide/cursive#2001]
Thanks for a brilliant IDE.

I'm trying to use a `.cljc` file with the following `ns` form:
```
(ns common.db
  (:require #?@(:clj [[clojure.spec.alpha :as s]
                      [java-time :as time]]
                :cljs [[cljs.spec.alpha :as s]
                       [cljs-time.core :as time]
                       [cljs-time.extend]
                       [goog.date]])))
```

Cursive doesn't seem to recognise the vectors within the reader conditional. When I type `time/`, it offers generic completions from libraries which I'm not using in my project (e.g. `clj-time.`, `manifold.time`).

**Comment by jdf-id-au** [comment]
Oh man am I a noob.

I had erroneously left the file extension as `.cljs`. When I changed it to `.cljc`, and corrected `java-time` to `java-time.core`, Cursive correctly resolved both libraries and provides correct completions.

Sorry for the fuss!

**Comment by cursive-ide** [comment]
Ohhhh... actually, I had planned a warning when reader conditionals are used in a non-CLJC file - I'll add that :-)
