### ISSUE TITLE
deps.edn error: Can't find bundle for base name messages.JavaCoreBundle, locale en_X

### ISSUE THREAD

**Issue by visibletrap** [cursive-ide/cursive#2011]
When I try to open a deps.edn project, I get these errors. This doesn't happen when opening a lein project.

<img width="376" alt="screen shot 2018-07-20 at 02 24 30" src="https://user-images.githubusercontent.com/625523/42966285-d2af0e56-8bc6-11e8-9ad2-ee38ca4388c5.png">

<img width="414" alt="screen shot 2018-07-20 at 02 24 43" src="https://user-images.githubusercontent.com/625523/42966294-d90c8f26-8bc6-11e8-903e-ced3ba597162.png">

![jul-20-2018 02-59-27](https://user-images.githubusercontent.com/625523/42966990-02cd53e8-8bc9-11e8-84f9-78b79de41233.gif)

Maybe relate to this https://youtrack.jetbrains.com/issue/IDEA-191059

**Comment by cursive-ide** [comment]
It looks like that bug, yeah, although that bug should have been fixed - which IntelliJ version are you on?

**Comment by visibletrap** [comment]
Yeah, it's fixed by updating IntelliJ version. My bad. Sorry for the noise. Somehow I always missed their update notification, I'll need to check if it turns on. Thanks!
