### ISSUE TITLE
Parinfer is confused when functions are indirectly referenced

### ISSUE THREAD

**Issue by simongray** [cursive-ide/cursive#2027]
In our organisation's code base we have code taking the form:

```clojure
(('foo bar) :foobar)
```

where the first form ```('foo bar)``` is an indirect reference that resolves to a function and the second form :foobar is an argument to that function.

If we try to insert a newline (= press enter) between the first form and the second form, the parinfer implementation will move the parenthesis:

```clojure
(('foo bar 
  :foobar))
```

Suddenly, :foobar is made a part of the first form.

If we then manually correct it to this (the only way possible without parinfer moving it inside the first form)

```clojure
(('foo bar) 
 :foobar)
```

then using the automatic code formatting will put it back in the erroneous state again.

**Comment by Azzurite** [comment]
This is probably because of the styleguide stating that [function arguments on new lines should be indented with only one space](https://github.com/bbatsov/clojure-style-guide#one-space-indent).

In my Cursive Parinfer, one space produces

```
(('foo bar) 
 :foobar)
```

while two spaces produces

```
(('foo bar 
  :foobar))
```

**Comment by simongray** [comment]
@Azzurite Sure, I get why it is happening. The issue is that automatic code formatting will break it no matter how its formatted, so even if I wanted to use a single space, any event that triggers IntelliJ's code formatting will silently break the code.

**Comment by cursive-ide** [comment]
This is fixed for the next EAP build. Cursive will now indent any forms where the head form is some kind of braced form (lists, vectors, maps) with one space.
