### ISSUE TITLE
make nREPL ack wait time configurable

### ISSUE THREAD

**Issue by fbellomi** [cursive-ide/cursive#203]
Sometimes (more often with larger projects) launching nREPL within IJ fails with the message "No nREPL ack received". This happens at random, whereas "lein repl" from the terminal always works. 
I've tried both "use normal process" and "run with Lein"
I think this could be a problem with the timeout, and I would like to try to modify the wait time threshold.

Thanks, Francesco

**Comment by jbeja** [comment]
Just starting to use cursive and I have this problem too using a chestnut template.

**Comment by cursiveclojure** [comment]
@jbeja It's configurable, under *Settings&rarr;Clojure->REPL startup timeout*.
