### ISSUE TITLE
project.clj :resource-paths are marked as sources not resources in IDEA

### ISSUE THREAD

**Issue by scarytom** [cursive-ide/cursive#2058]
In my leiningen project.clj I define some resource paths like this:
  :resource-paths ["src/main/resources" "src/test/resources"]

When I import this project into IntelliJ IDEA using Cursive, the project structure shows these paths are classed as "sources" not "resources".  This is infuriating for me, as I have some JUnit tests that I can run in the IDE, but the required resources are not copied to the target directory, because IDEA doesn't know to do that as they are incorrectly classified.

**Comment by cursive-ide** [comment]
This is by design, due to unfortunate differences in how IntelliJ and Leiningen interpret the concept of resource folders. Full details and a possible workaround are described in #241.
