### ISSUE TITLE
`defn` inside a `with-test` cannot be resolved

### ISSUE THREAD

**Issue by holyjak** [cursive-ide/cursive#2063]
If I have 

```clj
(clojure.test/with-test
  (defn parse-command [] ...)
  ...)
 ```

then 1. autocompletion of `(pars` won't propose anything and 2. when I call `(parse-command ..)` from the code, it is highlighted and reports 
> parse-command cannot be resolved

Expected behavior: IntelliJ should see the defn and not report the function as not resolved; autocompletion should work.

Cursive 1.8

Thank you!

**Comment by jakubholynet** [comment]
Hi Colin, thanks a lot! Unfortunately. `do` does not seem to be supported: 

![telia-devbot____work_telia-devbot__-_t_core](https://user-images.githubusercontent.com/624958/46522339-cb7bec00-c882-11e8-8598-087860f0b2ee.jpg)

**Comment by jakubholynet** [comment]
Any update? Thank you!

**Comment by holyjak** [comment]
Hi @cursive-ide , as mentioned above, I am not able to apply your advice. Do I do something wrong? Thanks!

**Comment by cursive-ide** [comment]
Hi @holyjak, I've filed #2081 for the underlying issue. I'll try to fix this for the next build, and then you should be able to do this.

**Comment by cursive-ide** [comment]
Closing this as #2081 is now fixed and released.
