### ISSUE TITLE
"Stubs" are generated into `out` directory in project

### ISSUE THREAD

**Issue by thheller** [cursive-ide/cursive#2069]
Generating stubs for Cursive should not pollute the project directory with an `out` directory containing `.cache.json` files.

Calling `lein new fulcro fulcro-app` and then creating a new Cursive project using the `project.clj` will ask to generate the stubs and ends up putting them into `out`. There is no way to configure this as far as I can tell and I'd like the files to not be there as I'm using `out` for different purposes.

The default should probably generate them either into `target` or some other folder outside the project since its only relevant to Cursive.

**Comment by thheller** [comment]
Don't know how which API you are calling to generate the stubs but setting either `:output-dir "...some/path"` or `:cache-analysis false` should take care of it.

**Comment by cursive-ide** [comment]
`:cache-analysis false` did the trick, thanks!
