### ISSUE TITLE
Resolve result appears multiple times

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2077]
Reported by @wilkerlucio in Slack:

> Sometimes cursive doesn't offer to change how to resolve a form. I'm having this with some spec things, the problems happens more often in cljs/cljc files. I press the alt+return but nothing happens, and I can confirm its a macro. When I try to navigate to the macro it shows 2 places, and I think should be only one:

<img width="972" alt="screen shot 2018-11-09 at 15 01 43" src="https://user-images.githubusercontent.com/5589171/48286080-69ec0600-e45c-11e8-9af8-905b21dd2ca4.png">

**Comment by cursive-ide** [comment]
Wilker has created a repro repo (thanks!) at: [wilkerlucio/repro-cursive-resolve-issue](https://github.com/wilkerlucio/repro-cursive-resolve-issue).

**Comment by cursive-ide** [comment]
This is not actually a problem in Cursive, the issue is in `fulcrologic/fulcro-incubator`. In the jar file there are two copies of the source, one in the root and one under `/main`. Cursive finds and indexes both of them, and that's why there are two results.

**Comment by cursive-ide** [comment]
cc/ @awkay.

**Comment by awkay** [comment]
ooops...thanks!

**Comment by awkay** [comment]
Fixed in 0.0.16
