### ISSUE TITLE
Add support for :extend-via-metadata in protocol definitions

### ISSUE THREAD

**Issue by vlaaad** [cursive-ide/cursive#2085]
With release of [1.10.0-beta6](https://groups.google.com/forum/#!topic/clojure/oruh1-G7ujc) behavior for metadata-based protocol extension is now opt-in and requires to supply option to enable it:
```clj
(defprotocol Component
  :extend-via-metadata true
  (instance [this] "returns platform instance associated with this component"))
```
After adding `:extend-via-metadata true` Cursive can't see method declarations: 
![](https://imgur.com/npvYVxe.png)

I hope Cursive will get support for this one day!

**Comment by vlaaad** [comment]
You are awesome, Colin, thank you!

**Comment by sooheon** [comment]
Not sure if there has been a regression, but with v1.8.2-eap4-2019.1, I still see this issue:

<img width="582" alt="Screen Shot 2019-06-03 at 2 52 24 PM" src="https://user-images.githubusercontent.com/302945/58837022-34348780-860f-11e9-9210-15b9b91b7a75.png">

**Comment by jffry** [comment]
@sooheon If you're still having this issue, I narrowed down the cause.  Try moving `:extend-via-metadata true` _after_ the docstring for the `defprotocol` and Cursive should understand it.  I opened a related issue for this: https://github.com/cursive-ide/cursive/issues/2429
