### ISSUE TITLE
Cursive not loaded in IntelliJ 2018.3

### ISSUE THREAD

**Issue by PsukheDelos** [cursive-ide/cursive#2087]
I have upgraded to IntelliJ CE 2018.3 and I get stuck in a loop enabling Cursive. IntelliJ asks to restart to activate the changes. After it reboots, it again says Cursive required. I enable it and again have to restart. This continues indefinitely. 

```
Required plugins weren't loaded
Plugin 'Cursive' required for 'my-great-project' project is disabled.
Enable Cursive

IDE and Plugin Updates: Restart IntelliJ IDEA to activate changes in plugins?
```

Let me know if you need any more info. I really appreciate all your work on Cursive, so keep up the good work, Cursive rocks! 😄 

Reporting in from windy Wellington,
-G

**Comment by cursive-ide** [comment]
Sorry about this, this should be resolved now. There were problems with the JetBrains repo yesterday that prevented me from uploading the 1.8.0 stable build, but it should all be good now.

I'm going to close this, but feel free to reopen if you're still having problems.
