### ISSUE TITLE
"Evaluate Expression" hangs on Clojure 1.10

### ISSUE THREAD

**Issue by hjrnunes** [cursive-ide/cursive#2099]
If execution is stopped at a breakpoint, evaluation (Run -> Evaluate Expression) of context variables (or expressions containing them) seem to hang with Clojure 1.10. 

Eval of expressions not touching context variables seem fine, though.

Rolling back to Clojure 1.9 fixes the problem.

We can produce this on IJ 2018.3.2 both Community and Ultimate. Rolling back to 2018.3.1 yielded no difference: 1.10 hangs, 1.9 works.

**Comment by gorrus** [comment]
It started to fail in 1.10.0-alpha5

**Comment by cursive-ide** [comment]
Many thanks to @gorrus for diagnosing this and proposing the workaround, which does indeed work! This is fixed for the next build.
