### ISSUE TITLE
Remove border on REPL output window under 2018.3

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#2101]
I just updated to 2018.3 and noticed that they've removed some chrome from the Terminal frame. Previously there was a border similar to the one on the REPL output window. Under 2018.3 that is now gone.

<img width="217" alt="screenshot of intellij idea 11-01-19 7-06-46 pm" src="https://user-images.githubusercontent.com/811954/51016204-4a946500-15d4-11e9-8c27-364d6d091c77.png">

It looks like the REPL input window has the correct platform styling applied, but the output window has the old styling, perhaps because it was custom?

**Comment by cursive-ide** [comment]
This has been fixed (inadvertently) in 1.13.4.
