### ISSUE TITLE
Support IntelliJ IDEA 2019.1 EAP

### ISSUE THREAD

**Issue by dgelessus** [cursive-ide/cursive#2104]
The 2019.1 EAP was released a few days ago: https://blog.jetbrains.com/idea/2019/01/intellij-idea-2019-1-early-access-program-is-open/

Currently the plugin only supports 2018.3 and below.

**Comment by cursive-ide** [comment]
This is fixed in the next EAP release, 1.8.1-eap2, out shortly.
