### ISSUE TITLE
[deps.edn] Cursive picks up the wrong version of clojure-tools JAR when there are multiple versions of it under "/usr/local/lib/clojure/libexec"

### ISSUE THREAD

**Issue by finalfantasia** [cursive-ide/cursive#2105]
I came across the following two errors when attempting to import a simple deps.edn project:
```log
No such var: deps/combine-aliases, compiling:(cursive/deps/deps_tree.clj:39:32
```
and then
```
Attempting to call unbound fn: #'cursive.deps.deps-tree/deps-tree
```
Cursive would stop synchronizing the project and neither invalidating caches nor re-importing the project fixed this problem. After spending some time figuring out what was going on, I noticed that the version of the clojure-tools JAR in `$HOME/.IdeaIC2018.3/config/options/clojure-deps.settings.xml` (`1.9.0.273`) didn't match the latest version of Clojure CLI tools (`1.10.0.411`) that I have installed in my system:
```xml
<application>
  <component name="DepsSettings">
    <option name="clojureCommandPath" value="/usr/local/bin/clojure" />
    <option name="configFiles">
      <list>
        <option value="/usr/local/lib/clojure/deps.edn" />
        <option value="$USER_HOME$/.clojure/deps.edn" />
      </list>
    </option>
    <option name="configPath" value="$USER_HOME$/.clojure" />
    <option name="executableHash" value="-2141066841" />
    <option name="installPath" value="/usr/local/lib/clojure" />
    <option name="uberjarPath" value="/usr/local/lib/clojure/libexec/clojure-tools-1.9.0.273.jar" />
    <option name="version" value="1.10.0.411" />
  </component>
</application>
```
Confused by this, I went ahead to check the content of the `/usr/local/lib/clojure/libexec` directory and realized that I had 4 versions of clojure-tools JAR in there and, somehow, Cursive picked up the oldest version (`1.9.0.273`):
```bash
-rw-r--r--. 1 root root 22M Dec 17 19:07 clojure-tools-1.10.0.403.jar
-rw-r--r--. 1 root root 22M Feb  1 22:38 clojure-tools-1.10.0.411.jar
-rw-r--r--. 1 root root 14M Dec  9  2017 clojure-tools-1.9.0.273.jar
-rw-r--r--. 1 root root 21M Dec  9 13:32 clojure-tools-1.9.0.397.jar
```
As a work-around, deleting everything other than the latest version (`clojure-tools-1.10.0.411.jar`) and re-importing the project fixed the problem.

**Comment by finalfantasia** [comment]
Cursive v1.8.0-2018.3

IntelliJ IDEA 2018.3.4 (Community Edition)
Build #IC-183.5429.30, built on January 28, 2019
JRE: 1.8.0_191-b13 amd64
JVM: OpenJDK 64-Bit Server VM by Oracle Corporation
Linux 4.20.5-200.fc29.x86_64

**Comment by stijnopheide** [comment]
I had to 'Invalidate caches and restart' to make your workaround function.
