### ISSUE TITLE
Cursive obscures the repl expression with REBL

### ISSUE THREAD

**Issue by puredanger** [cursive-ide/cursive#2113]
You can use REBL with Cursive in a deps project by following the directions at https://github.com/cognitect-labs/REBL-distro/wiki/REBL-in-IntelliJ-Cursive. Works great!

One issue is that when you evaluate an expression in Cursive (specifically I'm doing "Send form before caret to REPL"), the expression that shows up in REBL has a lot of Cursive machinery wrapped around it:

```
(clojure.lang.Compiler/load (clojure.lang.LineNumberingPushbackReader. (java.io.StringReader. "in-ns 'foo)\n\n\n\n\n\n(hi 1)")) ...
```
rather than the actual expression (here just `(hi 1)`).

This is the stuff Cursive uses to get proper line and column numbers in error messages, etc. In Clojure 1.10, there is better support to do this via metadata on the expression itself without all the newline stuff.

Cursive could now instead annotate an expression with metadata:

```
^{:clojure.core/eval-file "a/b/foo.clj", :line 100, :column 1} (hi 1)
```

This will cause errors to throw with the proper source/line/column info, which I think was the main motivation for all the wrapping. REBL would not print the metadata and all you would see in REBL is `(hi 1)`.

Some caveats: only in Clojure 1.10, can only apply metadata to expressions that can have metadata, but just sniffing the first character or two to indicate a collection would probably get it right 99% of the time.

**Comment by stuarthalloway** [comment]
Improvements here would be a big help for my team, where this is an obstacle to composing Cursive with other tools we use.

Also would welcome any feedback on the new 1.10 facilities, if they need additional enhancement.

Thanks!

**Comment by cursive-ide** [comment]
@puredanger Just checking - should the file key in the metadata be `:clojure.core/eval-file`? In [CLJ-1079](https://dev.clojure.org/jira/browse/CLJ-1079) it seems to just reference `:file`, and that was the example you had sent to me previously over Slack too. Also, are `:line` and `:column` 0 or 1 based (I assume 1, just checking).

**Comment by cursive-ide** [comment]
Oh, also, in the example here it looks like the file name contains a local path component, whereas all the previous examples I've seen have just the file name.

**Comment by puredanger** [comment]
It should be `:clojure.core/eval-file` - there were several follow-ups after CLJ-1079. I believe they are 1-based.

**Comment by cursive-ide** [comment]
Ok, thanks. And should there be a path component passed in the file value, or just the file name?

**Comment by puredanger** [comment]
A path like the example in the ticket description

**Comment by cursive-ide** [comment]
This is fixed. I'm not sure yet when the fix will be released, currently I'm waiting on some critical platform bugs in the IntelliJ 2019.2 EAP to be addressed, so this is sitting in a branch for the next major Cursive release, but it should hopefully be out before too long.

The expression in REPL is still somewhat hard to read, since the metadata appears there too:

![Screen Shot 2019-07-15 at 12 44 47](https://user-images.githubusercontent.com/5589171/61191397-c6618e00-a699-11e9-8d4d-8653ef0860fb.png)

This fix is controlled by a switch in the REPL run configuration. I thought about various types of magic I could use to do it automatically, but in the end I opted for doing this manually and just prompting the user if they're probably doing the wrong thing:

![Screen Shot 2019-07-14 at 16 25 03](https://user-images.githubusercontent.com/5589171/61191415-04f74880-a69a-11e9-9b9c-d6d0d3ae2051.png)

![Screen Shot 2019-07-14 at 16 24 19](https://user-images.githubusercontent.com/5589171/61191417-09bbfc80-a69a-11e9-83e6-10ca4575c134.png)

The default is to use metadata, i.e. for Clojure 1.10, since Clojure users tend to upgrade pretty quickly.

I may change this to use magic later as I make some upcoming changes to the REPL initialisation process.

**Comment by richhickey** [comment]
We can suppress that metadata printing on the REBL end, thanks!

**Comment by imrekoszo** [comment]
Hey Colin, now, that 2019.2.3 is out, when do you think this will be available in a dev build?

**Comment by Vitexus** [comment]
Cursive is still pushing some unneeded lines into Rebl. :crying_cat_face: 

![obrazek](https://user-images.githubusercontent.com/2621130/73194123-f818de80-412b-11ea-9228-1908df009908.png)

Please, is there any way how to mute/filter out this messages ?

**Comment by cursive-ide** [comment]
@vitexus How are you connecting to REBL, via nREPL?

**Comment by Vitexus** [comment]
cat ~/.clojure/deps.edn 
```
{:aliases

 {;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
  ;;
  ;;    REPL
  :cider
             {:extra-deps {nrepl             {:mvn/version "0.6.0"}
                           cider/cider-nrepl {:mvn/version "0.22.0-beta11"}}}

  :piggieback
             {:extra-deps {cider/piggieback {:mvn/version "0.4.1"}}}


  :cider-22  {:extra-deps {org.clojure/clojure {:mvn/version "1.10.1"}
                           cider/cider-nrepl   {:mvn/version "0.22.1"}}
              :main-opts  ["-m" "nrepl.cmdline" "--middleware" "[cider.nrepl/cider-middleware]"]}

 :rebl-11
 {:extra-deps {rickmoynihan/nrebl.middleware {:mvn/version "0.2.0"}
               org.clojure/core.async      {:mvn/version "0.4.490"}
               ;; deps for file datafication (0.9.149 or later)
               org.clojure/data.csv        {:mvn/version "0.1.4"}
               org.clojure/data.json       {:mvn/version "0.2.3"}
               org.yaml/snakeyaml          {:mvn/version "1.23"}
               com.cognitect/rebl          {:local/root "/opt/REBL-0.9.220/REBL-0.9.220.jar"}
               org.openjfx/javafx-fxml     {:mvn/version "11.0.1"}
               org.openjfx/javafx-controls {:mvn/version "11.0.1"}
               org.openjfx/javafx-graphics {:mvn/version "11.0.1"}
               org.openjfx/javafx-media    {:mvn/version "11.0.1"}
               org.openjfx/javafx-swing    {:mvn/version "11.0.1"}
               org.openjfx/javafx-base     {:mvn/version "11.0.1"}
               org.openjfx/javafx-web      {:mvn/version "11.0.1"}}}

  }
 }

```

**Comment by ertugrulcetin** [comment]
@cursive-ide getting same unneeded lines like @Vitexus get

**Comment by imrekoszo** [comment]
@Vitexus @ertugrulcetin it is `nrebl.middleware` forwarding those commands. I use it from my fork which pulls in some editor-aware fixes to suppress some of these: https://github.com/RickMoynihan/nrebl.middleware/compare/master...imrekoszo:editors
