### ISSUE TITLE
Improve run options

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#212]
- [ ] Don't allow JVM args to be set for Leiningen run configs
- [ ] Add a way to run uberjar apps
- [ ] Remove "Run in REPL" checkbox from Clojure Script
- [ ] Add a flag to run `main` functions in Clojure Script
- [x] Allow specifying profiles for lein run configs

**Comment by alexanderkiel** [comment]
Are there any new on run configs with special leiningen profiles?

**Comment by cursiveclojure** [comment]
Yes, I'm planning to get to this soon.

**Comment by cursiveclojure** [comment]
Run configs with lein profiles are supported as of 0.1.64.

**Comment by cursive-ide** [comment]
I'm going to close this issue since all tasks are either obsolete or slated to be fixed in other issues.
