### ISSUE TITLE
Test result / diff not showing 

### ISSUE THREAD

**Issue by d-t-w** [cursive-ide/cursive#2123]
Clojure: 1.10

Cursive:
Built on: 2019-02-20 14:17
Built from: 1.8.1-eap3-5-g1263cdf

Project is a mixture of clj, cljs, cljc, not sure if that matters.

This regression is very recent (I only noticed it last night when I rebooted Intellij after a few days, and also noticed Cursive uses nRepl now).

When the expected / result in a test is over a certain size there is no marker shown for test result, and no diff available in the case of failed tests. Finally, some output is written to the REPL, e.g.

```bash
Testing operativ.ui.chart.data-test
0000 41] [1547004420000 48] [1547004480000 40] [1547004540000 45] [1547004600000 49] [1547004660000 45] [1547004720000 48]], :linkedTo \":previous\", :name \"p99\", :type \"spline\", :zIndex 3}]} (data/range [[1547004300000 0 65 23 38 49] [1547004360000 4 53 22 36 41] [1547004420000 10 80 22 26 48] [1547004480000 1 82 22 24 40] [1547004540000 8 47 23 35 45] [1547004600000 3 63 22 34 49] [1547004660000 2 48 21 24 45] [1547004720000 1 67 23 34 48]] true))", :message nil}1547004480000 1987]], \"broker-4\" [[1547004300000 1386] [1547004360000 1347] [1547004420000 1343] [1547004480000 1363]]}))", :message nil}
Ran 2 tests containing 9 assertions.
```

There is no prn statement anywhere in the code, that is coming from the test runner.

Screenshots follow of four cases, each case is the editor pane post-test run (and other tests in the same ns showing marker / diff as expected):

1. Test passes, output muted

![image](https://user-images.githubusercontent.com/2832467/53378099-8df63780-39b8-11e9-88c4-4be9a5a9213f.png)

2. Test fails, output muted

![image](https://user-images.githubusercontent.com/2832467/53378141-afefba00-39b8-11e9-998e-cf4085d23136.png)

3. Test passes, output fine (all I have done is reduce the size of both expected and result)

![image](https://user-images.githubusercontent.com/2832467/53378179-c72ea780-39b8-11e9-80bf-d028bb3632eb.png)

4. Test fails, output fine (same as [3] but failing test)

![image](https://user-images.githubusercontent.com/2832467/53378202-db72a480-39b8-11e9-993b-86db3a5a87a9.png)

Test follows:

```clojure
  (is (= {:min    1343
          :max    2892
          :mean   (/ (+ 1698 1697 1656 1692 2869 2858 2869 2892 2003 2040 2027 1987 1386 1347 1343 1363) 16)
          :final  7934
          :series [{:name "broker-1" :data [[1547004300000 1698] [1547004360000 1697] [1547004420000 1656] [1547004480000 1692]]}
                   {:name "broker-2" :data [[1547004300000 2869] [1547004360000 2858] [1547004420000 2869] [1547004480000 2892]]}
                   {:name "broker-3" :data [[1547004300000 2003] [1547004360000 2040] [1547004420000 2027] [1547004480000 1987]]}
                   {:name "broker-4" :data [[1547004300000 1386] [1547004360000 1347] [1547004420000 1343] [1547004480000 1363]]}]}
         {:min    1343
          :max    2892
          :mean   (/ (+ 1698 1697 1656 1692 2869 2858 2869 2892 2003 2040 2027 1987 1386 1347 1343 1363) 16)
          :final  7934
          :series [{:name "broker-1" :data [[1547004300000 1698] [1547004360000 1697] [1547004420000 1656] [1547004480000 1692]]}
                   {:name "broker-2" :data [[1547004300000 2869] [1547004360000 2858] [1547004420000 2869] [1547004480000 2892]]}
                   {:name "broker-3" :data [[1547004300000 2003] [1547004360000 2040] [1547004420000 2027] [1547004480000 1987]]}
                   {:name "broker-4" :data [[1547004300000 1386] [1547004360000 1347] [1547004420000 1343] [1547004480000 1363]]}]})))
```

**Comment by d-t-w** [comment]
Anyone else experiencing this? It's killing my productivity.

**Comment by voj** [comment]
I've got this too. When the asserted result is too large, it's printed partially on the repl, and no result markers are drawn, no diff is available.

But not everybody in the company has these problems. We haven't figured out why this happens to me but not others.

**Comment by voj** [comment]
Downgrading to `v1.8.0-2018.3` did indeed fix this problem for me.

**Comment by d-t-w** [comment]
Thanks @voj, I'm on the EAP as well so perhaps that it and it'll get wrapped up in a stable release.

**Comment by jsbed** [comment]
+1 It's been happening to me as well. Doesn't seem to be related to Clojure's version.

**Comment by MattVane** [comment]
+1 its definitely the version of cursive (and is present in the 1.8.2 EAP), but I'm on IDEA 2019.1, so no downgrade available without taking everything back a version.... :(
It seems to be **any** test with a lot of output causes some sort of overflow into the REPL, which then means cursive can't parse the output and display test status in the gutter,

I'm using test-refresh with the :test-refresh/focus selector for now, but its nowhere near as good... Please please fix!

**Comment by neuromantik33** [comment]
+1 So annoying. Can't downgrade either since I'm running 2019.1 as well

**Comment by cursive-ide** [comment]
My apologies for the delay with this - this is fixed for the next build.

This code actually  hasn't changed in Cursive for a long time. My theory is that upgrading Cursive caused a new version of lein to be used, which caused a new version of nREPL to be used, and due to nREPL's new streaming output this caused some messages to be partially sent when large, whereas previously they were completely sent.

I'll try to get this out ASAP, I know this has been annoying.

**Comment by d-t-w** [comment]
Thanks Colin! If it helps in any way I did notice that the version of nREPL being used by Cursive did bump up to 4.0 before the Cursive release that specifically included that upgrade. So sounds like you might be on the right track.

**Comment by cursive-ide** [comment]
It also depends on how you're running your project. If you're using lein, then the version of nREPL is the one that lein uses. But coincidentally, recent versions of Clojure also started using recent versions of Leiningen (mostly because of all the churn in the tooling world because of the nREPL split), and since the most recent version of lein is the one used by default, a side effect of upgrading Cursive will also be upgrading nREPL.
