### ISSUE TITLE
"Import Project from deps" - fails on Windows

### ISSUE THREAD

**Issue by thheller** [cursive-ide/cursive#2126]
I'm trying to create a "New Project from Existing Sources" by importing a `deps.edn` file. This never works as I can't seem to get `tools.deps` installed. It always complains about "Press Refresh to see available tools.deps versions." although I have done that. Doesn't matter which version I select or if I press "Download" or not. The Download seems to succeed but doesn't change the outcome.

One suspicious issue is the "Path to user deps.edn" since it seems to use `/` when it shouldn't.

```
C:\Users\thheller/.clojure/deps.edn
```

![cursive-error-deps](https://user-images.githubusercontent.com/144930/53561426-27575200-3b4f-11e9-950a-d3442c2f20ab.jpg)

Using Cursive `v1.8.1-eap3-2018.3` with `IntelliJ CE 2018.3.5`. (Also tried with older version before updating, forgot which Cursive version but probably latest for `IntelliJ CE 2018.1`)

**Comment by cursive-ide** [comment]
This is #2117 - the workaround is to configure deps first and then import, as described in that ticket. Unfortunately this is proving surprisingly tricky to fix, I'm waiting on feedback from JetBrains.

**Comment by thheller** [comment]
Confirmed. It works when done as #2117 describes. Thanks.
