### ISSUE TITLE
Trigger Visual Diff from REPL

### ISSUE THREAD

**Issue by d-t-w** [cursive-ide/cursive#2128]
More a feature request than a bug.

Would it be possible to support triggering of the visual diff (displayed on error failures in the editor pane) from the REPL? Sometimes I want to diff data, and that visual diff is really neat.

**Comment by cursive-ide** [comment]
Yes, this is something I'm planning - it's a little tricky because the server end has to pass requests to the client which is not a concept that I have at the moment. But it's definitely something I want to do.

**Comment by d-t-w** [comment]
Santa, is that you? I will be unreasonably excited about this one. :)

**Comment by cursive-ide** [comment]
Ho Ho Ho!

🎄 🎁
