### ISSUE TITLE
Highlighting in comment forms

### ISSUE THREAD

**Issue by tuh8888** [cursive-ide/cursive#2130]
Great IDE! It's really made learning Clojure easy and often fun. 

Anyway, it would be nice to still have inspections and highlighting inside `(comment)` forms, or at least have an option to toggle it on and off. I often have to uncomment the block to check if anything looks weird. Of course, you don't want things defined inside the comment to be resolved outside of the comment, so I'm not sure how difficult it would be to keep them separate.

**Comment by cursive-ide** [comment]
Thanks for the kind words!

So this used to work as you request, but in the end it was more annoying than useful. It's very common to have snippets of work in progress or even just broken code there, or things like a series of commands to be executed at the REPL which don't make sense in the context of a file. I haven't found a good way to handle that, so for the moment it's disabled entirely.
