### ISSUE TITLE
"Move caret to matching brace" misses closing brace

### ISSUE THREAD

**Issue by sooheon** [cursive-ide/cursive#2143]
Seemingly after the v1.8.1-2019.1 update, I'm seeing the matching brace behavior be off by one.

expected:
``` 
|(foo bar)
->
(foo bar)|
```

actual:
``` 
|(foo bar)
->
(foo bar|)
```

**Comment by metametadata** [comment]
Also when moving caret around it incorrectly highlights the matching braces:

<img width="113" alt="Screenshot 2019-03-30 02 39 55" src="https://user-images.githubusercontent.com/4689913/55268724-2bcd7280-5295-11e9-9ec4-65c9b6fb898e.png">

**Comment by d-t-w** [comment]
Think I'm here to submit a variant of the same, I'm certain that the caret position now highlights a different sexp (favours outer/right where it was previously inner/left)

Similar experience, changed after update to 2019.1

e.g. new behaviour showing highlight and caret position

![image](https://user-images.githubusercontent.com/2832467/55399548-1f982c80-5597-11e9-8d67-cff56082f55b.png)

**Comment by cursive-ide** [comment]
Yes, I believe this is a bug introduced in IntelliJ 2019.1, as part of [RUBY-23203](https://youtrack.jetbrains.com/issue/RUBY-23203). The relevant issue is [IDEA-210104](https://youtrack.jetbrains.com/issue/IDEA-210104). 

I'm going to close this one, but please feel free to vote over on YouTrack.
