### ISSUE TITLE
Form highliting broken?

### ISSUE THREAD

**Issue by juskrey** [cursive-ide/cursive#2151]
Cursive v1.8.1-2019.1
Placing cursor after the closing bracket of non-top form highlights opening bracket of parent form.
If the form is a top ns form, everything is ok
Gif:
![cur](https://user-images.githubusercontent.com/3420759/55782194-6ebcf080-5ab4-11e9-8f53-a04b92b6d817.gif)

**Comment by cursive-ide** [comment]
This is [IDEA-210104](https://youtrack.jetbrains.com/issue/IDEA-210104), an IntelliJ bug in 2019.1. Please vote for it!
