### ISSUE TITLE
deps.edn with metadata does not import

### ISSUE THREAD

**Issue by danieroux** [cursive-ide/cursive#2155]
Opening this deps.edn as a project:

```clojure
{:deps {^:depot/ignore org.clojure/clojure {:mvn/version "1.10.1-beta2"}}}
```

Fails with:

<img width="398" alt="Screenshot 2019-04-17 at 10 52 12" src="https://user-images.githubusercontent.com/13940/56274545-33976e80-60ff-11e9-8857-fad8fb0374eb.png">

For background, this metadata is for https://github.com/Olical/depot

**Comment by voj** [comment]
That's not actually legal EDN https://github.com/edn-format/edn

**Comment by cursive-ide** [comment]
While I think that's true according to the spec, it does seem to work:
```
Clojure 1.7.0
(clojure.edn/read-string "{:deps {^:depot/ignore org.clojure/clojure {:mvn/version \"1.10.1-beta2\"}}}")
=> {:deps {org.clojure/clojure {:mvn/version "1.10.1-beta2"}}}
```
