### ISSUE TITLE
Intellij Dependency resolution error

### ISSUE THREAD

**Issue by superPershing** [cursive-ide/cursive#2166]
I install the Cursive plugin in IntelliJ:
```
IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-48-generic
```
And install leiningen in my Ubuntu 16.04.6 LTS 64-bit.  

When I init an Clojure app with leiningen `lein new app my-stuff`, then use IntelliJ open this app; or use intellij new Clojure app with leiningen option, event log always show:
```
Dependency resolution error
Error synchronising my-stuff:0.1.0-SNAPSHOT:
Failed to collect dependencies at nrepl:nrepl:jar:0.6.0
```
How to solve this problem?

**Comment by enthusiast17** [comment]
Hey @superPershing , how did you solve it this issue?

**Comment by superPershing** [comment]
> Hey @superPershing , how did you solve it this issue?

Maybe the network error, I didn't use Ubuntu as my Desktop for a long time now.
