### ISSUE TITLE
ns cannot be resolved

### ISSUE THREAD

**Issue by guv** [cursive-ide/cursive#2169]
With Cursive 1.8.2-eap2-2019.1, Cursive reports: "ns cannot be resolved" as well as "defn cannot be resolved".
This happens in existing and new (leiningen) projects. I have never seen this issue before.

**Comment by cursive-ide** [comment]
There's an issue at the moment on 2019.1, IntelliJ's underlying indexes appear to have changed in ways which provoke this problem in Cursive. It's currently being tracked in [IDEA-211736](https://youtrack.jetbrains.com/issue/IDEA-211736).

**Comment by guv** [comment]
Good to know. So, as a quickfix I'll have to downgrade IntelliJ.
Has there been information about this problem on the Cursive mailing list?

**Comment by guv** [comment]
With the update to IntelliJ 2019.1.2, Cursive is working again.

**Comment by n2o** [comment]
I am still having this issue with Cursive v1.8.2-eap4-2019.1 and IntelliJ 2019.1.2 (built on 7th May 2019).

Downgrading to Clojure 1.9.0 solves the problem. This seems only to occur with Clojure 1.10.0.

**Comment by cursive-ide** [comment]
@n2o This doesn't have anything to do with the Clojure version, it's just sporadic. The current investigation suggests that it's a platform bug in IntelliJ 2019.1.

This is also being tracked in #2173 so I'll close this one and discussion should go over there.
