### ISSUE TITLE
Pasting and converting HTML to Hiccup loses contents of <style> and <script> tags

### ISSUE THREAD

**Issue by jffry** [cursive-ide/cursive#2171]
Follow-on to https://github.com/cursive-ide/cursive/issues/2154: Pasting HTML and converting it to Hiccup doesn't correctly convert `<script>` or `<style>` tags that contain inline contents.

Paste this HTML into a Clojure file:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Sparkfund Email</title>
  <style type="text/css">.example { color: red; }</style>
  <script type="text/javascript">alert('hello?');</script>
</head>
<body>
  <p>The content of the style and script tags is dropped.</p>
  <style type="text/css">.example { color: red; }</style>
  <script type="text/javascript">alert('hello?');</script>
  <pre>
    What about the humble pre tag?
    which can have text on multiple lines?
  </pre>
  <textarea>And textareas?</textarea>
  <foo>Or custom tags?</foo>
</body>
</html>
```

Accept the option to convert to Hiccup:

![image](https://user-images.githubusercontent.com/602773/57456376-62ef5600-723b-11e9-8a42-02c2ff451406.png)

The resulting Hiccup is incorrect because it has lost the contents of the `<script>` and `<style>` tags:

```clj
[:html {:lang "en"}
 [:head
  [:meta {:charset "UTF-8"}]
  [:title "Sparkfund Email"]
  [:style {:type "text/css"}]
  [:script {:type "text/javascript"}]]
 [:body
  [:p "The content of the style and script tags is dropped."]
  [:style {:type "text/css"}]
  [:script {:type "text/javascript"}]
  [:pre "What about the humble pre tag?
    which can have text on multiple lines?"]
  [:textarea "And textareas?"]
  [:foo "Or custom tags?"]]]
```

This also happens in the case of isolated fragments, e.g.

```html
<script>
alert("test");
</script>
```

converts to just `[:script]`.

This is in Cursive v1.8.2-eap2-2018.3 and IDEA Ultimate 2018.3.6.

**Comment by jffry** [comment]
I'm also unsure whether or not it's a problem that the leading whitespace on the first line of the `<pre>` tag got trimmed

**Comment by cursive-ide** [comment]
Thanks for the report - I suspect this is because those fragments are embedded languages. I'll check what I need to do to fix this. I wonder about the `pre` tag too, I'll think about that.

**Comment by cursive-ide** [comment]
This is fixed for the next build, including a fix so that `pre` maintains its whitespace:
```clojure
[:html {:lang "en"}
 [:head
  [:meta {:charset "UTF-8"}]
  [:title "Sparkfund Email"]
  [:style {:type "text/css"} ".example { color: red; }"]
  [:script {:type "text/javascript"} "alert('hello?');"]]
 [:body
  [:p "The content of the style and script tags is dropped."]
  [:style {:type "text/css"} ".example { color: red; }"]
  [:script {:type "text/javascript"} "alert('hello?');"]
  [:pre "
    What about the humble pre tag?
    which can have text on multiple lines?
  "]
  [:textarea "And textareas?"]
  [:foo "Or custom tags?"]]]
```
