### ISSUE TITLE
Dependency completion doesn't always work

### ISSUE THREAD

**Issue by conan** [cursive-ide/cursive#2179]
I love the autocomplete functionality in my `deps.edn` which saves me from going to each dep's website and checking what the latest version is, it's a huge time-saver.  Quite frequently however it doesn't work, when I press `ctrl+space`:

![image](https://user-images.githubusercontent.com/3037019/58173990-b5e1f800-7c94-11e9-9b39-6966de7a4abb.png)

![image](https://user-images.githubusercontent.com/3037019/58174034-d7db7a80-7c94-11e9-9e00-338095d269ee.png)

I don't have any repositories in my *Build, Execution, Deployment* > *Build Tools* > *Maven* > *Repositories*, but I also don't know how to add them in either.

Is there a way to add repositories, or is there some other useful info I could add to help debug?  I realise this isn't a useful reproduction.

**Comment by cursive-ide** [comment]
They should be added when your project is refreshed. If you go to the Clojure Deps toolwindow and manually refresh your project, do they appear then?

**Comment by conan** [comment]
They don't appear from a refresh in the tools.deps window, but they do seem to for an intellij restart, so i guess this isn't a big problem.

**Comment by conan** [comment]
I can confirm that refreshing the clojure-deps tool window doesn't add the remote repositories in _Build, Execution, Deployment > Build Tools > Maven > Repositories_, and restarting doesn't either.  Sometimes they appear in there, but I don't know what makes that happen.  Happy to provide any extra info that might help?

**Comment by conan** [comment]
I have to keep an empty `project.clj` at the root of my repo for Heroku support, I wonder whether that interferes with the repositories

**Comment by cursive-ide** [comment]
@conan The latest EAP (1.9.0-eap8) contains some fixes to the dependency completion and repository support. If you get a chance, could you try that? If you're not running EAPs, I'm hoping that will be in a stable release within a week or so.

**Comment by conan** [comment]
I'm working with leiningen again and don't know when I'll be back in deps land.  I spun up my previous deps project to see if there was an issue and it all seems to be working with 1.9.0-eap8, so I'll close this issue assuming it's fixed.  Thanks!
