### ISSUE TITLE
Cursive not able to resolve anything

### ISSUE THREAD

**Issue by ashwinbhaskar** [cursive-ide/cursive#2181]
I have a similar issue as this - https://github.com/cursive-ide/cursive/issues/448

Cursive is not able to resolve anything. I tried invalidate & restart. I am not able to find the option `Add as Leiningen Project`. I guess that is because it is already a leiningen project.
Please help! (I am not using any JS)

Some additional information :
`lein deps` works without any issue
`lein run` works without anyissue

<img width="955" alt="Screenshot 2019-05-26 at 9 40 08 AM" src="https://user-images.githubusercontent.com/6818365/58377282-5d637100-7f9a-11e9-97d3-918b160fec80.png">
<img width="955" alt="Screenshot 2019-05-26 at 9 39 54 AM" src="https://user-images.githubusercontent.com/6818365/58377283-5d637100-7f9a-11e9-8278-552154733863.png">
<img width="955" alt="Screenshot 2019-05-26 at 9 39 31 AM" src="https://user-images.githubusercontent.com/6818365/58377284-5d637100-7f9a-11e9-811d-93d461e5a685.png">

**Comment by cursive-ide** [comment]
Yes, this is probably #2173. The best solution right now is to restart when it happens, sorry :(.
