### ISSUE TITLE
Stable sort of dependencies in .iml files

### ISSUE THREAD

**Issue by danieroux** [cursive-ide/cursive#2182]
Our module.iml file changes for no reason:

![image](https://user-images.githubusercontent.com/13940/58406544-22c90980-806a-11e9-8712-1b9698a0351c.png)

It's a small issue, of course.

**Comment by hanswesterbeek** [comment]
Keep your .iml files to yourself, I always say :) Don't put them in git, ignore them.

**Comment by cursive-ide** [comment]
Unfortunately there's nothing I can do about this, that's just how IntelliJ does it. I also agree that they generally don't have to be in version control, assuming they're mirroring what you have in lein/deps/whatever.
