### ISSUE TITLE
Impossible to set the starting namespace for REPL

### ISSUE THREAD

**Issue by p-himik** [cursive-ide/cursive#2187]
Cursive v1.8.2-eap4-2019.1.

I have this function in the `user` namespace:
```
(defn setup-cursive-repl []
  ;; This is mainly to circumvent https://github.com/cursive-ide/cursive/issues/2186
  ;; This function makes it possible to provide `-e (setup-cursive-repl)`
  ;; to the REPL run configuration.
  (require 'dev)
  (in-ns 'dev)
  nil)
```

To use that, I provide `-e (setup-cursive-repl)` in the "Parameters" input field of the REPL run configuration.
And when I try to run it:

```
Connecting to local nREPL server...
Clojure 1.10.0
nREPL server started on port 34249 on host 127.0.0.1
LOADED DEV ;; <- Actually comes from the `dev` namespace.
*ns*
=> #object[clojure.lang.Namespace 0xf186221 "user"]
```

**Comment by otwieracz** [comment]
And if you run `lein` from command line with this parameter it switches fine to `dev` namespace?

**Comment by p-himik** [comment]
@otwieracz I use `deps.edn`. And yes, it works:
```bash
$ clj -e "(dev)" -r
dev=> *ns*
#object[clojure.lang.Namespace 0x4fc28b23 "dev"]
```

**Comment by otwieracz** [comment]
And do you use `deps.edn` (and not `lein`) in Cursive?

**Comment by p-himik** [comment]
Good point, I use nREPL, and testing with `-m nrepl.cmdline` shows that it doesn't set the namespace as well.
I guess, a viable alternative would be to support making the client run arbitrary CLJ code upon nREPL connection. I'll create an issue if there isn't one already.
