### ISSUE TITLE
Exception lines are not correctly linked

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2199]
Reported by @kennyjwilli in Slack:

Cursive doesn't always correctly link line numbers in exceptions. For example, I'm in a project that contains `compute.db.formulas` namespace. The below exception highlights everything except the calls from that namespace. 

![Screenshot from 2019-07-01 17-23-44](https://user-images.githubusercontent.com/5589171/60637294-6b15dd00-9e09-11e9-853a-5857e3be7eb1.png)

It appears to have to do with the fact that the files are `.cljc` and not `.clj`.

**Comment by cursive-ide** [comment]
Another example:

![Screenshot from 2019-07-02 15-40-04](https://user-images.githubusercontent.com/5589171/60637894-c2b54800-9e0b-11e9-9967-97a70a431a4d.png)

**Comment by kennyjwilli** [comment]
Another example:

![Screenshot from 2019-08-09 16-18-05](https://user-images.githubusercontent.com/2453976/62815366-05ce9f00-bacd-11e9-832a-ac186173d089.png)
