### ISSUE TITLE
Update Cursive to use system deps.edn from t.d.a when available

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2200]
From @puredanger in Slack:

> The install deps.edn is now included in tools.deps as a resource. The new functions in `tools.deps.alpha.reader` should avoid needing to shell out for anything. In particular, there are new functions there that replicate what `clj` does to find all of the `clj` files.

**Comment by sooheon** [comment]
Very cool, this means for example you can add REBL config (https://github.com/cognitect-labs/REBL-distro/wiki/REBL-in-IntelliJ-Cursive) in your system deps.edn so you don't have to replicate that config for every project.
