### ISSUE TITLE
Allow switching REPL editor to plain text

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2206]
In IntelliJ, editors are strongly typed. The editor panel for the REPL is a Clojure editor, which is required for functionality like autocomplete and proper syntax highlighting. However when using a streaming REPL such as a socket REPL or clojure.main, when the server application reads from the input stream sometimes it is required to send values which are not valid Clojure. It should be possible to swap the editor for a text one so that Cursive won't complain about this while editing.

**Comment by sooheon** [comment]
Is there a streaming editor integration for Cursive I don't know about? Do you mean just starting a socket repl elsewhere and connecting as a remote repl?

**Comment by sooheon** [comment]
I read further in release notes, seems like Cursive can be configured to start a REBL backed repl, and this is to support uses like that (https://github.com/cursive-ide/cursive/issues/2113)

**Comment by cursive-ide** [comment]
@sooheon The new EAP (1.9.0-eap2) has support for remote socket REPL connections, yes. This is described in the [release email](https://groups.google.com/d/topic/cursive/_FsXPnhqpO4/discussion). It's not fully streaming as described there, but does allow you to switch to sending plain text when required.

**Comment by cursive-ide** [comment]
BTW I haven't tried these with REBL yet. It may not work well because of the structured nature of the socket REPL support in Cursive (similar to prepl).
