### ISSUE TITLE
Highlight Matching Paren Question

### ISSUE THREAD

**Issue by shaunparker** [cursive-ide/cursive#2210]
Paren highlighting seems to be matching the wrong opening paren when multiple ending parens are not separated by whitespace. The current functionality doesn't match the functionality of "Edit" > "Extend Selection" and "Navigate" > "Structural Movement" > "Move Forward" / "Move Backward". Here's an example:

### Works correctly when end paren _is not_ followed by another

<img width="233" alt="Screen Shot 2019-07-25 at 1 28 49 PM" src="https://user-images.githubusercontent.com/195140/61903132-09650200-aee1-11e9-88d8-2d8586b4f8c9.png">

The end paren correctly matches to the start of the function definition. Running "Extend Selection" correctly selects the entire function:

<img width="293" alt="Screen Shot 2019-07-25 at 1 29 14 PM" src="https://user-images.githubusercontent.com/195140/61903244-49c48000-aee1-11e9-8505-490c0e8a9a47.png">

### Works incorrectly when end paren is directly followed by another

<img width="262" alt="Screen Shot 2019-07-25 at 1 29 30 PM" src="https://user-images.githubusercontent.com/195140/61903354-88f2d100-aee1-11e9-84b0-d12c4f06a1a8.png">

I believe this should be showing `(let [a 42]...` as the matching paren, but instead it shows `(defn example-fn...` instead. Running "Extend Selection" selects the `(let [a 42]...` expression:

<img width="318" alt="Screen Shot 2019-07-25 at 1 29 43 PM" src="https://user-images.githubusercontent.com/195140/61903456-c6eff500-aee1-11e9-8200-288dd75ff0b2.png">

### Works correctly when whitespace is between end parens

From the previous example, introducing whitespace between the parens fixes the issue:

<img width="249" alt="Screen Shot 2019-07-25 at 1 55 29 PM" src="https://user-images.githubusercontent.com/195140/61904349-e556f000-aee3-11e9-8772-e36669b3f55e.png">

<img width="252" alt="Screen Shot 2019-07-25 at 1 31 38 PM" src="https://user-images.githubusercontent.com/195140/61903541-f4d53980-aee1-11e9-90e9-d899b6c29469.png">

I feel like this was changed at some point as I started getting confused while moving nested expressions, but perhaps I'm imagining it. If it was changed, is there anyway to change it back so that the matching behaves the way it does in the last two examples even when there's no whitespace? My apologies if this is the way it's always functioned.

Thanks!

**Comment by cursive-ide** [comment]
Yes, this was broken in IntelliJ 2019.1 - the relevant issues are [IDEA-210104](https://youtrack.jetbrains.com/issue/IDEA-210104) (the original one about caret movement), and then the followup was [IDEA-211720](https://youtrack.jetbrains.com/issue/IDEA-211720) about the brace matching. It appears to be fixed in 2019.2 but that still has a bunch of other serious problems so I don't recommend upgrading yet. The most stable IntelliJ version to use right now is still 2018.3.

I'm going to close this since it's not a Cursive issue. Hopefully everything will be good again in 2019.2.1 in a week or two.
