### ISSUE TITLE
Support selecting the clojure CLI config directory

### ISSUE THREAD

**Issue by kennyjwilli** [cursive-ide/cursive#2212]
We have a monorepo and would like to be able to set the "user" deps.edn config file to provide aliases available to all subprojects (similar to described [here](https://clojureverse.org/t/clj-cli-tools-workflow/4026/2)). It seems the only way to be able to set a custom config location is via the `CLJ_CONFIG` environment variable. 

It looks like you're able to set the "user" deps.edn if you select "use tools.deps directly" in the Run Configurations popup. 

I'd really like to be able to set this value once for my monorepo project and have it apply to all modules as well.

**Comment by mitchelkuijpers** [comment]
@kennyjwilli Did you manage to find a solution for this? We are also in the process of setting up a monorepo and were looking at that suggestion of using CLJ_CONFIG to basically mimic `managed-deps`. But I am not sure how I can make cursive resolve the right deps...
