### ISSUE TITLE
Configuriable "Use Leiningen REPL port" Option for remote nREPL

### ISSUE THREAD

**Issue by thheller** [cursive-ide/cursive#2216]
Currently Cursive can be configured to use the Leiningen generated `.nrepl-port` file to figure out which port to connect to. It would be very useful for `shadow-cljs` if it was possible to configure which file Cursive used. `shadow-cljs` generates `.shadow-cljs/nrepl.port` to avoid conflicting with `.nrepl-port` by default. Unfortunately there is no way to tell Cursive to use that file.

Maybe just a simple text input to configure the file path which defaults to `.nrepl-port`. Something generic that isn't tied to any particular tool would be nice.

**Comment by cursive-ide** [comment]
Yes, this is a good idea. I have some ongoing REPL work happening, I'll add this to that.

**Comment by thheller** [comment]
Any timeframe for this? Configuring a fixed nrepl port is still a major annoyance and I can't use `.nrepl-port` because `lein` uses that and I don't want to fight over that file.

**Comment by cursive-ide** [comment]
Sorry for the delay with this. This is fixed for the next EAP. Users can now select between "Default", which uses a fixed list of common port files, and specifying a custom file. `.shadow-cljs/nrepl.port` is now also in the default list, so most users shouldn't have to touch anything unless they're customising something.

**Comment by thheller** [comment]
Wohoo! Thanks.

**Comment by seanpoulter** [comment]
I'll second that. Thank you Colin! 👏
