### ISSUE TITLE
Bug when opening a deps.edn file

### ISSUE THREAD

**Issue by infosec-studio** [cursive-ide/cursive#2221]
When opening a simple deps.edn I get an Resolve Error which is a NullPointerException.

Steps to reproduce:

1. [Use cli-new](https://github.com/seancorfield/clj-new) to create a new lib type project;
2. Open the generated deps.edn file with IntelliF/Cursive;
3. Get an error.

Screenshots and sample project attached.

[Project.zip](https://github.com/cursive-ide/cursive/files/3525345/Project.zip)
[Screenshots.zip](https://github.com/cursive-ide/cursive/files/3525346/Screenshots.zip)

**Comment by cursive-ide** [comment]
Yes, this is reported and discussed over at #2209.
