### ISSUE TITLE
"Show usages" dialog not appearing for namespaced keywords

### ISSUE THREAD

**Issue by JoelSanchez** [cursive-ide/cursive#2233]
This dialog:

![image](https://user-images.githubusercontent.com/8020017/64860179-a6643180-d62c-11e9-8443-cb55e9d5ba0d.png)

Used to work for namespaced keywords, the same way it works for vars and local symbols.

Now, cmd-click does nothing, even though the list of usages can still be shown by using "Edit -> Find -> Show usages".

**Comment by keithharper** [comment]
Just updated to the latest version of Cursive and can confirm that this is still a valid issue. This is unfortunate because I used this feature heavily in my daily workflow, and am considering downgrading until this has been fixed.

**Comment by mustangJaro** [comment]
I completely agree with @keithharper on both accounts; it's still an issue and it's very disruptive to my workflow.
