### ISSUE TITLE
deps.edn project Resolve Error on "File->New->Project from Existing Sources"

### ISSUE THREAD

**Issue by theronic** [cursive-ide/cursive#2234]
When I try to turn a Clojure project into deps.edn project,

![image](https://user-images.githubusercontent.com/1011676/64906165-19c87a80-d6e3-11e9-9bb1-6723963bf2c3.png)

I get the following error:

![image](https://user-images.githubusercontent.com/1011676/64906162-1208d600-d6e3-11e9-8cb7-eed8c9787e6a.png)

**Comment by cursive-ide** [comment]
This is an IntelliJ platform problem, [IDEA-220192](https://youtrack.jetbrains.com/issue/IDEA-220192). See [here](https://groups.google.com/d/topic/cursive/ntvsiLAehY0/discussion) for a discussion of all the recent deps problems. This should hopefully have been solved by the new deps integration, which will be released today in 1.9.0-eap1.
