### ISSUE TITLE
Support for 2019.3

### ISSUE THREAD

**Issue by JeroenvdV** [cursive-ide/cursive#2240]
My IDE has updated and now I can't find the plugin in the marketplace. Could this be because there is no version that supports this IDE version?

**Comment by cursive-ide** [comment]
Yes, I'm planning to release the next EAP with support for the 2019.3 EAP today or tomorrow.

**Comment by dheerajbhaskar** [comment]
Still can't find this in the marketplace as of today. Is it juss me or this not released yet?
