### ISSUE TITLE
Fulcro 3 Code Motion

### ISSUE THREAD

**Issue by awkay** [cursive-ide/cursive#2241]
Fulcro 3 renamed pretty much everything. The macros look the same, so this is just a list of what they were, and what they are in F3:

| Old                                                                | New                                  | Notes  |
|-------------------------------|---------------------------------------|---|
|fulcro.client.mutations/defmutation | com.fulcrologic.fulcro.mutations/defmutation | |
|N/A | com.fulcrologic.fulcro.mutations/declare-mutation | Acts like `def` (not declare) |
|N/A | com.fulcrologic.fulcro.ui-state-machines/defstatemachine | Acts like `def` |
|fulcro.client.primitives/defsc | com.fulcrologic.fulcro.components/defsc | |
| N/A | com.fulcrologic.fulcro.routing.legacy-ui-routers/defsc-router | Same syntax as `defsc` |
| N/A  | com.fulcrologic.fulcro.routing.dynamic-routing/defrouter | Same syntax as `defsc`|

My code also now uses ghostwheel, so if you felt like adding these to your list (if they aren't there), it would help users to not have unresolved syms:

`ghostwheel.core/>defn` and `ghostwheel.core/>defn-`.  They resolve as `defn` and `defn-` as you might expect.

**Comment by cursive-ide** [comment]
Ok, I've added that support. There are some other forms which had support previously, have they been moved too, or are they now obsolete?
* `fulcro.client.primitives/defui`
* `fulcro.server/defquery-root`
* `fulcro.server/defquery-entity`

**Comment by awkay** [comment]
Those are all three gone in F3, but still in F2.

thanks!
