### ISSUE TITLE
No default Clojure platform for creating test namespace via New -> Clojure Namespace

### ISSUE THREAD

**Issue by jsyrjala** [cursive-ide/cursive#2249]
Cursive doesn't have default Clojure platform selected (Clojure Test, ClojureScript Test, CLJC Test) when doing New -> Clojure Namespace under `/test` directory.
It has default value Clojure Test, when doing the same thing under /src directory.

Now what often happens is:
- New -> Clojure Namespace under `/test` directory
- Type name for the test class to dialog
- Hit enter (no Clojure platform is selected)
- Dialog disappears
- Wondering for a moment why no namespace appears, then redo above steps but select Clojure platform this time.

I have a Leiningen project in Cursive 1.9.0-eap4-2019.2 on MacOS. I vaguely remember that this might have worked in previous versions.

**Comment by cursive-ide** [comment]
Yes, I think this is new. It's fixed for the next build, thanks!
