### ISSUE TITLE
Dependency completion no longer works

### ISSUE THREAD

**Issue by tuh8888** [cursive-ide/cursive#2255]
Dependency completion doesn't work. When typing a dependency I used to be able to type ctrl + space and get suggestions from clojars or maven and a list of versions when typing in the version. I can see that both of those repositories have been indexed in the repositories section under the maven settings. This was a great feature and saved me a lot of time looking for packages to add.

IntelliJ Version: 2019.3 EAP
Cursive Version: 1.9.0-eap6-2019.3
OS: Ubuntu 19.10

**Comment by conan** [comment]
I also have this problem.  Maven central is never indexed on my machine for some reason, but I can no longer get suggestions from clojars, which is.

**Comment by cursive-ide** [comment]
I've spent a bunch of time investigating this in the last couple of days, and I believe this is a platform issue in 2019.2 and 2019.3. [IDEA-225412](https://youtrack.jetbrains.com/issue/IDEA-225412) has all the gory details including @conan's issue - Maven Central is explicitly removed from the indexing in 2019.2. I have no idea why, there must be something I'm misunderstanding there.
