### ISSUE TITLE
Synchronizing a project in cursive 0.1.12 takes forever

### ISSUE THREAD

**Issue by theleoborges** [cursive-ide/cursive#226]
I'm using cursive version 0.1.12 with intelliJ 13 on Linux.

Prior to this version everything was working fine however now any time I synchronize a leiningen project, it takes forever to finish - something like 10 minutes.

Not a clue about what's going on. Any log files I could send you to help track the issue?

Tks

**Comment by tejasjadhav** [comment]
Running `lein deps` in the terminal first and then reopening the project in IDE fixed it for me.
