### ISSUE TITLE
Add support for :paths and `:deps` in tools-deps aliases

### ISSUE THREAD

**Issue by vlaaad** [cursive-ide/cursive#2262]
Since [version 1.10.1.478](https://www.reddit.com/r/Clojure/comments/dl2hl7/ann_toolsdepsalpha_08578_clj_1101478/), tools-deps allow setting `:paths` and `:deps` keys in aliases to override project-level aliases.

Latest version of cursive (1.9.0-eap8-2019.2) shows error dialog with message "Unknown alias key: :paths". It should allow such aliases.

**Comment by cursive-ide** [comment]
That message is actually coming from deps itself, and indicates that it doesn't understand those alias keys. What I think this means is that you're using a version of deps prior to 1.10.1.478, or that Cursive is picking an older version up somehow. Could you check how deps is configured at _Preferences | Build, Execution, Deployment | Build Tools | Clojure Deps_?

**Comment by cursive-ide** [comment]
I've just reproduced this again, and indeed I got this error when Cursive was using an older version, and then the problem disappeared when I upgraded `clojure`. I'll close this now, feel free to re-open if you have reason to believe that Cursive is doing the wrong thing here.
