### ISSUE TITLE
Add all project files as Leiningen projects

### ISSUE THREAD

**Issue by metametadata** [cursive-ide/cursive#2269]
I have a monorepo with many `project.clj` files. Is there a way to add all of them at once instead of clicking each file individually (to "Add as Leiningen Project")?

**Comment by cursive-ide** [comment]
Yes, you can import them as described in [working with multi-module projects](https://cursive-ide.com/userguide/leiningen.html#working-with-multi-module-projects).

**Comment by metametadata** [comment]
Thank you!
