### ISSUE TITLE
Unwrap scope/list action

### ISSUE THREAD

**Issue by bubblefoil** [cursive-ide/cursive#2275]
IntelliJ has an `Unwrap/Remove...` action (Ctrl+Shift+Delete) for Java code, which unwraps scope around cursor (typically a `{}` block) from its surrounding scope. It also allows user to choose the scope level to unwrap.
Example:
```
//before
if (x != null){
  |x.doStuff();
}
//Ctrl+Shift+Delete
//after
|x.doStuff();
```

I could use similar functionality in Clojure to e.g. unwrap an argument from a function invocation. Thinking of code as a tree, it would basically replace the parent node with selected sub-tree.
The simplest example would be following:
```
;before
(* 5 (inc x|))
;Ctrl+Shift+Delete
;after
(inc x|)
```
I've tried to mimic this behavior with a macro, using `Select word` and cut/paste actions, but `Select word` has too fine granularity and the result is not always easy to predict.

_Note: I've heard there is a plugin for another IDE which allows creating custom functions for code manipulation and assign them to shortcuts. Does it exist for IntelliJ? I could not find it. It would solve this issue._

**Comment by cursive-ide** [comment]
See the section here: https://cursive-ide.com/userguide/paredit.html#editing-commands - Raise does what you want if you only want to unwrap a single form, or the various splice variants will do it for multiple forms.
