### ISSUE TITLE
Non-static inner classes fail to recognize constructor

### ISSUE THREAD

**Issue by tekacs** [cursive-ide/cursive#2277]
An example is probably illustrative. The following Java syntax (from [here](https://github.com/box/box-java-sdk/blob/e8d33cf79c958e95a9041a5ddad17ff7f506ffb7/doc/users.md#update-user)):

```java
BoxUser user = new BoxUser(api, "0");
BoxUser.Info info = user.new Info();
info.setName(name);
user.updateInfo(info);
```

Can be converted to the following Clojure:

```clojure
(let [user (BoxUser. api "0")
      info (BoxUser$Info. user)]
  (.updateInfo user (doto info (.setName name))))
```

The Clojure compiler is happy to compile and run this, but Cursive complains that it can't find the constructor for `(BoxUser$Info user)`.

<img width="432" alt="CleanShot 2019-11-25 at 10 55 00@2x" src="https://user-images.githubusercontent.com/63247/69569237-128adc00-0f72-11ea-89c6-31818be1cf08.png">

If I instead write `(BoxUser$Info.)` then 'Go to definition leads me to the constructor of the inner class:

```java
public Info() {
    super(BoxUser.this);
}
```

... but this isn't actually the corresponding constructor — the approach from above is the way to call this.

**Comment by cursive-ide** [comment]
I'll try to reproduce that - that should work, and I use that syntax myself internally in Cursive.

**Comment by cursive-ide** [comment]
You're correct - this is indeed a problem with non-static inner classes. All the examples I was using in Cursive were static inner classes. I've fixed this and various other cases that didn't work correctly (parameter info, constructor resolution etc).
