### ISSUE TITLE
Add support for console input

### ISSUE THREAD

**Issue by jhalterman** [cursive-ide/cursive#228]
It would be great if the Cursive REPL's output/console window supported input, for things such as `(read-line)`, in the same way that a REPL in a terminal does.

**Comment by saeidscorp** [comment]
Yes I need it so badly ;-)

With this feature I can completely rely on the repl without getting distracted by input situations.

**Comment by jhau** [comment]
any workaround or is this feature on the roadmap? it's so painful to use the terminal to run "lein repl" after using Cursive!

**Comment by mickey** [comment]
Or do you see any trickery to go around this issue?

**Comment by EmmanuelOga** [comment]
Hi, I'm using cursive 1.8.2 writing this simple function:

```clj
(defn take-guess []
  (println)
  (println "Enter a letter: ")
  (flush)
  (let [input (.readline *in*)
        line (clojure.string/trim input)]
    line)
```

Produces the following output:
```
Enter a letter: 
Execution error (IllegalArgumentException) at hangman.core/take-guess (core.clj:59).
No matching field found: readline for class clojure.lang.LineNumberingPushbackReader
```
This bug seems related but I'm not sure.

**Comment by EmmanuelOga** [comment]
I was about to report an issue when I realized I had a typo:
```clj
(let [input (.readline *in*)] input)
```
```
No matching field found: readline for class clojure.lang.LineNumberingPushbackReader
```
... It should be readLine (camel-case)!

Cursive displays an input box when I use the correct method name 😃
