### ISSUE TITLE
Incorrect REPL NS handling when using "Send form to REPL" variants

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2286]
This was reported by @tslocke in the mailing list.

> I usually keep my REPL in a ‘dev’ namespace I’ve set up for that purpose. I was always able to eval defns from all over my codebase, without the REPL namespace changing. That seems to have changed quite recently (couple of weeks?). If I do “send top level form to REPL”, the REPL namespace switches to the one where that defn is.

>On closer inspection, it looks like a bug with the namespace label in the bottom right corner of the REPL:
> - Send a form to the REPL from a ns other than the current REPL ns
> - Focus the REPL
> Indicator now shows the other ns, but the REPL is not really in that ns
> - Eval anything
> Indicator switches back to (correctly) show the original ns

And also:

> Just a quick follow-up to say I am definitely seeing a bug beyond just an incorrect label. The REPL is evaling forms in the wrong ns, following a "send form to repl".

> Specifically: I have a repl in ns foo.a, with some history; I "send form to repl" from the editor in ns foo.b (works); I then pull a recent form from the history, assuming it will eval in foo.a; it fails, and I have to do (in-ns 'foo.a) to get it working again.

I initially thought that this was a behaviour that had changed in nrepl since I recently upgraded that, so I filed nrepl/nrepl#171. However as shown in the comments to that issue the behaviour over there has not changed in recent times, so I'm not sure what has changed in Cursive.

Probably related to #2115.

**Comment by cursive-ide** [comment]
I can reproduce the incorrect REPL ns labelling, but I cannot reproduce the evaluation in an incorrect namespace. Here's a sample REPL session:

```clojure
Clojure 1.10.1
Loading src/foo/a.clj... done
Loading src/foo/b.clj... done
*ns*                   ; typed into the REPL
=> #object[clojure.lang.Namespace 0x7d2565e8 "user"]
(defn foo [])          ; sent from foo/a.clj
=> #'foo.a/foo         ; ns indicator now shows foo.a
*ns*                   ; typed into REPL
=> #object[clojure.lang.Namespace 0x7d2565e8 "user"] ; ns indicator now shows user again
(defn bar [])          ; sent from foo/b
=> #'foo.b/bar         ; ns indicator shows foo.b
*ns*                   ; typed into REPL
=> #object[clojure.lang.Namespace 0x7d2565e8 "user"]
(defn bar [])          ; sent from foo/b.clj
=> #'foo.b/bar         ; indicator now shows foo.b
(defn baz [])          ; type this into the REPL
=> #'user/baz          ; it's actually executed in user
```

**Comment by tslocke** [comment]
There is something subtle going on. I'm having a hard time reproducing the problem consistently. Just now I found that the steps above (from "and also" in your opening comment) did NOT produce the problem, but I WAS seeing the problem with a "Re-do last" REPL command, which I have bound to a key. i.e. send-to-repl from a different ns; re-do-last to run something from the ns the repl is supposed to be in; error.

I saw the problem 3 or 4 times (`Unable to resolve symbol: foo in this context`), but then went back to double check the repro steps and it started working properly. Right now I can't reproduce it.

If it crops up again I'll try again to nail down the steps.

**Comment by cursive-ide** [comment]
Ok, in the meantime I've fixed the labelling problem for the next EAP. It's possible that will fix any other problems as well, since the label also represents some internal REPL state - if that's corrected, it's possible other things will be fixed as well.
