### ISSUE TITLE
Problem running REPL configurations on 2020.1

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2308]
Reported by Jonathan Woods on the mailing list:

> I'm using IntelliJ 2020.1 EAP and Cursive 1.9.1-eap3-2020.1 on JDK 13.  If I create a simple Leiningen project, and define a local REPL run config, I get an error message when I try to run it: "Error running <run config name>: Deferred parameters have not been cached!".   If I change the run config definition to use IntelliJ's classpath rather than Leiningen, it works fine.

**Comment by katox** [comment]
I still get this error in 1.9.2-eap2-2020.1.

**Comment by evilsneer** [comment]
Me to!
It appears when I stop REPL and try to start it again.

Intellij IDEA 2020.1.1 CE
#IC-201.7223.91 (30 April 2020)

Cursive 1.9.2-eap3-2020.1
