### ISSUE TITLE
Remote REPL config doesn't persist nREPL port module

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2311]
Reported in Slack by @grav:

> The “Use port from nREPL file” option in remote repl configs seems to be broken in latest EAP versions (tried a 1.9.0 EAP and a the most recent 1.9.1 EAP). If I select a module, click Ok, and then go back to the config, the module selection is gone again (and there’s a “Run Configuration Error: Please select a valid module” error in the bottom of the dialog).

**Comment by grav** [comment]
It seems this feature is still broken with latest eap - I don't get the "Please select a valid module" error anymore, but the repl just doesn't launch when I click the Run button or use the Run menu item. Nothing happens.
