### ISSUE TITLE
[Since eap5] Error running REPL: Receiver class cursive.repl.toolwindow... interface com.intellij.ui.content.ContentManagerListener.

### ISSUE THREAD

**Issue by juskrey** [cursive-ide/cursive#2317]
I get the following error whenever I am trying to run REPL second time:

`Error running REPL: Receiver class cursive.repl.toolwindow$repl_listener$reify__11845 does not define or inherit an implementation of the resolved method 'abstract void contentAdded(com.intellij.ui.content.ContentManagerEvent)' of interface com.intellij.ui.content.ContentManagerListener.
`

Also the X button does not close the REPL tab and I now get:
`Process finished with exit code 137 (interrupted by signal 9: SIGKILL)`

Currently on 1.9.1-eap6-2019.3
I believe the problem have started with 1.9.1-eap5-2019.3 

IDEA version:
IntelliJ IDEA 2019.3.2 (Ultimate Edition)
Build #IU-193.6015.39, built on January 21, 2020

**Comment by cursive-ide** [comment]
Yes, this issue is present in eap5 and eap6. Lots of people have reported this one, but I've been unable to reproduce it so far, and I can't construct a plausible explanation of how it might occur. I'm investigating it now.
