### ISSUE TITLE
Support for Lokeh/helix using stub generation

### ISSUE THREAD

**Issue by tekacs** [cursive-ide/cursive#2330]
The Lokeh/helix package is the successor to Lokeh/hx.

It makes heavy use of macros, including in `helix.dom` where it generates macros for each of the React-supported DOM tags in the following file:

https://github.com/Lokeh/helix/blob/6fc96e4ac330daeb1cb3e8372a13819f67570661/src/helix/dom.cljc#L139-L150

This currently results in Cursive rejecting all of those macro calls. Other than the single namespace of `helix.dom`, I don't believe there is currently any other use of generation, so perhaps that namespace could be added to the static list for stub generation?

cc/ @Lokeh in case any of this is subject to change.

**Comment by Lokeh** [comment]
That would be great! AFAIK this is the same strategy that Fulcro, Om, etc. generate dom helpers as well, so if there's anything they do to help that I can do on my end, let me know!
