### ISSUE TITLE
Classpath isn't updated after REPL restart (need to reopen the project)

### ISSUE THREAD

**Issue by fjolne** [cursive-ide/cursive#2331]
When adding a new dep via `deps.edn` it previously worked to restart REPL configuration for classpath to be updated and new dep to be available in the REPL. In the latests EAPs after restarting the REPL the dep is still unavailable (even though Cursive itself imports it correctly, so autocomplete on the dep works). But after restarting the entire IDE the dep becomes available.

The behaviour persists for all the newly added dependencies, and those dependencies are imported correctly when accessed via raw `clj` CLI.

IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.5985.32, built on February 27, 2020
Cursive 1.9.1-eap9-2020.1

**Comment by fjolne** [comment]
The same behaviour goes for ENV vars: previously after changing ENV vars (in the run configuration) it was enough to restart the REPL, now the changes are applied only after restarting IDE (or reopening the project?).

**Comment by cursive-ide** [comment]
This is fixed in 1.9.1-eap10, out now.
