### ISSUE TITLE
IDEA can't run clojure test

### ISSUE THREAD

**Issue by moqimoqidea** [cursive-ide/cursive#2336]
I installed the Cursive plugin and used it to create a simple clojure test project. Running Hello World has been unsuccessful.
IDEA version is 2020.1 EAP 201.6251, Cursive version is 1.9.1-eap10-2020.1.
Wrong message is here: 00:19 Error running 'core': failed to access class com.intellij.execution.impl.ProcessStreamsSynchronizer from class com.intellij.execution.impl.ConsoleViewRunningState (com.intellij.execution.impl.ProcessStreamsSynchronizer is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @62ee68d8; com.intellij.execution.impl.ConsoleViewRunningState is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @4c5539c9)

<img width="478" alt="Snipaste_2020-03-14_00-20-58" src="https://user-images.githubusercontent.com/39821951/76671604-2c5c3780-65d2-11ea-92ca-6f049353e3ef.png">
<img width="1680" alt="Snipaste_2020-03-14_00-20-36" src="https://user-images.githubusercontent.com/39821951/76671608-2ebe9180-65d2-11ea-8465-5195048da143.png">
<img width="997" alt="Snipaste_2020-03-14_00-20-17" src="https://user-images.githubusercontent.com/39821951/76671609-31b98200-65d2-11ea-9605-eb5772583d93.png">

**Comment by cursive-ide** [comment]
This is #2350, which is fixed for the next EAP build.
