### ISSUE TITLE
Deftype method implementations show false errors in CLJC files when method arity over 1

### ISSUE THREAD

**Issue by vehvis** [cursive-ide/cursive#2346]
To reproduce:

1. Create two namespaces, one in a **.clj** file and the other in a **.cljc** file
2. Place the following definitions into **both** namespaces:
```
(defprotocol IFoo
  (foo [this y])
  (bar [this y z]))
(deftype Foo1 [x]
  IFoo
  (foo [this y]
    (+ x y))
  (bar [this y z]
    (+ x y z)))
```
3. Note that in the CLJC namespace, the `bar` method shows an "incorrect arity 2" error but not in the CLJ namespace.

Reproducible on Cursive 1.9.1-2019.3 (but possibly not on 1.8.2, so maybe a regression?).

**Comment by vehvis** [comment]
This continues to occur (as expected) on 1.9.1-2020.1

**Comment by cursive-ide** [comment]
I can't reproduce this on current Cursive. I looked at it after fixing some related problems, so I'm going to optimistically mark this as fixed. Let me know if that's not the case.

**Comment by cursive-ide** [comment]
Actually, I did manage to reproduce this and fix it.
