### ISSUE TITLE
Under 2020.1, the structural editing widget has disappeared

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2349]
Also, searching for "Parinfer" in the main preferences takes the user to _Preferences | Editor | General | Smart Keys_, but the Clojure-specific config is now in a sub-pane under "Smart Keys". This is very confusing and it's hard to find the right config.

**Comment by holyjak** [comment]
FYI When I opened Smart Keys - Clojure, the mode was set to Parinfer indent mode but actually it was not, par* was off. I had to switch it off in the menu -> apply -> switch it on again to get it working.
