### ISSUE TITLE
Running Clojure files using Cursive on Intellij and Debian results in error.

### ISSUE THREAD

**Issue by sameertj** [cursive-ide/cursive#2352]
What steps will reproduce the issue?

1) Install the cursive plugin
2) Import a clojure project
3) Click on run.

What is the expected result?
The Clojure program should run.

What happens instead?

1:24 AM Error running 'relax': failed to access class com.intellij.execution.impl.ProcessStreamsSynchronizer from class com.intellij.execution.impl.ConsoleViewRunningState (com.intellij.execution.impl.ProcessStreamsSynchronizer is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @402f32ff; com.intellij.execution.impl.ConsoleViewRunningState is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @243f5a0d)

The screen shot is also attached.

![cursive-error](https://user-images.githubusercontent.com/13229782/79318065-c827de80-7ec3-11ea-8997-1212aff72e3f.png)

**Comment by cursive-ide** [comment]
This is being tracked in #2350.
