### ISSUE TITLE
IDE becomes unusable after Deps project import

### ISSUE THREAD

**Issue by finalfantasia** [cursive-ide/cursive#2355]
Given a Deps project, after importing it using the "Open or Import" option from the welcome screen of IntelliJ IDEA, the IDE becomes unusable. There are no tool windows other than the (functional) Clojure Deps tool window. The only workaround seems to be closing the imported project (Shift + Command + A and then type "close project") and re-opening it (from the recent project list on the welcome screen). 

My environment:
Cursive 1.9.1-2020.1 and 1.9.2-eap1-2020.1

IntelliJ IDEA 2020.1 (Ultimate Edition)
Build #IU-201.6668.121, built on April 8, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

macOS 10.15.4

IntelliJ IDEA log:
[intellij_idea_cursive.log](https://github.com/cursive-ide/cursive/files/4531965/intellij_idea_cursive.log)

**Comment by den1k** [comment]
Also running into this. Thanks @finalfantasia for providing a workaround.
