### ISSUE TITLE
Dependencies specified via :extra-deps parameter of an alias are ignored by cursive

### ISSUE THREAD

**Issue by fctorial** [cursive-ide/cursive#2383]
It's a common pattern to have separate modules in a tools.deps project, `:extra-deps` attribute of an alias is used to specify the dependencies used by it. For example a testing framework for `:test` alias. Cursive ignores these dependencies, hence they show up as unresolved when editing these modules.

**Comment by fctorial** [comment]
A straightforward solution is to collect all the dependencies when importing/indexing the project. This will be good enough for most cases.

**Comment by cursive-ide** [comment]
I think this is what you want: https://cursive-ide.com/userguide/deps.html#working-with-aliases

**Comment by fctorial** [comment]
This is it, thanks.
