### ISSUE TITLE
Identify context from `deftest` and `clojure.test/testing` in assertion failure 

### ISSUE THREAD

**Issue by hlship** [cursive-ide/cursive#2387]
AFAIK Cursive does nothing with the `testing` macro; it would be very useful if the details of the executing test, and any testing contexts, was presented as part of the assertion differences panel; this would partially offset #1945.

![image](https://user-images.githubusercontent.com/52660/84426874-ca16d100-abd8-11ea-9d0b-94cea4695879.png)

It would be nice if there was a banner of some kind that would identify the FQN of the executing test and any nested `testing` contexts.

**Comment by hlship** [comment]
I'm really looking forward to this, thanks!  I've sometimes gotten in the habit of writing test helpers as macros, rather than functions, because otherwise it can be problematic to figure out which test, in a large namespace, actually failed - I hope this will help address that.

**Comment by cursive-ide** [comment]
@hlship Great, let me know how it works and if there could be improvements. There are other fixes in this area planned for the next build, they're all in the [1.12.4 milestone](https://github.com/cursive-ide/cursive/milestone/204). #823 will hopefully help with this too.
