### ISSUE TITLE
Go to definition not working on 'Symbol Resolution' symbols in 1.9.2-eap-6-2020.2

### ISSUE THREAD

**Issue by tekacs** [cursive-ide/cursive#2389]
I'm finding that in 2020.2 EAP + 1.9.2-eap6-2020.2 my Ctrl+Click/MiddleClick has stopped working entirely for anything that is defined through Symbol Resolution.

If I set up a symbol to be an alias of defn or def, prior to this version I could Ctrl+Click to go to its definition point (IIRC) -- now it only works on things natively defn'd.

I've tried Invalidate Caches + Restart, this is a deps.edn project, not sure what else I should share to ensure that it can be replicated.

I'm going to try downgrading both for now if I can, but I do need to find a way to fix this to keep on going. :)

**Comment by tekacs** [comment]
I also tried deleting the .idea directory and app.iml and re-importing the Clojure Deps project from scratch -- also to no avail

**Comment by tekacs** [comment]
Could this be related to the fix to #1069 at all?

**Comment by tekacs** [comment]
I also just tested this in another two separate Clojure Deps projects, finding the same issue to be the case.

This is happening both with my own definitions and external ones, (like `ghostwheel.core/>defn`)

**Comment by tekacs** [comment]
Downgrading to 2020.1.2 immediately fixed this issue in all of the projects for which this was occuring, for me. I'm still on eap6. Presumably this is a new interaction between Cursive and IDEA 2020.2 :)

**Comment by cursive-ide** [comment]
Yes, I've reported this with JetBrains [here](https://youtrack.jetbrains.com/issue/IDEA-243212), and I'm discussing it with them.

**Comment by coltnz** [comment]
I can't cmd click to defs in current namespace [unless i prefix them with the ns]. Is that related or a new ticket? Latest EAP and Cursive on OSX.

**Comment by cursive-ide** [comment]
@coltnz It's the same one if you're on the IntelliJ 2020.2 EAP.
