### ISSUE TITLE
Displaying a very large diff for failed test completely hangs IDEA

### ISSUE THREAD

**Issue by jsyrjala** [cursive-ide/cursive#2396]
1. Make a test that fails with a large diff. For example `very-large-list-of-list-of-maps` is about 300k as EDN file.
```clojure
(is (= {} very-large-list-of-list-of-maps))
```
2. Hover on the test to get diff
3. IDEA becomes completely unresponsive. Even cmd-Q will not kill the app.

MacOS, IDEA 2020.1.2, Cursive 1.9.2-2020.1

It would be better for Cursive to detect that this amount of text could hang IDEA and instead say that "can't show diff because it is too large" or "diff may be too large to show, click here to show the diff".

**Comment by jsyrjala** [comment]
The same thing happens with IDEA 2020.1.3

**Comment by iechevarria** [comment]
I'm also experiencing this – it's worth noting that the hitching is most pronounced when the tooltip is rendering. This happens for relatively small maps with fewer than 100 values.

macOS, IDEA 2021.1, Cursive 1.10.2-2021.1
