### ISSUE TITLE
Add Resolve as: none option to form resolution customisation

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2417]
Sometimes users use macros which Cursive is unaware of and can't be easily customised to handle. In these cases it would be useful to turn off syntax highlighting warnings in the bodies of these macros so that the user isn't overwhelmed with false positives.

**Comment by tekacs** [comment]
Thank you so much for this @cursive-ide! I've been playing with this and it's absolutely joyous to finally see my IDE be close to free of errors/warnings, with those last few macros hidden away. :)

CLJS symbols from JS-land are the final frontier now, I think. 😆

**Comment by cursive-ide** [comment]
@tekacs Great! And yes, I'm planning to do the JS interop bit soon.
