### ISSUE TITLE
HTML->Hiccup conversion producing invalid code

### ISSUE THREAD

**Issue by thheller** [cursive-ide/cursive#2420]
I have been working on a few projects recently that use [tailwind CSS](https://tailwindcss.com/). I usually get HTML/CSS from designers and then port them to Clojure to generate the dynamic versions via hiccup. Unfortunately there are some tailwind classes that break the Cursive HTML->hiccup conversion.

The simplest example being [width](https://tailwindcss.com/docs/width#fluid-width). `w-1/2` being `width: 50%`. While this is a perfectly valid CSS classname it is not a valid keyword and breaks even worse when using the responsive style
```
<div class="w-1/2 md:w-1/3 lg:w-1/4">hello world</div>
;; producing
[:div.w-1/2.md:w-1/3.lg:w-1/4 "hello world"]
```

In general I'd prefer Cursive to always generate `[:div {:class "..."}]` instead of using the keyword syntax sugar. Would be neat if there was an option to do this.

**Comment by cursive-ide** [comment]
This is fixed for the next EAP. Classes which aren't valid keywords are always added to the `:class` attribute, and there's also a new config switch _Use shortcuts for class/ID_ to turn those off altogether.

**Comment by thheller** [comment]
Sweet. Thank you.
