### ISSUE TITLE
Allow disabling symbol resolution for specific macros

### ISSUE THREAD

**Issue by aneilbaboo** [cursive-ide/cursive#2425]
If you're using a macro which doesn't follow an existing symbol resolution pattern, you're stuck with symbol resolution errors. As far as I can tell, there's no way to disable this. Can we get something like this:

### Add a menu item "disable symbol resolution" here
![image](https://user-images.githubusercontent.com/2592723/92330719-fd28ff00-f025-11ea-9261-29c78e4e933d.png)

It's really a blocker for me in using Cursive. I love the REPL integration, but the editor experience is practically unusable from a visual standpoint. I'm writing a DSL which relies heavily on a macro which cannot be resolved using any of the existing patterns (the macro expansion contains `letfn` bindings). This means that the editor is littered with spurious symbol resolution errors.

I notice that macro symbol resolution has been a long standing problem, it was noted as the [#1 problem](https://github.com/cursive-ide/cursive/issues/218#issuecomment-31553687 ) over 6 years ago, and there are a number of related issues that could be solved with this feature. While the ability to resolve symbols using an existing pattern is helpful, it is very limited and hard to use (how do I know an obscure existing form matches the pattern I want to use) . Given that macros and DSLs are a main selling point of Clojure, it seems pretty important to be able to give macro authors the ability to turn off spurious warnings which clutter the UI.

Would this be easy to implement? It seems like it could be solved by adding a symbol resolution pattern that treats arguments as quoted expressions.

This is hoisted from a comment in https://github.com/cursive-ide/cursive/issues/147 and relates to https://github.com/cursive-ide/cursive/issues/1618 https://github.com/cursive-ide/cursive/issues/218 https://github.com/cursive-ide/cursive/issues/917 https://github.com/cursive-ide/cursive/issues/2053 https://github.com/cursive-ide/cursive/issues/1881 https://github.com/cursive-ide/cursive/issues/1835 https://github.com/cursive-ide/cursive/issues/1665 https://github.com/cursive-ide/cursive/issues/1618

**Comment by tekacs** [comment]
@aneilbaboo it looks like this was just resolved in #2417!

**Comment by aneilbaboo** [comment]
Woohoo! Thanks so much for pointing me at that, @tekacs.
