### ISSUE TITLE
Type Check Current NS falsely reports unused alias

### ISSUE THREAD

**Issue by jimka2001** [cursive-ide/cursive#2433]
I've defined a namespace as follows and *Type Check Current NS* claims that `ty` and `dfa` are unused aliases.  However, they are used.

```clojure
(ns clojure-rte.core
  (:require [clojure.set :refer [union]]
            [clojure.pprint :refer [cl-format]]
            [clojure-rte.cl-compat :refer [cl-cond]]
            [clojure-rte.util :refer [with-first-match call-with-collector
                                      fixed-point
                                      visit-permutations rte-constantly rte-identity
                                      partition-by-pred
                                      print-vals sort-operands member]]
            [clojure-rte.type :as ty]
            [clojure-rte.dfa :as dfa ]
            [clojure-rte.rte]
            [clojure-rte.memoize]
            [clojure-rte.api]
            [clojure-rte.type-extend]
            )
  (:gen-class))
```
Here is a link to the project.
[clojure-rte](https://gitlab.lrde.epita.fr/jnewton/clojure-rte/-/tree/180118911e37024c9216bd05b9fee93a327095bf)
You can reproduce this by opening the project using IntelliJ/Cursive, opening the file `clojure-rte/src/clojure_rte/core.clj`, and activating the popup menu item *REPL->Type Check Current NS*.

It reports, for example, that `ty` is an unused alias, but if you look in the file `api.clj` on line 104, that the function `rte-match` defined in the *same NS* has the call `(if (ty/typep item type) ...)`.

**Comment by cursive-ide** [comment]
That action (Type Check Current NS) is unfortunately horribly obsolete. I implemented it years ago when it looked like Typed Clojure might become a useful thing, but it never became popular. That action is implemented against an ancient version and I'm surprised it even works. I've removed the action, which I should have done a long time ago.
