### ISSUE TITLE
REPL -> Send '(in-ns ...)' does not change ns of repl

### ISSUE THREAD

**Issue by jimka2001** [cursive-ide/cursive#2436]
If I type 
```clojure
(in-ns 'my-ns) 
```
into the cursive repl, then the ns changes, as is seen by the notation at the bottom right of the repl window.

![Screenshot 2020-09-18 at 19 16 33](https://user-images.githubusercontent.com/6414129/93626273-80adfd00-f9e3-11ea-94b6-5d30782cbcd5.png)

However, when I use the menu item *REPL -> Send ...* to send an `(in-ns ...)` to the REPL it doesn't seem to change.

![Screenshot 2020-09-18 at 19 18 05](https://user-images.githubusercontent.com/6414129/93626429-b2bf5f00-f9e3-11ea-8c32-0c738531b00a.png)

![Screenshot 2020-09-18 at 19 21 02](https://user-images.githubusercontent.com/6414129/93626721-2497a880-f9e4-11ea-88e9-56925678b44d.png)

**Comment by cursive-ide** [comment]
When sending forms to the REPL, there are two options, controlled by a config flag: _Settings→Languages & Frameworks→Clojure→Evaluate forms in REPL namespace_. This controls whether the forms will be executed in the current REPL namespace, or in the namespace of the file from which they were sent. So for example, if you send a form from a file which defines `my-ns.core` and your REPL is currently in `user`, that form will by default be executed in the `my-ns.core namespace`. In this case, you're executing the `in-ns` form in whichever namespace is defined by the file, not the current REPL namespace, so `*ns*` remains untouched. If you're coming from Common Lisp, you might prefer to set that config flag, which I believe is how CL REPLs tend to work.

**Comment by jimka2001** [comment]
Interesting,   I don't really understand the reasoning.   I do want my `(in-ns ...)` form to be evaluated in the repl namespace, but a side effect of that expression is that the name space changes.   Exactly as if I type the same `(in-ns ...)` form into the repl, which changes the namespace.

Is the menu item callback somehow wrapped in a `(binding [*ns* ...] ...)` form, which prohibits such code from changing the value of `*ns*` ?   That would explain what's happening.

**Comment by jimka2001** [comment]
I see there's another menu item called *Switch REPL NS to current file*.
It would be nice if that menu item actually substituted the target NS name in the menu item text,
similar to the clever way the *Send '(...)'* works.

**Comment by cursive-ide** [comment]
> Is the menu item callback somehow wrapped in a (binding [*ns* ...] ...) form, which prohibits such code from changing the value of *ns* ?

That's how it's implemented, yes. Although the idea is not to prevent `*ns*` being changed so much as ensuring that any definitions are made in the bound namespace. For example, if the user sends a `defn` form from their editor, it's often very surprising to them if the function is not defined in the namespace of the file it was sent from.

**Comment by cursive-ide** [comment]
> It would be nice if that menu item actually substituted the target NS name in the menu item text

That's a good idea, yes, and easy to implement - I'll do that. I've filed #2437 for that.

**Comment by jimka2001** [comment]
Yes I understand now why the `ns` variable is protected by this evaluation.  Thanks for the explanation.
