### ISSUE TITLE
Support babashka as valid REPL target

### ISSUE THREAD

**Issue by beders** [cursive-ide/cursive#2452]
This is a request for enhancement to support babashka's runtime environment:

Babashka already has a built-in nrepl server and I can connect to it via Cursive just fine,
but completions aren't working and I'm getting an error message for every evaluated line.

At the beginning of the session (when Cursive wants to inject some code supposedly), I'm getting this output:

```
clojure.lang.ExceptionInfo: Unable to resolve classname: java.lang.reflect.Method
Error initialising completion
Error initialising locals clearing:
clojure.lang.ExceptionInfo: Could not resolve symbol: *compiler-options* [at line 1, column 6]
clojure.lang.ExceptionInfo: Could not resolve symbol: clojure.core/clojure-version [at line 1, column 57]
Error initialising REPL:Error updating completions:
clojure.lang.ExceptionInfo: Could not resolve symbol: cursive.repl.runtime/completions [at line 1, column 2]
1 
Error updating completions:
clojure.lang.ExceptionInfo: Could not resolve symbol: cursive.repl.runtime/completions [at line 1, column 2]
```

## Desired Behavior

Have Cursive connect and auto-detect babashka and suppress errors. Bonus points if completions can be made to work.

Babashka is here: 
https://github.com/borkdude/babashka

**Comment by onetom** [comment]
Currently it's possible to connect to a Babashka *socket REPL*, using https://github.com/vlaaad/remote-repl .
I already have a Clojure Deps project, so I've just added an alias in my `deps.edn`:
```
{:deps {,,,}
 :aliases {,,, :remote-repl {:extra-deps {vlaaad/remote-repl {:mvn/version "1.1"}}}}}
```

1. Run `bb socket-repl` in some terminal.
2. Create and run a Clojure Local run config with the following options:
   1.  _Which type of REPL to run_: `clojure.main`
   2. _How to run it_: _Run with Deps_ / _Aliases:_ `remote-repl`
   3. _Common options_
      1. _Module_: <your existing Clojure Deps IntelliJ module>
      2. _Parameters_: `-m vlaaad.remote-repl :port 1666`

This would pull in the main dependencies of your existing project too, which is not necessary, but I'm not sure yet what's the best approach to avoid that.

**Comment by borkdude** [comment]
@onetom I think `:replace-deps` instead of `:extra-deps` is the answer to the last remark.

**Comment by onetom** [comment]
Cursive `1.10.3-eap2-2021.2` doesn't find the `vlaaad/remote-repl` dependency, if I use `:replace-deps`, instead of `:extra-deps`.

This is how it's starting up:
```
Starting clojure.main REPL...
/nix/store/yypccdfg34ms7j1hbv2yqy7v0jdn3x3i-zulu11.43.21-ca-jdk11.0.9/zulu-11.jdk/Contents/Home/bin/java -Dclojure.libfile=/private/var/folders/4q/fcvqptl53wj8sdb5p1g3w7r40000gn/T/libfile1068.libs "-javaagent:/Users/xxx/JetBrains/apps/IDEA-U/ch-1/212.4746.2/IntelliJ IDEA 2021.2 EAP.app/Contents/lib/idea_rt.jar=51272:/Users/xxx/JetBrains/apps/IDEA-U/ch-1/212.4746.2/IntelliJ IDEA 2021.2 EAP.app/Contents/bin" -Dfile.encoding=UTF-8 -classpath ... clojure.main -m vlaaad.remote-repl :port 50505 :host \"1.2.3.4\"
```

and this is the error message I get:
```
Execution error (FileNotFoundException) at clojure.main/main (main.java:40).
Could not locate vlaaad/remote_repl__init.class, vlaaad/remote_repl.clj or vlaaad/remote_repl.cljc on classpath. Please check that namespaces with dashes use underscores in the Clojure file name.

Full report at:
/var/folders/4q/fcvqptl53wj8sdb5p1g3w7r40000gn/T/clojure-14672245791511011879.edn

Process finished with exit code 1
```
