### ISSUE TITLE
Namespace navigation not available with IntelliJIdea 2020.3/Cursive 1.9.4-2020.3

### ISSUE THREAD

**Issue by aposorovaschi** [cursive-ide/cursive#2467]
The namespace navigation (Alt+Shift+N) is not available in the latest stable IntelliJIdea, and associated Cursive plugin: `1.9.4-2020.3`.
In other words:
* `Namespaces` section is missing from the "Navigation" dialog (the one with `All  Classes  Files Symbols Actions Keywords`).
* Hitting `Alt+Shift+N` (Linux machine) does nothing.

I'm using a `Cursive Personal Licence`.

**Comment by mitchelkuijpers** [comment]
Can confirm I have the same issue. It drives me crazy to be honest I am very dependent on this.

I'm using a `Cursive Commercial License` and I am running Arch linux.

**Comment by cursive-ide** [comment]
This is described on the mailing list [here](https://groups.google.com/g/cursive/c/r6ORtyx4nnM/m/TlFKB-EABAAJ) - it's due to an [IntelliJ bug](https://youtrack.jetbrains.com/issue/IDEA-253572) and is fixed for the next EAP, out shortly.
