### ISSUE TITLE
Test runner

### ISSUE THREAD

**Issue by georgewfraser** [cursive-ide/cursive#247]
It would be nice to just be able to run all the tests in the same way that lein test works. I find the repl-based test system:
1. Requires lots of clicks. Tools -> REPL -> Run tests in current NS in REPL
2. Provides no mechanism to run ALL tests, which is 90% of the time what I want to do.
3. Fragile. Often I click "Run tests in current NS" and it runs 0 tests, and I have no idea why.

Perhaps I am failing to comprehend the way you are re-imagining test runners, but I end up just running lein test from the command line. It would be nice if cursive had a test runner that worked the same way as every other test runner.

**Comment by danielcompton** [comment]
This might be helpful for building a runner https://github.com/mikera/cljunit

**Comment by pkozikow** [comment]
Is this still on the roadmap? For us it would help a lot since we have many java classes tested in Clojure. The repl approach is not practical in this case since the repl needs to be reloaded every time the Java class being tested is changed.

**Comment by cursive-ide** [comment]
Yes, it is, and it's on the shortlist part of the roadmap.

**Comment by Misophistful** [comment]
My team and I are really missing not having a test runner in Cursive. `lein test` works, but it's a pain to view the results and navigate to the code that's causing the issue.

We were wondering if the test runner feature is getting closer to the top of your backlog?

**Comment by mikkoronkkomaki** [comment]
Is there any hope of getting a test runner into Cursive in the foreseeable future? Our team also  would greatly appreciate this feature. We managed to go around this by using test2junit to generate a html document of the test results, but this still is very cumbersome. Having a runner being able to run all tests in a single project and viewing their outcome in a single report would be really handy.

**Comment by russellwstanley** [comment]
Would be great to see this as running tests in the repl is not a reliable process because the REPL holds on to a bunch of state between test runs (defs, classes etc) and you have to remember to constantly clean and refresh it.

**Comment by wmatson** [comment]
Might be possible to use/integrate [kaocha](https://github.com/lambdaisland/kaocha) which can report results as junit xml

**Comment by sooheon** [comment]
Kaocha JUnit XML integration: https://github.com/lambdaisland/kaocha-junit-xml

**Comment by aneilbaboo** [comment]
Is there an ETA on this? It would be really useful.

**Comment by rutchkiwi** [comment]
Ohh @cursive-ide does the close mean this is coming? Exciting if so

**Comment by cursive-ide** [comment]
@rutchkiwi Yes indeed! It should be out soon.

**Comment by aneilbaboo** [comment]
Hi @cursive-ide - What happened to this one? It was tracked by the 1.10.0-eap1 milestone, but never got delivered.

**Comment by cursive-ide** [comment]
@aneilbaboo Yes, this has been in for a while now. See: https://cursive-ide.com/userguide/testing.html#test-runner.
