### ISSUE TITLE
Importing Metabase project results in bogus "profiles"

### ISSUE THREAD

**Issue by jeff303** [cursive-ide/cursive#2487]
When importing [metabase](https://github.com/metabase/metabase), it seems that Cursive detects a bunch of bogus [profiles](https://github.com/metabase/metabase/blob/master/project.clj#L188).  Looks to be some kind of parsing problem.  Example screenshot here:

![MdhcC17](https://user-images.githubusercontent.com/3521562/105726666-ec532a00-5eef-11eb-81c1-f6e8a8cec17d.png)

**Comment by cursive-ide** [comment]
The problem with this is the composite profiles, which contain both keywords and maps:

```clojure
   :run-with-repl
   [:exclude-tests
    :include-all-drivers

    {:env
     {:mb-jetty-join "false"}

     :repl-options
     {:init    (do (require 'metabase.core)
                   (metabase.core/-main))
      :timeout 60000}}]
```

I've never seen maps used in composite profiles before. The [documentation](https://github.com/technomancy/leiningen/blob/master/doc/PROFILES.md#composite-profiles) doesn't say this is allowed, but then hints that it might be but says not to mix them:

> It is not recommended to make a composite profile which contains both keywords and maps; they should either be all keywords or all maps.

Anyway, this will be fixed for the next build.
