### ISSUE TITLE
Passing the line number in REPL commands

### ISSUE THREAD

**Issue by daslu** [cursive-ide/cursive#2488]
Many thanks for Cursive!

On REPL commands, it will be useful to be able to pass the cursor line number from the IDE state (say, `~line` or `~line-number`).

This will allow tighter integration with the [Notespace](https://github.com/scicloj/notespace) tool we are developing -- a tool that connects the REPL with a browser notebook-like view for literate programming. 
This will be analogous to similar functionality we already have [for CIDER](https://github.com/scicloj/notespace/blob/master/emacs-config.el) and [for Calva](https://github.com/BetterThanTomorrow/calva/issues/863).

**Comment by cursive-ide** [comment]
This makes sense and looks easy, I'll fix this shortly.

**Comment by cursive-ide** [comment]
This is fixed. Note that the values returned will be 0-based, not 1-based as they are displayed in the status bar.

**Comment by daslu** [comment]
Thank you for the quick and kind help, @cursive-ide !
