### ISSUE TITLE
Cursive Run/Debug Configuration forgets the "Specify custom port file" setting

### ISSUE THREAD

**Issue by karimarttila** [cursive-ide/cursive#2498]
I do Clojure/script full stack programming using IntelliJ IDEA 2020.3.2 Ultimate and Cursive 1.10.1-eap2-2020.3.

In Run/Debug Configurations I have configured two Clojure remote repls: one for backend and one for shadow-cljs frontend. Both are nREPLs.

I have selected "Use port from nREPL file" and "Specify custom port file", and given the "Port file" explicitly as:
- for backend: .nrepl-port
- for frontend: .shadow-cljs/nrepl.port

Occasionally e.g. the frontend configuration "forgets" this configuration and the repl connection doesn't work any more - I go to see the Run/Debug Configuration for the frontend and it says: "Use standard port file" - and I suspect that it is using the ".nrepl-port" file which belongs to the backend repl.

**Comment by cursive-ide** [comment]
That's a little embarrassing, my apologies - this is fixed for the next build.

**Comment by karimarttila** [comment]
No need to apologize! Cursive is just great, I love it!
