### ISSUE TITLE
Can't start REPL with 2019.3

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2504]
When trying to start a REPL with recently Cursive versions on IntelliJ 2019.3, the following error is produced:
```
Error running 'CLJ Local': class clojure.lang.PersistentVector cannot be cast to class [Lcom.intellij.openapi.actionSystem.AnAction; (clojure.lang.PersistentVector is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @7e26aea8; [Lcom.intellij.openapi.actionSystem.AnAction; is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @5419f379)
```

**Comment by isaac-siegel** [comment]
Verified fixed in 1.10.1-eap3-2019.3, huge thank you!

**Comment by lensgolda** [comment]
Got the same today 28/02/2021
2019.3.5 clojure 1.10.1
leiningen project.clj
:jvm-opts ["-Dclojure.server.repl={:address,\"0.0.0.0\",:port,50505,:accept,clojure.core.server/repl}"] 
Run/Debug -> ClojureREPL Remote -> Socket : Connect to server: localhost port: 50505

`Error running 'REPL': class clojure.lang.PersistentVector cannot be cast to class [Lcom.intellij.openapi.actionSystem.AnAction; (clojure.lang.PersistentVector is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @179f5098; [Lcom.intellij.openapi.actionSystem.AnAction; is in unnamed module of loader com.intellij.util.lang.UrlClassLoader @192c3f1e)
`

**Comment by cursive-ide** [comment]
@lensgolda This is fixed in the EAP build detailed above. Instructions for using EAP builds are [here](https://cursive-ide.com/userguide/index.html#eap). Alternatively, you could wait a bit - I should have a stable release out with this fix soon.
