### ISSUE TITLE
Module XXX is managed by Maven and cannot be managed by Leiningen at the same time.

### ISSUE THREAD

**Issue by kassapo** [cursive-ide/cursive#2528]
The is a **horrible** regression in 1.10.2-eap2-2020.3
We have many maven modules with many languages.
One module is in clojure.
Why does cursive refuse to play along with others?
Used to work before...
All we need is clojure support and a REPL.

Cannot use cursive if this does not change

**Comment by cursive-ide** [comment]
Nothing has changed in the relevant code in a long time. Do you want the clojure module to be managed by Maven or Leiningen? It cannot be both at the same time.

**Comment by kassapo** [comment]
Thanks for the quick response. I am very confused. All I need is clojure support and a good repl. I have no need for "management". Maybe something changed in intellij.

This means cursive cannot be used with maven?! Is that really intentional?

**Comment by cursive-ide** [comment]
No, that's not the case. When I talk about a module being managed by Maven or Leiningen, I'm referring to its source paths, dependency libraries etc being sourced from the project file of that build tool (i.e. `pom.xml` or `project.clj`). A given module must be managed by one or the other, not both at the same time. Cursive can definitely be used with Maven.
