### ISSUE TITLE
Redundant slash `/` in the path of :mvn/local-repo deps.edn key

### ISSUE THREAD

**Issue by lensgolda** [cursive-ide/cursive#2550]
To reproduce add explicitly `:mvn/local-repo "~/.m2/repository"` key to deps.edn file.
Run `clj -P`, IDEA 2020.3+Cursive completely loses all dependencies and does not see the cache.

And for example, shows error tooltip.

> 11:53	Errors during project resolution
>			The following errors were found during project resolve:
>			/Users/lens/dev/my/project/deps.edn:
>			/~/.m2/repository/org/clojure/data.json/2.2.2/data.json-2.2.2.pom.part.lock (No such file or directory)

Take a look at the start of the path `/~/.m2`/repository/...` - here it is  `/` starting

**Comment by shinichy** [comment]
Isn't this issue same as https://github.com/cursive-ide/cursive/issues/2535?

**Comment by stanislas** [comment]
I have the same problem and use the following workaround to configure gitlab in my build scripts. With this, the `:mvn/local-repo` key is not needed in the project deps.edn. In a sense, it is even better: on a development machine, the project uses the global maven cache.

```bash
# to put at the top of the build script.
if [ -n "${GITLAB_CI}" ]; then
  mkdir -p ~/.clojure
  echo "{ :mvn/local-repo \"${CI_PROJECT_DIR}/.m2/repository\" }" >~/.clojure/deps.edn
  cat ~/.clojure/deps.edn
fi
```

**Comment by cursive-ide** [comment]
Yes, I think this duplicates #2535.
