### ISSUE TITLE
Add option "Always generate stubs (for this project|for all projects)"

### ISSUE THREAD

**Issue by ivarref** [cursive-ide/cursive#2556]
Hi,

and thanks again for an excellent IDE.

I would like to have an option not only to generate stubs, but to *always* generate stubs for this project or for all projects.

Would that be possible?

As I'm sure you can tell I'm always pressing "Generate stubs" when presented with that option.

Thanks.

**Comment by cursive-ide** [comment]
This is fixed for the next build. In the end for boring reasons, there's only a global flag to enable this for all projects. If it's critical to do this per-project, let me know and I'll look for a solution.
