### ISSUE TITLE
cursive plugin stop working with IntelliJ IDEA 2021.2 EAP

### ISSUE THREAD

**Issue by eddumelendez** [cursive-ide/cursive#2558]
IntelliJ IDEA 2021.2 EAP (Ultimate Edition) was just released and the plugin stop working.

**Comment by euneuber** [comment]
Hi, thanks for your fast response!
Currently, it is not in Jetbrains Marketplace for plugins -- how log will this take?

**Comment by cursive-ide** [comment]
It's there now, but you'll have to be signed up to receive EAP releases, see [here](https://cursive-ide.com/userguide/index.html#eap) for details on how to do this.

**Comment by euneuber** [comment]
Thank you again for your fast response!
I still do not see it in the Marketplace (fresh install on IntelliJ IDEA 2021.2 EAP):
![grafik](https://user-images.githubusercontent.com/3296589/120307339-2768ce00-c2d3-11eb-9b99-b1b0c47e95c0.png)

How can I enable EAP builds without having it installed before?

**Comment by cursive-ide** [comment]
Ah, yes, if this is the first install, that's described [here](https://cursive-ide.com/userguide/troubleshooting.html#cursive-on-intellij-eap-builds).

**Comment by euneuber** [comment]
:+1: problem solved! Thank you again!
