### ISSUE TITLE
Add Programmatic Setting of Remote REPL Host

### ISSUE THREAD

**Issue by vatchedj** [cursive-ide/cursive#2559]
Not sure if this already exists, but it would be nice to set the host of a Remote REPL programmatically or through a configuration file. In cases where a the host IP changes frequently (container/instance behind a load balancer), it would be easier to be able to run a script before the REPL starts up that retrieves the host IP and sets it.

**Comment by cursive-ide** [comment]
Fix released in 1.13.2-eap5 on 2024-03-07.

**Comment by cursive-ide** [comment]
Fix released in 1.13.2 on 2024-04-04.
