### ISSUE TITLE
Set JAVA_HOME when invoking deps -Sdescribe

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2561]
Reported by @xaibeha over email:

> I (intentionally) have no java on the PATH these days; many JDKs 
> installed and I want to control what gets run in which, mostly to avoid 
> upgrade surprises when some SDK manager defaults to one or the other at 
> various times.
> 
> Cursive seems to have problems creating new deps projects that way - it 
> doesn't use the SDK selected for the project in IDEA but just emits:
> 
> ```
> 2021-06-05 22:57:46,257 [ 381854]   WARN - #cursive.deps.DepsSettings - 
> Output from /usr/local/bin/clojure -Sdescribe: Couldn't find 'java'. 
> Please set JAVA_HOME.
> ```
>
> Is there a way to make it use project SDK, or to set JAVA_HOME 
> specifically for it, or do I have to have some Java binary on the path 
> again?

It makes sense to set JAVA_HOME to the project SDK when shelling out to deps.

**Comment by dilbernd** [comment]
Hi @cursive-ide please use @dilbernd for me; @xaibeha was my GH at a former employer. NP, good terms, but I have no control of that account any more.

**Comment by dilbernd** [comment]
Please use this account for me, the other one was my GH for work tickets etc at a former employer. Thanks.

**Comment by cursive-ide** [comment]
So this is trickier than I expected. The issue is that `-Sdescribe` is used to work out the deps config, but that doesn't happen in the context of a project. You can open the settings from the welcome screen, for example, where there is no project yet. Similarly, your example is from creating a project, but that project won't yet have an SDK defined. I'll have to think about this.

**Comment by cursive-ide** [comment]
Ok, I think I've managed this. In most cases there is a project available, and when there isn't it'll try to default to something sensible (the most recent JDK you have registered with IntelliJ). If there aren't any, it won't set the env var.

**Comment by dilbernd** [comment]
Maybe, for the default case, the bundled JDK instead of the last registered, for better reproducibility given IDE version?
