### ISSUE TITLE
test markers not staying visible in gutter

### ISSUE THREAD

**Issue by stevebuik** [cursive-ide/cursive#2574]
IntelliJ IDEA 2021.2 (Ultimate Edition)
Build #IU-212.4746.92, built on July 27, 2021
Licensed to Steve Buikhuizen
Subscription is active until December 15, 2021.
Runtime version: 11.0.11+9-b1504.13 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.3.1
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Non-Bundled Plugins: com.illuminatedcloud2.intellij (2.1.8.2), PlantUML integration (5.5.1), com.cursiveclojure.cursive (1.10.3-2021.2)
Kotlin: 212-1.5.10-release-IJ4746.92

**Comment by stevebuik** [comment]
![Screen Recording 2021-08-02 at 11 38 58 am](https://user-images.githubusercontent.com/758151/127793696-1f1c4389-1f3f-4c39-b9ac-d7641981f4ad.gif)

**Comment by stevebuik** [comment]
gif in prev comment is 5Mb so takes a bit to download. illustrates the problem with a simple test.

doesn't happen for clj tests, only cljc tests. 

in the example above, it fixes itself after the first run. in other tests in my codebase, it does not fix itself

**Comment by stevebuik** [comment]
correction: I just noticed it in a clj test as well. 

in case it's relevant, this is on an M1 mac mini

**Comment by d-t-w** [comment]
+1 I noticed the same since updating to Intellij 2021.2

**Comment by AndyCorlin** [comment]
Hello! This seems to be broken again, tested version 1.12.1 - 1.12.3 where it works, but not in 1.12.4 and above. I guess I'll create a new issue.
