### ISSUE TITLE
New versions of Tools Deps breaks git SHA support

### ISSUE THREAD

**Issue by awkay** [cursive-ide/cursive#2581]
I upgraded to CLI version 1.10.3.933, and my git SHA-based deps stopped working in Cursive. Other users on the channel that use the tools-deps library directly report that version 0.12.x also breaks.

Downgrading to older versions of tools deps fixes it.

I'm running Cursive version 1.10.3-2021.2.

**Comment by alexanderkiel** [comment]
Works for me with 1.11.0-eap3. Thanks.
