### ISSUE TITLE
Cursive causes IDE Hang

### ISSUE THREAD

**Issue by awkay** [cursive-ide/cursive#2587]
I reported this to IntelliJ team here, and they diagnosed that Cursive was the problem:

https://youtrack.jetbrains.com/issue/IDEA-278698

**Comment by cursive-ide** [comment]
I think this should be fixed in the latest EAP, 1.12.0-eap2. I never managed to reproduce it but based on the thread dumps from @awkay and @lowecg, I believe it should be fixed. Let me know if I need to reopen this.
