### ISSUE TITLE
Support Evaluating Bookmarked Forms

### ISSUE THREAD

**Issue by finalfantasia** [cursive-ide/cursive#2623]
With [Conjure](https://github.com/Olical/conjure) in [Neovim](https://neovim.io), you can mark a form and evaluate it later using a keyboard shortcut:
> \<localleader\>em[mark]
Evaluate the form under the cursor at the given |mark|. Set a regular Neovim mark on a form using `mF` for example in any file, then jump to another file. You can evaluate that form at any time with `<localleader>emF`.

As can be seen from the documentation, this feature integrates and works with the built-in Neovim bookmark feature. 

As a Cursive user, I would like to take advantage of [the revamped Bookmark feature](https://blog.jetbrains.com/idea/2021/10/intellij-idea-2021-3-eap-2/#new_bookmarks_tool_window) in the latest versions of IntelliJ IDEA and be able to bookmark any form so that I can evaluate it later via a keyboard shortcut. This comes in handy in the context of the [Reloaded Workflow](https://cognitect.com/blog/2013/06/04/clojure-workflow-reloaded) in which a form (usually a function called `reset`) is frequently called to reload a running system with incremental changes.

Slack thread: https://clojurians.slack.com/archives/C0744GXCJ/p1630437334050500

**Comment by cursive-ide** [comment]
I've investigated this a bit, one issue with this is that the bookmarks are per-line, they don't mark a specific offset in the source file. So the evaluation would be of the first form encountered on that line, you couldn't mark a sub-form within a line.

I'm not quite sure how this would be invoked for execution. Since there may be many bookmarks, I guess you would have a shortcut for "Execute a bookmark" and then choose from a popup list of all bookmarks in Clojure source files (with type-to-narrow etc).

**Comment by finalfantasia** [comment]
> So the evaluation would be of the first form encountered on that line, you couldn't mark a sub-form within a line.

I think this is good enough and works in most cases (e.g., evaluating a form on its own line inside a Rich `comment` block or evaluating a `def` that starts on a bookmarked line).

> Since there may be many bookmarks, I guess you would have a shortcut for "Execute a bookmark" and then choose from a popup list of all bookmarks in Clojure source files (with type-to-narrow etc).

Yes, the UI/UX definitely needs some thinking. I'm not sure whether this is possible but if Cursive could leverage IntelliJ IDEA's built-in support for two-stroke keyboard shortcuts (shown below), the user should be able to trigger this action using a keyboard shortcut and specify the bookmark using the second stroke (which would be a bookmark mnemonic). If the user applied the same keyboard shortcut twice in succession (a common pattern in IntelliJ IDEA, e.g., Command + E or Shift + Command + E), Cursive would show the Bookmarks pop-up window (triggered with Command + F3 on macOS) for the user to pick a bookmark to evaluate.

<img width="412" alt="Screen Shot 2021-12-03 at 2 51 50 PM" src="https://user-images.githubusercontent.com/2316604/144683148-26e99c85-96c8-4a2b-b50f-e5ce86aeedc0.png">
