### ISSUE TITLE
leiningen plugin uses Intellij startup directory as working directory 

### ISSUE THREAD

**Issue by matthoffman** [cursive-ide/cursive#264]
I don't know if this is something that can be fixed inside Cursive, but it's worth asking: 
I have a project that is using a private Maven repository that requires a username and password to access. So we wrote a project.clj like this: 
https://gist.github.com/matthoffman/db7575f8b3a16f10d87d

It's looking for an auth.properties file from the project's root directory and loading it, then using that to log into the repository. This works when using Lein from the command line. But when loading that project.clj in Cursive, it looks like Cursive is using <intellij home>/bin as the working directory, and looking for auth.properties there instead of in the project working dir. So as a consequence Cursive throws an exception when trying to load the project.clj. 
I'm assuming, for compatibility, we'd like that behavior to be equivalent between Cursive and lein from the command line. But I know that changing Java's concept of "current working directory" isn't straightforward... 

That gist should be all you need to replicate it. Just put both files in a new directory and try to import with Cursive.

**Comment by roanosullivan** [comment]
I know this issue is closed, but wondering if there are any workarounds available for this issue? I have a similar issue with a lein plugin that needs to read the project.clj, and depends on working directory being the project root.

**Comment by cursive-ide** [comment]
@roanosullivan: This now works for nearly all cases. Can you share the code which is depends on the project root? How is the file being loaded?

**Comment by viesti** [comment]
I had a similar issue, using `ansible-vault` to read a crypted file inside the repository. Solved by looking up the project.clj location from `*file*`, which holds location of file currently being evaluated.
