### ISSUE TITLE
Find usages of in other modules in project

### ISSUE THREAD

**Issue by cap10morgan** [cursive-ide/cursive#2660]
Not sure if this is a bug report or a feature request, but when I try to use Find Usages in a module that is being imported via deps' `:local/root` and is configured as another module in the project, Cursive reports "No usages found in Project Files".

If I manually find a usage in the other module (i.e. the one that has the `:local/root` dep for the other in its `deps.edn` file), and use Go To Declaration it correctly finds the definition in the other module.

I tried using "Refresh Clojure Deps Projects" and "Invalidate Caches" but neither seemed to have an effect.

This is Cursive 1.12.2-eap6-2021.3 on IntelliJ 2021.3.2.

**Comment by danielcompton** [comment]
I can confirm this also happens on 1.12.3-2022.1 in IntelliJ 2022.1.
