### ISSUE TITLE
Unused require removal is broken with Parinfer 

### ISSUE THREAD

**Issue by axelarge** [cursive-ide/cursive#2661]
Whenever an unused require is deleted, it indents lines after the next line by one space, nesting them under the first line's vector.
Naturally, this causes compilation errors.
This only happens in Parinfer mode.

```clojure
;; Before
(ns my.namespace
  (:require [my.foo :as a]
            [my.bar :as b] ;; unused and will get removed by "optimize imports" 
            [my.baz :as c]
            [my.quux :as d]
            [my.other :as e]))

;; After
(ns my.namespace
  (:require [my.foo :as a]
            [my.baz :as c
             [my.quux :as d]
             [my.other :as e]]))

```

**Comment by cursive-ide** [comment]
I believe this is fixed. I just tried to reproduce this and it works as expected now. If I'm missing a case here, let me know and I'll reopen it.
