### ISSUE TITLE
"Error during project resolution: class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode"

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#2667]
When resolving one of the deps.edn projects in our monorepo I get this error from Cursive:

```
The following errors were found during project resolve:
<repo>/<project>/deps.edn:
class java.util.HashMap$Node cannot be cast to class java.util.HashMap$TreeNode (java.util.HashMap$Node and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
```

There's no stack trace or button to report it so I'm not sure where to go from here. I don't think I get this error outside of Cursive, though I'm not sure quite what I'd need to run to reproduce the error.

```
IntelliJ IDEA 2021.3 (Ultimate Edition)
Runtime version: 17.0.1+12-b164.8 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

Cursive: 1.12.2-eap6-2021.3
```

**Comment by danielcompton** [comment]
Clearing my `target` directory stopped the issue from reoccurring, though I'm still not sure why it happened.

**Comment by danielcompton** [comment]
Looks like this is probably a tools.deps issue: https://clojure.atlassian.net/browse/TDEPS-153

**Comment by cursive-ide** [comment]
Yes, it seems to be an sporadic error from the Maven support that deps uses. I'll close this, since it doesn't seem to be Cursive-related.
