### ISSUE TITLE
spec alias shows as not being used when you import it via clojure ns in clojurescript

### ISSUE THREAD

**Issue by ottonascarella** [cursive-ide/cursive#2673]
<img width="598" alt="Screenshot 2022-04-07 at 17 06 54" src="https://user-images.githubusercontent.com/1014206/162287280-b8f1955b-547b-4612-b1b3-1c0e385fd329.png">

if I change the import to `[cljs.spec.alpha :as s]` the warning disappears

**Comment by cursive-ide** [comment]
Good catch, thanks, I'll fix that.
