### ISSUE TITLE
Make Cursive more forgiving in cases of unresolved symbols

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2682]
There is an issue currently where symbols are not being resolved correctly, and the workaround for this requires fiddling with the resolution customisation. Unfortunately, the intention does not appear when the symbol is not resolved correctly. Additionally, if symbols don't resolve correctly, then Cursive will remove imports unnecessarily. If possible, both of these cases should be made more tolerant to unresolved symbols.

**Comment by awkay** [comment]
I got it to start working again by reverting to Nov 29th (install plugin from disk) release of Cursive on 2021.3.2. I did not notice this issue until I updated Cursive past that version of Cursive, if it is any help.
