### ISSUE TITLE
Report raw test results

### ISSUE THREAD

**Issue by wilkerlucio** [cursive-ide/cursive#2687]
When using tests in Cursive that don't use the format `(is (= something something-else))`, Cursive will display the raw results in the tooltip on mouse over:

<img width="581" alt="Screen Shot 2022-05-02 at 21 28 53" src="https://user-images.githubusercontent.com/25736/166346522-4c0b41d2-ee55-49f6-8702-4b038ddcde63.png">

But when trying to click for the error details, Cursive will behave like there is not error there (toggling debugger on that line):

![click-error-details](https://user-images.githubusercontent.com/25736/166351758-1c29ccbb-80ac-41e5-8fc4-3247f62fb598.gif)

Per discussion on Slack, this issue is to suggest that in these cases Cursive should open the raw response in a modal. As an extra, it would be great if this modal supports ASCII colors, so tests running with something like [matcher combinators](https://github.com/nubank/matcher-combinators/) will have a nice output. If we can't color for some reason, would be nice to remove the color markers from the result to improve readability.

**Comment by cursive-ide** [comment]
Note to self: check comes from https://gitlab.com/mauricioszabo/check, which uses matcher combinators under the hood.

**Comment by jtrunick** [comment]
I also have this issue. It just started happening today/yesterday, it worked before just fine.

**Comment by cursive-ide** [comment]
Fix released in 1.13.4-eap5 on 2024-07-11.

**Comment by cursive-ide** [comment]
Fix released in 1.13.4 on 2024-08-06.
