### ISSUE TITLE
"Mark Directory as Sources Root" is lost on "Refresh Clojure Deps"

### ISSUE THREAD

**Issue by nottmey** [cursive-ide/cursive#2693]
https://user-images.githubusercontent.com/6448974/167272892-ab919b4f-3f8f-45f0-b7f6-037558d021c2.mov

Happens on any Deps refresh.

I guess the relevant part ist that the following config is not picked up. One would expect this to be set automatically.
```edn
; deps.edn
{:aliases {:repl {:extra-paths ["repl"]}}}
```

The complete project config can be found here: https://github.com/nottmey/datomic-lacinia/blob/edf9cb45673c7fda5f7f5dd2530715f8a512b4cc/deps.edn

**Comment by nottmey** [comment]
If it helps, that's config related to it. But it does not seem to affect this behaviour.
<img width="1103" alt="Screenshot 2022-05-08 at 00 01 03" src="https://user-images.githubusercontent.com/6448974/167273126-041b178d-2ebd-44ea-8ce7-f6e9d24d4c70.png">
<img width="1000" alt="Screenshot 2022-05-08 at 00 03 48" src="https://user-images.githubusercontent.com/6448974/167273149-214bc6a1-bc67-4c22-bba2-445270115d1e.png">

**Comment by cursive-ide** [comment]
You'll need to configure that alias as described in the doc [here](https://cursive-ide.com/userguide/deps.html#working-with-aliases).

**Comment by nottmey** [comment]
Oh great, that was an easy fix. Thank you!
