### ISSUE TITLE
Alias dependencies are not resolved in editor

### ISSUE THREAD

**Issue by nottmey** [cursive-ide/cursive#2694]
I have this `user.clj` file in folder `repl` next to `src`. This folder is configured as `extra-paths` under an alias which is then used when starting the REPL. In the REPL everything works fine. In the editor though some dependencies are not resolved.

<img width="807" alt="Screenshot 2022-05-08 at 00 07 41" src="https://user-images.githubusercontent.com/6448974/167273295-ad3c4a7c-1746-464c-9e5d-eca9fcb141e0.png">

The project where this occurs can be found here: https://github.com/nottmey/datomic-lacinia/tree/edf9cb45673c7fda5f7f5dd2530715f8a512b4cc

**Comment by cursive-ide** [comment]
As described in #2693, you'll have to configure Cursive to use that alias when synchronising the project.

**Comment by nottmey** [comment]
Oh great, that was an easy fix. Thank you!
