### ISSUE TITLE
Add code author inlay hints

### ISSUE THREAD

**Issue by thumbnail** [cursive-ide/cursive#2698]
IntelliJ can show the code author for functions / methods like this:
![image](https://user-images.githubusercontent.com/4689114/170197762-35b091ad-cdc8-42d2-b4e8-19a7f7b6a8c1.png)

Upon clicking the name, the 'git blame'-sidebar opens on the left of the editor. 

It'd be a very cool addition to Cursive!

**Comment by MarvinLeiers** [comment]
Hi. How can I enable this feature?

**Comment by cursive-ide** [comment]
@MarvinLeiers This is something I will have to fix in code, I have to scheduled for the current EAP series.

**Comment by cursive-ide** [comment]
This is fixed for the next build. I'm not 100% sure that the annotations are in the right places, if there's anywhere else you'd like to see them, let me know.
