### ISSUE TITLE
With IntelliJ/Cursive, why does clojure.test.is treats  empty-string equal to any string

### ISSUE THREAD

**Issue by JoshuaFox** [cursive-ide/cursive#2699]
[See StackOverflow discussion](https://stackoverflow.com/questions/72364215).

Upgrading Cursive from v. 1.12.1-2021.3 to v. 1.12.3-2021.3 solves this.

With Intellij and Cursive's "run tests" feature (green Run arrow on a test or a namespace), a simple unit test in Clojure passes when it finds that "X" equals "". I checked this by replacing "" by "Y" and found that the unit testing system works as expected.  

Full  example:

 ```
   (ns my-test
      (:require [clojure.test :refer [deftest is run-tests]]))
    
    (deftest compare-empty
      (is (= "X" "")))
```

However, if I add `(run-tests)` to the above and run this script directly (as an "application"), the above correctly fails.

**Comment by cursive-ide** [comment]
I just checked that this is fixed in the latest version, including the current EAP which has had significant refactoring in this area, so I'm going to close this one.
