### ISSUE TITLE
Exceptions are not reported correctly in 1.12.4-eap1

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2700]
The following test reports an error at the end of the test run, but doesn't indicate anywhere where the error happened:
```
(deftest foo
  (/ 1 0)
  (is (= 1 1)))
```

Additionally, no exceptions are logged to the console any more.

**Comment by tomasd** [comment]
I have experienced this problem in 1.12.4-eap1. 

I'm not sure if it's the same issue but in 1.12.4-eap2, but in some specific case the error is reported in the function in another namespace:

<img width="613" alt="Snímka obrazovky 2022-05-30 o 12 03 21" src="https://user-images.githubusercontent.com/120671/170969263-92797af1-ddde-4b1e-8e4a-cc47ff978dea.png">

```clojure
(ns my_test
  (:require [clojure.test :refer :all])
  (:require [myproject-shared-app-utils :as utils]))


(deftest my-test
  (utils/gen-data))
```

Here are the files:
```clojure
(ns myproject-shared-app-utils
  (:require
    [clojure.test :refer :all]
    [com.stuartsierra.component :as component]))


(defn gen-data []
  (/ 1 0))
```

Note that `com.stuartsierra.component` in latter is unused, if I uncomment it, then everything works OK. In the real project the namespaces are much longer but it looks like I've experienced the behaviour if there were multiple other function calls, commenting them out "fixed" the reporting.

I can create a new issue if it's not related to this one.

Thank you!
