### ISSUE TITLE
Allow selecting up to date Leiningen versions

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2732]
Currently the Leiningen versions that are available to select from are hard-coded into Cursive. That means that if I forget to update them, or someone is using an old version of Cursive, they cannot access current versions. The hard-coded list should be updated automatically as part of the build process, and it should also be occasionally dynamically checked by the running IDE to allow use of newer versions.

**Comment by PaulaOliveiraM** [comment]
Hi guys, do you know if there is a work around for this? Currently I've a project that only works with Leiningen 2.9.10 and the Cursive plugin for IntelliJ only supports til version 2.9.3

**Comment by makarichevss** [comment]
Yes, same for me - please update Leiningen version
