### ISSUE TITLE
Organize imports removes imported Java classes if method calls use reflection

### ISSUE THREAD

**Issue by Sardtok** [cursive-ide/cursive#2734]
If the only use of a Java class uses an overloaded method that is resolved in runtime, the class is marked as unused and removed by Organize imports. Adding type annotations to arguments to ensure the resolution happens AOT, marks the classes as used, and Organize imports acts fine.

Ran into issues with this using the Elasticsearch Java APIs, where constructors are overloaded for some request classes.

**Comment by cursive-ide** [comment]
Fix released in 1.13.4-eap4 on 2024-07-02.

**Comment by cursive-ide** [comment]
Ugh, sorry, this fix didn't quite fix the problem. The actual fix will be in the next EAP.

**Comment by cursive-ide** [comment]
Fix released in 1.13.4-eap5 on 2024-07-11.

**Comment by cursive-ide** [comment]
Fix released in 1.13.4 on 2024-08-06.
