### ISSUE TITLE
Code vision for references

### ISSUE THREAD

**Issue by wilkerlucio** [cursive-ide/cursive#2741]
Hello, recently I had to do some Java coding and noticed there is code vision for usage all over the place there:

![SCR-20221020-fw0](https://user-images.githubusercontent.com/25736/196978598-e6753e5f-576b-4aec-acf9-c403eb16a1a9.png)

Can we have such annotations on Clojure too?

**Comment by cursive-ide** [comment]
Fix released in 1.13.2-eap5 on 2024-03-07.

**Comment by cursive-ide** [comment]
Fix released in 1.13.2 on 2024-04-04.
