### ISSUE TITLE
Test marked successful in cursive yet fails (correctly) with cognitect test runner

### ISSUE THREAD

**Issue by humphrej** [cursive-ide/cursive#2744]
* See [this repo](https://github.com/humphrej/clj-cursive-test-failure) for a minimal reproduction.
* When the tests are running from the command line using clj -M:test, there are two failures (correct behaviour)
* When the tests are running from cursive then there is only one failure.

Observed with:
* Clojure CLI version 1.10.3.822
* Cursive 1.12.4-2022.1, IntelliJ IDEA 2022.1.4 (Community Edition)
* Cursive 1.12.4-2022.2, IntelliJ IDEA 2022.2.3 (Community Edition)

**Comment by cursive-ide** [comment]
Fix released in 1.13.4-eap5 on 2024-07-11.

**Comment by cursive-ide** [comment]
Fix released in 1.13.4 on 2024-08-06.
