### ISSUE TITLE
Test markers not visible in the gutter

### ISSUE THREAD

**Issue by AndyCorlin** [cursive-ide/cursive#2762]
I'm having the same issue as previously resolved in:
https://github.com/cursive-ide/cursive/issues/2574

I see the markers in versions 1.12.1 - 1.12.3, but no longer in 1.12.4 and above.

My main environment is IntelliJ Ultimate 2022.2.4 with Cursive 1.12.7, but also reproduced in IntelliJ 2021.3.3 with Cursive 1.12.4 and above.

**Comment by AndyCorlin** [comment]
Was curious if this problem was related to https://github.com/cursive-ide/cursive/issues/2723, so I tested the fixed version for the latter, Cursive 1.12.8-eap3-2022.2, but it seems to be two different issues since I still have no test markers in the gutter.

**Comment by AndyCorlin** [comment]
Downloaded EAP-8 and can confirm it's working again!

I'm so happy now!!

**Comment by cursive-ide** [comment]
Great! And my apologies for this taking so long to fix.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1-eap8 on 2023-10-26.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1 on 2023-12-07.
