### ISSUE TITLE
Ctrl+Mousewheel REPL zoom

### ISSUE THREAD

**Issue by aschofie** [cursive-ide/cursive#2766]
Ctrl+Mousewheel is not working for me in the Clojure REPL, although I am able to adjust the font through settings.  Being able to use Ctrl+Mousewheel adjust the font size on the fly is a feature I use everywhere all the time in Intellij and I would really like to see this implemented/fixed in Cursive.

IntelliJ IDEA 2022.3 (Ultimate Edition)
Build #IU-223.7571.182, built on November 29, 2022
Runtime version: 17.0.5+1-b653.14 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0

**Comment by cursive-ide** [comment]
Fix released in 1.13.1-eap9 on 2023-11-27.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1 on 2023-12-07.
