### ISSUE TITLE
Add stub generation support for Specter

### ISSUE THREAD

**Issue by colin-p-hill** [cursive-ide/cursive#2767]
The [Specter](https://github.com/redplanetlabs/specter) library uses [custom macros](https://github.com/redplanetlabs/specter/blob/67e86806020b9d02fbca8cdb1efad3002fc81a32/src/clj/com/rpl/specter.cljc#L57-L65) to define some of its public API. It would be helpful if this library had stub generation support.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1-eap9 on 2023-11-27.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1 on 2023-12-07.
