### ISSUE TITLE
Leiningen task command line parameters with spaces

### ISSUE THREAD

**Issue by ejschoen** [cursive-ide/cursive#2769]
I'm sure this has been asked and answered elsewhere, but I can't find it.  I need to run a Leiningen task that takes command line arguments, and one of those arguments is a token with a space in it.  E.g., "Mapped Term".  I simply can't figure out how to get this from IntelliJ/Cursive's Leiningen task Run/Debug configuration to my running program without the token being split at the space.  I've tried all combinations of quoting the token, putting \ before the space, putting two \ before the space, URI encoding the token, ...  

Is it possible?

**Comment by cursive-ide** [comment]
Fix released in 1.13.1-eap2 on 2023-08-07.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1 on 2023-12-07.
