### ISSUE TITLE
Test failures from matcher-combinators have stopped displaying

### ISSUE THREAD

**Issue by guess-burger** [cursive-ide/cursive#2787]
I recently upgraded my IntelliJ version and therefore my Cursive version. I discovered that tests using [matcher-combinators](https://github.com/nubank/matcher-combinators) have stopped displaying the failure report.

IntelliJ IDEA 2022.1.4 CE with Cursive 1.12.3-2022.1
![image](https://user-images.githubusercontent.com/8173463/232513087-59be9bad-c78d-4d1b-96dd-30693545dfa3.png)

IntelliJ IDEA 2023.1 (Ultimate Edition) with Cursive 1.12.8-2023.1
![image](https://user-images.githubusercontent.com/8173463/232515552-7ebe8876-622e-4609-b0a6-9be766051c75.png)

While the report wasn't perfect, it was readable enough to work with those tests. However, getting nothing from Cursive is forcing me to either run tests only via the terminal _or_ fire-up my old Intellij instance (depending on how heavily matcher-combinators is used).

Related issues
- [My comment](https://github.com/cursive-ide/cursive/issues/2723#issuecomment-1275988733) on #2723 showing the hover to see assertion failure info seeming to break after Cursive 1.12.3. That looked like it was resolved in 1.12.8 which prompted the upgrade
- #2687 asking to view the raw report from matcher-combinators on clicking the gutter icon. Also asks for colour or removal of colour codes to improve readability

**Comment by cursive-ide** [comment]
Fix released in 1.13.4-eap5 on 2024-07-11.

**Comment by cursive-ide** [comment]
Fix released in 1.13.4 on 2024-08-06.
