### ISSUE TITLE
New IDE zoom doesn't affect the REPL-window

### ISSUE THREAD

**Issue by kolstae** [cursive-ide/cursive#2793]
When using the new `IDE zoom` in `IntelliJ 2023.1` the REPL-window is not affected.

This might be related to or duplicate of #2766 and #2726

**Comment by cursive-ide** [comment]
Fix released in 1.13.1-eap9 on 2023-11-27.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1 on 2023-12-07.
