### ISSUE TITLE
REPL Copy to result clipboard doesn't work

### ISSUE THREAD

**Issue by jlangson** [cursive-ide/cursive#2794]
See video https://www.youtube.com/watch?v=aZfvP07Nen0

I enable the option to copy result to clipboard. I enter some commands in the REPL. The output of the REPL does not go into clipboard. Ctrl+v continues to paste the original contents.

**Comment by cursive-ide** [comment]
My apologies for taking so long to look at this. I think this is a misunderstanding about how this works - that setting is for [REPL commands](https://cursive-ide.com/userguide/repl.html#repl-commands), which are a way to create custom commands you can execute and bind to keys. If that option is enabled for a particular command then the results of that command will be copied to the clipboard when it's executed, but it's not a general mechanism for copying the results of any execution in the REPL
