### ISSUE TITLE
Error resolving dependencies

### ISSUE THREAD

**Issue by honzabrecka** [cursive-ide/cursive#2817]
`Error resolving dependencies for <project>`
`org.eclipse.aether.internal.impl.CursiveEclipseLocalRepositoryManager$Provider`

An old project based on leiningen, IntelliJ IDEA 2023.1.3 (Build #IC-231.9161.38, built on June 20, 2023), Cursive 1.13.0-eap5-2023.1

**Comment by andrey-sanchez** [comment]
I have the same issue after updating to `1.13.0-eap5-2023.1`

**Comment by cursive-ide** [comment]
Ugh, sorry about that - I'll fix for the next build.

**Comment by cursive-ide** [comment]
Apologies for the regression, the fix is out now in 1.13.0-eap6.

**Comment by honzabrecka** [comment]
Thank you for quick fix.
