### ISSUE TITLE
REPL is read only

### ISSUE THREAD

**Issue by manish-2014** [cursive-ide/cursive#2830]
Hi

I am using the instructions for configuring and using REP. My issue is that when I start REPL , I do not see the editor panel or tab. I only  see the  read only REPL output tab.  When I start the REPL , (using run configuration) ,I see this output:
Starting nREPL server...

Connecting to local nREPL server...
Clojure 1.10.1
nREPL server started on port 46377 on host 127.0.0.1 - nrepl://127.0.0.1:46377

I do no see any tab or window to interact with the REPL

What am I doing wrong?

I am using Cursive 1.13.0-2022.3 on
IntelliJ IDEA 2022.3.3 RC (Community Edition)
Build #IC-223.8836.35, built on March 8, 2023
Runtime version: 17.0.6+1-b653.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.19.0-50-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Non-Bundled Plugins:
    com.github.copilot (1.2.17.2887)
    idea.plugin.protoeditor (223.8214.6)
    Docker (223.8836.46)
    net.ashald.envfile (3.4.1)
    PlantUML integration (6.3.0-IJ2022.2)
    com.cursiveclojure.cursive (1.13.0-2022.3)

Kotlin: 223-1.8.0-release-345-IJ8836.35
Current Desktop: ubuntu:GNOME

![Screenshot from 2023-08-09 11-50-35](https://github.com/cursive-ide/cursive/assets/8448167/dfe34f10-23ec-45a2-b5fc-16d3fce96e64)
![Screenshot from 2023-08-09 11-57-35](https://github.com/cursive-ide/cursive/assets/8448167/88aa3763-ac1f-4a24-aa22-f25a9fdc868c)

**Comment by gerdint** [comment]
I get a variation of this when the REPL is a bit slow to start:

```Starting nREPL server...
/Library/Java/JavaVirtualMachines/jbrsdk-17.0.4-x64-b469/Contents/Home/bin/java [...]
Connected to the target VM, address: '127.0.0.1:64076', transport: 'socket'
No nREPL connection details received
nREPL server started on port 64413 on host localhost - nrepl://localhost:64413
```

When I then focus the REPL to enter commands, a tooltip says "This view is read-only". And (unlike in Emacs) I do not know how to override this...

**Comment by manish-2014** [comment]
I was able to fix my issue by uninstalling cursive, stopping Intellij ,  deleting all Intellij caches, and re-installing cursive.

**Comment by manish-2014** [comment]
I was able to fix my issue by uninstalling cursive, stopping Intellij , deleting all Intellij caches, and re-installing cursive.

**Comment by gerdint** [comment]
Not very elegant, and unfortunately I did not work for me. I will open a new issue I guess.
