### ISSUE TITLE
Can't create REPL Commands

### ISSUE THREAD

**Issue by conan** [cursive-ide/cursive#2834]
The option to create REPL Commands is greyed out at all times:

![image](https://github.com/cursive-ide/cursive/assets/3037019/9e91909c-6181-41ab-9f8e-49ea96e24b0c)

I bound a key to the Commands shortcut but it doesn't allow access to creating Commands:

![image](https://github.com/cursive-ide/cursive/assets/3037019/da0fc786-a1a9-448b-b85b-19ccf225305e)

This means I'm unable to create REPL Commands.  The problem began when I updated Intellij to 2023.2 and the corresponding Cursive update (my existing REPL commands were lost in this process too).

Expected behaviour: Tools > Repl > Commands menu is available, to allow creation of REPL Commands
Actual behaviour: Tools > Repl > Commands menu is greyed out, so it's not possible to create REPL Commands

Cursive 1.13.0-2023.2
Intellij 2023.2 Build #IU-232.8660.185, built on July 26, 2023
WSLG 
Ubuntu 20.04.6 LTS
WSL version: 1.2.5.0
Kernel version: 5.15.90.1
WSLg version: 1.0.51
MSRDC version: 1.2.3770
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22621.2134

**Comment by cursive-ide** [comment]
In recent Cursive versions (this has not yet made it into the documentation, sorry), REPL commands are managed (created, edited, etc) in the settings at _Preferences | Languages & Frameworks | Clojure | REPL Commands_. That should always be available. The Commands submenu is only available when you have a REPL running.

**Comment by conan** [comment]
Ah!  That's it.  I was able to create my commands from there, and the keymap (which syncs correctly) had also preserved my mappings. 

It looks like the Commands submenu is only available when you have a REPL running and you already have valid commands, so I'm all set apart from #2820

Thanks!
