### ISSUE TITLE
The project has an outdated format on startup

### ISSUE THREAD

**Issue by conan** [cursive-ide/cursive#2835]
Every time I load Intellij, I get a message saying the project has an outdated format and will be converted:

![image](https://github.com/cursive-ide/cursive/assets/3037019/25f30bfe-79eb-40d9-b7b0-ff21f0b8db04)

Clicking on "Details" says the only change will be that REPL run configurations will have their display name defaulted to the run config name:

![image](https://github.com/cursive-ide/cursive/assets/3037019/a74bbf01-79e8-4207-a94b-c4b714e24928)

I always press Convert and it always asks me again next time I start.  I'm not sure how to prevent this from happening?  I'm happy for my run configurations to be named after sprinters or famous fugitives if it helps

Cusive 1.13.0-2023.2

IntelliJ IDEA 2023.2 (Ultimate Edition)
Build #IU-232.8660.185, built on July 26, 2023
Runtime version: 17.0.7+7-b1000.6 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.90.1-microsoft-standard-wsl2
GC: G1 Young Generation, G1 Old Generation
Memory: 8192M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    editor.minimap.enabled=true

Non-Bundled Plugins:
    com.thvardhan.gradianto (5.3)
    com.github.copilot (1.2.18.2908)
    Pythonid (232.8660.185)
    com.cursiveclojure.cursive (1.13.0-2023.2)
    aws.toolkit (1.75-232)

Kotlin: 232-1.9.0-IJ8660.185
Current Desktop: Undefined

**Comment by conan** [comment]
This may be nothing to do with Cursive, but the mention of run configurations made me wonder

**Comment by cursive-ide** [comment]
That's annoying, something must have broken in that migration, I'll look at that.

As a workaround, make sure that your REPL run configs have the Display Name set:

<img width="380" alt="Screenshot 2023-08-18 at 10 49 14" src="https://github.com/cursive-ide/cursive/assets/5589171/c974d7c1-a3b6-4dbd-9a01-1dee5cee5eb8">

That should prevent the migration from being required. Note that the editor will default the field if it's not supplied, so you might have to hit apply even if it looks like nothing has changed. You can hopefully tell which configurations require this by looking in the `projectFilesBackup` folder to see which configs have been migrated.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1-eap4 on 2023-09-19.
