### ISSUE TITLE
REPL is read only (still)

### ISSUE THREAD

**Issue by gerdint** [cursive-ide/cursive#2836]
Similar to issue #2830, but the solution there-in did not work for me and I have still have the below behaviour in my project:

```
/Library/Java/JavaVirtualMachines/jbrsdk-17.0.4-x64-b469/Contents/Home/bin/java [...]
Connected to the target VM, address: '127.0.0.1:64076', transport: 'socket'
No nREPL connection details received
nREPL server started on port 64413 on host localhost - nrepl://localhost:64413
```

When I then focus the REPL to enter commands, a tooltip says "This view is read-only". And (unlike in Emacs) I do not know how to override this...

When I run with a clojure.main REPL it works, the problem is with nREPL (as can be seen above). 

I'm on Cursive 1.13.0-2023.1 on MacOS Big Sur version 11.7.8 (20G1351). Let me know if you want additional details.

In general, I do not think making the REPL read-only is very helpful to start with. Perhaps this issue could be solved by just doing away with that behaviour?

**Comment by gerdint** [comment]
To clarify, the 3rd line of the output (`No ...`) appears a few seconds before the last line.

**Comment by cursive-ide** [comment]
You can adjust the REPL startup timeout when you have a REPL that is very slow to start: _Preferences | Languages & Frameworks | Clojure | REPL Options | REPL startup timeout_.

In Cursive, the REPL input pane is separate from the output pane, see: https://cursive-ide.com/userguide/repl.html#using-the-repl

**Comment by gerdint** [comment]
OK I bumped the timeout and it seems to work now. I can't believe it takes more than 2 minutes to start the REPL (nREPL-based). Since it seems like clojure.main repls are faster, perhaps I should go with that.
