### ISSUE TITLE
Empty horizontal bar/panel at the bottom of the editor

### ISSUE THREAD

**Issue by pflingstring** [cursive-ide/cursive#2848]
Hello, first of all I would like to thank you wholeheartedly for this amazing plugin!

When `cursive` is active, an empty horizontal bar is always displayed at the bottom of the editor.
When you open any (horizontal) tool window e.g. `Git` or `Find`, it's always there on top of the opened window.
I'm attaching a screenshot so that it's hopefully more clear what I mean:
![image](https://github.com/cursive-ide/cursive/assets/6469268/141e60d7-a86e-43ab-a4a9-aa031576e2fa)

When you right click on it, it shows the same menu as when you'd right click on the line numbers panel.
Would it be possible to hide it?

**Comment by pflingstring** [comment]
I have just seen this comment that helped me understand what the issue is: https://github.com/cursive-ide/cursive/issues/2706#issuecomment-1734489366
It turns out that it's the `Breadcrumbs` bar.
It can be disabled from `Actions (Ctrl+Shift+A by default) > View | Active Editor: Show Breadcrumbs`

I'm sorry for opening an unnecessary issue.

**Comment by cursive-ide** [comment]
Yes, that's right - in the latest EAP it appears because I implemented breadcrumbs for EDN, but hadn't finished it for Clojure yet. That's done now and will be in the next EAP.
