### ISSUE TITLE
When sending forms to REPL, they should include any metadata

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2859]
Reported by @timothypratley [by email](https://groups.google.com/g/cursive/c/6Air5oUA-u4/m/Bx7LImxEDgAJ). 

If you send the following via a custom command:

```clojure
^:kind/table
{:rows-vector []}
```

The metadata is lost, and only `{:rows-vector []}` gets sent through.

Metadata should be considered part of the form.

To reproduce the issue:
- Preferences -> REPL Commands
- Add a new command
- Select "Execute command"
- Enter `(handle-form ~form-before-caret)` or similar
- And define `handle-form`

The problem also affects `top-level-form`

The reason this is an important behavior is the rise to popularity of many wonderful visualization tools like Portal that depend on metadata annotations to provide hints at how best to render certain forms and values.

The above example I use the Kindly annotation to indicate the kind of visualization that is appropriate. But when using a custom command to send the form to Portal, the metadata has been stripped, and so it does not display correctly.

Please consider changing this functionality to include the metadata.

**Comment by cursive-ide** [comment]
Fix released in 1.13.1-eap9 on 2023-11-27.

**Comment by timothypratley** [comment]
Thank you! :)
