### ISSUE TITLE
local deps within git deps don't appear correctly in Cursive

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2861]
Reported by @imrekoszo over slack: https://clojurians.slack.com/archives/C0744GXCJ/p1699354581230229?thread_ts=1696509602.605699&cid=C0744GXCJ

> I have an app that git-references libs in a monorepo and some of those libs local/root reference other libs in the same monorepo.
> I found that now those git-then-local libs
> - don't show up in the dependency browser
> - cannot be navigated to
> - aren't on the classpath when I try to launch a "use ide classpath" repl

After some discussion, the change that seems to be needed is that these deps should be added as libs, instead of being removed entirely (which #2845 incorrectly did).

**Comment by imrekoszo** [comment]
One more note to this: before #2845 became an issue, there was only one version of every git->local lib under libraries, the one that tools.deps decided was the resolution winner. In 1.13.1-eap5 (which #2845 was reported on), if I had multiple versions of the same (ultimately local) lib in the pre-resolution dependency tree, I ended up having all of those among modules.

It would be great to have the "IJ classpath" and available libs be the same as what the cli tools would resolve the dep configuration to.

Original screenshot from 1.13.1-eap5, note the duplicate modules:
![image (7)](https://github.com/cursive-ide/cursive/assets/1116295/10df0589-07a2-44b7-91d6-edd245f92a00)
