### ISSUE TITLE
Don't select namespace text when creating a new namespace

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#2881]
Recently, new namespace creation was updated to include the full namespace path, and highlight it. This is helpful, but means that if you create a new file and start typing, you will lose the namespace.

<img width="354" alt="Screenshot of IntelliJ IDEA at 26:02:2024 at 11_04_12 PM" src="https://github.com/cursive-ide/cursive/assets/811954/704d1fbe-8310-4dbd-bc77-e6e2f6fc95b1">

What do you think about deselecting the text, but keeping the cursor at the end? Then people can keep typing to create a file at the current namespace depth, or they can delete parts of the namespace if they want to go further up?

<img width="345" alt="Screenshot of IntelliJ IDEA at 26:02:2024 at 11_04_18 PM" src="https://github.com/cursive-ide/cursive/assets/811954/e01e309f-6882-49f4-88fe-44fbb8568173">

**Comment by k7d** [comment]
+100, the new behaviour is highly irritating and the muscle memory factor is strong. I personally end up creating new namespaces in root more than half the time.

**Comment by cursive-ide** [comment]
Fix released in 1.13.2-eap5 on 2024-03-07.
