### ISSUE TITLE
defn and friends not recognised in CLJS buffers (Shadow-CLJS, deps.edn)

### ISSUE THREAD

**Issue by gerdint** [cursive-ide/cursive#2888]
Cursive appear to be confused over basic CLJS forms for me (see screenshot). I am aware that Shadow-CLJS support is spotty but is it really the case that unresolved deps break basic language forms like `defn`? (and with that its indetation rules etc). I have my CLJS deps managed via Shadow's deps.edn support, as this will make Cursive resolve the non-NPM ones it seems.

<img width="826" alt="cursive cljs" src="https://github.com/cursive-ide/cursive/assets/14966/86118398-12e3-4092-a394-accfe0cba240">

I use IntelliJ IDEA 2023.3.4+Cursive 1.13.1-2023.3

**Comment by gerdint** [comment]
@cursive-ide Do you need more info here (deps.edn or such?) or have any idea of what's up?

**Comment by cursive-ide** [comment]
@gerdint There's a section in the doc dealing with problems like this: https://cursive-ide.com/userguide/troubleshooting.html#help-lots-of-symbols-don-t-resolve. In your case, I suspect the project is not added correctly (step 3). Could you check that and let me know what you find?

**Comment by gerdint** [comment]
@cursive-ide I checked the stuff in the user guide and no progress. It's a full-stack project and all the CLJ files are fine.
As you can see some stuff in the above CLJS file is resolved, but odd that core forms like 'defn' and 'let' are not I think.

**Comment by cursive-ide** [comment]
Could you try _File | Cache Recovery | Repair IDE_ and follow the steps there to see if that helps?

If not, could you send a screenshot of your deps toolwindow with the dependencies expanded?

**Comment by gerdint** [comment]
I only have _File | Repair IDE_ and _File | Invalidate caches_. I tried them with same result.
Do you want to expand the whole deps tree? That looks like 10 screenfuls of content, onerous to screenshot! But below you have the non-expanded view:
<img width="452" alt="Skärmavbild 2024-03-28 kl  11 05 03" src="https://github.com/cursive-ide/cursive/assets/14966/a1063d71-1ea4-44bb-818e-3662369b381c">
<img width="448" alt="Skärmavbild 2024-03-28 kl  11 06 07" src="https://github.com/cursive-ide/cursive/assets/14966/62cc0a2e-604b-4239-bd04-a74bce222237">

**Comment by cursive-ide** [comment]
What I don't see in that list is ClojureScript itself. If you go to _File | Project Structure_, then choose Modules and select your problematic module, does it have the ClojureScript library attached under Dependencies?

**Comment by gerdint** [comment]
Good catch! I put shadow-cljs with its dependancy on clojurescript under a _cljs_ alias in my deps.edn, which was not selected in the deps aliases sidebar. I selected it and now all the core CLJS forms are indeed resolved! Now it's just the NPM deps and DOM API functions which are not resolved, and there are already existing issues for that I believe. Cheers!

**Comment by gerdint** [comment]
@cursive-ide Some more docs on how to work with CLJS projects (such as the Shadow deps.edn hack) would be good I think (though I admit that in this case I was pretty stupid).

**Comment by jjtolton** [comment]
This worked for me as well.  Apparently the clojurescript deps tucked in an alias in `deps.edn` doesn't work, it needs to be in the top level `:deps` key.
