### ISSUE TITLE
Can't see text typed in REPL

### ISSUE THREAD

**Issue by karaal** [cursive-ide/cursive#2913]
This happens in Cursive 1.13.3-2024.1 on macOS. When REPL is started I can't see text I type in interactive environment. However, when I blindly put some expression and eveluate it, typed text suddenly appears.

https://github.com/cursive-ide/cursive/assets/8842882/3c40c953-ce01-4ec9-808e-658e962c773a

**Comment by cursive-ide** [comment]
One thing that is unusual in Cursive is that the REPL input pane is at the bottom of the REPL toolwindow, you can see how it should look here: https://cursive-ide.com/userguide/repl.html#using-the-repl. Sometimes that input pane can become very small (like 1 pixel high), I've never managed to reproduce it or figure out why. But if that's the case, you should be able to click near the bottom and drag the separator up.

**Comment by karaal** [comment]
Yes, that was the case. The input was squashed down at bottom of REPL toolwindow. Thanks.
