### ISSUE TITLE
Cannot press Escape to remove all highlighting, also in all other languages than Clojure

### ISSUE THREAD

**Issue by luontola** [cursive-ide/cursive#2923]
After you use "Highlight Usages in File" (Cmd+Shift+F7) to highlight some variables, normally you should be able to press Escape to remove all highlightings. But when Cursive 1.13.4-eap6-2024.1 is installed, pressing Escape does nothing. This problem happens also in other languages, such as TypeScript, as long as the Cursive plugin is enabled.

**Comment by cursive-ide** [comment]
Hmm, I'll check this, I suspect this is because of the escape handling for the new inlay feature.

**Comment by cursive-ide** [comment]
Indeed, that was the problem, this is fixed for the next build.

**Comment by cursive-ide** [comment]
Fix released in 1.13.4-eap7 on 2024-07-17.

**Comment by luontola** [comment]
@cursive-ide This problem seems to have reappeared in 1.13.4-2024.2

**Comment by cursive-ide** [comment]
Arg, my apologies - eap12 contained a fix for an exception from the tracker, and that has broken this again. This is difficult to provide automated tests for unfortunately. I'll fix this and get a release out.
