### ISSUE TITLE
Failure details not reported for assertions inside fixtures

### ISSUE THREAD

**Issue by samharad** [cursive-ide/cursive#2929]
- failed `is` assertions made inside fixtures don't surface any details
- I think it's a legitimate use case to make assertions there, e.g. about environment health

```clojure
(ns cursive-hook-test
  (:require [clojure.test :refer :all]))

(use-fixtures :each
              (fn [f]
                (f)
                (is false)))

(deftest foo-test
  (is (= 1 1)))
```

<img width="1401" alt="Screen Shot 2024-07-18 at 1 47 07 PM" src="https://github.com/user-attachments/assets/f2c81e25-aa1d-45ef-a2e4-859b64662825">

**Comment by cursive-ide** [comment]
Fix released in 1.13.4 on 2024-08-06.
