### ISSUE TITLE
Cannot upgrade to 1.13.4-eap8 due to wrong version tag

### ISSUE THREAD

**Issue by Sardtok** [cursive-ide/cursive#2933]
When trying to upgrade to eap8, I get the following error.

![Screenshot-2024-07-24 09-21-53](https://github.com/user-attachments/assets/5ba80947-deea-4b63-b40e-e13c91c174f0)

The Plugin Updates window shows the correct version, but I'm guessing the manifest and pom contains the wrong version number.
![Screenshot-2024-07-24 09-23-51](https://github.com/user-attachments/assets/de8e02ed-0e53-4985-8b65-be9bd8b6a842)

**Comment by cursive-ide** [comment]
That's very strange. I'm pretty sure the archive is ok, the JetBrains marketplace isn't complaining about it and is showing the correct information. Could you try manually downloading it from https://plugins.jetbrains.com/plugin/8090-cursive/edit/versions/eap, and then doing Install Plugin from Disk to try installing it manually?

**Comment by Sardtok** [comment]
Downloading and installing manually fixed the problem. Strange that IntelliJ would download the old stable release instead of the EAP.

**Comment by cursive-ide** [comment]
Do you have _Settings | Languages & Frameworks | Clojure | Update Options | Check for EAP builds_ selected?

**Comment by Sardtok** [comment]
Yes. I did not manually upgrade to EAP7 before trying to upgrade to EAP8.

**Comment by cursive-ide** [comment]
I'm really not sure what happened here. However, I don't think it's anything that I could fix in Cursive, so I'm going to close this. Let me know if this continues to be an issue with future releases.
