### ISSUE TITLE
Shell escape codes for colors not working in REPL

### ISSUE THREAD

**Issue by Sardtok** [cursive-ide/cursive#2934]
After I upgraded from 1.13.4-eap3 to 1.13.4-eap7, I noticed my REPL is full of shell escapes for coloring.

Unsure if this is a duplicate of #2932 as I cannot upgrade to eap8, see #2933.

**Comment by cursive-ide** [comment]
Yes, I'm pretty sure that is #2932, which is fixed in eap8. I'll close this, but do let me know if it continues to be a problem once you're on eap8.
