### ISSUE TITLE
Show directory in editor tabs for non unique file names

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2946]
Reported by @serioga in Slack:

> Is it possible to “show directory for non-unique file names” for Clojure files in editor tabs, when I choose Editor tab style: File name in Cursive settings?
>
> Now it looks odd:
![2024-08-12_224123](https://github.com/user-attachments/assets/00452540-3426-4013-a079-72ea4270da87)

**Comment by cursive-ide** [comment]
This is fixed for the next EAP release. I've changed the "File name" style to just be called "Default", which will use the default IntelliJ naming. This shows the file name, but will also disambiguate using folders if required. It's also more customisable, it has a bunch of config options at _Settings | Editor | General | Editor Tabs_.

**Comment by serioga** [comment]
It works great.

**Comment by cursive-ide** [comment]
Fix released in 1.14.0 on 2024-11-13.
