### ISSUE TITLE
Inline REPL results are causing a line wrap

### ISSUE THREAD

**Issue by jdhollis** [cursive-ide/cursive#2958]
Hi, Colin.

Just started using 1.14.0-eap1-2024.2 with IntelliJ IDEA 2024.2.1.

I like the inline REPL results (though it’s taking some getting used to).

Running into a visual issue—

![Screenshot 2024-09-13 at 5 04 03 PM](https://github.com/user-attachments/assets/6a7f59a3-b532-4580-8dd5-ba0b9e3ebfcf)
![Screenshot 2024-09-13 at 5 04 10 PM](https://github.com/user-attachments/assets/e6ed4c7f-6fc0-41cd-8345-af5b3da3ec28)

Functions are getting wrapped at their alias when I send to the REPL. And they remain that way after I escape out of the inline output. If I hit a newline after the expression, the view corrects itself and removes the wrap.

Happy to provide any additional information (though at the moment, I don’t know what else would be useful).

**Comment by jdhollis** [comment]
More screenshots (before and after hitting escape)—

![Screenshot 2024-09-13 at 5 22 12 PM](https://github.com/user-attachments/assets/d20bfbdd-048a-4d5b-81e5-36ca5d257517)
![Screenshot 2024-09-13 at 5 22 24 PM](https://github.com/user-attachments/assets/ce8f2530-01ef-4cd5-9a3d-b110544fb984)

**Comment by cursive-ide** [comment]
I see, looks like you have soft wraps on, right? @imrekoszo also reported a problem with that, but I haven't got to looking at it yet.

**Comment by jdhollis** [comment]
Yep. I’ve got soft wrap on.

**Comment by jdhollis** [comment]
Really liking this feature. Especially the ability to drill down into the return data.

![Screenshot 2024-09-15 at 7 24 23 PM](https://github.com/user-attachments/assets/67caa252-5849-4a07-9e4b-606b511cbb09)

**Comment by imrekoszo** [comment]
> I see, looks like you have soft wraps on, right? @imrekoszo also reported a problem with that, but I haven't got to looking at it yet.

Yep, this is the same as I reported at https://clojurians.slack.com/archives/C0744GXCJ/p1725270101089459?thread_ts=1725263381.140519&cid=C0744GXCJ

Minor annoyance only, the feature is great.

**Comment by cursive-ide** [comment]
Ok, I believe this is fixed for the next build.

**Comment by cursive-ide** [comment]
Fix released in 1.14.0-eap2 on 2024-11-08.
