### ISSUE TITLE
repl inline evaluation does not take effect.

### ISSUE THREAD

**Issue by swuecho** [cursive-ide/cursive#2960]
![image](https://github.com/user-attachments/assets/7a1ef046-b433-49fb-8b7f-b48e31e34320)

First time to try out cursive IDE(mostly for the inline eval feature), but can not get it work properly. Does I miss some obvious? Thanks.

**Comment by swuecho** [comment]
![image](https://github.com/user-attachments/assets/542e9c4e-7028-419b-b835-d1ba263d91f3)

**Comment by cursive-ide** [comment]
I can't see anything obvious wrong there. Are you executing the forms from the editor as described here: https://cursive-ide.com/userguide/eap/repl.html#interaction-with-the-editor? i.e. using e.g. Send Top Form to REPL?

**Comment by swuecho** [comment]
If I send the the form to the repl, the result is displayed inline. I thought the default behavior is auto eval (watching mode). 
Does watch mode supported?

**Comment by cursive-ide** [comment]
No, there is no auto-eval mode. I'm planning to add watches, where the inline value will be updated, but there won't be a lighttable-style auto eval mode.
