### ISSUE TITLE
Inline REPL results ignores zoom level

### ISSUE THREAD

**Issue by kolstae** [cursive-ide/cursive#2961]
The new inline REPL results are great!

However the results are not following the zoom of the IDE when not on the same line:

Here's a screenshot of zoom 200% to illustrate
![screenshot-20240918-135324](https://github.com/user-attachments/assets/06116485-3f81-47c7-bd16-29de3f6b7d39)

**Comment by cursive-ide** [comment]
Fix released in 1.14.0-eap2 on 2024-11-08.
