### ISSUE TITLE
Serialization error in exceptions

### ISSUE THREAD

**Issue by souenzzo** [cursive-ide/cursive#2963]
Version: `1.14.0-eap1-2024.1`

this didn't happen before. It was introduced in this new release of "inline eval results"

Having some non-serializable values in exception data (like a regex) causes the REPL to throw  `Error handling response - class java.lang.RuntimeException: No dispatch macro for: "`

From the exception, the root of this issue may be nrepl actually. 

<img width="767" alt="Screenshot 2024-09-26 at 09 20 21" src="https://github.com/user-attachments/assets/8aea8948-a52f-4cf0-92f6-94b3e8996b5e">

Clojure: 1.11.3
JVM: adopt-11, graal 21, open 22  ...

**Comment by cursive-ide** [comment]
Thanks, this is fixed for the next build. The issue was that Cursive was parsing the exceptions as EDN, which doesn't support regexes.

**Comment by cursive-ide** [comment]
Fix released in 1.14.0-eap2 on 2024-11-08.
