### ISSUE TITLE
Stacking multiple #_ isn't shown as a comment

### ISSUE THREAD

**Issue by djpowell** [cursive-ide/cursive#2964]
I often use #_ #_ to comment out the next two symbols, such as in a map.  I thought that this used to display correctly in Cursive, but it doesn't seem to in 1.14.0-eap1-2024.2.

Eg:

```clojure
(let [a 1
      #_#_ b 3])
```
I also notice, that Reformat Code, removes whitespace after the #_ token, I'm not sure if that is intended.

**Comment by cursive-ide** [comment]
Thanks, this is fixed for the next build.

**Comment by cursive-ide** [comment]
Fix released in 1.14.0-eap2 on 2024-11-08.
