### ISSUE TITLE
Datalevin datom doesn't support empty function

### ISSUE THREAD

**Issue by cursive-ide** [cursive-ide/cursive#2970]
Reported in Slack by @simongray here: https://clojurians.slack.com/archives/C0744GXCJ/p1727946413145859

> I’m trying out Datalevin. Unfortunately, Cursive won’t let me view the exception I’m getting. Cursive seems to crawl the exception before outputting it, so I get a runtime exception caused by Cursive calling an unsupported method instead of the ex-info I would like, e.g.

![Skærmbillede 2024-10-03 kl  11 06 10](https://github.com/user-attachments/assets/5e45dec1-bbc3-4118-9624-ea78a6c4c4f4)

**Comment by cursive-ide** [comment]
After some discussion in Slack, I've filed https://github.com/juji-io/datalevin/issues/286 which should fix this in Datalevin. In the meantime I'll catch errors when walking the exception and just return the raw data in case of an error.

**Comment by cursive-ide** [comment]
@simongray This has been fixed upstream in datalevin.

**Comment by simongray** [comment]
@cursive-ide Thank you. Yes I noticed that too, just waiting for a new release of Datalevin now :)

**Comment by cursive-ide** [comment]
I'm going to close this, let me know if there's reason to reopen it.

**Comment by cursive-ide** [comment]
Fix released in 1.14.0-eap2 on 2024-11-08.
