### ISSUE TITLE
Cursive IDE Not Highlighting Consecutive #_#_ Discarded Expressions Properly

### ISSUE THREAD

**Issue by juskrey** [cursive-ide/cursive#2972]
**Steps to Reproduce:**

1. Add two consecutive forms, e.g., `(+ 1 1) (+ 2 2)`.
2. Comment both forms using `#_#_`, like so: `#_#_(+ 1 1) (+ 2 2)`.

- **Expected Result:** Both forms should be grayed out or styled to indicate they are commented out.
- **Actual Result:** Only the first form `(+ 1 1)` is highlighted as a comment, while the second form `(+ 2 2)` retains normal code styling.
- **Workaround:** Currently, none identified; each form has to be individually commented to achieve proper syntax highlighting.
- **Impact:** This issue affects readability and may cause confusion regarding which parts of the code are actively commented out, especially in complex code blocks.

**Comment by cursive-ide** [comment]
This is a dupe of #2964, which is fixed for the next build.
