### ISSUE TITLE
spell checker does not work on .clj files

### ISSUE THREAD

**Issue by KevinCorcoran** [cursive-ide/cursive#298]
Specifically, I would like my docstrings to be spell-checked.  I fiddled with all the settings and there doesn't seem to be a way to make it happen.

**Comment by bilekt3** [comment]
I am voting for this - I am not native English speaker and spell checking helps me keep at least typos out of Docs and Comments

**Comment by aadrian** [comment]
The built in (IntelliJ) spell checker is still quite broken, and there are many issues that were not yet solved:
https://youtrack.jetbrains.com/issues?q=%23SpellChecker

**Comment by bilekt3** [comment]
This issue is still open @cursive-ide do you have any ETA to deliver this. I hope that I am not alone to wanted this?

**Comment by bilekt3** [comment]
Please, please, please - this longstanding issue is very annoying. As not native speaker collaborating with native speakers I am really tired to switching to other programs to ensure spelling!

**Comment by cursive-ide** [comment]
Sorry this one has been ignored for so long - it'll be in the next EAP build.

**Comment by d-t-w** [comment]
Preferences -> Editor -> Inspections -> Spelling -> Typo for those who want to turn this off.
