### ISSUE TITLE
"Internal error: cannot patch the selected configuration" when running debugger

### ISSUE THREAD

**Issue by wmkroo** [cursive-ide/cursive#2995]
Using IntelliJ 243.21565.193 and Cursive and Cursive 1.14.0-2024.3, I am getting "Internal error: cannot patch the selected configuration" when I attempt to run unit tests in the debugger. Some of my team mates also have the same issue, so it's not unique to my system. Downgrading to IntelliJ 2024.2.4 apparently fixes the problem.

**Comment by cursive-ide** [comment]
This appears to be caused by an [IntelliJ bug](https://youtrack.jetbrains.com/issue/IJPL-172742). I've added an awful workaround, so this should work now, but hopefully they fix it soon.

**Comment by cursive-ide** [comment]
Fix released in 1.14.1-eap1 on 2024-12-11.

**Comment by cursive-ide** [comment]
Fix released in 2025.1 on 2025-04-16.
