### ISSUE TITLE
Feature Request: Warn when namespace doesn't match Filename

### ISSUE THREAD

**Issue by deaddowney** [cursive-ide/cursive#317]
This bit me in the butt yesterday.  It would be nice if Cursive could see if your namespace matched the name of the file it is in and warn if they didn't match

e.g.

in file fred.clj
src/main/my_ns/fred.clj

(ns my-ns.joe)  <warn  here

**Comment by danielcompton** [comment]
Just for completeness, this inspection should also check the path that it lives in.
