### ISSUE TITLE
Structural Movement/Editing problems & get on par with Emacs paredit

### ISSUE THREAD

**Issue by gerrit-hntschl** [cursive-ide/cursive#359]
All in all structural editing & movement works pretty well, good job! But there are some edge cases that are a bit annoying:
- When the cursor is at the last position in a file/REPL then you cannot use `move backward` (which I permanently try to do: Jump to the end of the file and then move backwards up).
- Structural Movement does not work in dependencies/external libraries. 
- Structural Editing Kill differs from Emacs paredit in that it kills all forms that start on the same line instead of just the next form. The Emacs behavior makes more sense in my opinion, as it allows to chain kills easily, while currently one has to move the second form to a newline before killing and then join the lines back together.
- paredit has `transpose-sexps (C-M-t) - swap the sexp before point with the sexp after point.` which would be really nice to have in Cursive as well!

Cheers!

**Comment by tsmacdonald** [comment]
This is very useful, but subtly different from `transpose-sexps` in a kind of irritating way:

Given (where `|` is the cursor):

   (foo)
   (bar [order | out-of])

In Emacs transposing sexps yields:

    (foo)
    (bar [out-of | order])

whereas IntelliJ will have

    (bar [order | out-of])
    (foo)

**Comment by cursiveclojure** [comment]
I can't reproduce this - I suspect that you're actually executing the IntelliJ action, not the Cursive one. Can you go to Settings->Keymaps and check which actions are bound to the key you're using?

**Comment by tsmacdonald** [comment]
Ah, everything is great with the `Move Form Up` command, which I bound to `C-M-t`.

**Comment by tsmacdonald** [comment]
Thanks anyway

**Comment by cursiveclojure** [comment]
Great, glad it's working.

**Comment by cursiveclojure** [comment]
@tsmacdonald  BTW note that you can bind the Move Form Up/Down to the same key as the IntelliJ equivalent actions if you like - the Cursive action will be executed in Clojure contexts, and the IntelliJ one will be executed in other contexts (e.g. Java).

**Comment by Bagnall** [comment]
I'm very much a noob, but I'm having problems with slurp/barf backwards. I believe I set it up correctly in settings / keymap, having removed any other definition for those key combos, checking them in the Clojure keybindings and applying. (No conflicts shown in the Clojure pane).
