### ISSUE TITLE
datomic.api namespace is not loaded

### ISSUE THREAD

**Issue by laurio** [cursive-ide/cursive#38]
```
(ns bar.core
  (:require [datomic.api :as d]))
```

shows two issues in file editor: "datomic cannot be resolved" and "datomic.api cannot be resolved".

In repl

```
(require [datomic.api])
```

throws

```
CompilerException java.lang.ClassNotFoundException: datomic.api, compiling:(NO_SOURCE_PATH:1:1)
```

However

```
(require '[datomic.api])
```

executes without issues and I can use the datomic.api namespace functions after that in repl. But it won't help in file editor as datomic.api functions would be still unresolved and as a result it is not possible to use "Load file in REPL" command.

**Comment by wilkerlucio** [comment]
@cursiveclojure I was going to try this here now and I realised I don't have the `mvn` command installed on my system, which would be the proper way to set it up? I'm not sure if I can install `brew install maven` or `brew install mvnvm` or other thing, could you clarify this please?

**Comment by cursiveclojure** [comment]
See [here](http://stackoverflow.com/a/17481557/155368), looks like that should work.

**Comment by wilkerlucio** [comment]
Thanks, that works :+1:
