### ISSUE TITLE
(ns ... (:require [... :rename {a b}]) not handled

### ISSUE THREAD

**Issue by fbellomi** [cursive-ide/cursive#394]
Hi,
when I use

(ns ... (:require [... :rename {a b}]) 

b is marked as unresolved in the rest of the code

**Comment by MerelyAPseudonym** [comment]
Bumping this issue! =)

By the way, since the Eastwood repo has changed since this issue was first opened, here's a link to the line that fbellomi was probably talking about: <https://github.com/jonase/eastwood/blob/706e9bb85548ab3a82d5ee8c33b5555844a14b1d/src/eastwood/analyze_ns.clj#L15>.

**Comment by n2o** [comment]
This issue still persists (tested in a ClojureScript project)

![screenshot-20190108-155207](https://user-images.githubusercontent.com/1507474/50838035-5de9cb00-135d-11e9-95d0-0a5c2924c134.png)

`doc` appears to be not available as `d`. In Figwheel this is then no problem, only the IDE highlights this as unresolved in further usage.

**Comment by ichramm** [comment]
Hi,

Bumping again since it is still happening.

Tested in both Clojure and ClojureScript.

![image](https://user-images.githubusercontent.com/487268/84073892-04e5f280-a9a8-11ea-8bf5-4eb99ec8ee07.png)
