### ISSUE TITLE
0.1.28 Breaks separate head symbol highlighting 

### ISSUE THREAD

**Issue by dannypurcell** [cursive-ide/cursive#404]
After taking the latest patch this morning I noticed the syntax highlighting for head symbols no longer differentiates between symbols defined in clojure.core and those defined elsewhere. 
- Open IDE Settings > Editor > Colors & Fonts > Clojure
- Select a color for `Head Symbol`
- Set a different color for `Head Symbol from clojure.core`
- Apply and close settings
- Add the following to an open editor window

```
(defn
#^{:doc "mymax [xs+] gets the maximum value in xs using > "
   :test (fn []
             (assert (= 42  (max 2 42 5 4))))
   :user/comment "this is the best fn ever!"}
  mymax
  ([x] x)
  ([x y] (if (> x y) x y))
  ([x y & nil]
   (reduce mymax (mymax x y) more {\tab "  "})))
```

The head symbols `fn`, `assert`, `=`, `max`, `if`, `>`, and `mymax` will be the same color as `defn` and `reduce`.
##### Workaround
- Open IDE Settings > Plugins 
- Select Cursive > Uninstall plugin
- Restart IntelliJ
- Download http://cursiveclojure.com/cursive-13.1-0.1.27.zip
- Open IDE Settings > Plugins 
- Select Instal Plugin from disk > Select `<download_location>/cursive-13.1-0.1.27.zip`
- Restart IntelliJ
- Verify color settings display correctly

**Comment by martinhynar** [comment]
FYI: This same error just occurred for me on version 0.1.42. I changed color scheme to darkula and bum! Upgrading to 0.1.44 fixed it.
