### ISSUE TITLE
Losing custom project modules definitions every time I the project

### ISSUE THREAD

**Issue by wilkerlucio** [cursive-ide/cursive#421]
Hi,

I'm working a lot using both Clojure and ClojureScript, and for that I use this folder structure:

![](http://i.imgur.com/oMkOX3S.png)

But every time I close the project, and open it again, Cursive undo my module definitions and I get this:

![](http://i.imgur.com/H034VyP.png)

Is not a big deal, but it's very annoying that I have to re-setup that every time I open the project...

**Comment by cursiveclojure** [comment]
BTW there's now a warning in recent versions of Cursive when you open a file that's not under a source root. It will allow you to mark the correct directory as a source root, but it doesn't do anything lein-specific at the moment.

**Comment by alebellu** [comment]
Hi,

I think that :java-source-paths is also not detected in project.clj
I have a mixed language project and I have to re-select the source root
for the java source folder every time I close and reopen the project.

BTW, it is the first time I write here but I have been using Cursive for a
while and it is great, thank you!

Alessandro
