### ISSUE TITLE
ToolWindow icons should be 13x13

### ISSUE THREAD

**Issue by itegebo** [cursive-ide/cursive#456]
I get warnings on startup:

> WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix jar:file:/home/user/.IdeaIC13/config/plugins/clojure-plugin/lib/cursive.jar!/cursive/icons/clojure_icon_16x16.png  
> WARN - openapi.wm.impl.ToolWindowImpl - ToolWindow icons should be 13x13. Please fix jar:file:/home/user/.IdeaIC13/config/plugins/clojure-plugin/lib/cursive.jar!/cursive/icons/project.png

**Comment by danielcompton** [comment]
This can probably be closed now?

**Comment by cursiveclojure** [comment]
No, it's still open, I haven't fixed it because it doesn't actually affect anything important.
