### ISSUE TITLE
Dependency cycle check on namespace load should only check project, not libs

### ISSUE THREAD

**Issue by cursive-ghost** [cursive-ide/cursive#535]
Some libs (e.g. [manifold](https://github.com/ztellman/manifold/blob/master/src/manifold/stream.clj#L647-L651)) do some pretty crazy things.

**Comment by hadronzoo** [comment]
I'm seeing dependency cycle errors with manifold's `time.clj` in Cursive 1.2.1.

**Comment by rborer** [comment]
Same issue than reported by @hadronzoo with version 1.2.1 :cry:

**Comment by shmish111** [comment]
This is a major issue for us :(

**Comment by agofilo** [comment]
I have encountered the same erroro working with budu/lobos. As now i cannot load any files in the repl that has lobos.connectivity as dependency. There is a way to disable the dependency check in Cursive?

**Comment by cursive-ide** [comment]
See #1298 for the workaround.

**Comment by agofilo** [comment]
Thank you. This works for me.
