### ISSUE TITLE
Unable to modify / save Clojure -> Keybindings

### ISSUE THREAD

**Issue by Frizzled** [cursive-ide/cursive#552]
Clojure -> Keybindings (for me) cannot be saved or changed. None of the left-most check boxes can be selected. If I choose a Binding Set from the top drop-down the mapped keys do not save.

I've have the same problem with IntelliJ 12 & 13 ... I switched to La Clojure and had no problems saving keybindings.

**Comment by ricardojmendez** [comment]
For what it's worth, @chmllr's comment of "I really understood this settings panel as a stateful UI screen." applies to me as well. I had to come to this issue to figure out why I couldn't actually select any of the checkboxes on the left on *Other Settings > Clojure > Keybindings*.   

Perhaps a brief text clarifying it would be in order.

**Comment by cursiveclojure** [comment]
Yes, this UI has been clarified in the latest version. However IIRC you're on v12, right @ricardojmendez? Since v12 doesn't receive changes any more you might not have seen this.

**Comment by ricardojmendez** [comment]
I actually switched to v14 just yesterday. Congratulations @cursiveclojure, you sold me an upgrade.

**Comment by cursiveclojure** [comment]
Nice! So did you find the UI on that panel still confusing in v14? Actually, I see that you did, since that's the v14 config panel location. I'll see if I can add some clarifying text to the panel itself.

**Comment by cursiveclojure** [comment]
Oh, and in case you haven't seen it, the doc is [here](https://cursiveclojure.com/userguide/keybindings.html), feedback also welcome on whether that helps or not.

**Comment by ricardojmendez** [comment]
That does clarify it, and I did read it after, but in time-honored fashion I didn't go for the documentation first.  Maybe linking to that page from the panel would help those who go there first and are baffled that it seems read-only.

**Comment by patrickaroo** [comment]
I also experienced this situation just as described above.  Thank you for describing the approach we should take; I worry for those getting into Clojure who might not figure out how to find this issue.

**Comment by grantpeltier** [comment]
This is still an issue in IntelliJ 2016.2.4 using Cursive 1.6.0-2016.2. When viewing the Settings -> Keymap -> Clojure Keybindings screen, the "Apply" button is disabled. Changing the "Binding Set" from "None" to "Cursive" does nothing. "Apply" is still disabled and clicking "OK" does not register any changes and the keybindings state does not change. I am not able to actually apply the "Cursive" binding set until I change some other key binding (which enables the "Apply" button), and then change the the "Binding Set" dropdown to select the "Cursive" set.

**Comment by krisleech** [comment]
IntelliJ 2017.3.2 - I see no "Clojure" option to select in Settings -> Keymap.
