### ISSUE TITLE
REPL window - ESC key binding conflicts with IdeaVIM

### ISSUE THREAD

**Issue by evmin** [cursive-ide/cursive#647]
When in REPL mode ESC closes REPL window. This conflicts with IdeaVIM, where ESC is used to switch from "insert" to normal mode.

Suggested alternative is to follow the general IntelliJ IDEA practice of having a dedicated shortcut to toggle REPL window. I.e. if pressed when the REPL window is not visible to bring one up, and if REPL window is visible to close it.

**Comment by awebneck** [comment]
I'm also suffering from this issue - @evmin, is there a workaround?

**Comment by ronbu** [comment]
Had the same issue. I just use CTRL-C which has the same effect without changing the focus.

**Comment by cursive-ide** [comment]
As of IntelliJ 2019.3, this behaviour can be configured in IntelliJ. The jumping from toolwindows back to the active editor is now controlled by the Focus Editor action, which can be remapped like any other.

Since this seems like an acceptable workaround, I'm going to close this issue.
