### ISSUE TITLE
Reformatting doesn't reflow doc strings

### ISSUE THREAD

**Issue by yatesco** [cursive-ide/cursive#653]
and it would be awesome if it did ;).

IntelliJ's "reformat code" works well except for comments. Is there a
way to force these to wrap at X characters, ideally calculating the
wrapping every time?

For example, it would be great if it could take the following:

;; this is a long sentence<X> and would be great if<X> it wrapped

and turn it into

;; this is a long sentence,
;; and would be great if
;; it wrapped

then if I did the following:

;; this is a long sentence,
;; nice if
;; it wrapped

after the magic keypress to reformat it produced:

;; this is a long sentence,
;; nice if it wrapped

(I have no idea if the number of characters is equal in each line, but
you get the idea I hope :)).

Thanks!

**Comment by danielcompton** [comment]
Looks like the title for this should be "Reformatting doesn't reflow comments"?

**Comment by cursiveclojure** [comment]
I'm planning to add this functionality to the Fill Paragraph command after some discussion with @michalmarczyk, see #851.

**Comment by cursive-ide** [comment]
Fix released in 1.14.1-eap1 on 2024-12-11.

**Comment by cursive-ide** [comment]
Fix released in 2025.1 on 2025-04-16.
