### ISSUE TITLE
[0.1.43] Spurious error "inserted id is not valid"

### ISSUE THREAD

**Issue by hlship** [cursive-ide/cursive#709]
I have a local symbol in a let named "graph".

I hit Shift-F6 to rename it in place; I want to name it graph' (ending with an apostrophe).

![fan_bootstrap_-__flashiz__-_fan-suite_-____workspaces_fexco_fan-suite_](https://cloud.githubusercontent.com/assets/52660/5821804/b6e356be-a083-11e4-9a49-df1ec064e6ff.png)

But when I hit enter to finalize the rename:

![fan_bootstrap_-__flashiz__-_fan-suite_-____workspaces_fexco_fan-suite_](https://cloud.githubusercontent.com/assets/52660/5821820/ca10d09a-a083-11e4-8d0a-7ccd5c7e1c8a.png)

**Comment by tobias** [comment]
I'm seeing this same issue with a symbol with an apostrophe (`foo'`).
