### ISSUE TITLE
Resource directory not being used from lein project

### ISSUE THREAD

**Issue by habemus-papadum** [cursive-ide/cursive#743]
Hi -- I use cursive and my lein project has the following entry
`:resource-paths ["src/main/resources"]`

When building from the command line, the resources are copied fine, however, when I load the project in intellij, the resources folder is listed as a `source` folder rather than `resources.`  Occasionally I build the project with intellij's make and in this case the resources are not copied.  If I manually change the folder to be a `resource` folder things of course work fine, but for some reason I have to do this every time i restart intellij. 

I believe this is an cursive issue -- perhaps just a small typo somewhere related to processing the resource folders.  

thanks!

**Comment by awkay** [comment]
I have a similar problem with src/test/resources. I've got a mixed source project with JUnit tests that need resources in src/test/resources. I can get them to mark up as sources, but not as resources.

Basically, anyting in the :dev profile marked as :resource-paths should end up as test resources in IntelliJ
