### ISSUE TITLE
Identify unused namespaces (via import or require) - 0.1.04

### ISSUE THREAD

**Issue by hlship** [cursive-ide/cursive#75]
I would very much like it if Cursive could identify (use) and (require) in the (ns) element that are not actually used, and provide an intention to clean them up.

**Comment by hlship** [comment]
So, how the :refer part coming along?  And the intentions?

I'm just a bit obsessive about my (ns) block containing only exactly what's currently used by the code.

**Comment by dmarjenburgh** [comment]
@hlship you might want to take a look at [slamhound](https://github.com/technomancy/slamhound). It sounds like it does exactly what you want.

**Comment by cursiveclojure** [comment]
No real progress, sorry, I've been tied up with other things - I'll try to get to it soon. Once that's working I can do a proper "Optimize namespace", too, which will be great, and this is also the basis of other useful things like moving functions to other namespaces (see #817).

**Comment by pmoriarty** [comment]
We're using :refer quite a lot and would love to see unused refers highlighted at least.
