### ISSUE TITLE
Suggestion - Organize (ns) - 0.1.04

### ISSUE THREAD

**Issue by hlship** [cursive-ide/cursive#77]
Functionality for "organizing" the (ns) declaration would be nice, comparable to the Java Imports support ... or at the very least, doing the require's into alphabetical order, and perhaps merging related ones together.

e.g.

```
(ns 'my.namespace
  (require [foo.bar.baz :as baz]
             [biff.bop :as bop]
             [foo.bar.gnip :as gnip]))
```

to

```
(ns 'my.namespace
  (require [biff.bop :as bop]
              [foo.bar 
                [baz :as baz] 
                [gnip :as gnip]]))
```

**Comment by danielcompton** [comment]
There's some good test cases in Storm, e.g. https://github.com/apache/storm/blob/v0.9.5/storm-core/src/clj/backtype/storm/util.clj

**Comment by ertugrulcetin** [comment]
@hlship @ricardojmendez I was also looking for this feature and wrote a lein plugin for that: https://github.com/ertugrulcetin/lein-nsort
