### ISSUE TITLE
Keyword incorrectly marked as 'Invalid token: ":/"'

### ISSUE THREAD

**Issue by leonid-shevtsov** [cursive-ide/cursive#772]
Keyword `:/` is incorrectly marked as an invalid token in Clojure source code, though it works just fine, both in a source file and from the REPL:

```
(= :/ (keyword "/"))
=> true
```

Cursive 0.1.48

**Comment by cursiveclojure** [comment]
I guess I underestimated the need to have emoticons in source code :-)

This is related to #245.

**Comment by leonid-shevtsov** [comment]
I work with arithmetic expressions, so there's also `:*` and all kinds of other keywords, but the slash was the odd one out :)
