### ISSUE TITLE
ClojureScript macro defined with latest syntax are not recognized

### ISSUE THREAD

**Issue by jeluard** [cursive-ide/cursive#775]
ClojureScript library writer can now make macros visible using the following syntax:

```clojure
; this is a cljs file
(ns my-lib.core
  (:require-macros my-lib.core))
```

```clojure
; this is a clj file
(ns my-lib.core)

(defmacro my-macro
  [])
```

Then library user can simply use the macro as a regular function:

```clojure
; this is a cljs file
(ns some-other-lib.core
  (:require [my-lib.core :as m]))

(m/my-macro)
```

Cursive will not correctly resolve `my-macro`.

**Comment by ikitommi** [comment]
+1

**Comment by mfikes** [comment]
There is also a revision in the works that would introduce some inference for symbols included in `:refer` or `:only`: http://dev.clojure.org/jira/browse/CLJS-1507

**Comment by thheller** [comment]
FWIW shadow-build supports `:refer` for macros (ie. without `:refer-macros`) but Cursive does not recognize this as well. What I started doing to me own namespaces is to have a fake function in my cljs that mirrors the macro signature, this will lead Cursive to recognize the `var` although not as a macro. It works as a small workaround though.

Example:

```clojure
;; test.clj
(ns my.test)
(defmacro sugar [hello & world] ...)

;; test.cljs
(ns my.test
  (:require-macros [my.test :as m]))

(defn sugar [hello & world]
  (throw (ex-info "my.test/sugar can only be called as a macro" {})))
```

Not a solution, just a quick-fix to get auto-completion, tooltips etc.

**Comment by ikitommi** [comment]
<img width="464" alt="refer-macros" src="https://cloud.githubusercontent.com/assets/567532/14953673/7c14b2f0-1074-11e6-8d94-09747ab043b4.png">

Starting to have lot's of extra requires in the codebase because of this.

**Comment by favila** [comment]
To be more precise, Cursive does not understand what Clojurescript calls [Implicit macro loading](https://github.com/clojure/clojurescript/wiki/Differences-from-Clojure#namespaces)

> Implicit macro loading: If a namespace is required or used, and that namespace itself requires or uses macros from its own namespace, then the macros will be implicitly required or used using the same specifications. This oftentimes leads to simplified library usage, such that the consuming namespace need not be concerned about explicitly distinguishing between whether certain vars are functions or macros.

Cursive does not consider macros from the identically-namespaced clj(c) file to be in-scope.

A workaround is to add `:include-macros true` to the require: Cursive does understand this, and Clojurescript accepts but does not require it. Based on the example above:

```clojure
(ns frontend-test
  (:require [schema.core :as s :include-macros true]))

(s/defschema Kikka
  {:value s/Str})
```

**Comment by cursive-ide** [comment]
The first time I fixed this, it was quite tricky to fix. I've now opted for a much simpler fix with one issue - it doesn't check this part: *and that namespace itself requires or uses macros from its own namespace*. i.e. if you require a cljs namespace and there is an equivalent clj namespace containing macros, Cursive will assume they are available even if the cljs namespace does not `require-macros` the clj one. This seems like a case that is unlikely to give anyone any problems, but if it does I'll have to revisit this.

For the curious, this is because when IntelliJ indexes, I only have access to the content of the file actually being indexed, not the content of any other file nor the indexes themselves. I can't make this check when indexing, so there are basically two options - 1. apply the check when the indexes are read (which is tricky, but only in a fiddly ugly way - I could do this), or 2. allow it and provide an inspection which warns if you do this. I think I will opt for 2 if this proves to be a problem for anyone.

**Comment by mfikes** [comment]
The syntax just got a little easier! https://github.com/clojure/clojurescript/commit/783001a6786f8dca4a13fdeadc995716903b07f9

**Comment by cursive-ide** [comment]
@mfikes Looking at that, I'm unsure what the changes to the syntax actually are - can you summarise them?

**Comment by mfikes** [comment]
If you scroll down to the "Implicit Refer" section of [this post](http://blog.fikesfarm.com/posts/2016-03-01-clojurescript-macro-sugar.html) you will see an example.

In short, if you use `:require` / `:refer` today, the items in the `:refer` part of the spec can only list runtime vars, and with the change, the scope is expanded to include macro vars. The high-level idea is that it will allow you to `:require` / `:refer` some var that might be either a function or macro, without having to explicitly encode that in your consuming `ns` form. 

Here is an example (expressed in terms of `require` which is actually implemented in terms of  the `ns` special form under the hood):

Today you have to do something like this:

```
(require '[cljs.pprint :refer [pprint] :refer-macros [pp]])
```

With the change, you will no longer be burdened with knowing that `pprint` is a function and that `pp` is a macro and can simply do this:

```
(require '[cljs.pprint :refer [pprint pp]])
```

This is exactly what you can do in Clojure:

```
(require '[clojure.pprint :refer [pprint pp]])
```

_And_, in fact, with a concomitant change that David made to alias `cljs` to `clojure` in some namespaces, you can exactly do this in ClojureScript so there _is_ no difference with respect to Clojure:

```
(require '[clojure.pprint :refer [pprint pp]])
```

**Comment by cursive-ide** [comment]
Oh nice, thanks for the explanation! I'll add support for this change with the other one.

**Comment by raymcdermott** [comment]
this seems to be back - the macros are resolved with `:refer-macros` but not without

<img width="724" alt="image" src="https://user-images.githubusercontent.com/120437/48922235-99136600-eea5-11e8-8630-e5699b761bc9.png">
<img width="728" alt="image" src="https://user-images.githubusercontent.com/120437/48922241-a7618200-eea5-11e8-8464-047158fd5e7e.png">
<img width="548" alt="image" src="https://user-images.githubusercontent.com/120437/48922281-f7d8df80-eea5-11e8-8809-8ba9542395b5.png">
<img width="439" alt="image" src="https://user-images.githubusercontent.com/120437/48922296-0d4e0980-eea6-11e8-8706-63c958a11983.png">
