### ISSUE TITLE
Dependency autocomplete in project.clj

### ISSUE THREAD

**Issue by CmdrDats** [cursive-ide/cursive#837]
I'd really appreciate a dependency autocomplete feature so that I can ctrl+space inside the project.clj and have it fill in the latest version (or even dropdown with version ranges).. so if I type:

```
[sente<ctrl+space>]
```

It should autocomplete to:

```
[com.taoensso/sente "1.4.1"]
```

or bring up a list of possible candidates.

From an implementation standpoint, having an at-hand index of every jar on maven-central, clojars, et al. is probably infeasible - but perhaps there's slower ways of searching these repo's on-demand. Even an incomplete local index between my projects would be a great start.

**Comment by cursiveclojure** [comment]
Actually it's feasible to get an index of all deps from Clojars and all the org.clojure ones from maven central - I'm planning to add this.

**Comment by CmdrDats** [comment]
awesome! one thing to keep in mind is that there's often a need to include plain java libraries (like quartz, or solrj, for instance) - so it would be especially useful to be able to get those without needing to traverse maven central.

**Comment by cursiveclojure** [comment]
Yeah, that's a much harder problem though. I'll think about a solution to this, but it's less likely to happen I think. Fortunately I think it's much less common than Clojure/Clojars deps.

**Comment by cursiveclojure** [comment]
Actually, I might be able to invoke `search.maven.org` on a double-completion press or something like that. The convention in IntelliJ is usually one press for symbols from your project, two for project + libs, and three for everywhere. But here really only fast and slow options make sense, but an explicit double completion for a remote search might make sense.

**Comment by CmdrDats** [comment]
That sounds perfect!

**Comment by bilekt3** [comment]
Excellent idea, in Python or PHP plugins there are dedicated windows. PHP Composer plugin has nice features like inline display of actual version or autocomplete of version numbers. There might be a lot of inspiration.

**Comment by danielcompton** [comment]
Relates to #329.
