### ISSUE TITLE
"Visually separate REPL evaluations" should work for test actions as well

### ISSUE THREAD

**Issue by cprice404** [cursive-ide/cursive#839]
When I have checked 'visually separate REPL evaluations' in the REPL options dialogue, it draws a nice line between commands that I type into the REPL.

However, one of my major workflows involves use of the "re-run last test action in REPL" action, and when I execute that multiple times in a row, there is no visual indicator between them.  It'd be extremely useful if there was.  :)

**Comment by cursive-ide** [comment]
I'm closing this issue since unfortunately the "visually separate REPL evaluations" option has been removed in the most recent Cursive version due to changes in the way the console works.
