### ISSUE TITLE
Missing command?

### ISSUE THREAD

**Issue by brandonparsons** [cursive-ide/cursive#843]
Hi there,

I could be doing something wrong, but I'd like to be able to send an inner form to the REPL, but the only way to do that appears to be to highlight a form and then "send top form to REPL".

e.g. with the following code:

``` clojure
(start-dates (:results (first (test-schedule))))
```

I can only easily send the first form `(start-dates...` to the REPL. I can't figure out how to use a keyboard shortcut to evaluate the inner form `(:results ....` without highlighting the code first.

Any help would be appreciated!

**Comment by cursiveclojure** [comment]
There's another command "Send form before caret to REPL", which would send it if you had the caret here:
```
(start-dates (:results (first (test-schedule)))|)
```
That's really designed for sending a form you've just written, though. If there's a better way you'd like this to work, let me know - the problem is how to identify the form you'd like sent.

**Comment by brandonparsons** [comment]
Thanks for the reply!

I'm obviously not aware of the intricacies here, but would it be possible to have a command that just evaluates the form that your cursor is *within*, rather than *after*?

i.e., to evaluate `:results...` above, cursor here would work:

`(start-dates (:results | (first (test-schedule))))`

or here:

`(start-dates (:res|ults (first (test-schedule))))`

The SublimeText cloure REPL integration works this way, and I found it was quite convenient as you tab around your source code.

**Comment by cursiveclojure** [comment]
Well, the main issue is that you're using "form" to really mean "list". Working as you suggest, you couldn't evaluate a symbol to see what its value is, or a map (presumably with some elements calculated from code) to see what it looked like.

That said, I'm sure 99% of the time your suggestion makes sense. One thing you might not be aware of is the selection expansion (see [here](https://cursiveclojure.com/userguide/paredit.html) under Selecting things), which makes selecting semantic units much easier and faster. Have you tried that?

**Comment by brandonparsons** [comment]
Yeah that is what I have been doing to accomplish what I want - e.g. put cursor in the `:results` portion, hit the selection expansion keyboard shortcut 2-3 times, then evaluated selected form in the REPL.

I can continue like this, I just figured I'd check to see if there was a one-click way of doing this that I was missing :)

**Comment by vincentjames501** [comment]
I also find this behavior odd. It would be nice to add something along the lines of *Send form after caret to REPL* and *Send outer form to REPL* (may want to tweak wording to list or something).

*Send form after cursor to REPL*
```clojure
(+ 1 |(+ 2 3)) ; The | denotes the caret and would eval (+ 2 3)
```

*Send outer form to REPL*
```clojure
(+ 1 (+ 2 3)) ; If I had my caret anywhere inside (+ 2 3) it would eval (+ 2 3)
```

You mentioned doing the selection expansion which I use often, but how do I evaluate only that selection? I normally just copy and paste into the REPL which I'd rather not do.

**Comment by cursiveclojure** [comment]
It's tricky, what I don't want is to have a multiplicative combination of selection commands + execution. This is one area where Vim-style editing really shines, you can say "Do to <this thing> <this command>".

@vincentjames501 Once you have a form selected, either of the "Send form to REPL" commands will send only the selection to the REPL, i.e. the selection always overrides the form they would otherwise select.
