### ISSUE TITLE
Feature Request: Run stored expression in REPL

### ISSUE THREAD

**Issue by sfnelson** [cursive-ide/cursive#85]
It would be great to be able to create a stored expression and keybind it to run in the REPL, using IntelliJ's macro support or some other mechanism.

My primary use case for this is for running tests in the current namespace, but it would also be useful for bootstrapping the REPL environment.

Example user interaction:

1. Tools => REPL => Create REPL Macro
2. Enter command: "(test-ns *ns*)"
3. Assign name: "Test Current Namespace"
(optional) Assign keybinding via IntelliJ Preferences.
4. Tools => REPL => Macros => Test Current Namespace

**Comment by wilkerlucio** [comment]
+1

**Comment by andykitchen** [comment]
+1

**Comment by malchmih** [comment]
Is there any progress on this? Really waiting for the feature =)

**Comment by madvas** [comment]
+1

**Comment by andykitchen** [comment]
In emacs I've create one command that will reload the current file and re-run the last command on the REPL. It's really a super smooth for development. This feature and others would be so simple to add to Cursive and they'll make a huge difference to the experience.

**Comment by ayazmaroof** [comment]
+1

**Comment by bguthrie** [comment]
Meant to thumbs-up this before: :+1:. In particular this would be handy for executing full-wipe REPL reloads.

**Comment by ohlo** [comment]
I'm surprised no one has mentioned intellij 'live templates'.  ctrl-J then type your abbreviation. 

it would do quite a bit of what people want i would think. esp. combined with intellij macros.

**Comment by cursive-ide** [comment]
@ohlo That doesn't do the same thing though, since it doesn't send anything to the REPL. You could possibly use a macro to do that, but it would be pretty brittle.

**Comment by ohlo** [comment]
yep. didnt claim it was the same thing. but if you're after this feature it at least gets you a good part of the way there today.

**Comment by danielcompton** [comment]
For future searches, this is called "REPL Commands": https://cursive-ide.com/userguide/repl.html#repl-commands
