### ISSUE TITLE
Delineate private functions from public functions

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#867]
The structure view of a Clojure namespace is really powerful, and one that I really like. It would be neat if it was able to show a different icon for public vs private functions. In [ring.middleware.multipart-params](https://github.com/mmcgrana/ring/blob/master/ring-core/src/ring/middleware/multipart_params.clj) most of the functions in the namespace are private, but the structure view uses the same (f) icon for all of them. I'm not sure if this level of customisation is available to you from IntelliJ though.

![screenshot of intellij idea 4-05-15 10 06 23 am](https://cloud.githubusercontent.com/assets/811954/7447174/3c69c76a-f245-11e4-9bbf-1507db9cf089.png)

**Comment by cursiveclojure** [comment]
Yeah, it is, in fact IntelliJ has decorator icons for visibility - if you look at the structure for a Java class, they have the lock signifying private/protected. I can probably add that.

**Comment by cursiveclojure** [comment]
Note to self: com.intellij.psi.impl.ElementPresentationUtil#addVisibilityIcon
