### ISSUE TITLE
Add support for converting .clj files to .cljc files

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#893]
There doesn't seem to be a way within IntelliJ to rename a .clj file to a .cljc file. It's not hard to rename it from the file explorer, but it would be neat to stay inside IntelliJ for this. Would it be possible to make this another refactoring option next to Rename?

Relates to #811

**Comment by danielcompton** [comment]
It could be a "Convert to" refactoring option with the sub options being:
* ClojureScript
* Clojure
* Cljx
* cljc (not sure what you'd call this)

**Comment by cursiveclojure** [comment]
Hmm, I see - that does make sense. Good idea, thanks!

**Comment by CmdrDats** [comment]
I'm also so keen on this - particularly when you start a project as cljs files and want to migrate to cljc, or get it wrong where you meant to choose cljs, but chose clj to start with and only realize half-way through. having to drop to Finder for this is painful!

**Comment by CmdrDats** [comment]
Awesome! Thanks :D

**Comment by danielcompton** [comment]
Is it possible to put this in the refactoring menu, or is it much easier to make it a top level right click action?
