### ISSUE TITLE
Put Datomic Stubs on Clojars

### ISSUE THREAD

**Issue by alexanderkiel** [cursive-ide/cursive#896]
Big thanks for your work on Datomic stubs!

But I need this on Clojars. I have your stubs in the dev profile of my project but Travis CI and others too will complain about not having it.

If you have not the time... Can I do the work for you? Can I put your jar on Clojars?

**Comment by cursiveclojure** [comment]
I'll need to check with Cognitect if there's any problem with me doing this. I'll let you know.

**Comment by bilekt3** [comment]
+1 for this

**Comment by danielcompton** [comment]
Relates to #326.

**Comment by aboy021** [comment]
Any update on this?
I've ended up putting in a dirty hack using leiningen's support for ```:resource-paths``` in the dev profile.

**Comment by Sorceror** [comment]
Is there any way how to generate those stubs? Latest found stubs are for year old datomic version..

**Comment by cursive-ide** [comment]
It probably won't make it into the next drop, but the following one should have functionality to generate them automatically from the version of Datomic that you're using.

**Comment by Sorceror** [comment]
Do I gave to trigger it somehow or it should be done automatically? When diatomic simply adde  as a dependency, the stubs are still missing and diatomic API is unresolved in the code.
Thanks a lot for the help

**Comment by cursive-ide** [comment]
This is fixed in 1.4.0-eap1, which should be out later today. When using datomic (or other similar namespaces) you'll be prompted to create stub files automatically. The external jar is no longer required.
