### ISSUE TITLE
Find Usages in external libraries

### ISSUE THREAD

**Issue by jhalterman** [cursive-ide/cursive#915]
I'm a big "Find Usages" user in Eclipse. One of the ways I often use it is when I'm browsing code in external libraries and I want to find the usages of some method. Sometimes the usages are in my project's code, but often they're in the library itself, or perhaps even in another library that depends on it. It would be great if Cursive had that same ability, to find usages within external libraries (such as while browsing external libraries), regardless of where the code lives.

**Comment by cursiveclojure** [comment]
You can do this - in the find usages popup or toolwindow, click the gear settings icon and you can select the scope you're interested in there. You can also show the settings dialog before each search (Cmd-Alt-Shift F7 on OSX). Let me know if this isn't what you're looking for.

**Comment by jhalterman** [comment]
I tried the various scopes but none of them seem to search external libraries.

**Comment by cursiveclojure** [comment]
Project and Libraries should do that. I believe that once you've selected that scope in the settings dialog that then becomes your default scope for future searches (which is occasionally useful, and occasionally confusing).

**Comment by jhalterman** [comment]
Perhaps it's just not working then. Using the "project and libraries" scope, looking for usages of the `time-since-last-update` function in the screenshot (which is used two function down) yields no results.

![screen shot 2015-06-04 at 2 16 58 pm](https://cloud.githubusercontent.com/assets/228804/7994712/66619574-0ac4-11e5-9dca-db8299549b3e.png)

**Comment by cursiveclojure** [comment]
Hmm, I'll try this. Someone reported a while ago something similar - it's possible that for some reason you can't search in dependencies from other dependencies. If you search for time-since-last-update from your own code does that work?

**Comment by jhalterman** [comment]
Yep, if I do a "Find in Path" with the Project and Libraries scope, I'm able to find time-since-last-update.

**Comment by cursiveclojure** [comment]
Ok, so it looks like there's a bug finding usages of dependencies from dependency code. I'll see if I can track this down.

**Comment by AlexanderMann** [comment]
Having the same problem. Find usages is one of the biggest draws to Cursive for me.
