### ISSUE TITLE
Set REPL to only keep last 10,000 messages

### ISSUE THREAD

**Issue by danielcompton** [cursive-ide/cursive#932]
When working in a program with (admittedly excessive) logging, after a time, IntelliJ can run out of memory, presumably because of too many logs being kept. Is it possible to keep the last 10,000 or so?

**Comment by danielcompton** [comment]
It may be good to also set a space limit of 10 MB, if people print out very large strings.

**Comment by christophercurrie** [comment]
Reusing the idea.properties value `idea.cycle.buffer.size` would be nicely consistent for this.

**Comment by danielcompton** [comment]
Not sure if #1605 addresses this, or if it should stay open?

**Comment by cursive-ide** [comment]
Yes, this is fixed by #1605.
