### ISSUE TITLE
Sending selection content to REPL cannot include last form

### ISSUE THREAD

**Issue by marhel** [cursive-ide/cursive#948]
If the file has five forms, and you want to send the last four of them to the REPL, by selecting them Cursive does nothing. Unless you mark them bottom-to-top, so your cursor is not at the end of the file. 
Happens even if the last form is followed by newlines and whitespace, which you don't select. 

Possibly related to #750.

**Comment by cursive-ide** [comment]
This was fixed in the last release as part of #1371.
