### ISSUE TITLE
clojure.algo.monads macro support

### ISSUE THREAD

**Issue by sfnelson** [cursive-ide/cursive#953]
Clojure's monad implementation has several commonly used macros that are not supported by cursive. Syntax highlighting and symbol resolution for at least `domonad` would be a significant usability improvement.

`domonad` is a binding form similar to `for`, it also supports `:let` and `:when`.

**Comment by danielcompton** [comment]
Relates to #147.

**Comment by sfnelson** [comment]
@cursive-ide now that there is support for customising macro resolution it would be very nice if you could add a macro pattern that will help with `domonad` – it's like `for` but takes an extra form before the binding vector that provides a context for evaluation.

**Comment by cursive-ide** [comment]
This is fixed for the next build. There is one caveat - Cursive isn't aware that `m-result` and friends are special symbols inside monad-aware blocks, so it will mark them as unresolved for now. But everything else should work.
