### ISSUE TITLE
REPL Search History Renders Incorrectly

### ISSUE THREAD

**Issue by shaunparker** [cursive-ide/cursive#971]
The REPL search history renders incorrectly on dual monitors when there is a long expression in the search history. I have IntelliJ on the left monitor, when I activate the search history it renders on the right monitor. I believe the width of the history window is as wide as the longest expression in the history:

![cursive search history render issue](https://cloud.githubusercontent.com/assets/195140/8835761/aed1d62c-3079-11e5-8aaa-ee64150be54f.jpg)

The long expression is a ways back, so it appears as though the history is empty. If I resize the history window width down I can see the list of expressions, but the width isn't persisted and the issue reappears the next time I open the history.

Is there a way to remove an expression from my REPL history? I'd love to be able remove the offending expressions until the issue is fixed.

I'm running the IntelliJ IDEA 14 (Build IU-139.1038.6) with the latest version of Cursive (0.1.58)

Thanks!

**Comment by shaunparker** [comment]
The easiest way to fix this is to remove the offending expression. I did this by hand editing the REPL history which is located in your project's IDEA folder: ```.idea/replstate.xml```.

**Comment by blandinw** [comment]
Confirmed, after copy/pasting a big function in the REPL and maybe restart IntelliJ, this happens.
Would be nice to wrap at 80 char, or at least truncate it if history width > screen width

**Comment by rborer** [comment]
Same issue here, never realised it was related to long expressions in the history, thanks for the tip :wink:

**Comment by thheller** [comment]
I'm stuck with this now too but there is no `.idea/replstate.xml` in my project. Where would this be located nowadays?

**Comment by shaunparker** [comment]
@thheller I just checked my current project and I still see it. I'm running ```IDEA 2017.2``` with ```Cursive 1.6.2-eap3-2017.2```.

It's either changed in the most recent version or perhaps you're looking in the wrong directory? 

Can you verify you see ```$PROJECT_DIR/.idea/workspace.xml```? I believe that is created by IntelliJ for every project. If you don't see it, I think you're looking in the wrong folder. If it is there, then the file has changed.

If the file has changed, you should be able to find the new file by searching your project folder. I just tested this using Mac OS, but it should work with any ```grep``` that supports the ```-R``` option (recursive searching).

1. Start your REPL
2. Run the following expression ```(println "repl-state-here")```
3. Stop the REPL (this is important as Cursive only writes the state once the REPL is stopped)
4. Open a terminal window and go to the project directory
5. From your project directory, run ```grep -Ril . -e 'repl-state-here'``` (this will print out the filename of any file that contains ```repl-state-here ```)

You should see something like this (which hopefully has the file where your REPL history is being stored):
```
my-project-folder$ grep -Ril . -e 'repl-state-here'
./.idea/workspace.xml
```

Good Luck,
Shaun

**Comment by tslocke** [comment]
@cursive-ide adding a +1 to this old issue. The simple solution would be to limit the history window width to something reasonable like 80 characters. In my case, limiting to screen width would not be a solution because I have an extremely wide monitor.
