### ISSUE TITLE
Schema defmethod

### ISSUE THREAD

**Issue by dignati** [cursive-ide/cursive#993]
Support for schema.core/defmethod would be nice. Currently, arguments for methods can't be resolved.

**Comment by tonyvanriet** [comment]
+1 for `s/defmethod` support.
I get unresolved arguments and the formatting is off.

<img width="285" alt="cursive s-defmethod" src="https://cloud.githubusercontent.com/assets/306897/12868054/aade1de6-ccc3-11e5-8a8d-f4c13a6d9ddd.png">

**Comment by tonyvanriet** [comment]
I found that I can at least fix the indenting by manually adding `:schema.core/defmethod :only-indent` to the `ClojureCodeStyleSettings` section of `codeStyleSettings.xml`.
This setting doesn't appear in `Preferences > Editor > Code Style > Clojure` by default, but it will appear after you add it manually to `codeStyleSettings.xml` and restart the IDE.

**Comment by cursive-ide** [comment]
@tonyvanriet You don't have to do that - see [here](https://cursive-ide.com/userguide/formatting.html).

**Comment by tonyvanriet** [comment]
Much better. I read the user guide cover-to-cover but forgot all about that. Thanks.

**Comment by rauhs** [comment]
+1, with om.next I used these multimethods a bunch (also on the server side).

**Comment by lacarmen** [comment]
Are there any updates on this issue? I'm starting to use `schema.core/defmethod` more heavily and my code looks like its been attacked by a highlighter D:
